start32data



s10_chip_list	dw	45+disk_1
	dw	46+disk_1
	dw	55+disk_1
	dw	57+disk_1
	dw	58+disk_1
	dw	59+disk_1
	dw	60+disk_1
	dw	61+disk_1
	dw	62+disk_1
	dw	63+disk_1
	dw	64+disk_1
	dw	65+disk_1
	dw	66+disk_1
	dw	70+disk_1
	dw	71+disk_1
	dw	30+disk_1
	dw	31+disk_1
	dw	32+disk_1
	dw	72+disk_1
	dw	0


grid10	dd 0 dup (0)

s10_pal	dw	0
	dw	1024
	dw	1540
	dw	1542
	dw	2054
	dw	2054
	dw	2056
	dw	2054
	dw	2056
	dw	2058
	dw	2566
	dw	2056
	dw	2058
	dw	2570
	dw	2570
	dw	2572
	dw	3594
	dw	2058
	dw	3084
	dw	3596
	dw	3084
	dw	3596
	dw	3596
	dw	3596
	dw	3596
	dw	4622
	dw	2060
	dw	3090
	dw	3594
	dw	3598
	dw	3600
	dw	3600
	dw	4112
	dw	4112
	dw	5646
	dw	2574
	dw	3602
	dw	4626
	dw	3088
	dw	4112
	dw	4114
	dw	5136
	dw	3608
	dw	4620
	dw	5136
	dw	4626
	dw	5136
	dw	3602
	dw	4118
	dw	6672
	dw	3088
	dw	4628
	dw	5140
	dw	4628
	dw	5142
	dw	5648
	dw	5650
	dw	4632
	dw	5652
	dw	6162
	dw	5652
	dw	5652
	dw	4630
	dw	5656
	dw	5648
	dw	6676
	dw	5652
	dw	6682
	dw	5140
	dw	5144
	dw	6170
	dw	5142
	dw	5146
	dw	5656
	dw	6168
	dw	5656
	dw	6172
	dw	5656
	dw	5662
	dw	6674
	dw	5144
	dw	5660
	dw	7704
	dw	5654
	dw	6680
	dw	6168
	dw	7704
	dw	5660
	dw	6684
	dw	7192
	dw	7196
	dw	6670
	dw	7704
	dw	6174
	dw	7192
	dw	7704
	dw	6682
	dw	7710
	dw	6682
	dw	7196
	dw	6682
	dw	6174
	dw	6684
	dw	8481
	dw	6682
	dw	7203
	dw	8470
	dw	5662
	dw	6689
	dw	8993
	dw	8474
	dw	7708
	dw	7713
	dw	7710
	dw	7205
	dw	8988
	dw	8988
	dw	8478
	dw	7713
	dw	8993
	dw	8483
	dw	8986
	dw	8990
	dw	8993
	dw	10012
	dw	7198
	dw	8993
	dw	10014
	dw	7710
	dw	8489
	dw	9494
	dw	6179
	dw	8997
	dw	10017
	dw	6181
	dw	8997
	dw	10531
	dw	8481
	dw	9507
	dw	11045
	dw	8481
	dw	10021
	dw	10529
	dw	6695
	dw	10025
	dw	10012
	dw	10021
	dw	10021
	dw	10023
	dw	8489
	dw	9517
	dw	10019
	dw	9001
	dw	9517
	dw	11045
	dw	10535
	dw	11049
	dw	10019
	dw	11561
	dw	11049
	dw	12073
	dw	10025
	dw	11563
	dw	11043
	dw	10539
	dw	11563
	dw	12069
	dw	8493
	dw	11565
	dw	11563
	dw	10031
	dw	11567
	dw	12587
	dw	11053
	dw	12077
	dw	13103
	dw	9519
	dw	12591
	dw	12071
	dw	12079
	dw	12595
	dw	13101
	dw	12083
	dw	13619
	dw	14129
	dw	11573
	dw	13621
	dw	14131
	dw	13111
	dw	14649
	dw	15157
	dw	14139
	dw	15163
	dw	15409
	dw	11067
	dw	15165
	dw	9509
	dw	8487
	dw	9507
	dw	11294
	dw	9518
	dw	11049
	dw	10019
	dw	8489
	dw	10524
	dw	2580
	dw	2056
	dw	8491
	dw	9984
	dw	32
	dw	2574
	dw	6152
	dw	4118
	dw	3343
	dw	15369
	dw	19
	dw	3855
	dw	3086
	dw	3341
	dw	4369
	dw	5135
	dw	4115
	dw	3854
	dw	3855
	dw	3857
	dw	7195
	dw	1055
	dw	1028
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	14129
	dw	11549
	dw	7220
	dw	12586
	dw	10011
	dw	6702
	dw	11300
	dw	8472
	dw	5929
	dw	9759
	dw	7190
	dw	5411
	dw	8474
	dw	5907
	dw	4638
	dw	6933
	dw	4625
	dw	3865
	dw	5648
	dw	3598
	dw	3091
	dw	4108
	dw	2570
	dw	2318
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s10_logic	dw	id_foster
	dw	id_scanner_10
	dw	id_pod
	dw	id_pod_light
	dw	id_monitor_10
	dw	id_liyt_1
	dw	id_liyt_2
	dw	id_liyt_3
	dw	id_liyt_4
	dw	id_litebank
	dw	$ffff
	dw	id_menu_logic


s10_mouse	dw	id_joey
	dw	id_left_exit_10
	dw	id_lift_slot_10
	dw	id_linc_10
	dw	id_pod_light
	dw	id_terminal_10
	dw	id_scanner_10
	dw	id_lift_10
	dw	id_fake_floor_10
	dw	id_s10_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s10_floor	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	s10_floor_table
	dw	152
	dw	264
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	(312-264)-1
	dw	floor_action



end32save_data

start32data



s10_floor_table	dw	id_s10_floor
	dw	return_ok
	dw	id_left_exit_10
	dw	GT_left_exit_10
	dw	0
	dw	s10_right_on
	dw	id_lift_slot_10
	dw	GT_slot_10
	dw	id_pod_light
	dw	GT_pod_light
	dw	id_linc_10
	dw	GT_linc_10
	dw	id_terminal_10
	dw	GT_terminal_10
	dw	id_scanner_10
	dw	GT_scanner_10
	dw	id_lift_10
	dw	GT_door_10
	dw	-1


rs_foster_11_10	dw	c_xcood
	dw	128
	dw	c_ycood
	dw	288
	dw	c_screen
	dw	10
	dw	c_place
	dw	id_s10_floor
	dw	-1


rs_foster_10_11	dw	c_xcood
	dw	384
	dw	c_ycood
	dw	272
	dw	c_screen
	dw	11
	dw	c_place
	dw	id_s11_floor
	dw	-1



end32data

start32save_data



left_exit_10	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	154
	dw	226
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	171-154
	dw	288-226
	dw	el10_action


lift_10	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	NULL
	dw	358
	dw	217
	dw	s45
	dw	139
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-4
	dw	0
	dw	6
	dw	62
	dw	door_10_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	lift_10_logic
	dw	0



end32save_data

start32data



lift_10_open	dw	s45
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	0


lift_10_close	dw	s45
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



lift_slot_10	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	361
	dw	245
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	366-361
	dw	258-245
	dw	slot_10_action



end32save_data

start32data



card2_seq	dw	s55
	dw	328
	dw	224
	dw	0
	dw	328
	dw	224
	dw	1
	dw	328
	dw	224
	dw	2
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	3
	dw	328
	dw	224
	dw	2
	dw	328
	dw	224
	dw	1
	dw	328
	dw	224
	dw	0
	dw	0


scanline_seq	dw	s57
	dw	329
	dw	226
	dw	0
	dw	329
	dw	226
	dw	1
	dw	329
	dw	226
	dw	2
	dw	329
	dw	226
	dw	3
	dw	329
	dw	226
	dw	4
	dw	329
	dw	226
	dw	5
	dw	329
	dw	226
	dw	6
	dw	329
	dw	226
	dw	7
	dw	329
	dw	226
	dw	8
	dw	329
	dw	226
	dw	9
	dw	329
	dw	226
	dw	10
	dw	329
	dw	226
	dw	11
	dw	329
	dw	226
	dw	12
	dw	329
	dw	226
	dw	13
	dw	329
	dw	226
	dw	14
	dw	329
	dw	226
	dw	15
	dw	329
	dw	226
	dw	16
	dw	329
	dw	226
	dw	17
	dw	1
	dw	1
	dw	16
	dw	1
	dw	1
	dw	15
	dw	1
	dw	1
	dw	14
	dw	1
	dw	1
	dw	13
	dw	1
	dw	1
	dw	12
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



scanner_10	dw	l_script
	dw	st_logic+st_recreate+st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	329
	dw	226
	dw	0
	dw	138
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	45
	dw	25
	dw	11
	dw	scanner_10_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	scanner_10_logic
	dw	0


pod	dw	l_script
	dw	st_logic+st_recreate+st_foreground
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	204
	dw	180
	dw	s58
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	366-361
	dw	258-245
	dw	slot_10_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	pod_logic
	dw	0



end32save_data

start32data



pod_down	dw	s58
	dw	204
	dw	180
	dw	0
	dw	204
	dw	180
	dw	1
	dw	204
	dw	181
	dw	1
	dw	204
	dw	182
	dw	1
	dw	204
	dw	183
	dw	1
	dw	204
	dw	184
	dw	1
	dw	204
	dw	185
	dw	1
	dw	204
	dw	186
	dw	1
	dw	204
	dw	187
	dw	1
	dw	204
	dw	188
	dw	1
	dw	204
	dw	189
	dw	1
	dw	204
	dw	190
	dw	1
	dw	204
	dw	191
	dw	1
	dw	204
	dw	192
	dw	1
	dw	204
	dw	193
	dw	1
	dw	204
	dw	194
	dw	1
	dw	204
	dw	195
	dw	1
	dw	204
	dw	196
	dw	1
	dw	204
	dw	197
	dw	1
	dw	204
	dw	198
	dw	1
	dw	204
	dw	199
	dw	1
	dw	204
	dw	200
	dw	1
	dw	204
	dw	201
	dw	1
	dw	204
	dw	202
	dw	1
	dw	204
	dw	203
	dw	1
	dw	204
	dw	204
	dw	1
	dw	204
	dw	205
	dw	1
	dw	204
	dw	206
	dw	1
	dw	204
	dw	207
	dw	1
	dw	204
	dw	208
	dw	1
	dw	204
	dw	209
	dw	1
	dw	204
	dw	210
	dw	1
	dw	204
	dw	211
	dw	1
	dw	204
	dw	212
	dw	1
	dw	204
	dw	213
	dw	1
	dw	204
	dw	214
	dw	1
	dw	204
	dw	215
	dw	1
	dw	204
	dw	216
	dw	1
	dw	204
	dw	216
	dw	1
	dw	204
	dw	216
	dw	1
	dw	0


pod_up	dw	s58
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	216
	dw	0
	dw	204
	dw	215
	dw	0
	dw	204
	dw	214
	dw	0
	dw	204
	dw	213
	dw	0
	dw	204
	dw	212
	dw	0
	dw	204
	dw	211
	dw	0
	dw	204
	dw	210
	dw	0
	dw	204
	dw	209
	dw	0
	dw	204
	dw	208
	dw	0
	dw	204
	dw	207
	dw	0
	dw	204
	dw	206
	dw	0
	dw	204
	dw	205
	dw	0
	dw	204
	dw	204
	dw	0
	dw	204
	dw	203
	dw	0
	dw	204
	dw	202
	dw	0
	dw	204
	dw	201
	dw	0
	dw	204
	dw	200
	dw	0
	dw	204
	dw	199
	dw	0
	dw	204
	dw	198
	dw	0
	dw	204
	dw	197
	dw	0
	dw	204
	dw	196
	dw	0
	dw	204
	dw	195
	dw	0
	dw	204
	dw	194
	dw	0
	dw	204
	dw	193
	dw	0
	dw	204
	dw	192
	dw	0
	dw	204
	dw	191
	dw	0
	dw	204
	dw	190
	dw	0
	dw	204
	dw	189
	dw	0
	dw	204
	dw	188
	dw	0
	dw	204
	dw	187
	dw	0
	dw	204
	dw	186
	dw	0
	dw	204
	dw	185
	dw	0
	dw	204
	dw	184
	dw	0
	dw	204
	dw	183
	dw	0
	dw	204
	dw	182
	dw	0
	dw	204
	dw	181
	dw	0
	dw	0



end32data

start32save_data



linc_10	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	linc_10_table
	dw	203
	dw	222
	dw	s58
	dw	56
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	231-203
	dw	269-222
	dw	linc_10_action



end32save_data

start32data



linc_10_table	dw	id_s10_floor
	dw	GT_floor_from_chair10
	dw	id_left_exit_10
	dw	GT_floor_from_chair10
	dw	id_lift_slot_10
	dw	GT_floor_from_chair10
	dw	id_pod_light
	dw	GT_floor_from_chair10
	dw	id_terminal_10
	dw	GT_floor_from_chair10
	dw	id_scanner_10
	dw	GT_floor_from_chair10
	dw	id_lift_10
	dw	GT_floor_from_chair10
	dw	id_linc_10
	dw	return_ok
	dw	-1



end32data

start32save_data



pod_light	dw	l_script
	dw	st_logic+st_recreate+st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	pod_light_logic
	dw	0



end32save_data

start32data



pod_light_seq	dw	s59
	dw	239
	dw	244
	dw	0
	dw	239
	dw	244
	dw	0
	dw	239
	dw	244
	dw	1
	dw	239
	dw	244
	dw	1
	dw	239
	dw	244
	dw	1
	dw	239
	dw	244
	dw	1
	dw	239
	dw	244
	dw	0
	dw	239
	dw	244
	dw	0
	dw	239
	dw	244
	dw	0
	dw	239
	dw	244
	dw	0
	dw	0


linc_card_seq	dw	s60
	dw	224
	dw	224
	dw	0
	dw	224
	dw	224
	dw	1
	dw	224
	dw	224
	dw	2
	dw	224
	dw	224
	dw	2
	dw	224
	dw	224
	dw	2
	dw	224
	dw	224
	dw	2
	dw	224
	dw	224
	dw	2
	dw	224
	dw	224
	dw	1
	dw	224
	dw	224
	dw	0
	dw	0


sit_10_seq	dw	s61
	dw	210
	dw	228
	dw	0
	dw	207
	dw	228
	dw	1
	dw	207
	dw	228
	dw	2
	dw	207
	dw	227
	dw	3
	dw	207
	dw	224
	dw	4
	dw	207
	dw	225
	dw	5
	dw	207
	dw	225
	dw	6
	dw	207
	dw	225
	dw	7
	dw	207
	dw	225
	dw	8
	dw	207
	dw	225
	dw	8
	dw	0


stand_10_seq	dw	s62
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	3
	dw	207
	dw	224
	dw	4
	dw	207
	dw	227
	dw	5
	dw	207
	dw	228
	dw	6
	dw	212
	dw	228
	dw	7
	dw	216
	dw	228
	dw	8
	dw	223
	dw	226
	dw	9
	dw	0



end32data

start32save_data



monitor_10	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0


liyt_1	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0


liyt_2	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0


liyt_3	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0


liyt_4	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0


litebank	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	239
	dw	244
	dw	s59
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	6
	dw	pod_light_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0



end32save_data

start32data



monitor_10_seq	dw	s63
	dw	322
	dw	229
	dw	0
	dw	322
	dw	229
	dw	1
	dw	322
	dw	229
	dw	2
	dw	322
	dw	229
	dw	3
	dw	322
	dw	229
	dw	4
	dw	322
	dw	229
	dw	5
	dw	322
	dw	229
	dw	6
	dw	322
	dw	229
	dw	7
	dw	322
	dw	229
	dw	8
	dw	322
	dw	229
	dw	9
	dw	322
	dw	229
	dw	10
	dw	322
	dw	229
	dw	11
	dw	322
	dw	229
	dw	12
	dw	322
	dw	229
	dw	13
	dw	322
	dw	229
	dw	14
	dw	322
	dw	229
	dw	15
	dw	322
	dw	229
	dw	16
	dw	0


liyt_1_seq	dw	s64
	dw	413
	dw	270
	dw	0
	dw	413
	dw	270
	dw	0
	dw	413
	dw	270
	dw	0
	dw	413
	dw	270
	dw	0
	dw	413
	dw	270
	dw	0
	dw	413
	dw	270
	dw	1
	dw	413
	dw	270
	dw	1
	dw	413
	dw	270
	dw	1
	dw	413
	dw	270
	dw	1
	dw	413
	dw	270
	dw	1
	dw	0


liyt_2_seq	dw	s65
	dw	409
	dw	274
	dw	0
	dw	409
	dw	274
	dw	0
	dw	409
	dw	274
	dw	0
	dw	409
	dw	274
	dw	0
	dw	409
	dw	274
	dw	1
	dw	409
	dw	274
	dw	1
	dw	409
	dw	274
	dw	1
	dw	0


liyt_3_seq	dw	s66
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	1
	dw	325
	dw	170
	dw	0
	dw	325
	dw	170
	dw	0
	dw	0


liyt_4_seq	dw	s70
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	3
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	0
	dw	128
	dw	147
	dw	4
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	1
	dw	128
	dw	147
	dw	2
	dw	128
	dw	147
	dw	2
	dw	0


litebank_seq	dw	s71
	dw	226
	dw	198
	dw	0
	dw	226
	dw	198
	dw	0
	dw	226
	dw	198
	dw	1
	dw	226
	dw	198
	dw	1
	dw	226
	dw	198
	dw	2
	dw	226
	dw	198
	dw	2
	dw	226
	dw	198
	dw	3
	dw	226
	dw	198
	dw	3
	dw	226
	dw	198
	dw	4
	dw	226
	dw	198
	dw	4
	dw	226
	dw	198
	dw	5
	dw	226
	dw	198
	dw	5
	dw	226
	dw	198
	dw	6
	dw	226
	dw	198
	dw	6
	dw	226
	dw	198
	dw	7
	dw	226
	dw	198
	dw	7
	dw	226
	dw	198
	dw	8
	dw	226
	dw	198
	dw	8
	dw	226
	dw	198
	dw	9
	dw	226
	dw	198
	dw	9
	dw	226
	dw	198
	dw	0
	dw	226
	dw	198
	dw	0
	dw	226
	dw	198
	dw	1
	dw	226
	dw	198
	dw	1
	dw	226
	dw	198
	dw	2
	dw	226
	dw	198
	dw	2
	dw	226
	dw	198
	dw	3
	dw	226
	dw	198
	dw	3
	dw	226
	dw	198
	dw	4
	dw	226
	dw	198
	dw	4
	dw	226
	dw	198
	dw	5
	dw	226
	dw	198
	dw	5
	dw	226
	dw	198
	dw	6
	dw	226
	dw	198
	dw	6
	dw	226
	dw	198
	dw	7
	dw	226
	dw	198
	dw	7
	dw	226
	dw	198
	dw	8
	dw	226
	dw	198
	dw	8
	dw	226
	dw	198
	dw	9
	dw	226
	dw	198
	dw	9
	dw	226
	dw	198
	dw	4
	dw	226
	dw	198
	dw	4
	dw	0


fsit_talk_seq	dw	s72
	dw	s61+8
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	1
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	2
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	0
	dw	207
	dw	225
	dw	3
	dw	207
	dw	225
	dw	3
	dw	0



end32data

start32save_data



terminal_10	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	400
	dw	265
	dw	0
	dw	51
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	26
	dw	308-265
	dw	terminal_10_action


fake_floor_10	dw	0
	dw	st_mouse
	dw	0
	dw	10
	dw	NULL
	dd	0
	dw	356
	dw	271
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	320
	dw	12



end32save_data

start32data



rs_foster_from_linc	dw	c_xcood
	dw	$cf
	dw	c_ycood
	dw	$e1
	dw	c_frame
	dw	$f48
	dw	c_place
	dw	id_linc_10
	dw	c_screen
	dw	10
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_ar_priority+st_grid_plot+st_collision
	dw	-1



end32data

start32save_data



end32save_data
