start32data



s11_chip_list	dw	17+disk_1
	dw	18+disk_1
	dw	20+disk_1
	dw	21+disk_1
	dw	22+disk_1
	dw	23+disk_1
	dw	24+disk_1
	dw	25+disk_1
	dw	26+disk_1
	dw	27+disk_1
	dw	28+disk_1
	dw	29+disk_1
	dw	14+disk_1
	dw	15+disk_1
	dw	85+disk_1
	dw	0


grid11	dd 0 dup (0)

s11_pal	dw	0
	dw	512
	dw	1026
	dw	1026
	dw	1028
	dw	1028
	dw	1028
	dw	1542
	dw	516
	dw	1540
	dw	1028
	dw	1542
	dw	1542
	dw	1540
	dw	1542
	dw	1542
	dw	1032
	dw	1544
	dw	2054
	dw	2054
	dw	2054
	dw	2054
	dw	2056
	dw	1544
	dw	2056
	dw	1544
	dw	2058
	dw	2568
	dw	2056
	dw	2570
	dw	2572
	dw	2564
	dw	2058
	dw	2568
	dw	2572
	dw	2570
	dw	2062
	dw	2056
	dw	3084
	dw	2572
	dw	2572
	dw	2572
	dw	3082
	dw	3596
	dw	3082
	dw	3084
	dw	3084
	dw	3596
	dw	3594
	dw	4108
	dw	2060
	dw	3088
	dw	3082
	dw	3086
	dw	3086
	dw	3086
	dw	3598
	dw	4106
	dw	4108
	dw	3596
	dw	3598
	dw	3086
	dw	3600
	dw	3598
	dw	4624
	dw	2062
	dw	4110
	dw	3084
	dw	4112
	dw	4110
	dw	4110
	dw	4110
	dw	4110
	dw	3600
	dw	4624
	dw	4114
	dw	5130
	dw	2576
	dw	4622
	dw	5650
	dw	2576
	dw	4624
	dw	4624
	dw	4624
	dw	4624
	dw	5138
	dw	3090
	dw	4116
	dw	5650
	dw	2578
	dw	4626
	dw	4114
	dw	4628
	dw	5138
	dw	5136
	dw	5138
	dw	4632
	dw	4620
	dw	4628
	dw	5648
	dw	4114
	dw	5142
	dw	5144
	dw	5132
	dw	5140
	dw	5650
	dw	5652
	dw	3606
	dw	5652
	dw	5138
	dw	5142
	dw	5142
	dw	5142
	dw	5654
	dw	5142
	dw	5656
	dw	4120
	dw	6164
	dw	4628
	dw	5146
	dw	5656
	dw	5656
	dw	6168
	dw	6678
	dw	5654
	dw	6170
	dw	6680
	dw	6164
	dw	4636
	dw	7190
	dw	5656
	dw	6174
	dw	7704
	dw	7192
	dw	5660
	dw	7706
	dw	6166
	dw	6689
	dw	7198
	dw	6684
	dw	6689
	dw	8474
	dw	7708
	dw	6177
	dw	8986
	dw	8476
	dw	6177
	dw	8990
	dw	6680
	dw	7717
	dw	9500
	dw	7196
	dw	7717
	dw	9502
	dw	7710
	dw	8485
	dw	10012
	dw	8481
	dw	6695
	dw	10014
	dw	7710
	dw	8487
	dw	10021
	dw	8478
	dw	8489
	dw	10531
	dw	8995
	dw	8491
	dw	11045
	dw	8990
	dw	9515
	dw	11557
	dw	9505
	dw	9517
	dw	11557
	dw	9511
	dw	9007
	dw	12069
	dw	10023
	dw	9007
	dw	12071
	dw	10021
	dw	10031
	dw	12585
	dw	11045
	dw	10543
	dw	13099
	dw	11045
	dw	10547
	dw	13611
	dw	11559
	dw	10549
	dw	4381
	dw	16128
	dw	40
	dw	6955
	dw	10240
	dw	31
	dw	26
	dw	16128
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	63
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s11_logic	dw	id_foster
	dw	id_cable_fall
	dw	id_cable_fall2
	dw	id_smashed_window
	dw	id_bits
	dw	id_bits2
	dw	id_spy_11
	dw	id_locker_11
	dw	$ffff
	dw	id_menu_logic


s11_mouse	dw	id_joey
	dw	id_cable_fall
	dw	id_slot_11
	dw	id_locker_11
	dw	id_slat_1
	dw	id_slat_2
	dw	id_slat_3
	dw	id_slat_4
	dw	id_slat_5
	dw	id_soccer_1
	dw	id_soccer_2
	dw	id_soccer_3
	dw	id_soccer_4
	dw	id_soccer_5
	dw	id_right_exit_11
	dw	id_s11_floor
	dw	id_spy_11
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s11_floor	dw	0
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	s11_floor_table
	dw	184
	dw	256
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	400-184
	dw	4242
	dw	floor_action



end32save_data

start32data



s11_floor_table	dw	id_s11_floor
	dw	return_ok
	dw	id_cable_fall
	dw	GT_cable_11
	dw	id_locker_11
	dw	GT_locker_11
	dw	id_slot_11
	dw	GT_slot_11
	dw	id_soccer_1
	dw	GT_soccer_1
	dw	id_soccer_2
	dw	GT_soccer_2
	dw	id_soccer_3
	dw	GT_soccer_3
	dw	id_soccer_4
	dw	GT_soccer_4
	dw	id_soccer_5
	dw	GT_soccer_5
	dw	id_slat_1
	dw	GT_soccer_1
	dw	id_slat_2
	dw	GT_soccer_2
	dw	id_slat_3
	dw	GT_soccer_3
	dw	id_slat_4
	dw	GT_soccer_4
	dw	id_slat_5
	dw	GT_soccer_5
	dw	id_right_exit_11
	dw	GT_right_exit_11
	dw	0
	dw	s11_left_on
	dw	-1


rs_foster_1_11	dw	c_xcood
	dw	320
	dw	c_ycood
	dw	288
	dw	c_screen
	dw	11
	dw	c_place
	dw	id_s11_floor
	dw	-1


fallin_seq	dw	s17
	dw	198
	dw	173
	dw	0
	dw	202
	dw	168
	dw	1
	dw	206
	dw	174
	dw	2
	dw	216
	dw	183
	dw	3
	dw	232
	dw	190
	dw	4
	dw	250
	dw	201
	dw	5
	dw	275
	dw	217
	dw	6
	dw	289
	dw	232
	dw	7
	dw	306
	dw	259
	dw	8
	dw	0


fallin2_seq	dw	s18
	dw	319
	dw	273
	dw	0
	dw	322
	dw	276
	dw	1
	dw	322
	dw	279
	dw	2
	dw	322
	dw	278
	dw	3
	dw	320
	dw	277
	dw	4
	dw	320
	dw	278
	dw	5
	dw	320
	dw	279
	dw	6
	dw	320
	dw	279
	dw	7
	dw	320
	dw	279
	dw	8
	dw	320
	dw	279
	dw	9
	dw	320
	dw	278
	dw	10
	dw	319
	dw	279
	dw	11
	dw	317
	dw	275
	dw	12
	dw	317
	dw	272
	dw	13
	dw	0


fallin3_seq	dw	s20
	dw	317
	dw	267
	dw	0
	dw	314
	dw	266
	dw	1
	dw	314
	dw	264
	dw	2
	dw	315
	dw	255
	dw	3
	dw	314
	dw	247
	dw	4
	dw	314
	dw	243
	dw	5
	dw	0



end32data

start32save_data



cable_fall	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s21
	dw	49
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	44
	dw	16
	dw	9
	dw	cable_11_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	cable_fall_logic
	dw	0


cable_fall2	dw	l_script
	dw	st_background+st_logic+st_recreate
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s22
	dw	49
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	44
	dw	16
	dw	9
	dw	cable_11_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	cable2_logic
	dw	0



end32save_data

start32data



cable_fall1_seq	dw	s21
	dw	195
	dw	178
	dw	0
	dw	195
	dw	178
	dw	0
	dw	195
	dw	178
	dw	0
	dw	195
	dw	178
	dw	1
	dw	195
	dw	178
	dw	2
	dw	195
	dw	178
	dw	3
	dw	195
	dw	178
	dw	4
	dw	195
	dw	178
	dw	5
	dw	195
	dw	178
	dw	6
	dw	195
	dw	178
	dw	7
	dw	195
	dw	178
	dw	8
	dw	195
	dw	178
	dw	9
	dw	195
	dw	178
	dw	10
	dw	195
	dw	178
	dw	11
	dw	195
	dw	178
	dw	12
	dw	195
	dw	178
	dw	13
	dw	195
	dw	178
	dw	14
	dw	195
	dw	178
	dw	15
	dw	195
	dw	178
	dw	16
	dw	195
	dw	178
	dw	17
	dw	195
	dw	178
	dw	18
	dw	195
	dw	178
	dw	19
	dw	195
	dw	178
	dw	20
	dw	195
	dw	178
	dw	21
	dw	195
	dw	178
	dw	22
	dw	0


cable_fall2_seq	dw	s22
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	0
	dw	209
	dw	242
	dw	1
	dw	209
	dw	242
	dw	2
	dw	209
	dw	242
	dw	3
	dw	209
	dw	242
	dw	3
	dw	209
	dw	242
	dw	3
	dw	209
	dw	242
	dw	3
	dw	209
	dw	242
	dw	4
	dw	209
	dw	242
	dw	5
	dw	209
	dw	242
	dw	6
	dw	209
	dw	242
	dw	6
	dw	209
	dw	242
	dw	6
	dw	209
	dw	242
	dw	7
	dw	209
	dw	242
	dw	8
	dw	209
	dw	242
	dw	9
	dw	209
	dw	242
	dw	10
	dw	209
	dw	242
	dw	10
	dw	209
	dw	242
	dw	10
	dw	209
	dw	242
	dw	10
	dw	209
	dw	242
	dw	11
	dw	209
	dw	242
	dw	12
	dw	209
	dw	242
	dw	13
	dw	0



end32data

start32save_data



smashed_window	dw	l_script
	dw	st_background+st_logic+st_recreate
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s23
	dw	49
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	44
	dw	16
	dw	9
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	smashed_window_logic
	dw	0



end32save_data

start32data



smashed_window_seq	dw	s23
	dw	201
	dw	151
	dw	0
	dw	201
	dw	153
	dw	1
	dw	201
	dw	153
	dw	2
	dw	201
	dw	153
	dw	3
	dw	201
	dw	153
	dw	4
	dw	201
	dw	153
	dw	3
	dw	201
	dw	153
	dw	4
	dw	201
	dw	153
	dw	3
	dw	201
	dw	153
	dw	4
	dw	201
	dw	153
	dw	3
	dw	201
	dw	153
	dw	4
	dw	201
	dw	153
	dw	3
	dw	0



end32data

start32save_data



bits	dw	l_script
	dw	st_background+st_logic+st_recreate
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s24
	dw	0
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	44
	dw	16
	dw	9
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bits_logic
	dw	0



end32save_data

start32data



bits_seq	dw	s24
	dw	213
	dw	170
	dw	0
	dw	229
	dw	168
	dw	1
	dw	240
	dw	170
	dw	2
	dw	250
	dw	174
	dw	3
	dw	266
	dw	180
	dw	4
	dw	0



end32data

start32save_data



bits2	dw	l_script
	dw	st_background+st_logic+st_recreate
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s25
	dw	0
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	44
	dw	16
	dw	9
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bits_logic
	dw	0



end32save_data

start32data



bits2_seq	dw	s25
	dw	198
	dw	182
	dw	0
	dw	199
	dw	182
	dw	1
	dw	208
	dw	191
	dw	2
	dw	214
	dw	221
	dw	3
	dw	219
	dw	245
	dw	4
	dw	0


get_cable_11	dw	s27
	dw	293
	dw	252
	dw	0
	dw	293
	dw	252
	dw	1
	dw	293
	dw	252
	dw	2
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	2
	dw	293
	dw	252
	dw	1
	dw	293
	dw	252
	dw	0
	dw	0



end32data

start32save_data



spy_11	dw	l_script
	dw	st_logic
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	167
	dw	138
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	1
	dw	1
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	spy11_logic
	dw	0


locker_11	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	301
	dw	217
	dw	s26
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	0
	dw	16
	dw	44
	dw	locker_11_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	locker_11_logic
	dw	0



end32save_data

start32data



locker_11_open	dw	s26
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	0


locker_11_close	dw	s26
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



slot_11	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	320
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slot_11_action



end32save_data

start32data



usecard_11_seq	dw	s28
	dw	258
	dw	173
	dw	0
	dw	258
	dw	173
	dw	1
	dw	258
	dw	173
	dw	2
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	2
	dw	258
	dw	173
	dw	1
	dw	258
	dw	173
	dw	0
	dw	0


open_11_locker	dw	s29
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	1
	dw	237
	dw	184
	dw	2
	dw	237
	dw	184
	dw	3
	dw	237
	dw	184
	dw	4
	dw	237
	dw	184
	dw	5
	dw	237
	dw	184
	dw	6
	dw	0


close_11_locker	dw	s29
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


cant_open_locker	dw	s29
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



soccer_1	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	238
	dw	217
	dw	0
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	255-238
	dw	260-217
	dw	soccer_1_action


soccer_2	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	257
	dw	217
	dw	0
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	271-257
	dw	260-217
	dw	soccer_1_action


soccer_3	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	273
	dw	217
	dw	0
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	289-273
	dw	260-217
	dw	soccer_1_action


soccer_4	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	291
	dw	217
	dw	0
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	307-291
	dw	260-217
	dw	soccer_1_action


soccer_5	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	327
	dw	217
	dw	0
	dw	12703
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	343-327
	dw	260-217
	dw	soccer_1_action


slat_1	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	250
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slat_action


slat_2	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	267
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slat_action


slat_3	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	285
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slat_action


slat_4	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	302
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slat_action


slat_5	dw	l_script
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	NULL
	dw	337
	dw	236
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	3
	dw	7
	dw	slat_action


right_exit_11	dw	0
	dw	st_mouse
	dw	0
	dw	11
	dw	NULL
	dd	0
	dw	359
	dw	223
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	364-359
	dw	282-223
	dw	er11_action



end32save_data

start32data



end32data
