start32data



s12_new_chip	dw	173
	dw	111
	dw	136+disk_2
	dw	137+disk_2
	dw	131+disk_2
	dw	132+disk_2
	dw	44+disk_3
	dw	45+disk_3
	dw	46+disk_3+$8000
	dw	69+disk_3+$8000
	dw	70+disk_3+$8000
	dw	71+disk_3+$8000
	dw	15+disk_3
	dw	92+disk_3
	dw	0


s12_chip_list	dw	173
	dw	111
	dw	136+disk_2
	dw	137+disk_2
	dw	131+disk_2
	dw	132+disk_2
	dw	27+disk_3
	dw	28+disk_3+$8000
	dw	29+disk_3+$8000
	dw	30+disk_3+$8000
	dw	44+disk_3
	dw	45+disk_3
	dw	46+disk_3+$8000
	dw	90+disk_3+$8000
	dw	15+disk_3
	dw	92+disk_3
	dw	0


s12_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	14+disk_3
	dw	16+disk_3
	dw	91+disk_3
	dw	0


grid12	dd 0 dup (0)

s12_pal	dw	0
	dw	1024
	dw	516
	dw	1030
	dw	1540
	dw	1542
	dw	1544
	dw	2052
	dw	1542
	dw	2058
	dw	2566
	dw	2056
	dw	2060
	dw	3078
	dw	2570
	dw	2574
	dw	4106
	dw	2058
	dw	3084
	dw	3594
	dw	2572
	dw	2580
	dw	3590
	dw	3084
	dw	2580
	dw	3592
	dw	4110
	dw	3600
	dw	4622
	dw	3086
	dw	3096
	dw	3592
	dw	4112
	dw	4112
	dw	7184
	dw	2060
	dw	3608
	dw	6666
	dw	3086
	dw	4118
	dw	4622
	dw	4626
	dw	4628
	dw	8462
	dw	2572
	dw	4634
	dw	4616
	dw	4628
	dw	5138
	dw	6164
	dw	4114
	dw	5140
	dw	8980
	dw	3086
	dw	4131
	dw	6156
	dw	5140
	dw	4131
	dw	5646
	dw	5142
	dw	5654
	dw	5656
	dw	4632
	dw	5148
	dw	7698
	dw	3094
	dw	5150
	dw	7186
	dw	4630
	dw	6166
	dw	6170
	dw	6168
	dw	6170
	dw	6678
	dw	4122
	dw	6168
	dw	8474
	dw	5144
	dw	7706
	dw	10002
	dw	4630
	dw	6179
	dw	7188
	dw	6682
	dw	6686
	dw	9496
	dw	5144
	dw	6689
	dw	7190
	dw	3617
	dw	7196
	dw	7708
	dw	6684
	dw	7205
	dw	10510
	dw	3098
	dw	7205
	dw	9488
	dw	6170
	dw	7708
	dw	7710
	dw	5665
	dw	7205
	dw	7704
	dw	8478
	dw	8990
	dw	7700
	dw	6689
	dw	7713
	dw	7710
	dw	8993
	dw	8489
	dw	9998
	dw	6686
	dw	8483
	dw	10014
	dw	4131
	dw	8993
	dw	10531
	dw	6689
	dw	8993
	dw	10533
	dw	7201
	dw	10019
	dw	11032
	dw	7201
	dw	9517
	dw	9486
	dw	4649
	dw	9517
	dw	10512
	dw	7715
	dw	9507
	dw	10021
	dw	8485
	dw	10533
	dw	12058
	dw	3623
	dw	9511
	dw	9509
	dw	7209
	dw	9005
	dw	10526
	dw	5673
	dw	10021
	dw	9511
	dw	10535
	dw	9517
	dw	10017
	dw	10023
	dw	10545
	dw	12048
	dw	8485
	dw	11057
	dw	12560
	dw	4651
	dw	10031
	dw	10531
	dw	7213
	dw	11563
	dw	10524
	dw	9005
	dw	11049
	dw	10537
	dw	11051
	dw	10543
	dw	12581
	dw	9001
	dw	11051
	dw	12073
	dw	6703
	dw	12077
	dw	11041
	dw	9519
	dw	11059
	dw	11559
	dw	11567
	dw	12077
	dw	12591
	dw	7731
	dw	13103
	dw	12069
	dw	11057
	dw	12085
	dw	12585
	dw	11057
	dw	13105
	dw	13105
	dw	12083
	dw	13619
	dw	14129
	dw	13111
	dw	2829
	dw	3851
	dw	3341
	dw	3856
	dw	4367
	dw	4369
	dw	2111
	dw	6144
	dw	7193
	dw	6681
	dw	6941
	dw	7708
	dw	7452
	dw	12575
	dw	8
	dw	5663
	dw	8211
	dw	4887
	dw	6178
	dw	9237
	dw	5914
	dw	7207
	dw	10521
	dw	6686
	dw	3102
	dw	9482
	dw	3603
	dw	6439
	dw	10512
	dw	4638
	dw	9259
	dw	11540
	dw	5929
	dw	12079
	dw	6426
	dw	4891
	dw	7963
	dw	8211
	dw	5669
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s12_logic	dw	id_foster
	dw	id_joey
	dw	id_anita
	dw	id_anita_spy
	dw	id_lamb
	dw	id_lift_s7
	dw	id_lift7_light
	dw	id_foreman
	dw	id_top_belt
	dw	id_pipes
	dw	id_bot_belt
	dw	id_cogs
	dw	id_gears
	dw	id_belt1
	dw	id_belt2
	dw	id_pipe1
	dw	id_pipe2
	dw	id_pipe3
	dw	id_pipe4
	dw	id_welder
	dw	id_cable_7
	dw	$ffff
	dw	id_menu_logic


s12_mouse	dw	id_joey
	dw	id_factory_exit
	dw	id_fact1_exit
	dw	id_anita
	dw	id_lamb
	dw	id_stump
	dw	id_console_12
	dw	id_s12_floor
	dw	id_anita_spy
	dw	id_welder
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s12_floor	dw	0
	dw	st_mouse
	dw	0
	dw	12
	dw	NULL
	dd	s12_floor_table
	dw	184
	dw	216
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	79
	dw	floor_action



end32save_data

start32data



s12_floor_table	dw	id_s12_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s12_left_on
	dw	1
	dw	s12_right_on
	dw	4
	dw	GT_tick_off
	dw	5
	dw	GT_tour_1
	dw	id_factory_exit
	dw	get_to_factory_exit
	dw	id_fact1_exit
	dw	GT_fact1_exit
	dw	id_anita
	dw	GT_anita
	dw	id_welder
	dw	GT_welder
	dw	id_stump
	dw	GT_stump
	dw	id_console_12
	dw	GT_console_12
	dw	id_std_left_talk
	dw	GT_l_talk_12
	dw	id_std_right_talk
	dw	GT_r_talk_12
	dw	-1


rs_foster_7_12	dw	c_xcood
	dw	144
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	12
	dw	c_place
	dw	id_s12_floor
	dw	-1


joey_list_12	dw	230
	dw	376
	dw	256
	dw	272
	dw	1
	dw	0



end32data

start32save_data



factory_exit	dw	0
	dw	st_mouse
	dw	0
	dw	12
	dw	NULL
	dd	0
	dw	171
	dw	190
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	190-171
	dw	248-190
	dw	factory_exit_action



end32save_data

start32data



rs_foster_12_7	dw	c_xcood
	dw	376
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	7
	dw	c_place
	dw	id_s7_floor
	dw	-1


rs_joey_start_12	dw	c_xcood
	dw	256
	dw	c_ycood
	dw	264
	dw	c_place
	dw	id_s12_floor
	dw	c_screen
	dw	12
	dw	c_mode
	dw	0
	dw	c_base_sub
	dw	joey_logic
	dw	c_base_sub+2
	dw	0
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	c_dir
	dw	right
	dw	-1



end32data

start32save_data



fact1_right_exit	dw	0
	dw	st_mouse
	dw	0
	dw	12
	dw	NULL
	dd	0
	dw	432
	dw	190
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	1000
	dw	295-190
	dw	fact1_exit_action



end32save_data

start32data



anita_work_seq	dw	s27
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	4
	dw	343
	dw	178
	dw	4
	dw	343
	dw	178
	dw	5
	dw	343
	dw	178
	dw	5
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	7
	dw	343
	dw	178
	dw	7
	dw	343
	dw	178
	dw	8
	dw	343
	dw	178
	dw	8
	dw	343
	dw	178
	dw	9
	dw	343
	dw	178
	dw	9
	dw	343
	dw	178
	dw	10
	dw	343
	dw	178
	dw	10
	dw	343
	dw	178
	dw	11
	dw	343
	dw	178
	dw	11
	dw	343
	dw	178
	dw	9
	dw	343
	dw	178
	dw	9
	dw	343
	dw	178
	dw	12
	dw	343
	dw	178
	dw	12
	dw	343
	dw	178
	dw	13
	dw	343
	dw	178
	dw	13
	dw	343
	dw	178
	dw	14
	dw	343
	dw	178
	dw	14
	dw	343
	dw	178
	dw	15
	dw	343
	dw	178
	dw	15
	dw	343
	dw	178
	dw	16
	dw	343
	dw	178
	dw	16
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	4
	dw	343
	dw	178
	dw	4
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	5
	dw	343
	dw	178
	dw	5
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	7
	dw	343
	dw	178
	dw	7
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	6
	dw	343
	dw	178
	dw	7
	dw	343
	dw	178
	dw	7
	dw	$157
	dw	$b3
	dw	0
	dw	0



end32data

start32save_data



topbelt	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s91
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



topbelt_seq	dw	s91
	dw	222
	dw	180
	dw	0
	dw	222
	dw	180
	dw	1
	dw	222
	dw	180
	dw	2
	dw	222
	dw	180
	dw	3
	dw	222
	dw	180
	dw	4
	dw	222
	dw	180
	dw	5
	dw	222
	dw	180
	dw	6
	dw	222
	dw	180
	dw	7
	dw	222
	dw	180
	dw	8
	dw	222
	dw	180
	dw	9
	dw	222
	dw	180
	dw	10
	dw	222
	dw	180
	dw	11
	dw	222
	dw	180
	dw	12
	dw	222
	dw	180
	dw	13
	dw	222
	dw	180
	dw	14
	dw	222
	dw	180
	dw	15
	dw	222
	dw	180
	dw	16
	dw	222
	dw	180
	dw	17
	dw	222
	dw	180
	dw	18
	dw	222
	dw	180
	dw	19
	dw	222
	dw	180
	dw	20
	dw	222
	dw	180
	dw	21
	dw	222
	dw	180
	dw	22
	dw	222
	dw	180
	dw	23
	dw	222
	dw	180
	dw	24
	dw	222
	dw	180
	dw	25
	dw	222
	dw	180
	dw	26
	dw	222
	dw	180
	dw	27
	dw	222
	dw	180
	dw	28
	dw	222
	dw	180
	dw	29
	dw	222
	dw	180
	dw	30
	dw	222
	dw	180
	dw	31
	dw	222
	dw	180
	dw	32
	dw	222
	dw	180
	dw	33
	dw	222
	dw	180
	dw	34
	dw	222
	dw	180
	dw	35
	dw	222
	dw	180
	dw	36
	dw	222
	dw	180
	dw	37
	dw	222
	dw	180
	dw	38
	dw	222
	dw	180
	dw	39
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	40
	dw	222
	dw	180
	dw	41
	dw	222
	dw	180
	dw	42
	dw	0



end32data

start32save_data



botbelt	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	botbelt_logic
	dw	0



end32save_data

start32data



botbelt_seq	dw	s44
	dw	280
	dw	295
	dw	0
	dw	280
	dw	295
	dw	1
	dw	280
	dw	295
	dw	2
	dw	280
	dw	295
	dw	3
	dw	280
	dw	295
	dw	4
	dw	280
	dw	295
	dw	5
	dw	280
	dw	295
	dw	6
	dw	280
	dw	295
	dw	7
	dw	280
	dw	295
	dw	5
	dw	280
	dw	295
	dw	6
	dw	280
	dw	295
	dw	8
	dw	280
	dw	295
	dw	9
	dw	280
	dw	295
	dw	10
	dw	280
	dw	295
	dw	11
	dw	280
	dw	295
	dw	12
	dw	280
	dw	295
	dw	13
	dw	280
	dw	295
	dw	14
	dw	280
	dw	295
	dw	15
	dw	280
	dw	295
	dw	16
	dw	280
	dw	295
	dw	17
	dw	280
	dw	295
	dw	18
	dw	280
	dw	295
	dw	19
	dw	280
	dw	295
	dw	20
	dw	280
	dw	295
	dw	21
	dw	280
	dw	295
	dw	22
	dw	280
	dw	295
	dw	23
	dw	280
	dw	295
	dw	24
	dw	280
	dw	295
	dw	25
	dw	280
	dw	295
	dw	26
	dw	280
	dw	295
	dw	27
	dw	280
	dw	295
	dw	28
	dw	280
	dw	295
	dw	29
	dw	280
	dw	295
	dw	30
	dw	280
	dw	295
	dw	31
	dw	280
	dw	295
	dw	7
	dw	280
	dw	295
	dw	5
	dw	280
	dw	295
	dw	6
	dw	280
	dw	295
	dw	7
	dw	280
	dw	295
	dw	5
	dw	280
	dw	295
	dw	6
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	32
	dw	280
	dw	295
	dw	33
	dw	0



end32data

start32save_data



pipes	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s92
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



pipes_seq	dw	s92
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	3
	dw	281
	dw	206
	dw	4
	dw	281
	dw	206
	dw	5
	dw	281
	dw	206
	dw	6
	dw	281
	dw	206
	dw	7
	dw	281
	dw	206
	dw	8
	dw	281
	dw	206
	dw	9
	dw	281
	dw	206
	dw	10
	dw	281
	dw	206
	dw	11
	dw	281
	dw	206
	dw	12
	dw	281
	dw	206
	dw	13
	dw	281
	dw	206
	dw	14
	dw	281
	dw	206
	dw	15
	dw	281
	dw	206
	dw	16
	dw	281
	dw	206
	dw	17
	dw	281
	dw	206
	dw	18
	dw	281
	dw	206
	dw	19
	dw	281
	dw	206
	dw	20
	dw	281
	dw	206
	dw	21
	dw	281
	dw	206
	dw	22
	dw	281
	dw	206
	dw	23
	dw	281
	dw	206
	dw	24
	dw	281
	dw	206
	dw	0
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	1
	dw	281
	dw	206
	dw	2
	dw	0



end32data

start32save_data



anita_spy	dw	l_script
	dw	st_logic
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	375
	dw	151
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	1
	dw	1
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	anita_spy_logic
	dw	0



end32save_data

start32data



anita_turn_seq	dw	s29
	dw	343
	dw	178
	dw	0
	dw	343
	dw	178
	dw	1
	dw	343
	dw	178
	dw	2
	dw	343
	dw	178
	dw	3
	dw	343
	dw	178
	dw	4
	dw	343
	dw	178
	dw	5
	dw	0


anita_walk_seq	dw	s90
	dw	352
	dw	181
	dw	0
	dw	352
	dw	184
	dw	1
	dw	351
	dw	185
	dw	2
	dw	351
	dw	187
	dw	3
	dw	351
	dw	189
	dw	4
	dw	351
	dw	192
	dw	5
	dw	351
	dw	193
	dw	6
	dw	352
	dw	195
	dw	7
	dw	352
	dw	197
	dw	0
	dw	352
	dw	200
	dw	1
	dw	351
	dw	201
	dw	2
	dw	351
	dw	203
	dw	3
	dw	351
	dw	205
	dw	4
	dw	351
	dw	208
	dw	5
	dw	351
	dw	209
	dw	6
	dw	352
	dw	211
	dw	7
	dw	352
	dw	211
	dw	8
	dw	352
	dw	211
	dw	9
	dw	351
	dw	211
	dw	10
	dw	355
	dw	212
	dw	11
	dw	363
	dw	211
	dw	12
	dw	368
	dw	211
	dw	13
	dw	367
	dw	211
	dw	14
	dw	371
	dw	212
	dw	15
	dw	380
	dw	211
	dw	16
	dw	384
	dw	211
	dw	9
	dw	383
	dw	211
	dw	10
	dw	387
	dw	212
	dw	11
	dw	395
	dw	211
	dw	12
	dw	400
	dw	211
	dw	13
	dw	399
	dw	211
	dw	14
	dw	403
	dw	212
	dw	15
	dw	412
	dw	211
	dw	16
	dw	416
	dw	211
	dw	9
	dw	415
	dw	211
	dw	10
	dw	419
	dw	212
	dw	11
	dw	425
	dw	211
	dw	17
	dw	425
	dw	211
	dw	18
	dw	425
	dw	211
	dw	19
	dw	425
	dw	212
	dw	20
	dw	425
	dw	215
	dw	21
	dw	0


anita_turn_back	dw	s29
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



welder	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	$fb
	dw	$bb
	dw	s45
	dw	59
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	NULL
	dw	24
	dw	40
	dw	welder_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	welder_logic
	dw	0



end32save_data

start32data



welder_seq	dw	s45
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	0
	dw	0


factory_spanner_seq	dw	s46
	dw	239
	dw	195
	dw	0
	dw	239
	dw	195
	dw	0
	dw	239
	dw	195
	dw	1
	dw	239
	dw	195
	dw	1
	dw	239
	dw	195
	dw	2
	dw	239
	dw	195
	dw	3
	dw	239
	dw	195
	dw	4
	dw	239
	dw	195
	dw	5
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	7
	dw	239
	dw	195
	dw	8
	dw	239
	dw	195
	dw	9
	dw	239
	dw	195
	dw	7
	dw	239
	dw	195
	dw	10
	dw	239
	dw	195
	dw	10
	dw	239
	dw	195
	dw	11
	dw	239
	dw	195
	dw	12
	dw	0


swap1_seq	dw	s69
	dw	248
	dw	184
	dw	0
	dw	248
	dw	184
	dw	1
	dw	248
	dw	184
	dw	2
	dw	248
	dw	184
	dw	3
	dw	248
	dw	184
	dw	4
	dw	248
	dw	184
	dw	5
	dw	248
	dw	184
	dw	6
	dw	248
	dw	184
	dw	7
	dw	248
	dw	184
	dw	8
	dw	248
	dw	184
	dw	9
	dw	248
	dw	184
	dw	10
	dw	248
	dw	184
	dw	11
	dw	248
	dw	184
	dw	10
	dw	248
	dw	184
	dw	12
	dw	248
	dw	184
	dw	13
	dw	248
	dw	184
	dw	14
	dw	248
	dw	184
	dw	15
	dw	248
	dw	184
	dw	16
	dw	248
	dw	184
	dw	17
	dw	248
	dw	184
	dw	18
	dw	248
	dw	184
	dw	19
	dw	0


swap2_seq	dw	s70
	dw	252
	dw	183
	dw	0
	dw	251
	dw	183
	dw	1
	dw	250
	dw	183
	dw	2
	dw	248
	dw	183
	dw	3
	dw	249
	dw	183
	dw	4
	dw	248
	dw	183
	dw	5
	dw	248
	dw	183
	dw	6
	dw	247
	dw	183
	dw	7
	dw	244
	dw	183
	dw	8
	dw	241
	dw	183
	dw	9
	dw	237
	dw	183
	dw	10
	dw	235
	dw	183
	dw	11
	dw	0


swap3_seq	dw	s71
	dw	222
	dw	184
	dw	0
	dw	222
	dw	184
	dw	1
	dw	222
	dw	184
	dw	2
	dw	220
	dw	184
	dw	3
	dw	219
	dw	184
	dw	4
	dw	218
	dw	184
	dw	5
	dw	219
	dw	184
	dw	6
	dw	220
	dw	184
	dw	7
	dw	219
	dw	185
	dw	8
	dw	219
	dw	186
	dw	9
	dw	221
	dw	185
	dw	10
	dw	222
	dw	185
	dw	11
	dw	222
	dw	185
	dw	12
	dw	222
	dw	185
	dw	11
	dw	221
	dw	185
	dw	10
	dw	220
	dw	185
	dw	13
	dw	221
	dw	185
	dw	10
	dw	221
	dw	186
	dw	14
	dw	218
	dw	187
	dw	15
	dw	216
	dw	189
	dw	16
	dw	218
	dw	187
	dw	17
	dw	219
	dw	186
	dw	18
	dw	220
	dw	186
	dw	19
	dw	221
	dw	186
	dw	20
	dw	220
	dw	186
	dw	19
	dw	0


cant_lift_seq	dw	s69
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	12
	dw	1
	dw	1
	dw	13
	dw	1
	dw	1
	dw	14
	dw	1
	dw	1
	dw	15
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	1
	dw	0



end32data

start32save_data



stump	dw	l_script
	dw	0
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	249
	dw	208
	dw	0
	dw	9282
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	NULL
	dw	279-249
	dw	230-208
	dw	stump_action


console_12	dw	0
	dw	0
	dw	0
	dw	12
	dw	NULL
	dd	NULL
	dw	341
	dw	197
	dw	0
	dw	8371
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	NULL
	dw	368-341
	dw	6
	dw	console_12_action



end32save_data

start32data



rs_lamb_start_fact	dw	c_xcood
	dw	336
	dw	c_ycood
	dw	224
	dw	c_screen
	dw	12
	dw	c_place
	dw	id_s12_floor
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	-1



end32data

start32save_data



end32save_data
