start32data



new_13_chip	dw	131+disk_2
	dw	132+disk_2
	dw	136+disk_2
	dw	137+disk_2
	dw	63+disk_3
	dw	64+disk_3+$8000
	dw	65+disk_3+$8000
	dw	68+disk_3+$8000
	dw	48+disk_3
	dw	60+disk_3
	dw	61+disk_3
	dw	55+disk_3+$8000
	dw	62+disk_3
	dw	66+disk_3
	dw	67+disk_3
	dw	89+disk_3
	dw	17+disk_3
	dw	18+disk_3
	dw	0


s13_chip_list	dw	173
	dw	111
	dw	136+disk_2
	dw	137+disk_2
	dw	63+disk_3
	dw	64+disk_3+$8000
	dw	65+disk_3+$8000
	dw	68+disk_3+$8000
	dw	48+disk_3
	dw	60+disk_3
	dw	61+disk_3
	dw	55+disk_3+$8000
	dw	62+disk_3
	dw	66+disk_3
	dw	67+disk_3
	dw	89+disk_3
	dw	138+disk_3+$8000
	dw	139+disk_3+$8000
	dw	143+disk_3+$8000
	dw	17+disk_3
	dw	18+disk_3
	dw	0


s13_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	20+disk_3
	dw	140+disk_3
	dw	141+disk_3
	dw	142+disk_3
	dw	47+disk_3
	dw	56+disk_3
	dw	57+disk_3
	dw	58+disk_3
	dw	59+disk_3
	dw	0


grid13	dd 0 dup (0)

s13_pal	dw	0
	dw	1024
	dw	1028
	dw	1028
	dw	1542
	dw	1028
	dw	1542
	dw	2054
	dw	1030
	dw	2054
	dw	2056
	dw	2056
	dw	2060
	dw	3078
	dw	2056
	dw	2062
	dw	2568
	dw	2570
	dw	2572
	dw	2568
	dw	3084
	dw	3084
	dw	4620
	dw	2060
	dw	3598
	dw	4620
	dw	2572
	dw	3598
	dw	4110
	dw	3598
	dw	4112
	dw	5648
	dw	3086
	dw	4114
	dw	4622
	dw	4112
	dw	4624
	dw	5650
	dw	3088
	dw	3102
	dw	6154
	dw	3600
	dw	3614
	dw	4620
	dw	5140
	dw	4630
	dw	5138
	dw	3094
	dw	5140
	dw	5138
	dw	5140
	dw	4634
	dw	6160
	dw	3604
	dw	4636
	dw	7696
	dw	4114
	dw	5654
	dw	8982
	dw	3600
	dw	6166
	dw	6160
	dw	5142
	dw	6164
	dw	9494
	dw	3088
	dw	5150
	dw	6674
	dw	5142
	dw	4135
	dw	5646
	dw	4634
	dw	6166
	dw	6168
	dw	6168
	dw	5667
	dw	7180
	dw	5656
	dw	4649
	dw	8462
	dw	4630
	dw	5157
	dw	8464
	dw	5142
	dw	6686
	dw	6158
	dw	7194
	dw	6177
	dw	10516
	dw	4116
	dw	6179
	dw	6676
	dw	6684
	dw	7706
	dw	6676
	dw	5662
	dw	7194
	dw	7196
	dw	6684
	dw	7713
	dw	8972
	dw	5658
	dw	5675
	dw	10002
	dw	3610
	dw	6693
	dw	7190
	dw	7710
	dw	7201
	dw	10010
	dw	5658
	dw	8476
	dw	7192
	dw	8478
	dw	8478
	dw	10008
	dw	6172
	dw	7713
	dw	9502
	dw	6686
	dw	7715
	dw	7710
	dw	8481
	dw	8489
	dw	9996
	dw	6686
	dw	8990
	dw	10524
	dw	6686
	dw	8481
	dw	8481
	dw	8995
	dw	10017
	dw	11032
	dw	4131
	dw	8489
	dw	8476
	dw	9507
	dw	9517
	dw	11020
	dw	7201
	dw	9515
	dw	10000
	dw	8483
	dw	9507
	dw	8995
	dw	9509
	dw	10531
	dw	11034
	dw	7715
	dw	10533
	dw	12060
	dw	3623
	dw	9005
	dw	9502
	dw	8489
	dw	10021
	dw	11559
	dw	7717
	dw	10023
	dw	9509
	dw	10535
	dw	10545
	dw	11534
	dw	8485
	dw	11047
	dw	11036
	dw	9511
	dw	10535
	dw	10537
	dw	7725
	dw	10539
	dw	10535
	dw	9517
	dw	11049
	dw	11051
	dw	11051
	dw	11055
	dw	11045
	dw	9007
	dw	11055
	dw	11049
	dw	11565
	dw	12077
	dw	11567
	dw	10545
	dw	12591
	dw	12591
	dw	11569
	dw	13619
	dw	13617
	dw	13111
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s13_logic	dw	id_foster
	dw	id_joey
	dw	id_lamb
	dw	id_lift_s7
	dw	id_lift7_light
	dw	id_foreman
	dw	id_top_belt
	dw	id_pipes
	dw	id_bot_belt
	dw	id_welder
	dw	id_cogs
	dw	id_gears
	dw	id_belt1
	dw	id_belt2
	dw	id_pipe1
	dw	id_pipe2
	dw	id_pipe3
	dw	id_pipe4
	dw	id_sensor
	dw	id_lite1
	dw	id_lite2
	dw	id_fact_console
	dw	id_coat
	dw	id_fact2_spy
	dw	177
	dw	$ffff
	dw	id_menu_logic


s13_mouse	dw	id_joey
	dw	id_foreman
	dw	id_fact2_l_exit
	dw	id_fact2_r_exit
	dw	id_f2_store_exit
	dw	id_cogs
	dw	id_fact2_spy
	dw	id_sensors
	dw	id_fact_console
	dw	id_s13_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s13_floor	dw	0
	dw	st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	s13_floor_table
	dw	128
	dw	216
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	71
	dw	floor_action



end32save_data

start32data



s13_floor_table	dw	id_s13_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s13_left_on
	dw	1
	dw	s13_right_on
	dw	3
	dw	on_from_s15
	dw	4
	dw	GT_store_stop
	dw	5
	dw	GT_tour_2
	dw	id_lite1
	dw	GT_lite1
	dw	id_fact2_l_exit
	dw	GT_fact2_l_exit
	dw	id_fact2_r_exit
	dw	GT_fact2_r_exit
	dw	id_f2_store_exit
	dw	GT_fact2_store_exit
	dw	id_cogs
	dw	GT_cogs
	dw	id_std_left_talk
	dw	GT_l_talk_13
	dw	id_std_right_talk
	dw	GT_r_talk_13
	dw	id_fact2_spy
	dw	GT_window
	dw	id_sensors
	dw	GT_sensors
	dw	id_fact_console
	dw	GT_fact_console
	dw	-1


rs_foster_12_13	dw	c_xcood
	dw	120
	dw	c_ycood
	dw	280
	dw	c_screen
	dw	13
	dw	c_place
	dw	id_s13_floor
	dw	-1



end32data

start32save_data



fact2_exit_left	dw	0
	dw	st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	0
	dw	126
	dw	136
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	11
	dw	300
	dw	fact2_action



end32save_data

start32data



rs_foster_13_12	dw	c_xcood
	dw	456
	dw	c_screen
	dw	12
	dw	c_place
	dw	id_s12_floor
	dw	-1



end32data

start32save_data



fact2_exit_right	dw	0
	dw	st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	0
	dw	432
	dw	174
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	16
	dw	267-174
	dw	fact2_right_action


fact2_store_exit	dw	0
	dw	st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	0
	dw	203
	dw	175
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	8
	dw	238-175
	dw	fact2_store_action


cogs	dw	l_script
	dw	st_background+st_logic+st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s47
	dw	8255
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	1
	dw	0
	dw	21
	dw	7
	dw	cogs_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



cogs_seq	dw	s47
	dw	294
	dw	218
	dw	0
	dw	294
	dw	218
	dw	1
	dw	294
	dw	218
	dw	2
	dw	0



end32data

start32save_data



gears	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s48
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



gears_seq	dw	s48
	dw	284
	dw	291
	dw	0
	dw	284
	dw	291
	dw	1
	dw	284
	dw	291
	dw	2
	dw	0



end32data

start32save_data



belts1	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s60
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



belts1_seq	dw	s60
	dw	217
	dw	174
	dw	0
	dw	217
	dw	174
	dw	1
	dw	217
	dw	174
	dw	2
	dw	217
	dw	174
	dw	3
	dw	217
	dw	174
	dw	4
	dw	217
	dw	174
	dw	5
	dw	217
	dw	174
	dw	6
	dw	217
	dw	174
	dw	7
	dw	217
	dw	174
	dw	8
	dw	217
	dw	174
	dw	9
	dw	217
	dw	174
	dw	10
	dw	217
	dw	174
	dw	11
	dw	217
	dw	174
	dw	12
	dw	217
	dw	174
	dw	13
	dw	217
	dw	174
	dw	14
	dw	217
	dw	174
	dw	15
	dw	217
	dw	174
	dw	16
	dw	217
	dw	174
	dw	17
	dw	217
	dw	174
	dw	18
	dw	217
	dw	174
	dw	19
	dw	217
	dw	174
	dw	20
	dw	217
	dw	174
	dw	21
	dw	217
	dw	174
	dw	22
	dw	217
	dw	174
	dw	23
	dw	217
	dw	174
	dw	24
	dw	217
	dw	174
	dw	25
	dw	217
	dw	174
	dw	26
	dw	217
	dw	174
	dw	27
	dw	217
	dw	174
	dw	28
	dw	217
	dw	174
	dw	29
	dw	217
	dw	174
	dw	30
	dw	217
	dw	174
	dw	31
	dw	217
	dw	174
	dw	32
	dw	217
	dw	174
	dw	33
	dw	217
	dw	174
	dw	34
	dw	217
	dw	174
	dw	35
	dw	217
	dw	174
	dw	36
	dw	217
	dw	174
	dw	37
	dw	217
	dw	174
	dw	38
	dw	217
	dw	174
	dw	39
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	40
	dw	217
	dw	174
	dw	41
	dw	0



end32data

start32save_data



belts2	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s61
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



belts2_seq	dw	s61
	dw	368
	dw	184
	dw	0
	dw	368
	dw	184
	dw	1
	dw	368
	dw	184
	dw	2
	dw	368
	dw	184
	dw	3
	dw	368
	dw	184
	dw	4
	dw	368
	dw	184
	dw	5
	dw	368
	dw	184
	dw	6
	dw	368
	dw	184
	dw	7
	dw	368
	dw	184
	dw	8
	dw	368
	dw	184
	dw	9
	dw	368
	dw	184
	dw	10
	dw	368
	dw	184
	dw	11
	dw	368
	dw	184
	dw	12
	dw	368
	dw	184
	dw	13
	dw	368
	dw	184
	dw	14
	dw	368
	dw	184
	dw	15
	dw	368
	dw	184
	dw	16
	dw	368
	dw	184
	dw	17
	dw	368
	dw	184
	dw	18
	dw	368
	dw	184
	dw	19
	dw	368
	dw	184
	dw	20
	dw	368
	dw	184
	dw	21
	dw	368
	dw	184
	dw	22
	dw	368
	dw	184
	dw	23
	dw	368
	dw	184
	dw	24
	dw	368
	dw	184
	dw	25
	dw	368
	dw	184
	dw	26
	dw	368
	dw	184
	dw	27
	dw	368
	dw	184
	dw	28
	dw	368
	dw	184
	dw	29
	dw	368
	dw	184
	dw	30
	dw	368
	dw	184
	dw	31
	dw	368
	dw	184
	dw	32
	dw	368
	dw	184
	dw	33
	dw	368
	dw	184
	dw	34
	dw	368
	dw	184
	dw	35
	dw	368
	dw	184
	dw	36
	dw	368
	dw	184
	dw	37
	dw	368
	dw	184
	dw	38
	dw	368
	dw	184
	dw	39
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	40
	dw	368
	dw	184
	dw	41
	dw	0



end32data

start32save_data



pipe1	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s56
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



pipe1_seq	dw	s56
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	$ec
	dw	$c4
	dw	0
	dw	0



end32data

start32save_data



pipe2	dw	l_script
	dw	st_recreate+st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	$120
	dw	$c9
	dw	s57
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



pipe2_seq	dw	s57
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	$120
	dw	$c9
	dw	0
	dw	0



end32data

start32save_data



pipe3	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s58
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



pipe3_seq	dw	s58
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	$146
	dw	$c4
	dw	0
	dw	0



end32data

start32save_data



pipe4	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s59
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	std_fact_logic
	dw	0



end32save_data

start32data



pipe4_seq	dw	s59
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	348
	dw	241
	dw	0
	dw	$14c
	dw	$123
	dw	0
	dw	0


fost_cog_seq	dw	s55
	dw	288
	dw	184
	dw	0
	dw	288
	dw	184
	dw	1
	dw	288
	dw	184
	dw	2
	dw	288
	dw	184
	dw	3
	dw	288
	dw	184
	dw	4
	dw	288
	dw	184
	dw	5
	dw	288
	dw	184
	dw	6
	dw	288
	dw	184
	dw	7
	dw	288
	dw	184
	dw	7
	dw	288
	dw	184
	dw	8
	dw	288
	dw	184
	dw	8
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	9
	dw	288
	dw	184
	dw	8
	dw	288
	dw	184
	dw	8
	dw	288
	dw	184
	dw	7
	dw	288
	dw	184
	dw	7
	dw	288
	dw	184
	dw	6
	dw	288
	dw	184
	dw	1
	dw	288
	dw	184
	dw	0
	dw	0



end32data

start32save_data



sensor	dw	l_script
	dw	st_logic+st_recreate
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s59
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	sensor_logic
	dw	0



end32save_data

start32data



sensor_seq	dw	s62
	dw	222
	dw	194
	dw	0
	dw	222
	dw	194
	dw	1
	dw	222
	dw	194
	dw	2
	dw	0



end32data

start32save_data



lite1	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	13
	dw	NULL
	dd	lite1_table
	dw	28
	dw	36
	dw	s59
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0



end32save_data

start32data



lite1_table	dw	id_std_right_talk
	dw	GT_r_talk_13
	dw	-1


lite1_seq	dw	s66
	dw	417
	dw	203
	dw	0
	dw	417
	dw	203
	dw	0
	dw	417
	dw	203
	dw	0
	dw	417
	dw	203
	dw	1
	dw	417
	dw	203
	dw	1
	dw	417
	dw	203
	dw	1
	dw	0



end32data

start32save_data



lite2	dw	l_script
	dw	st_logic+st_background
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	28
	dw	36
	dw	s59
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	animate_logic
	dw	0



end32save_data

start32data



lite2_seq	dw	s67
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	0
	dw	417
	dw	206
	dw	1
	dw	417
	dw	206
	dw	1
	dw	417
	dw	206
	dw	1
	dw	417
	dw	206
	dw	1
	dw	0


foreman_work_seq	dw	s65
	dw	259
	dw	190
	dw	0
	dw	259
	dw	190
	dw	0
	dw	259
	dw	190
	dw	1
	dw	259
	dw	190
	dw	1
	dw	259
	dw	190
	dw	2
	dw	259
	dw	190
	dw	2
	dw	259
	dw	190
	dw	3
	dw	259
	dw	190
	dw	3
	dw	259
	dw	190
	dw	4
	dw	259
	dw	190
	dw	4
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	4
	dw	259
	dw	190
	dw	4
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	5
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	6
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	7
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	8
	dw	259
	dw	190
	dw	3
	dw	259
	dw	190
	dw	3
	dw	259
	dw	190
	dw	2
	dw	259
	dw	190
	dw	2
	dw	259
	dw	190
	dw	9
	dw	259
	dw	190
	dw	9
	dw	259
	dw	190
	dw	10
	dw	259
	dw	190
	dw	10
	dw	259
	dw	190
	dw	11
	dw	259
	dw	190
	dw	11
	dw	259
	dw	190
	dw	12
	dw	259
	dw	190
	dw	12
	dw	259
	dw	190
	dw	13
	dw	259
	dw	190
	dw	13
	dw	259
	dw	190
	dw	14
	dw	259
	dw	190
	dw	14
	dw	259
	dw	190
	dw	15
	dw	259
	dw	190
	dw	15
	dw	259
	dw	190
	dw	16
	dw	259
	dw	190
	dw	16
	dw	0



end32data

start32save_data



fact2_spy_and_window	dw	l_script
	dw	st_logic+st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	145
	dw	213
	dw	NULL
	dw	9218
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	171-145
	dw	235-213
	dw	window_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	fact2_spy_logic
	dw	0


fact_console	dw	l_script
	dw	st_logic+st_background+st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	$1a2
	dw	$c3
	dw	s89
	dw	8371
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	10
	dw	10
	dw	console_13_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	fact_console_logic
	dw	0



end32save_data

start32data



fact_console_seq	dw	s89
	dw	418
	dw	196
	dw	0
	dw	418
	dw	196
	dw	1
	dw	418
	dw	196
	dw	2
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	3
	dw	418
	dw	196
	dw	4
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	6
	dw	418
	dw	196
	dw	7
	dw	418
	dw	196
	dw	7
	dw	418
	dw	196
	dw	7
	dw	418
	dw	196
	dw	8
	dw	418
	dw	196
	dw	8
	dw	418
	dw	196
	dw	8
	dw	418
	dw	196
	dw	8
	dw	418
	dw	196
	dw	8
	dw	418
	dw	196
	dw	9
	dw	418
	dw	196
	dw	10
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	11
	dw	418
	dw	196
	dw	12
	dw	418
	dw	196
	dw	13
	dw	418
	dw	196
	dw	14
	dw	418
	dw	196
	dw	15
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	17
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	18
	dw	418
	dw	196
	dw	19
	dw	418
	dw	196
	dw	20
	dw	418
	dw	196
	dw	21
	dw	418
	dw	196
	dw	22
	dw	418
	dw	196
	dw	23
	dw	418
	dw	196
	dw	24
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	25
	dw	418
	dw	196
	dw	26
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	27
	dw	418
	dw	196
	dw	28
	dw	418
	dw	196
	dw	29
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	5
	dw	418
	dw	196
	dw	30
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	31
	dw	418
	dw	196
	dw	32
	dw	418
	dw	196
	dw	33
	dw	418
	dw	196
	dw	34
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	35
	dw	418
	dw	196
	dw	36
	dw	418
	dw	196
	dw	37
	dw	418
	dw	196
	dw	38
	dw	418
	dw	196
	dw	39
	dw	418
	dw	196
	dw	40
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	418
	dw	196
	dw	16
	dw	0


fact_console_dead	dw	s89
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	0


rs_storeman	dw	c_xcood
	dw	288
	dw	c_ycood
	dw	232
	dw	c_frame
	dw	s63+34
	dw	c_place
	dw	id_s13_floor
	dw	c_mode
	dw	c_base_mode
	dw	c_base_sub
	dw	foreman_store_check
	dw	c_base_sub+2
	dw	0
	dw	c_dir
	dw	left
	dw	c_logic
	dw	l_script
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_mouse
	dw	-1


forfrisk_seq	dw	s138
	dw	243
	dw	163
	dw	0
	dw	243
	dw	163
	dw	0
	dw	243
	dw	163
	dw	1
	dw	243
	dw	163
	dw	2
	dw	243
	dw	163
	dw	3
	dw	243
	dw	163
	dw	4
	dw	243
	dw	163
	dw	5
	dw	243
	dw	163
	dw	6
	dw	243
	dw	163
	dw	2
	dw	243
	dw	163
	dw	7
	dw	243
	dw	163
	dw	8
	dw	243
	dw	163
	dw	9
	dw	243
	dw	163
	dw	10
	dw	243
	dw	163
	dw	11
	dw	243
	dw	163
	dw	12
	dw	243
	dw	163
	dw	1
	dw	243
	dw	163
	dw	0
	dw	243
	dw	163
	dw	0
	dw	0


armsup_seq	dw	s140
	dw	400
	dw	246
	dw	0
	dw	400
	dw	246
	dw	1
	dw	400
	dw	246
	dw	2
	dw	400
	dw	246
	dw	3
	dw	400
	dw	246
	dw	4
	dw	400
	dw	246
	dw	4
	dw	400
	dw	246
	dw	3
	dw	400
	dw	246
	dw	4
	dw	400
	dw	246
	dw	5
	dw	400
	dw	246
	dw	4
	dw	400
	dw	246
	dw	6
	dw	400
	dw	246
	dw	7
	dw	400
	dw	246
	dw	2
	dw	400
	dw	246
	dw	2
	dw	400
	dw	246
	dw	2
	dw	400
	dw	246
	dw	2
	dw	400
	dw	246
	dw	1
	dw	400
	dw	246
	dw	0
	dw	0


opencoat_seq	dw	s141
	dw	198
	dw	163
	dw	0
	dw	198
	dw	163
	dw	1
	dw	198
	dw	163
	dw	2
	dw	198
	dw	163
	dw	3
	dw	198
	dw	163
	dw	4
	dw	198
	dw	163
	dw	5
	dw	198
	dw	163
	dw	6
	dw	198
	dw	163
	dw	7
	dw	198
	dw	163
	dw	8
	dw	0


fsearch_seq	dw	s143
	dw	367
	dw	163
	dw	0
	dw	367
	dw	163
	dw	1
	dw	367
	dw	163
	dw	2
	dw	367
	dw	163
	dw	3
	dw	367
	dw	163
	dw	4
	dw	367
	dw	163
	dw	5
	dw	367
	dw	163
	dw	6
	dw	367
	dw	163
	dw	7
	dw	367
	dw	163
	dw	8
	dw	367
	dw	163
	dw	9
	dw	367
	dw	163
	dw	10
	dw	367
	dw	163
	dw	11
	dw	367
	dw	163
	dw	12
	dw	0


rs_foster	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_ar_priority+st_grid_plot+st_collision
	dw	-1


rs_foreman	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_mouse+st_collision
	dw	-1


closecoat	dw	s141
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


nu_s13_chip	dw	136+disk_2
	dw	137+disk_2
	dw	63+disk_3
	dw	64+disk_3
	dw	65+disk_3
	dw	68+disk_3
	dw	47+disk_3
	dw	48+disk_3
	dw	60+disk_3
	dw	61+disk_3
	dw	56+disk_3
	dw	57+disk_3
	dw	58+disk_3
	dw	59+disk_3
	dw	62+disk_3
	dw	66+disk_3
	dw	67+disk_3
	dw	89+disk_3
	dw	90+disk_6
	dw	106+disk_6
	dw	17+disk_3
	dw	18+disk_3
	dw	0



end32data

start32save_data



sensors	dw	l_script
	dw	st_mouse
	dw	0
	dw	13
	dw	NULL
	dd	NULL
	dw	212
	dw	195
	dw	0
	dw	8381
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	NULL
	dw	229-212
	dw	241-195
	dw	sensors_action


foreman	dw	l_script
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_mouse+st_collision
	dw	0
	dw	13
	dw	id_s13_floor
	dd	0
	dw	408
	dw	224+32
	dw	s63
	dw	4
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-16
	dw	-48
	dw	24
	dw	48
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	foreman_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	0
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_foreman
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	foreman_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	foreman_up
	dd	foreman_down
	dd	foreman_left
	dd	foreman_right
	dd	foreman_st_up
	dd	foreman_st_down
	dd	foreman_st_left
	dd	foreman_st_right
	dd	foreman_st_talk
	dd	0
	dd	foreman_u_to_d
	dd	foreman_u_to_l
	dd	foreman_u_to_r
	dd	0
	dd	foreman_d_to_u
	dd	0
	dd	foreman_d_to_l
	dd	foreman_d_to_r
	dd	0
	dd	foreman_l_to_u
	dd	foreman_l_to_d
	dd	0
	dd	foreman_l_to_r
	dd	0
	dd	foreman_r_to_u
	dd	foreman_r_to_d
	dd	foreman_r_to_l
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0


foreman_auto	db	64 dup (0)



end32save_data

start32data



foreman_left	dw	4
	dw	16+s63
	dw	-4
	dw	0
	dw	4
	dw	17+s63
	dw	-4
	dw	0
	dw	4
	dw	18+s63
	dw	-4
	dw	0
	dw	4
	dw	19+s63
	dw	-4
	dw	0
	dw	4
	dw	20+s63
	dw	-4
	dw	0
	dw	4
	dw	21+s63
	dw	-4
	dw	0
	dw	4
	dw	22+s63
	dw	-4
	dw	0
	dw	4
	dw	23+s63
	dw	-4
	dw	0
	dw	0


foreman_right	dw	4
	dw	24+s63
	dw	4
	dw	0
	dw	4
	dw	25+s63
	dw	4
	dw	0
	dw	4
	dw	26+s63
	dw	4
	dw	0
	dw	4
	dw	27+s63
	dw	4
	dw	0
	dw	4
	dw	28+s63
	dw	4
	dw	0
	dw	4
	dw	29+s63
	dw	4
	dw	0
	dw	4
	dw	30+s63
	dw	4
	dw	0
	dw	4
	dw	31+s63
	dw	4
	dw	0
	dw	0


foreman_up	dw	2
	dw	0+s63
	dw	0
	dw	-2
	dw	2
	dw	1+s63
	dw	0
	dw	-2
	dw	2
	dw	2+s63
	dw	0
	dw	-2
	dw	2
	dw	3+s63
	dw	0
	dw	-2
	dw	2
	dw	4+s63
	dw	0
	dw	-2
	dw	2
	dw	5+s63
	dw	0
	dw	-2
	dw	2
	dw	6+s63
	dw	0
	dw	-2
	dw	2
	dw	7+s63
	dw	0
	dw	-2
	dw	0


foreman_down	dw	2
	dw	8+s63
	dw	0
	dw	2
	dw	2
	dw	9+s63
	dw	0
	dw	2
	dw	2
	dw	10+s63
	dw	0
	dw	2
	dw	2
	dw	11+s63
	dw	0
	dw	2
	dw	2
	dw	12+s63
	dw	0
	dw	2
	dw	2
	dw	13+s63
	dw	0
	dw	2
	dw	2
	dw	14+s63
	dw	0
	dw	2
	dw	2
	dw	15+s63
	dw	0
	dw	2
	dw	0


foreman_st_up	dw	s63
	dw	1
	dw	1
	dw	36
	dw	0


foreman_st_down	dw	s63
	dw	1
	dw	1
	dw	32
	dw	0


foreman_st_left	dw	s63
	dw	1
	dw	1
	dw	34
	dw	0


foreman_st_right	dw	s63
	dw	1
	dw	1
	dw	38
	dw	0


foreman_st_talk	dw	s64
	dw	1
	dw	1
	dw	0
	dw	0


foreman_r_to_u	dw	45-8+s63
	dw	0


foreman_r_to_d	dw	47-8+s63
	dw	0


foreman_r_to_l	dw	45-8+s63
	dw	44-8+s63
	dw	43-8+s63
	dw	0


foreman_u_to_d	dw	43-8+s63
	dw	42-8+s63
	dw	41-8+s63
	dw	0


foreman_u_to_l	dw	43-8+s63
	dw	0


foreman_u_to_r	dw	45-8+s63
	dw	0


foreman_d_to_u	dw	47-8+s63
	dw	46-8+s63
	dw	45-8+s63
	dw	0


foreman_d_to_l	dw	41-8+s63
	dw	0


foreman_d_to_r	dw	47-8+s63
	dw	0


foreman_l_to_u	dw	43-8+s63
	dw	0


foreman_l_to_d	dw	41-8+s63
	dw	0


foreman_l_to_r	dw	41-8+s63
	dw	40-8+s63
	dw	47-8+s63
	dw	0



end32data

start32save_data



end32save_data
