start32data



s14_chip_list	dw	173
	dw	111
	dw	136+disk_2
	dw	137+disk_2
	dw	90+disk_6
	dw	96+disk_6+$8000
	dw	97+disk_6
	dw	106+disk_6
	dw	107+disk_6+$8000
	dw	28+disk_6
	dw	98+disk_6
	dw	43+disk_6
	dw	44+disk_6+$8000
	dw	21+disk_6
	dw	91+disk_6
	dw	0


s14_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	22+disk_6
	dw	23+disk_6
	dw	92+disk_6
	dw	27+disk_6
	dw	0


grid14	dd 0 dup (0)

s14_pal	dw	0
	dw	1536
	dw	1542
	dw	1544
	dw	2052
	dw	1542
	dw	2056
	dw	3080
	dw	1544
	dw	2570
	dw	3082
	dw	2570
	dw	2576
	dw	3080
	dw	3084
	dw	3088
	dw	3594
	dw	3598
	dw	3600
	dw	5644
	dw	2572
	dw	4110
	dw	4112
	dw	4112
	dw	4116
	dw	7180
	dw	2572
	dw	4118
	dw	4622
	dw	4626
	dw	3612
	dw	6668
	dw	3602
	dw	3619
	dw	9484
	dw	3086
	dw	5654
	dw	5136
	dw	5142
	dw	4636
	dw	5648
	dw	5142
	dw	5146
	dw	5652
	dw	5654
	dw	4135
	dw	8462
	dw	4628
	dw	6172
	dw	6158
	dw	6168
	dw	5667
	dw	6668
	dw	4634
	dw	4649
	dw	7182
	dw	5656
	dw	6686
	dw	6670
	dw	5658
	dw	5667
	dw	6676
	dw	6682
	dw	7196
	dw	12562
	dw	2578
	dw	5163
	dw	6672
	dw	7196
	dw	6181
	dw	7190
	dw	6684
	dw	6183
	dw	8978
	dw	4124
	dw	6691
	dw	11544
	dw	4630
	dw	7201
	dw	7194
	dw	7198
	dw	7207
	dw	9998
	dw	5658
	dw	8485
	dw	10508
	dw	2590
	dw	7710
	dw	8990
	dw	4641
	dw	8476
	dw	8481
	dw	6177
	dw	6193
	dw	11024
	dw	4636
	dw	8478
	dw	10529
	dw	3105
	dw	8990
	dw	10522
	dw	6172
	dw	8481
	dw	10529
	dw	4129
	dw	8483
	dw	9500
	dw	4133
	dw	7721
	dw	12058
	dw	4126
	dw	9003
	dw	8972
	dw	8995
	dw	9509
	dw	9498
	dw	7205
	dw	10023
	dw	11026
	dw	7201
	dw	10529
	dw	12058
	dw	5665
	dw	10019
	dw	8990
	dw	9509
	dw	9515
	dw	11540
	dw	7201
	dw	10029
	dw	11534
	dw	4135
	dw	10023
	dw	9502
	dw	9511
	dw	10035
	dw	11018
	dw	8485
	dw	10021
	dw	11049
	dw	6185
	dw	10025
	dw	10021
	dw	7723
	dw	10543
	dw	12564
	dw	3627
	dw	10535
	dw	12585
	dw	4139
	dw	10537
	dw	10023
	dw	8493
	dw	11055
	dw	12566
	dw	4653
	dw	11053
	dw	13603
	dw	5163
	dw	11051
	dw	11051
	dw	8495
	dw	12085
	dw	13582
	dw	4143
	dw	11565
	dw	11559
	dw	9007
	dw	12083
	dw	13592
	dw	5681
	dw	12077
	dw	11565
	dw	12079
	dw	12591
	dw	12069
	dw	10033
	dw	12079
	dw	14125
	dw	4659
	dw	12591
	dw	12591
	dw	10547
	dw	13623
	dw	14102
	dw	6709
	dw	13105
	dw	13105
	dw	12597
	dw	14135
	dw	14643
	dw	13625
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s14_logic	dw	id_anita
	dw	id_foster
	dw	id_joey
	dw	id_radman
	dw	id_foreman
	dw	id_locker1
	dw	id_coat
	dw	id_locker2
	dw	id_locker3
	dw	id_lamb
	dw	id_lift_s7
	dw	id_lift7_light
	dw	$ffff
	dw	id_menu_logic


s14_mouse	dw	id_joey
	dw	id_fact3_l_exit
	dw	id_fact3_r_exit
	dw	id_anita
	dw	id_radman
	dw	id_locker1
	dw	id_coat
	dw	id_locker2
	dw	id_locker3
	dw	id_machine
	dw	id_rad_screen
	dw	id_14_console
	dw	id_s14_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s14_floor	dw	0
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	s14_floor_table
	dw	128
	dw	216
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	71
	dw	floor_action



end32save_data

start32data



s14_floor_table	dw	id_s14_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s14_left_on
	dw	1
	dw	s14_right_on
	dw	id_fact3_l_exit
	dw	GT_fact3_l_exit
	dw	id_fact3_r_exit
	dw	GT_fact3_r_exit
	dw	id_locker1
	dw	GT_locker1
	dw	id_locker2
	dw	GT_locker2
	dw	id_locker3
	dw	GT_locker3
	dw	id_machine
	dw	GT_machine
	dw	id_rad_screen
	dw	GT_rad_screen
	dw	id_14_console
	dw	GT_14_console
	dw	id_coat
	dw	GT_coat
	dw	id_anita
	dw	GT_nu_anita
	dw	id_std_left_talk
	dw	GT_l_talk_14
	dw	id_std_right_talk
	dw	GT_r_talk_14
	dw	-1


rs_foster_13_14	dw	c_xcood
	dw	120
	dw	c_ycood
	dw	256
	dw	c_screen
	dw	14
	dw	c_place
	dw	id_s14_floor
	dw	-1



end32data

start32save_data



fact3_exit_left	dw	0
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	0
	dw	126
	dw	175
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	11
	dw	272-175
	dw	fact3_action



end32save_data

start32data



rs_foster_14_13	dw	c_xcood
	dw	456
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	13
	dw	c_place
	dw	id_s13_floor
	dw	-1


rs_anita_to_14	dw	c_xcood
	dw	227
	dw	c_ycood
	dw	189
	dw	c_screen
	dw	14
	dw	c_status
	dw	st_background+st_recreate+st_logic+st_mouse
	dw	c_base_sub
	dw	anita_work
	dw	c_base_sub+2
	dw	0
	dw	-1


joey_list_14	dw	230
	dw	376
	dw	248
	dw	272
	dw	1
	dw	0



end32data

start32save_data



fact3_exit_right	dw	0
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	0
	dw	381
	dw	184
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	403-381
	dw	263-184
	dw	fact3_r_action


locker3	dw	l_script
	dw	st_recreate+st_logic+st_background+st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	187
	dw	192
	dw	s91
	dw	8254
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	NULL
	dw	17
	dw	235-192
	dw	locker3_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	locker3_logic
	dw	0



end32save_data

start32data



locker_open_seq	dw	s91
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	0


locker_close_seq	dw	s91
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



locker2	dw	l_script
	dw	st_recreate+st_logic+st_background+st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	166
	dw	192
	dw	s91
	dw	8254
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	NULL
	dw	17
	dw	235-192
	dw	locker2_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	locker2_logic
	dw	0


locker1	dw	l_script
	dw	st_recreate+st_logic+st_background+st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	146
	dw	192
	dw	s91
	dw	8254
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	NULL
	dw	17
	dw	235-192
	dw	locker1_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	locker1_logic
	dw	0



end32save_data

start32data



open_locker_seq	dw	s92
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	1
	dw	237
	dw	184
	dw	2
	dw	237
	dw	184
	dw	3
	dw	237
	dw	184
	dw	4
	dw	237
	dw	184
	dw	5
	dw	237
	dw	184
	dw	6
	dw	0


close_locker_seq	dw	s92
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



machine	dw	l_script
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	316
	dw	174
	dw	0
	dw	9290
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	NULL
	dw	359-316
	dw	224-174
	dw	machine_action



end32save_data

start32data



start_joey_14	dw	c_xcood
	dw	256
	dw	c_ycood
	dw	264
	dw	c_place
	dw	id_s14_floor
	dw	c_screen
	dw	14
	dw	c_mode
	dw	0
	dw	c_base_sub
	dw	joey_logic
	dw	c_base_sub+2
	dw	0
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	c_dir
	dw	right
	dw	-1


rs_foster_16_14	dw	c_xcood
	dw	416
	dw	c_ycood
	dw	256
	dw	c_screen
	dw	14
	dw	c_place
	dw	id_s14_floor
	dw	-1



end32data

start32save_data



rad_screen	dw	l_script
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	292
	dw	195
	dw	0
	dw	9288
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	307-292
	dw	245-195
	dw	rad_screen_action


console_14	dw	l_script
	dw	st_mouse
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	216
	dw	204
	dw	0
	dw	8371
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	250-216
	dw	214-204
	dw	console_14_action


coat	dw	l_script
	dw	st_logic
	dw	0
	dw	14
	dw	NULL
	dd	NULL
	dw	$af
	dw	$cf
	dw	0
	dw	8377
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	10
	dw	225-$cf
	dw	coat_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	coat_logic
	dw	0



end32save_data

start32data



change1_seq	dw	s99
	dw	162
	dw	190
	dw	0
	dw	162
	dw	190
	dw	1
	dw	162
	dw	190
	dw	1
	dw	162
	dw	190
	dw	0
	dw	162
	dw	190
	dw	2
	dw	162
	dw	190
	dw	3
	dw	162
	dw	190
	dw	4
	dw	162
	dw	190
	dw	5
	dw	162
	dw	190
	dw	6
	dw	162
	dw	190
	dw	7
	dw	162
	dw	190
	dw	7
	dw	162
	dw	190
	dw	8
	dw	162
	dw	190
	dw	9
	dw	162
	dw	190
	dw	10
	dw	162
	dw	190
	dw	11
	dw	162
	dw	190
	dw	12
	dw	162
	dw	190
	dw	13
	dw	162
	dw	190
	dw	14
	dw	162
	dw	190
	dw	15
	dw	162
	dw	190
	dw	16
	dw	162
	dw	190
	dw	17
	dw	162
	dw	190
	dw	18
	dw	162
	dw	190
	dw	19
	dw	162
	dw	190
	dw	20
	dw	162
	dw	190
	dw	21
	dw	162
	dw	190
	dw	22
	dw	162
	dw	190
	dw	23
	dw	162
	dw	190
	dw	24
	dw	162
	dw	190
	dw	25
	dw	162
	dw	190
	dw	26
	dw	0


change2_seq	dw	s100
	dw	170
	dw	193
	dw	0
	dw	170
	dw	193
	dw	1
	dw	170
	dw	193
	dw	2
	dw	170
	dw	193
	dw	3
	dw	170
	dw	193
	dw	4
	dw	170
	dw	193
	dw	5
	dw	170
	dw	193
	dw	6
	dw	170
	dw	193
	dw	7
	dw	170
	dw	193
	dw	8
	dw	170
	dw	193
	dw	8
	dw	0


change3_seq	dw	s101
	dw	170
	dw	193
	dw	0
	dw	170
	dw	193
	dw	1
	dw	170
	dw	193
	dw	1
	dw	170
	dw	193
	dw	2
	dw	170
	dw	193
	dw	3
	dw	170
	dw	193
	dw	4
	dw	170
	dw	193
	dw	5
	dw	170
	dw	193
	dw	6
	dw	170
	dw	193
	dw	7
	dw	170
	dw	193
	dw	8
	dw	0


change4_seq	dw	s102
	dw	177
	dw	194
	dw	0
	dw	177
	dw	194
	dw	1
	dw	177
	dw	194
	dw	2
	dw	177
	dw	194
	dw	3
	dw	177
	dw	194
	dw	4
	dw	177
	dw	194
	dw	5
	dw	177
	dw	194
	dw	6
	dw	177
	dw	194
	dw	7
	dw	177
	dw	194
	dw	8
	dw	0


change5_seq	dw	s103
	dw	171
	dw	194
	dw	0
	dw	171
	dw	194
	dw	1
	dw	171
	dw	194
	dw	2
	dw	171
	dw	194
	dw	3
	dw	171
	dw	194
	dw	4
	dw	171
	dw	194
	dw	5
	dw	0


change6_seq	dw	s104
	dw	178
	dw	191
	dw	0
	dw	178
	dw	191
	dw	0
	dw	178
	dw	191
	dw	0
	dw	178
	dw	191
	dw	0
	dw	178
	dw	191
	dw	1
	dw	178
	dw	191
	dw	2
	dw	178
	dw	191
	dw	3
	dw	178
	dw	191
	dw	4
	dw	178
	dw	191
	dw	4
	dw	178
	dw	191
	dw	5
	dw	178
	dw	191
	dw	6
	dw	178
	dw	191
	dw	7
	dw	178
	dw	191
	dw	8
	dw	178
	dw	191
	dw	9
	dw	0


change_back6	dw	s105
	dw	162
	dw	190
	dw	0
	dw	162
	dw	190
	dw	1
	dw	162
	dw	190
	dw	2
	dw	162
	dw	190
	dw	3
	dw	162
	dw	190
	dw	4
	dw	162
	dw	190
	dw	5
	dw	162
	dw	190
	dw	6
	dw	162
	dw	190
	dw	7
	dw	162
	dw	190
	dw	8
	dw	162
	dw	190
	dw	8
	dw	162
	dw	190
	dw	9
	dw	162
	dw	190
	dw	9
	dw	162
	dw	190
	dw	10
	dw	162
	dw	190
	dw	11
	dw	162
	dw	190
	dw	12
	dw	162
	dw	190
	dw	13
	dw	162
	dw	190
	dw	14
	dw	162
	dw	190
	dw	14
	dw	162
	dw	190
	dw	15
	dw	162
	dw	190
	dw	16
	dw	162
	dw	190
	dw	17
	dw	162
	dw	190
	dw	18
	dw	162
	dw	190
	dw	19
	dw	162
	dw	190
	dw	19
	dw	162
	dw	190
	dw	20
	dw	162
	dw	190
	dw	20
	dw	162
	dw	190
	dw	20
	dw	162
	dw	190
	dw	19
	dw	162
	dw	190
	dw	19
	dw	162
	dw	190
	dw	21
	dw	0


change_back5	dw	s100
	dw	$aa
	dw	$c1
	dw	8
	dw	$aa
	dw	$c1
	dw	8
	dw	$aa
	dw	$c1
	dw	7
	dw	$aa
	dw	$c1
	dw	6
	dw	$aa
	dw	$c1
	dw	5
	dw	$aa
	dw	$c1
	dw	4
	dw	0


change_back4	dw	s101
	dw	$aa
	dw	$c1
	dw	8
	dw	$aa
	dw	$c1
	dw	7
	dw	$aa
	dw	$c1
	dw	6
	dw	$aa
	dw	$c1
	dw	5
	dw	$aa
	dw	$c1
	dw	4
	dw	$aa
	dw	$c1
	dw	3
	dw	$aa
	dw	$c1
	dw	2
	dw	$aa
	dw	$c1
	dw	1
	dw	$aa
	dw	$c1
	dw	1
	dw	$aa
	dw	$c1
	dw	0
	dw	0


change_back3	dw	s102
	dw	$b1
	dw	$c2
	dw	8
	dw	$b1
	dw	$c2
	dw	7
	dw	$b1
	dw	$c2
	dw	6
	dw	$b1
	dw	$c2
	dw	5
	dw	$b1
	dw	$c2
	dw	4
	dw	$b1
	dw	$c2
	dw	3
	dw	$b1
	dw	$c2
	dw	2
	dw	$b1
	dw	$c2
	dw	1
	dw	$b1
	dw	$c2
	dw	0
	dw	0


change_back2	dw	s103
	dw	$ab
	dw	$c2
	dw	5
	dw	$ab
	dw	$c2
	dw	4
	dw	$ab
	dw	$c2
	dw	3
	dw	$ab
	dw	$c2
	dw	2
	dw	$ab
	dw	$c2
	dw	1
	dw	$ab
	dw	$c2
	dw	0
	dw	0


change_back1	dw	s104
	dw	$b2
	dw	$bf
	dw	9
	dw	$b2
	dw	$bf
	dw	8
	dw	$b2
	dw	$bf
	dw	7
	dw	$b2
	dw	$bf
	dw	6
	dw	$b2
	dw	$bf
	dw	5
	dw	$b2
	dw	$bf
	dw	4
	dw	$b2
	dw	$bf
	dw	4
	dw	$b2
	dw	$bf
	dw	3
	dw	$b2
	dw	$bf
	dw	2
	dw	$b2
	dw	$bf
	dw	1
	dw	$b2
	dw	$bf
	dw	0
	dw	$b2
	dw	$bf
	dw	0
	dw	$b2
	dw	$bf
	dw	0
	dw	$b2
	dw	$bf
	dw	0
	dw	0


rad_open_locker	dw	s107
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	0
	dw	237
	dw	184
	dw	1
	dw	237
	dw	184
	dw	2
	dw	237
	dw	184
	dw	3
	dw	237
	dw	184
	dw	4
	dw	237
	dw	184
	dw	5
	dw	237
	dw	184
	dw	6
	dw	0


rad_close_locker	dw	s107
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


foster_give_seq	dw	s43
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


anita_give_seq	dw	s44
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



radman	dw	l_script
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_mouse+st_collision
	dw	0
	dw	14
	dw	id_s14_floor
	dd	0
	dw	280
	dw	256
	dw	s90
	dw	4
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-16
	dw	-48
	dw	32
	dw	48
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	radman_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	0
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_radman
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	radman_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	radman_up
	dd	radman_down
	dd	radman_left
	dd	radman_right
	dd	radman_st_up
	dd	radman_st_down
	dd	radman_st_left
	dd	radman_st_right
	dd	radman_st_talk
	dd	0
	dd	radman_u_to_d
	dd	radman_u_to_l
	dd	radman_u_to_r
	dd	0
	dd	radman_d_to_u
	dd	0
	dd	radman_d_to_l
	dd	radman_d_to_r
	dd	0
	dd	radman_l_to_u
	dd	radman_l_to_d
	dd	0
	dd	radman_l_to_r
	dd	0
	dd	radman_r_to_u
	dd	radman_r_to_d
	dd	radman_r_to_l
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0


radman_auto	db	64 dup (0)



end32save_data

start32data



radman_left	dw	4
	dw	20+s90
	dw	-4
	dw	0
	dw	4
	dw	21+s90
	dw	-4
	dw	0
	dw	4
	dw	22+s90
	dw	-4
	dw	0
	dw	4
	dw	23+s90
	dw	-4
	dw	0
	dw	4
	dw	24+s90
	dw	-4
	dw	0
	dw	4
	dw	25+s90
	dw	-4
	dw	0
	dw	4
	dw	26+s90
	dw	-4
	dw	0
	dw	4
	dw	27+s90
	dw	-4
	dw	0
	dw	4
	dw	28+s90
	dw	-4
	dw	0
	dw	4
	dw	29+s90
	dw	-4
	dw	0
	dw	0


radman_right	dw	4
	dw	30+s90
	dw	4
	dw	0
	dw	4
	dw	31+s90
	dw	4
	dw	0
	dw	4
	dw	32+s90
	dw	4
	dw	0
	dw	4
	dw	33+s90
	dw	4
	dw	0
	dw	4
	dw	34+s90
	dw	4
	dw	0
	dw	4
	dw	35+s90
	dw	4
	dw	0
	dw	4
	dw	36+s90
	dw	4
	dw	0
	dw	4
	dw	37+s90
	dw	4
	dw	0
	dw	4
	dw	38+s90
	dw	4
	dw	0
	dw	4
	dw	39+s90
	dw	4
	dw	0
	dw	0


radman_up	dw	2
	dw	0+s90
	dw	0
	dw	-2
	dw	2
	dw	1+s90
	dw	0
	dw	-2
	dw	2
	dw	2+s90
	dw	0
	dw	-2
	dw	2
	dw	3+s90
	dw	0
	dw	-2
	dw	2
	dw	4+s90
	dw	0
	dw	-2
	dw	2
	dw	5+s90
	dw	0
	dw	-2
	dw	2
	dw	6+s90
	dw	0
	dw	-2
	dw	2
	dw	7+s90
	dw	0
	dw	-2
	dw	2
	dw	8+s90
	dw	0
	dw	-2
	dw	2
	dw	9+s90
	dw	0
	dw	-2
	dw	0


radman_down	dw	2
	dw	10+s90
	dw	0
	dw	2
	dw	2
	dw	11+s90
	dw	0
	dw	2
	dw	2
	dw	12+s90
	dw	0
	dw	2
	dw	2
	dw	13+s90
	dw	0
	dw	2
	dw	2
	dw	14+s90
	dw	0
	dw	2
	dw	2
	dw	15+s90
	dw	0
	dw	2
	dw	2
	dw	16+s90
	dw	0
	dw	2
	dw	2
	dw	17+s90
	dw	0
	dw	2
	dw	2
	dw	18+s90
	dw	0
	dw	2
	dw	2
	dw	19+s90
	dw	0
	dw	2
	dw	0


radman_st_up	dw	s90
	dw	1
	dw	0
	dw	44
	dw	0


radman_st_down	dw	s90
	dw	1
	dw	0
	dw	40
	dw	0


radman_st_left	dw	s90
	dw	1
	dw	0
	dw	42
	dw	0


radman_st_right	dw	s90
	dw	1
	dw	0
	dw	46
	dw	0


radman_st_talk	dw	s97
	dw	1
	dw	0
	dw	0
	dw	0


radman_r_to_u	dw	45+s90
	dw	0


radman_r_to_d	dw	47+s90
	dw	0


radman_r_to_l	dw	45+s90
	dw	44+s90
	dw	43+s90
	dw	0


radman_u_to_d	dw	43+s90
	dw	42+s90
	dw	41+s90
	dw	0


radman_u_to_l	dw	43+s90
	dw	0


radman_u_to_r	dw	45+s90
	dw	0


radman_d_to_u	dw	47+s90
	dw	46+s90
	dw	45+s90
	dw	0


radman_d_to_l	dw	41+s90
	dw	0


radman_d_to_r	dw	47+s90
	dw	0


radman_l_to_u	dw	43+s90
	dw	0


radman_l_to_d	dw	41+s90
	dw	0


radman_l_to_r	dw	41+s90
	dw	40+s90
	dw	47+s90
	dw	0



end32data

start32save_data



end32save_data
