start32data



s18_logic	dw	id_foster
	dw	id_joey
	dw	id_monitor
	dw	id_steam
	dw	id_power_door
	dw	id_left_lever
	dw	id_right_lever
	dw	id_power_motor
	dw	id_power_panel
	dw	id_power_switch
	dw	id_power_bang
	dw	id_lamb
	dw	id_lift_s7
	dw	id_lift7_light
	dw	$ffff
	dw	id_menu_logic


s18_mouse	dw	id_joey
	dw	id_monitor
	dw	id_right_exit_s18
	dw	id_power_panel
	dw	id_power_switch
	dw	id_power_chair
	dw	id_s18_floor
	dw	id_left_skull
	dw	id_right_skull
	dw	id_power_door
	dw	id_left_lever
	dw	id_right_lever
	dw	$ffff
	dw	id_text_mouse


s18_pal	dw	0
	dw	1024
	dw	1540
	dw	1542
	dw	2054
	dw	2056
	dw	2058
	dw	2568
	dw	2570
	dw	2572
	dw	3084
	dw	3594
	dw	3084
	dw	4108
	dw	2570
	dw	3086
	dw	6158
	dw	2058
	dw	3598
	dw	4112
	dw	3598
	dw	3600
	dw	4112
	dw	4112
	dw	3606
	dw	5132
	dw	3088
	dw	4114
	dw	5650
	dw	2576
	dw	4626
	dw	6676
	dw	3600
	dw	4628
	dw	5652
	dw	4114
	dw	4630
	dw	5138
	dw	6162
	dw	5144
	dw	5132
	dw	5652
	dw	5146
	dw	5644
	dw	5654
	dw	5146
	dw	5652
	dw	6166
	dw	5660
	dw	6158
	dw	6166
	dw	5662
	dw	6158
	dw	6678
	dw	5656
	dw	6172
	dw	5656
	dw	6174
	dw	7184
	dw	5656
	dw	5665
	dw	6676
	dw	7192
	dw	6172
	dw	8474
	dw	4122
	dw	5671
	dw	7696
	dw	5658
	dw	6682
	dw	7198
	dw	7194
	dw	6689
	dw	8984
	dw	4636
	dw	6695
	dw	7700
	dw	7708
	dw	7198
	dw	8993
	dw	6684
	dw	7713
	dw	10526
	dw	5660
	dw	8483
	dw	8470
	dw	8990
	dw	7717
	dw	8986
	dw	7713
	dw	7717
	dw	11043
	dw	6174
	dw	8483
	dw	10019
	dw	7201
	dw	8999
	dw	8990
	dw	10019
	dw	8997
	dw	12071
	dw	6177
	dw	9001
	dw	8993
	dw	10021
	dw	9511
	dw	11045
	dw	7205
	dw	9011
	dw	11542
	dw	7717
	dw	9513
	dw	12587
	dw	6693
	dw	10025
	dw	11561
	dw	8999
	dw	10539
	dw	12579
	dw	7721
	dw	10029
	dw	13613
	dw	6185
	dw	10545
	dw	11041
	dw	10539
	dw	11051
	dw	12077
	dw	10027
	dw	11059
	dw	15649
	dw	6697
	dw	11567
	dw	14635
	dw	7211
	dw	11573
	dw	14115
	dw	7725
	dw	11567
	dw	12591
	dw	10543
	dw	12079
	dw	14641
	dw	9007
	dw	12605
	dw	13078
	dw	11057
	dw	12091
	dw	16161
	dw	7725
	dw	12599
	dw	13093
	dw	11569
	dw	12601
	dw	14113
	dw	10033
	dw	12593
	dw	12595
	dw	13617
	dw	13107
	dw	14643
	dw	10547
	dw	13109
	dw	13617
	dw	13107
	dw	13119
	dw	15649
	dw	9523
	dw	13627
	dw	16165
	dw	6199
	dw	13621
	dw	15669
	dw	10037
	dw	14139
	dw	14123
	dw	13623
	dw	14139
	dw	16173
	dw	8505
	dw	14655
	dw	14627
	dw	14135
	dw	14655
	dw	15145
	dw	13627
	dw	15679
	dw	16171
	dw	11581
	dw	15679
	dw	15665
	dw	14141
	dw	1073
	dw	2564
	dw	2570
	dw	3084
	dw	4108
	dw	3598
	dw	4112
	dw	5136
	dw	3088
	dw	4118
	dw	10
	dw	10
	dw	4630
	dw	5648
	dw	4626
	dw	5144
	dw	5132
	dw	5652
	dw	5146
	dw	7188
	dw	3606
	dw	6174
	dw	7184
	dw	6680
	dw	0
	dw	2111
	dw	2056
	dw	2572
	dw	3084
	dw	3594
	dw	3084
	dw	3596
	dw	4110
	dw	3600
	dw	4624
	dw	4624
	dw	4626
	dw	5140
	dw	6162
	dw	5140
	dw	6166
	dw	6166
	dw	5656
	dw	6682
	dw	7192
	dw	6684
	dw	7708
	dw	7708
	dw	63
	dw	2048
	dw	2056
	dw	3086
	dw	4622
	dw	4624
	dw	5140
	dw	6166
	dw	6166
	dw	6170
	dw	7708
	dw	7708
	dw	7713
	dw	8990
	dw	8993
	dw	8997
	dw	10023
	dw	9509
	dw	10025
	dw	11049
	dw	10539
	dw	11567
	dw	13099
	dw	11569
	dw	16128
	dw	2560
	dw	2570
	dw	2572
	dw	15116
	dw	11575
	dw	4628
	dw	6676
	dw	7192
	dw	7198
	dw	8990
	dw	8993
	dw	9511
	dw	11045
	dw	9001
	dw	11051
	dw	12073
	dw	11053
	dw	13109
	dw	14129
	dw	13623
	dw	15163
	dw	15669
	dw	14141
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191



end32data

start32save_data



s18_floor	dw	0
	dw	st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	s18_floor_table
	dw	128
	dw	272
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	14+16
	dw	floor_action



end32save_data

start32data



s18_floor_table	dw	id_s18_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s18_walk_on
	dw	1
	dw	get_to_talk
	dw	id_right_exit_s18
	dw	get_to_r_exit_s18
	dw	id_power_panel
	dw	get_to_power_panel
	dw	id_power_switch
	dw	get_to_power_switch
	dw	id_power_chair
	dw	get_to_power_chair
	dw	id_left_skull
	dw	get_to_left_skull
	dw	id_right_skull
	dw	get_to_right_skull
	dw	id_power_door
	dw	get_to_power_door
	dw	id_right_lever
	dw	get_to_right_lever
	dw	id_left_lever
	dw	get_to_left_lever
	dw	-1


s18_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	57+disk_2
	dw	58+disk_2
	dw	60+disk_2
	dw	0


s18_chip_list	dw	173
	dw	111
	dw	44+disk_2
	dw	45+disk_2
	dw	46+disk_2
	dw	61+disk_2
	dw	63+disk_2
	dw	64+disk_2
	dw	65+disk_2
	dw	66+disk_2
	dw	67+disk_2
	dw	68+disk_2
	dw	70+disk_2+$8000
	dw	71+disk_2
	dw	88+disk_2+$8000
	dw	92+disk_2+$8000
	dw	90+disk_2
	dw	91+disk_2
	dw	89+disk_2
	dw	72+disk_2
	dw	85+disk_2+$8000
	dw	86+disk_2+$8000
	dw	74+disk_2
	dw	76+disk_2+$8000
	dw	75+disk_2
	dw	0


nu_chip_18	dw	136+disk_2
	dw	137+disk_2
	dw	44+disk_2
	dw	45+disk_2
	dw	46+disk_2
	dw	61+disk_2
	dw	63+disk_2
	dw	64+disk_2
	dw	65+disk_2
	dw	66+disk_2
	dw	67+disk_2
	dw	68+disk_2
	dw	70+disk_2+$8000
	dw	71+disk_2
	dw	88+disk_2+$8000
	dw	92+disk_2+$8000
	dw	90+disk_2
	dw	91+disk_2
	dw	89+disk_2
	dw	72+disk_2
	dw	85+disk_2+$8000
	dw	86+disk_2+$8000
	dw	74+disk_2
	dw	76+disk_2+$8000
	dw	75+disk_2
	dw	0


rs_foster_to_18	dw	c_xcood
	dw	424
	dw	c_ycood
	dw	272
	dw	c_screen
	dw	18
	dw	c_place
	dw	id_s18_floor
	dw	-1


right_exit_s18	dw	0
	dw	st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	0
	dw	405
	dw	221
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	414-405
	dw	280-221
	dw	er18_action


joey_list_s18	dw	156
	dw	360
	dw	280
	dw	304
	dw	1
	dw	0



end32data

start32save_data



steam	dw	l_script
	dw	st_foreground+st_logic+st_recreate
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	10
	dw	10
	dw	s57
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	steam_logic
	dw	0



end32save_data

start32data



steam1_seq	dw	s57
	dw	386
	dw	137
	dw	0
	dw	386
	dw	137
	dw	1
	dw	386
	dw	137
	dw	2
	dw	386
	dw	137
	dw	3
	dw	386
	dw	137
	dw	4
	dw	386
	dw	137
	dw	5
	dw	386
	dw	137
	dw	6
	dw	386
	dw	137
	dw	7
	dw	386
	dw	137
	dw	8
	dw	386
	dw	137
	dw	9
	dw	0


steam2_seq	dw	s58
	dw	382
	dw	137
	dw	0
	dw	382
	dw	137
	dw	1
	dw	382
	dw	137
	dw	2
	dw	382
	dw	137
	dw	3
	dw	382
	dw	137
	dw	4
	dw	0


steam3_seq	dw	s59
	dw	380
	dw	137
	dw	0
	dw	380
	dw	137
	dw	1
	dw	380
	dw	137
	dw	2
	dw	380
	dw	137
	dw	3
	dw	380
	dw	137
	dw	4
	dw	380
	dw	137
	dw	5
	dw	0


steam4_seq	dw	s60
	dw	380
	dw	137
	dw	0
	dw	380
	dw	137
	dw	1
	dw	380
	dw	137
	dw	2
	dw	380
	dw	137
	dw	3
	dw	380
	dw	137
	dw	4
	dw	0



end32data

start32save_data



power_door	dw	l_script
	dw	st_background+st_logic+st_mouse+st_recreate
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	146
	dw	229
	dw	s61
	dw	8394
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	174-146
	dw	233-229
	dw	246-174
	dw	268-233
	dw	power_door_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	power_door_logic
	dw	0



end32save_data

start32data



door_blast_seq	dw	s61
	dw	146
	dw	229
	dw	0
	dw	146
	dw	229
	dw	1
	dw	146
	dw	229
	dw	2
	dw	146
	dw	229
	dw	3
	dw	0



end32data

start32save_data



power_motor	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	20
	dw	20
	dw	s67
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	power_motor_logic
	dw	0



end32save_data

start32data



power_stop_seq	dw	s68
	dw	157
	dw	315
	dw	0
	dw	157
	dw	315
	dw	1
	dw	157
	dw	315
	dw	2
	dw	157
	dw	315
	dw	3
	dw	157
	dw	315
	dw	0
	dw	157
	dw	315
	dw	4
	dw	157
	dw	315
	dw	5
	dw	157
	dw	315
	dw	6
	dw	157
	dw	315
	dw	7
	dw	157
	dw	315
	dw	8
	dw	0


power_start_seq	dw	s66
	dw	157
	dw	315
	dw	0
	dw	157
	dw	315
	dw	1
	dw	157
	dw	315
	dw	2
	dw	157
	dw	315
	dw	3
	dw	157
	dw	315
	dw	4
	dw	0


power_spin_seq	dw	s67
	dw	157
	dw	315
	dw	0
	dw	157
	dw	315
	dw	1
	dw	157
	dw	315
	dw	2
	dw	157
	dw	315
	dw	3
	dw	0



end32data

start32save_data



socket	dw	l_script
	dw	st_background+st_logic+st_mouse+st_recreate
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	185
	dw	220
	dw	s65
	dw	66
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	8
	dw	8
	dw	socket_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	power_panel_logic
	dw	0


power_switch	dw	l_script
	dw	st_background+st_logic+st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	237
	dw	222
	dw	s63
	dw	67
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	8
	dw	8
	dw	switch_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	power_switch_logic
	dw	0


power_chair	dw	l_script
	dw	st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	258
	dw	253
	dw	NULL
	dw	8908
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	20
	dw	24
	dw	chair_action


left_skull	dw	l_script
	dw	st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	329
	dw	247
	dw	NULL
	dw	65
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	4
	dw	5
	dw	left_skull_action


right_skull	dw	l_script
	dw	st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	379
	dw	247
	dw	NULL
	dw	65
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	4
	dw	5
	dw	right_skull_action


power_bang	dw	l_script
	dw	st_recreate+st_logic
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	0
	dw	0
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	power_bang_logic
	dw	0



end32save_data

start32data



power_bang_seq	dw	s62
	dw	179
	dw	216
	dw	0
	dw	173
	dw	207
	dw	1
	dw	172
	dw	205
	dw	2
	dw	171
	dw	204
	dw	3
	dw	169
	dw	204
	dw	4
	dw	167
	dw	203
	dw	5
	dw	164
	dw	201
	dw	6
	dw	158
	dw	198
	dw	7
	dw	155
	dw	196
	dw	8
	dw	150
	dw	192
	dw	9
	dw	145
	dw	189
	dw	10
	dw	138
	dw	183
	dw	11
	dw	134
	dw	177
	dw	12
	dw	134
	dw	174
	dw	13
	dw	138
	dw	170
	dw	14
	dw	139
	dw	167
	dw	15
	dw	0


push_but_seq	dw	s71
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	0


unpush_but_seq	dw	s71
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


spanner_seq	dw	s70
	dw	239
	dw	195
	dw	0
	dw	239
	dw	195
	dw	0
	dw	239
	dw	195
	dw	1
	dw	239
	dw	195
	dw	1
	dw	239
	dw	195
	dw	2
	dw	239
	dw	195
	dw	3
	dw	239
	dw	195
	dw	4
	dw	239
	dw	195
	dw	5
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	6
	dw	239
	dw	195
	dw	7
	dw	239
	dw	195
	dw	8
	dw	239
	dw	195
	dw	9
	dw	239
	dw	195
	dw	7
	dw	239
	dw	195
	dw	10
	dw	239
	dw	195
	dw	10
	dw	239
	dw	195
	dw	11
	dw	239
	dw	195
	dw	12
	dw	0


high_push_seq	dw	s72
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


high_unpush_seq	dw	s72
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


blowoff_seq	dw	s69
	dw	169
	dw	222
	dw	0
	dw	162
	dw	227
	dw	1
	dw	160
	dw	240
	dw	2
	dw	150
	dw	250
	dw	3
	dw	150
	dw	255
	dw	4
	dw	148
	dw	259
	dw	5
	dw	149
	dw	271
	dw	6
	dw	149
	dw	279
	dw	7
	dw	149
	dw	279
	dw	8
	dw	147
	dw	279
	dw	9
	dw	147
	dw	279
	dw	10
	dw	0


sleep_seq	dw	s75
	dw	250
	dw	231
	dw	0
	dw	250
	dw	231
	dw	0
	dw	250
	dw	231
	dw	0
	dw	250
	dw	231
	dw	1
	dw	250
	dw	231
	dw	1
	dw	250
	dw	231
	dw	1
	dw	250
	dw	231
	dw	2
	dw	250
	dw	231
	dw	2
	dw	250
	dw	231
	dw	2
	dw	250
	dw	231
	dw	3
	dw	250
	dw	231
	dw	3
	dw	250
	dw	231
	dw	3
	dw	250
	dw	231
	dw	4
	dw	250
	dw	231
	dw	4
	dw	250
	dw	231
	dw	4
	dw	250
	dw	231
	dw	5
	dw	250
	dw	231
	dw	5
	dw	250
	dw	231
	dw	5
	dw	250
	dw	231
	dw	6
	dw	250
	dw	231
	dw	6
	dw	250
	dw	231
	dw	6
	dw	250
	dw	231
	dw	7
	dw	250
	dw	231
	dw	7
	dw	250
	dw	231
	dw	7
	dw	0


monhit_seq	dw	s76
	dw	250
	dw	231
	dw	0
	dw	250
	dw	231
	dw	1
	dw	250
	dw	231
	dw	2
	dw	250
	dw	231
	dw	3
	dw	0


joey_push_seq	dw	s89
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	0


joey_unpush_seq	dw	s89
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


steam_alert_seq	dw	s86
	dw	258
	dw	242
	dw	0
	dw	258
	dw	242
	dw	1
	dw	258
	dw	243
	dw	2
	dw	257
	dw	239
	dw	3
	dw	254
	dw	235
	dw	4
	dw	253
	dw	234
	dw	5
	dw	251
	dw	233
	dw	6
	dw	251
	dw	233
	dw	7
	dw	0


rs_gordon_start	dw	c_xcood
	dw	264
	dw	c_ycood
	dw	272
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	c_action_script
	dw	shout_action
	dw	c_mouse_rel_x
	dw	-16
	dw	c_mouse_rel_y
	dw	-48
	dw	c_mouse_size_x
	dw	32
	dw	c_mouse_size_y
	dw	48
	dw	-1


rs_gordon_end	dw	c_xcood
	dw	250
	dw	c_ycood
	dw	231
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_mouse
	dw	c_action_script
	dw	sat_gordon_action
	dw	c_mouse_rel_x
	dw	10
	dw	c_mouse_rel_y
	dw	244-231
	dw	c_mouse_size_x
	dw	20
	dw	c_mouse_size_y
	dw	276-244
	dw	c_frame
	dw	s75
	dw	-1



end32data

start32save_data



left_lever	dw	l_script
	dw	st_logic+st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	181
	dw	236
	dw	s90+1
	dw	67
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	6
	dw	24
	dw	left_lever_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	left_lever_logic
	dw	0


right_lever	dw	l_script
	dw	st_logic+st_mouse
	dw	0
	dw	18
	dw	NULL
	dd	NULL
	dw	191
	dw	236
	dw	s91
	dw	67
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	6
	dw	24
	dw	right_lever_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	right_lever_logic
	dw	0



end32save_data

start32data



end32data
