start32data



s20_chip_list	dw	185+disk_9
	dw	186+disk_9
	dw	192+disk_9
	dw	90+disk_9
	dw	131+disk_2
	dw	132+disk_2
	dw	217+disk_9
	dw	0


s20_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	180+disk_9
	dw	181+disk_9
	dw	182+disk_9
	dw	183+disk_9
	dw	184+disk_9
	dw	0


grid20	dd 0 dup (0)

s20_pal	dw	0
	dw	512
	dw	2
	dw	514
	dw	771
	dw	5
	dw	1028
	dw	1027
	dw	1540
	dw	1032
	dw	1026
	dw	8
	dw	1797
	dw	1795
	dw	2054
	dw	2822
	dw	1793
	dw	1290
	dw	2059
	dw	3590
	dw	776
	dw	3081
	dw	2821
	dw	2569
	dw	2576
	dw	2822
	dw	2062
	dw	2580
	dw	2564
	dw	1552
	dw	3340
	dw	4108
	dw	2828
	dw	3601
	dw	3591
	dw	2320
	dw	2840
	dw	3076
	dw	1300
	dw	3349
	dw	4615
	dw	3598
	dw	3356
	dw	5124
	dw	3344
	dw	4880
	dw	3595
	dw	2070
	dw	5903
	dw	5380
	dw	4112
	dw	4376
	dw	4873
	dw	2325
	dw	4122
	dw	7179
	dw	1809
	dw	5143
	dw	8202
	dw	1296
	dw	6417
	dw	4871
	dw	2328
	dw	4632
	dw	5138
	dw	4629
	dw	5399
	dw	5389
	dw	3095
	dw	4637
	dw	7181
	dw	2069
	dw	7187
	dw	4613
	dw	3610
	dw	6421
	dw	6926
	dw	4116
	dw	4642
	dw	5640
	dw	2587
	dw	5407
	dw	6923
	dw	5141
	dw	7701
	dw	9480
	dw	1556
	dw	6429
	dw	6156
	dw	4890
	dw	7445
	dw	8722
	dw	3606
	dw	6428
	dw	6932
	dw	3612
	dw	6431
	dw	6160
	dw	3871
	dw	5926
	dw	6669
	dw	2849
	dw	6941
	dw	7448
	dw	4637
	dw	6436
	dw	8979
	dw	3866
	dw	8988
	dw	6408
	dw	4898
	dw	6697
	dw	9743
	dw	4380
	dw	7711
	dw	8474
	dw	4896
	dw	7207
	dw	8469
	dw	3364
	dw	9501
	dw	9233
	dw	5663
	dw	9245
	dw	11031
	dw	4381
	dw	7719
	dw	11033
	dw	5406
	dw	9762
	dw	8977
	dw	3112
	dw	8740
	dw	8475
	dw	7460
	dw	9255
	dw	8978
	dw	5415
	dw	8493
	dw	12311
	dw	4641
	dw	8746
	dw	10011
	dw	7715
	dw	9764
	dw	8736
	dw	7209
	dw	9768
	dw	11289
	dw	6437
	dw	9264
	dw	12310
	dw	6692
	dw	11045
	dw	10265
	dw	4907
	dw	10539
	dw	10005
	dw	8489
	dw	10538
	dw	12573
	dw	5672
	dw	10285
	dw	12576
	dw	7463
	dw	11566
	dw	13080
	dw	6697
	dw	11056
	dw	11805
	dw	9003
	dw	10802
	dw	13601
	dw	7721
	dw	11572
	dw	12570
	dw	9773
	dw	11319
	dw	13088
	dw	8750
	dw	11831
	dw	13604
	dw	8241
	dw	12598
	dw	14120
	dw	9266
	dw	13365
	dw	14635
	dw	10036
	dw	13879
	dw	14638
	dw	12345
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s20_logic	dw	id_foster
	dw	id_joey
	dw	id_lamb
	dw	id_reich_door_20
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_inner_r_door
	dw	id_lift_29
	dw	id_gallager_bel
	dw	id_cat
	dw	$ffff
	dw	id_menu_logic


s20_mouse	dw	id_joey
	dw	id_lamb
	dw	id_down_exit_20
	dw	id_reich_door_20
	dw	id_reich_slot
	dw	id_lamb_slot
	dw	id_lamb_door_20
	dw	id_shrub_1
	dw	id_shrub_2
	dw	id_shrub_3
	dw	id_gallager_bel
	dw	id_reich_window
	dw	id_lamb_window
	dw	id_s20_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s20_floor	dw	0
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	s20_floor_table
	dw	128
	dw	288
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	4242
	dw	4242
	dw	floor_action



end32save_data

start32data



s20_floor_table	dw	id_s20_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s20_start_on
	dw	1
	dw	s20_reich_on
	dw	3
	dw	s20_lamb_on
	dw	id_down_exit_20
	dw	GT_down_exit_20
	dw	id_reich_door_20
	dw	GT_reich_door_20
	dw	id_lamb_door_20
	dw	GT_lamb_door_20
	dw	id_reich_slot
	dw	GT_reich_slot
	dw	id_lamb_slot
	dw	GT_lamb_slot
	dw	id_shrub_1
	dw	GT_shrub_1
	dw	id_shrub_2
	dw	GT_shrub_2
	dw	id_shrub_3
	dw	GT_shrub_3
	dw	id_gallager_bel
	dw	GT_gallager_bel
	dw	id_reich_window
	dw	GT_reich_window
	dw	id_lamb_window
	dw	GT_lamb_window
	dw	id_std_left_talk
	dw	GT_l_talk_20
	dw	id_std_right_talk
	dw	GT_r_talk_20
	dw	-1


rs_all_28_20	dw	c_xcood
	dw	160
	dw	c_ycood
	dw	320
	dw	c_screen
	dw	20
	dw	c_place
	dw	id_s20_floor
	dw	-1



end32data

start32save_data



down_exit_20	dw	0
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	0
	dw	128
	dw	312
	dw	0
	dw	1+t7
	dw	std_exit_down_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	193-128
	dw	20
	dw	ed20_action



end32save_data

start32data



rs_foster_20_28	dw	c_xcood
	dw	408
	dw	c_ycood
	dw	248
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_floor
	dw	-1


joey_list_20	dw	208
	dw	352
	dw	296
	dw	330
	dw	1
	dw	0



end32data

start32save_data



reich_door_20	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	252
	dw	228
	dw	s185
	dw	181
	dw	reich_20_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	273-252
	dw	287-228
	dw	reich_door_20_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	reich_door_20_logic
	dw	0



end32save_data

start32data



reich_20_open	dw	s185
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	0


reich_20_close	dw	s185
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



reich_slot	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	232
	dw	256
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	7
	dw	11
	dw	reich_slot_action



end32save_data

start32data



usecard_seq	dw	s192
	dw	258
	dw	173
	dw	0
	dw	258
	dw	173
	dw	1
	dw	258
	dw	173
	dw	2
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	3
	dw	258
	dw	173
	dw	2
	dw	258
	dw	173
	dw	1
	dw	258
	dw	173
	dw	0
	dw	0



end32data

start32save_data



lamb_door_20	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	291
	dw	229
	dw	s186
	dw	181
	dw	lamb_20_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	273-252
	dw	287-228
	dw	lamb_door_20_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	lamb_door_20_logic
	dw	0



end32save_data

start32data



lamb_20_open	dw	s186
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	0


lamb_20_close	dw	s186
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



lamb_slot	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	323
	dw	256
	dw	0
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	7
	dw	11
	dw	lamb_slot_action


shrub_1	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	156
	dw	251
	dw	0
	dw	12659
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	193-156
	dw	294-251
	dw	shrub_1_action


shrub_2	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	249
	dw	303
	dw	0
	dw	12659
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	310-249
	dw	4242
	dw	shrub_2_action


shrub_3	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	396
	dw	257
	dw	0
	dw	12659
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	421-396
	dw	298-257
	dw	shrub_3_action



end32save_data

start32data



rs_joey_start_20	dw	c_xcood
	dw	168
	dw	c_ycood
	dw	296
	dw	c_screen
	dw	20
	dw	c_place
	dw	id_s20_floor
	dw	c_logic
	dw	l_script
	dw	c_base_sub
	dw	joey_logic
	dw	c_base_sub+2
	dw	0
	dw	c_frame
	dw	s136+2
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_collision+st_mouse+st_grid_plot
	dw	c_dir
	dw	up
	dw	-1



end32data

start32save_data



gallager_bel	dw	l_script
	dw	st_recreate+st_logic+st_mouse+st_foreground
	dw	0
	dw	20
	dw	0
	dd	0
	dw	346
	dw	282
	dw	s90
	dw	4
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	369-346
	dw	320-282
	dw	gal_bel_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	gal_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	null
	dw	null
	dw	null
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_galag
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	null
	dw	0



end32save_data

start32data



gal_look_up	dw	s90
	dw	1
	dw	1
	dw	0
	dw	11
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	0


gal_look_down	dw	s90
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



reich_window	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	194
	dw	239
	dw	0
	dw	60
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	223-194
	dw	255-239
	dw	reich_window_action


lamb_window	dw	l_script
	dw	st_mouse
	dw	0
	dw	20
	dw	NULL
	dd	NULL
	dw	342
	dw	240
	dw	0
	dw	60
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	368-342
	dw	257-240
	dw	lamb_window_action



end32save_data

start32data



lamb_card_seq2	dw	s217
	dw	276
	dw	231
	dw	0
	dw	276
	dw	231
	dw	1
	dw	276
	dw	231
	dw	2
	dw	276
	dw	231
	dw	3
	dw	276
	dw	231
	dw	4
	dw	276
	dw	231
	dw	5
	dw	276
	dw	231
	dw	6
	dw	276
	dw	231
	dw	1
	dw	276
	dw	231
	dw	0
	dw	0



end32data

start32save_data



end32save_data
