start32data



s21_chip_list	dw	201+disk_9
	dw	202+disk_9
	dw	110+disk_9
	dw	109+disk_9
	dw	108+disk_9
	dw	107+disk_9
	dw	101+disk_9
	dw	102+disk_9
	dw	89+disk_9
	dw	131+disk_2
	dw	132+disk_2
	dw	218+disk_9
	dw	0


s21_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	193+disk_9
	dw	194+disk_9
	dw	195+disk_9
	dw	219+disk_9
	dw	220+disk_9
	dw	0


grid21	dd 0 dup (0)

s21_pal	dw	0
	dw	1280
	dw	257
	dw	515
	dw	2308
	dw	257
	dw	775
	dw	1281
	dw	1795
	dw	1031
	dw	3332
	dw	258
	dw	779
	dw	2308
	dw	2052
	dw	1545
	dw	1541
	dw	1032
	dw	785
	dw	3073
	dw	1542
	dw	1801
	dw	2057
	dw	3079
	dw	2061
	dw	5123
	dw	773
	dw	1552
	dw	4359
	dw	519
	dw	2059
	dw	2317
	dw	3849
	dw	3082
	dw	6149
	dw	516
	dw	2062
	dw	5133
	dw	1798
	dw	1809
	dw	7179
	dw	516
	dw	2577
	dw	3078
	dw	2061
	dw	2571
	dw	6162
	dw	1542
	dw	2831
	dw	5387
	dw	1546
	dw	2579
	dw	3594
	dw	4364
	dw	3084
	dw	6165
	dw	1035
	dw	1822
	dw	4355
	dw	4875
	dw	2076
	dw	8966
	dw	773
	dw	3094
	dw	5385
	dw	3339
	dw	3342
	dw	4632
	dw	4109
	dw	3599
	dw	8212
	dw	1544
	dw	2843
	dw	6155
	dw	3085
	dw	1323
	dw	7169
	dw	782
	dw	3604
	dw	3859
	dw	6927
	dw	3857
	dw	9751
	dw	1287
	dw	2339
	dw	7176
	dw	3597
	dw	2089
	dw	6147
	dw	2833
	dw	4370
	dw	5658
	dw	4369
	dw	3360
	dw	7434
	dw	1042
	dw	4636
	dw	6664
	dw	3857
	dw	2348
	dw	7685
	dw	3088
	dw	4129
	dw	4614
	dw	7698
	dw	4887
	dw	5140
	dw	3096
	dw	4633
	dw	7447
	dw	4115
	dw	3623
	dw	8460
	dw	3346
	dw	4386
	dw	9233
	dw	2578
	dw	4639
	dw	6931
	dw	5141
	dw	4133
	dw	11023
	dw	3088
	dw	5406
	dw	6167
	dw	4124
	dw	5157
	dw	9999
	dw	4626
	dw	6174
	dw	7186
	dw	6168
	dw	5665
	dw	7445
	dw	7447
	dw	4906
	dw	10000
	dw	3607
	dw	4910
	dw	10254
	dw	4630
	dw	5670
	dw	11286
	dw	4885
	dw	6434
	dw	10780
	dw	5654
	dw	7965
	dw	8725
	dw	6172
	dw	5679
	dw	10513
	dw	5145
	dw	6948
	dw	12063
	dw	5400
	dw	7210
	dw	12824
	dw	4889
	dw	8993
	dw	9753
	dw	8222
	dw	7214
	dw	10006
	dw	6944
	dw	6706
	dw	11287
	dw	7197
	dw	7216
	dw	10266
	dw	8991
	dw	9763
	dw	13340
	dw	6684
	dw	8491
	dw	12834
	dw	6943
	dw	10022
	dw	14110
	dw	6430
	dw	8501
	dw	12061
	dw	8229
	dw	9518
	dw	10789
	dw	8234
	dw	9016
	dw	11038
	dw	9258
	dw	10290
	dw	12070
	dw	10029
	dw	3616
	dw	9231
	dw	2327
	dw	5154
	dw	7431
	dw	4367
	dw	1319
	dw	16130
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	5632
	dw	2316
	dw	4376
	dw	6667
	dw	3857
	dw	4126
	dw	5132
	dw	3096
	dw	4893
	dw	8720
	dw	4369
	dw	7192
	dw	9488
	dw	3860
	dw	7965
	dw	8725
	dw	6172
	dw	8993
	dw	9753
	dw	7719
	dw	10794
	dw	12064
	dw	10029
	dw	0
	dw	1280
	dw	257
	dw	515
	dw	2308
	dw	257
	dw	775
	dw	1281
	dw	1795
	dw	1031
	dw	3332
	dw	258
	dw	779
	dw	5124
	dw	773
	dw	1552
	dw	6151
	dw	1542
	dw	2076
	dw	8198
	dw	1544
	dw	2843
	dw	8971
	dw	2057
	dw	259
	dw	1795
	dw	1795
	dw	1547
	dw	3851
	dw	3593
	dw	3092
	dw	6162
	dw	5647
	dw	4892
	dw	8474
	dw	7703
	dw	7205
	dw	10529
	dw	9504
	dw	9517
	dw	12841
	dw	11818
	dw	12342
	dw	14899
	dw	14134
	dw	15423
	dw	61
	dw	0
	dw	0
	dw	14336
	dw	13364
	dw	10283
	dw	7720
	dw	7196
	dw	5401
	dw	5396
	dw	3855
	dw	2576
	dw	1802
	dw	1285
	dw	0
	dw	15616
	dw	9522
	dw	10041
	dw	12059
	dw	5152
	dw	5928
	dw	7948
	dw	1806
	dw	2836
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	12548
	dw	13361
	dw	10281
	dw	8236
	dw	8734
	dw	10284
	dw	9264
	dw	10271
	dw	5917
	dw	5664
	dw	6159
	dw	2319
	dw	2064
	dw	2052
	dw	13631
	dw	14376
	dw	6694
	dw	6189
	dw	8975
	dw	1805
	dw	1048
	dw	3586
	dw	0
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	13631
	dw	14376
	dw	6694
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s21_logic	dw	id_foster
	dw	id_joey
	dw	id_lamb
	dw	id_catfood
	dw	id_video
	dw	id_cassette
	dw	id_video_screen
	dw	id_cat
	dw	id_inner_lamb_door
	dw	id_lamb_door_20
	dw	id_gallager_bel
	dw	id_lift_29
	dw	$ffff
	dw	id_menu_logic


s21_mouse	dw	id_joey
	dw	id_lamb
	dw	id_inner_lamb_door
	dw	id_left_exit_21
	dw	id_lambs_books
	dw	id_lambs_chair
	dw	id_dispensor
	dw	id_catfood
	dw	id_video
	dw	id_cassette
	dw	id_big_pict1
	dw	id_big_pict2
	dw	id_big_pict3
	dw	id_video_screen
	dw	id_cat
	dw	id_s21_floor
	dw	id_fake_floor_21
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s21_floor	dw	0
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	s21_floor_table
	dw	128
	dw	248
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action



end32save_data

start32data



s21_floor_table	dw	id_s21_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s21_start_on
	dw	id_left_exit_21
	dw	GT_left_exit_21
	dw	id_lambs_books
	dw	GT_lambs_books
	dw	id_lambs_chair
	dw	GT_lambs_chair
	dw	id_dispensor
	dw	GT_dispensor
	dw	id_catfood
	dw	GT_cat_food
	dw	id_video
	dw	GT_video
	dw	id_cassette
	dw	GT_cassette
	dw	id_big_pict1
	dw	GT_big_pict1
	dw	id_big_pict2
	dw	GT_big_pict2
	dw	id_big_pict3
	dw	GT_big_pict3
	dw	id_video_screen
	dw	GT_video_screen
	dw	id_cat
	dw	GT_cat
	dw	-1


rs_foster_20_21	dw	c_xcood
	dw	136
	dw	c_ycood
	dw	296
	dw	c_screen
	dw	21
	dw	c_place
	dw	id_s21_floor
	dw	-1



end32data

start32save_data



left_exit_21	dw	0
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	0
	dw	173
	dw	240
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	181-173
	dw	301-240
	dw	el21_action



end32save_data

start32data



rs_foster_21_20	dw	c_xcood
	dw	328
	dw	c_ycood
	dw	280
	dw	c_screen
	dw	20
	dw	c_place
	dw	id_s20_floor
	dw	-1



end32data

start32save_data



lambs_books	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	202
	dw	240
	dw	null
	dw	12669
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	227-202
	dw	270-240
	dw	lambs_books_action


lambs_chair	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	250
	dw	262
	dw	null
	dw	12665
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	271-250
	dw	293-262
	dw	lambs_chair_action


dispensor	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	387
	dw	228
	dw	null
	dw	12668
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	398-387
	dw	280-228
	dw	dispensor_action



end32save_data

start32data



push_dispensor	dw	s201
	dw	352
	dw	224
	dw	0
	dw	352
	dw	224
	dw	1
	dw	352
	dw	224
	dw	2
	dw	352
	dw	224
	dw	3
	dw	352
	dw	224
	dw	4
	dw	352
	dw	224
	dw	4
	dw	352
	dw	224
	dw	4
	dw	352
	dw	224
	dw	4
	dw	352
	dw	224
	dw	2
	dw	352
	dw	224
	dw	5
	dw	352
	dw	224
	dw	0
	dw	0



end32data

start32save_data



cat_food	dw	l_script
	dw	st_logic+st_recreate
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	0
	dw	0
	dw	null
	dw	193
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	2
	dw	18
	dw	6
	dw	1
	dw	cat_food_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	cat_food_logic
	dw	0



end32save_data

start32data



cat_food_seq	dw	s202
	dw	372
	dw	263
	dw	0
	dw	372
	dw	263
	dw	1
	dw	372
	dw	263
	dw	2
	dw	372
	dw	263
	dw	3
	dw	372
	dw	263
	dw	4
	dw	372
	dw	263
	dw	5
	dw	372
	dw	263
	dw	2
	dw	372
	dw	263
	dw	3
	dw	372
	dw	263
	dw	4
	dw	372
	dw	263
	dw	5
	dw	372
	dw	263
	dw	6
	dw	372
	dw	263
	dw	7
	dw	372
	dw	263
	dw	8
	dw	372
	dw	263
	dw	9
	dw	372
	dw	263
	dw	10
	dw	372
	dw	263
	dw	11
	dw	372
	dw	263
	dw	12
	dw	372
	dw	263
	dw	13
	dw	372
	dw	263
	dw	14
	dw	372
	dw	263
	dw	15
	dw	372
	dw	263
	dw	16
	dw	372
	dw	263
	dw	17
	dw	372
	dw	263
	dw	18
	dw	372
	dw	263
	dw	19
	dw	372
	dw	263
	dw	20
	dw	0



end32data

start32save_data



video	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	345
	dw	259
	dw	null
	dw	12677
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	-7
	dw	25
	dw	19
	dw	video_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	video_logic
	dw	0


cassette	dw	l_script
	dw	st_mouse+st_background+st_recreate
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	216
	dw	230
	dw	s110
	dw	173
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	5
	dw	8
	dw	cassette_action



end32save_data

start32data



put_video_in	dw	s108
	dw	322
	dw	218
	dw	0
	dw	322
	dw	218
	dw	1
	dw	322
	dw	218
	dw	2
	dw	322
	dw	218
	dw	3
	dw	send_sync
	dw	id_video
	dw	1
	dw	322
	dw	218
	dw	4
	dw	0


take_video_out	dw	s108
	dw	322
	dw	218
	dw	3
	dw	send_sync
	dw	id_video
	dw	1
	dw	322
	dw	218
	dw	2
	dw	322
	dw	218
	dw	1
	dw	322
	dw	218
	dw	0
	dw	0


bend_down	dw	s108
	dw	322
	dw	218
	dw	0
	dw	322
	dw	218
	dw	7
	dw	322
	dw	218
	dw	6
	dw	322
	dw	218
	dw	5
	dw	322
	dw	218
	dw	4
	dw	0


watch_film	dw	s108
	dw	322
	dw	218
	dw	4
	dw	322
	dw	218
	dw	5
	dw	322
	dw	218
	dw	6
	dw	322
	dw	218
	dw	7
	dw	322
	dw	218
	dw	0
	dw	0


video_in	dw	s109
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	1
	dw	345
	dw	259
	dw	2
	dw	345
	dw	259
	dw	3
	dw	345
	dw	259
	dw	4
	dw	345
	dw	259
	dw	5
	dw	0


video_out	dw	s109
	dw	345
	dw	259
	dw	5
	dw	345
	dw	259
	dw	4
	dw	345
	dw	259
	dw	3
	dw	345
	dw	259
	dw	2
	dw	345
	dw	259
	dw	1
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	0
	dw	345
	dw	259
	dw	0
	dw	0


take_cassette_seq	dw	s107
	dw	217
	dw	216
	dw	0
	dw	217
	dw	216
	dw	1
	dw	217
	dw	216
	dw	2
	dw	217
	dw	216
	dw	3
	dw	217
	dw	216
	dw	3
	dw	217
	dw	216
	dw	3
	dw	217
	dw	216
	dw	3
	dw	0


more_cassette_seq	dw	s107
	dw	217
	dw	216
	dw	2
	dw	217
	dw	216
	dw	1
	dw	217
	dw	216
	dw	0
	dw	0



end32data

start32save_data



big_pict1	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	195
	dw	191
	dw	null
	dw	12680
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	211-195
	dw	228-191
	dw	big_pict1_action


video_screen	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	348
	dw	216
	dw	null
	dw	57
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	378-349
	dw	253-216
	dw	video_screen_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	video_screen_logic
	dw	0


big_pict2	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	227
	dw	188
	dw	null
	dw	12680
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	236-227
	dw	212-188
	dw	big_pict2_action


big_pict3	dw	null
	dw	st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	264
	dw	190
	dw	null
	dw	12680
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	295-264
	dw	213-190
	dw	big_pict3_action



end32save_data

start32data



cat1_seq	dw	s103
	dw	347
	dw	214
	dw	0
	dw	347
	dw	214
	dw	1
	dw	347
	dw	214
	dw	2
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	4
	dw	347
	dw	214
	dw	5
	dw	347
	dw	214
	dw	6
	dw	347
	dw	214
	dw	7
	dw	347
	dw	214
	dw	8
	dw	347
	dw	214
	dw	9
	dw	347
	dw	214
	dw	10
	dw	347
	dw	214
	dw	11
	dw	347
	dw	214
	dw	12
	dw	347
	dw	214
	dw	13
	dw	347
	dw	214
	dw	14
	dw	347
	dw	214
	dw	15
	dw	347
	dw	214
	dw	16
	dw	347
	dw	214
	dw	17
	dw	347
	dw	214
	dw	18
	dw	347
	dw	214
	dw	19
	dw	347
	dw	214
	dw	20
	dw	347
	dw	214
	dw	21
	dw	347
	dw	214
	dw	22
	dw	347
	dw	214
	dw	23
	dw	347
	dw	214
	dw	24
	dw	347
	dw	214
	dw	25
	dw	347
	dw	214
	dw	26
	dw	347
	dw	214
	dw	27
	dw	347
	dw	214
	dw	28
	dw	347
	dw	214
	dw	29
	dw	347
	dw	214
	dw	30
	dw	347
	dw	214
	dw	31
	dw	347
	dw	214
	dw	32
	dw	347
	dw	214
	dw	33
	dw	347
	dw	214
	dw	34
	dw	347
	dw	214
	dw	35
	dw	347
	dw	214
	dw	36
	dw	347
	dw	214
	dw	37
	dw	347
	dw	214
	dw	27
	dw	347
	dw	214
	dw	28
	dw	347
	dw	214
	dw	29
	dw	347
	dw	214
	dw	30
	dw	347
	dw	214
	dw	31
	dw	347
	dw	214
	dw	32
	dw	347
	dw	214
	dw	33
	dw	347
	dw	214
	dw	34
	dw	347
	dw	214
	dw	35
	dw	347
	dw	214
	dw	36
	dw	347
	dw	214
	dw	37
	dw	347
	dw	214
	dw	38
	dw	347
	dw	214
	dw	39
	dw	347
	dw	214
	dw	40
	dw	347
	dw	214
	dw	41
	dw	347
	dw	214
	dw	42
	dw	347
	dw	214
	dw	43
	dw	347
	dw	214
	dw	44
	dw	0


cat2_seq	dw	s104
	dw	347
	dw	214
	dw	0
	dw	347
	dw	214
	dw	1
	dw	347
	dw	214
	dw	2
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	4
	dw	347
	dw	214
	dw	5
	dw	347
	dw	214
	dw	6
	dw	347
	dw	214
	dw	7
	dw	347
	dw	214
	dw	8
	dw	347
	dw	214
	dw	9
	dw	347
	dw	214
	dw	10
	dw	347
	dw	214
	dw	11
	dw	347
	dw	214
	dw	12
	dw	347
	dw	214
	dw	13
	dw	347
	dw	214
	dw	14
	dw	347
	dw	214
	dw	15
	dw	347
	dw	214
	dw	16
	dw	347
	dw	214
	dw	17
	dw	347
	dw	214
	dw	18
	dw	347
	dw	214
	dw	19
	dw	347
	dw	214
	dw	20
	dw	347
	dw	214
	dw	21
	dw	347
	dw	214
	dw	22
	dw	0


cat3_seq	dw	s105
	dw	347
	dw	214
	dw	0
	dw	347
	dw	214
	dw	1
	dw	347
	dw	214
	dw	2
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	4
	dw	347
	dw	214
	dw	5
	dw	347
	dw	214
	dw	6
	dw	347
	dw	214
	dw	7
	dw	347
	dw	214
	dw	8
	dw	347
	dw	214
	dw	9
	dw	347
	dw	214
	dw	10
	dw	347
	dw	214
	dw	11
	dw	347
	dw	214
	dw	12
	dw	347
	dw	214
	dw	13
	dw	347
	dw	214
	dw	14
	dw	347
	dw	214
	dw	15
	dw	347
	dw	214
	dw	16
	dw	347
	dw	214
	dw	17
	dw	347
	dw	214
	dw	18
	dw	347
	dw	214
	dw	19
	dw	347
	dw	214
	dw	20
	dw	347
	dw	214
	dw	21
	dw	347
	dw	214
	dw	22
	dw	347
	dw	214
	dw	23
	dw	347
	dw	214
	dw	24
	dw	347
	dw	214
	dw	25
	dw	347
	dw	214
	dw	26
	dw	347
	dw	214
	dw	27
	dw	347
	dw	214
	dw	28
	dw	0


cat4_seq	dw	s106
	dw	347
	dw	214
	dw	0
	dw	347
	dw	214
	dw	1
	dw	347
	dw	214
	dw	2
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	4
	dw	347
	dw	214
	dw	5
	dw	347
	dw	214
	dw	6
	dw	347
	dw	214
	dw	7
	dw	347
	dw	214
	dw	8
	dw	347
	dw	214
	dw	9
	dw	347
	dw	214
	dw	10
	dw	347
	dw	214
	dw	11
	dw	347
	dw	214
	dw	12
	dw	347
	dw	214
	dw	13
	dw	347
	dw	214
	dw	14
	dw	347
	dw	214
	dw	15
	dw	347
	dw	214
	dw	16
	dw	347
	dw	214
	dw	17
	dw	347
	dw	214
	dw	18
	dw	347
	dw	214
	dw	19
	dw	347
	dw	214
	dw	0
	dw	347
	dw	214
	dw	1
	dw	347
	dw	214
	dw	2
	dw	347
	dw	214
	dw	3
	dw	347
	dw	214
	dw	4
	dw	347
	dw	214
	dw	5
	dw	347
	dw	214
	dw	6
	dw	347
	dw	214
	dw	7
	dw	347
	dw	214
	dw	8
	dw	347
	dw	214
	dw	9
	dw	347
	dw	214
	dw	10
	dw	347
	dw	214
	dw	11
	dw	347
	dw	214
	dw	12
	dw	347
	dw	214
	dw	13
	dw	347
	dw	214
	dw	14
	dw	347
	dw	214
	dw	15
	dw	347
	dw	214
	dw	16
	dw	347
	dw	214
	dw	20
	dw	347
	dw	214
	dw	21
	dw	347
	dw	214
	dw	22
	dw	347
	dw	214
	dw	23
	dw	0



end32data

start32save_data



cat	dw	l_script
	dw	st_mouse+st_logic+st_recreate+st_background
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	250
	dw	228
	dw	s101
	dw	195
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	274-250
	dw	235-228
	dw	cat_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	cat_logic
	dw	0



end32save_data

start32data



cat_walk_seq	dw	s101
	dw	250
	dw	228
	dw	0
	dw	250
	dw	228
	dw	1
	dw	250
	dw	228
	dw	2
	dw	251
	dw	226
	dw	3
	dw	254
	dw	224
	dw	4
	dw	254
	dw	221
	dw	5
	dw	254
	dw	221
	dw	6
	dw	254
	dw	222
	dw	7
	dw	254
	dw	220
	dw	8
	dw	253
	dw	218
	dw	9
	dw	253
	dw	218
	dw	9
	dw	253
	dw	218
	dw	9
	dw	253
	dw	218
	dw	10
	dw	253
	dw	218
	dw	10
	dw	253
	dw	220
	dw	11
	dw	253
	dw	219
	dw	12
	dw	254
	dw	220
	dw	13
	dw	254
	dw	219
	dw	14
	dw	254
	dw	220
	dw	15
	dw	254
	dw	221
	dw	16
	dw	254
	dw	222
	dw	17
	dw	254
	dw	222
	dw	18
	dw	254
	dw	224
	dw	19
	dw	254
	dw	226
	dw	20
	dw	255
	dw	226
	dw	21
	dw	255
	dw	226
	dw	22
	dw	255
	dw	226
	dw	23
	dw	254
	dw	227
	dw	24
	dw	256
	dw	228
	dw	25
	dw	256
	dw	230
	dw	26
	dw	264
	dw	232
	dw	27
	dw	278
	dw	238
	dw	28
	dw	289
	dw	250
	dw	29
	dw	292
	dw	256
	dw	30
	dw	293
	dw	260
	dw	31
	dw	296
	dw	261
	dw	32
	dw	297
	dw	262
	dw	33
	dw	299
	dw	263
	dw	34
	dw	300
	dw	264
	dw	35
	dw	302
	dw	265
	dw	36
	dw	305
	dw	265
	dw	37
	dw	307
	dw	266
	dw	38
	dw	309
	dw	266
	dw	39
	dw	314
	dw	267
	dw	40
	dw	316
	dw	268
	dw	41
	dw	317
	dw	268
	dw	42
	dw	320
	dw	268
	dw	43
	dw	322
	dw	268
	dw	44
	dw	324
	dw	268
	dw	45
	dw	327
	dw	269
	dw	46
	dw	329
	dw	269
	dw	47
	dw	331
	dw	269
	dw	48
	dw	334
	dw	269
	dw	49
	dw	338
	dw	269
	dw	50
	dw	340
	dw	269
	dw	51
	dw	344
	dw	269
	dw	52
	dw	347
	dw	269
	dw	53
	dw	0


cat_eat_seq	dw	s102
	dw	348
	dw	269
	dw	0
	dw	348
	dw	269
	dw	1
	dw	348
	dw	269
	dw	2
	dw	348
	dw	269
	dw	3
	dw	348
	dw	269
	dw	1
	dw	348
	dw	269
	dw	4
	dw	0



end32data

start32save_data



fake_floor_21	dw	0
	dw	0
	dw	0
	dw	21
	dw	NULL
	dd	s22_floor_table
	dw	128
	dw	136
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action


inner_lamb_door	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	21
	dw	NULL
	dd	NULL
	dw	173
	dw	242
	dw	s89
	dw	181
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	-2
	dw	181-173
	dw	308-242
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	inner_lamb_door_logic
	dw	0



end32save_data

start32data



inner_lamb_open	dw	s89
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	11
	dw	0


inner_lamb_close	dw	s89
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


lamb_sit_seq	dw	s218
	dw	268
	dw	241
	dw	0
	dw	264
	dw	241
	dw	1
	dw	253
	dw	247
	dw	2
	dw	249
	dw	246
	dw	3
	dw	249
	dw	245
	dw	4
	dw	249
	dw	246
	dw	5
	dw	248
	dw	246
	dw	6
	dw	248
	dw	246
	dw	7
	dw	248
	dw	246
	dw	8
	dw	248
	dw	246
	dw	9
	dw	0


lamb_sit_up	dw	s218
	dw	248
	dw	246
	dw	9
	dw	248
	dw	246
	dw	8
	dw	248
	dw	246
	dw	7
	dw	248
	dw	246
	dw	6
	dw	249
	dw	246
	dw	5
	dw	249
	dw	245
	dw	4
	dw	249
	dw	246
	dw	3
	dw	253
	dw	247
	dw	2
	dw	264
	dw	241
	dw	1
	dw	268
	dw	241
	dw	0
	dw	0



end32data

start32save_data



end32save_data
