start32data



s22_chip_list	dw	196+disk_9
	dw	197+disk_9
	dw	198+disk_9
	dw	199+disk_9
	dw	91+disk_9
	dw	92+disk_9
	dw	200+disk_9
	dw	85+disk_9
	dw	0


s22_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	187+disk_9
	dw	188+disk_9
	dw	189+disk_9
	dw	190+disk_9
	dw	191+disk_9
	dw	0


grid22	dd 0 dup (0)

s22_pal	dw	0
	dw	0
	dw	0
	dw	7
	dw	768
	dw	0
	dw	9
	dw	1024
	dw	259
	dw	266
	dw	2048
	dw	514
	dw	526
	dw	2560
	dw	4
	dw	1032
	dw	1540
	dw	1030
	dw	1037
	dw	4608
	dw	257
	dw	1292
	dw	4353
	dw	4
	dw	785
	dw	2307
	dw	1799
	dw	1806
	dw	5633
	dw	258
	dw	2316
	dw	5381
	dw	6
	dw	2061
	dw	4616
	dw	9
	dw	1050
	dw	4098
	dw	1034
	dw	2576
	dw	5130
	dw	522
	dw	2835
	dw	6149
	dw	9
	dw	3341
	dw	7435
	dw	1030
	dw	2073
	dw	5638
	dw	1292
	dw	3601
	dw	6921
	dw	1035
	dw	3601
	dw	3342
	dw	2067
	dw	4367
	dw	6412
	dw	526
	dw	3353
	dw	5385
	dw	3343
	dw	4121
	dw	7430
	dw	2061
	dw	4631
	dw	7434
	dw	1296
	dw	6414
	dw	8458
	dw	783
	dw	5393
	dw	6929
	dw	2833
	dw	5141
	dw	3854
	dw	3609
	dw	4129
	dw	7943
	dw	3088
	dw	5397
	dw	7698
	dw	2067
	dw	5147
	dw	6414
	dw	4628
	dw	5912
	dw	8717
	dw	2579
	dw	5155
	dw	7685
	dw	2838
	dw	6929
	dw	5909
	dw	5400
	dw	5915
	dw	4884
	dw	4637
	dw	6177
	dw	4873
	dw	3616
	dw	5669
	dw	7945
	dw	3864
	dw	7195
	dw	8975
	dw	3352
	dw	6684
	dw	10008
	dw	3096
	dw	8725
	dw	8467
	dw	3101
	dw	6691
	dw	6673
	dw	4385
	dw	8470
	dw	8473
	dw	5659
	dw	7710
	dw	7957
	dw	6684
	dw	7206
	dw	10767
	dw	2843
	dw	9240
	dw	9750
	dw	4892
	dw	7716
	dw	8471
	dw	7199
	dw	7721
	dw	9745
	dw	4896
	dw	10009
	dw	10009
	dw	2339
	dw	8235
	dw	8205
	dw	8226
	dw	9758
	dw	9496
	dw	6689
	dw	7980
	dw	10260
	dw	5922
	dw	10012
	dw	10783
	dw	4643
	dw	9005
	dw	11279
	dw	6177
	dw	9252
	dw	10017
	dw	7205
	dw	11038
	dw	10525
	dw	5415
	dw	9263
	dw	11032
	dw	7717
	dw	10023
	dw	12576
	dw	4902
	dw	11553
	dw	11552
	dw	6951
	dw	10026
	dw	11812
	dw	8486
	dw	10033
	dw	12314
	dw	7720
	dw	10797
	dw	10532
	dw	10028
	dw	10803
	dw	12572
	dw	8746
	dw	11571
	dw	11296
	dw	10798
	dw	11314
	dw	12070
	dw	11312
	dw	12339
	dw	12841
	dw	12081
	dw	13364
	dw	13356
	dw	12596
	dw	0
	dw	3840
	dw	3089
	dw	5393
	dw	5393
	dw	3604
	dw	5397
	dw	6162
	dw	3351
	dw	6929
	dw	5909
	dw	5400
	dw	7443
	dw	7186
	dw	6170
	dw	8470
	dw	7705
	dw	5406
	dw	10009
	dw	7193
	dw	7975
	dw	11038
	dw	8477
	dw	8237
	dw	0
	dw	4096
	dw	2570
	dw	3601
	dw	4361
	dw	3598
	dw	3861
	dw	5389
	dw	3604
	dw	5145
	dw	6930
	dw	5143
	dw	6175
	dw	7183
	dw	6170
	dw	6945
	dw	8470
	dw	7199
	dw	8485
	dw	10010
	dw	7205
	dw	9515
	dw	10014
	dw	8231
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	15360
	dw	13621
	dw	12856
	dw	13106
	dw	11309
	dw	9773
	dw	9253
	dw	7710
	dw	5916
	dw	5143
	dw	4112
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s22_logic	dw	id_foster
	dw	id_joey
	dw	id_fish_tank
	dw	id_magazine
	dw	id_pillow
	dw	id_inner_r_door
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_gallager_bel
	dw	id_lift_29
	dw	$ffff
	dw	id_menu_logic


s22_mouse	dw	id_joey
	dw	id_inner_r_door
	dw	id_right_exit_22
	dw	id_magazine
	dw	id_pillow
	dw	id_lamb_bed
	dw	id_lamb_tv
	dw	id_fish_tank
	dw	id_fish_poster
	dw	id_reich_chair
	dw	id_cabinet
	dw	id_cert
	dw	id_reich_picture
	dw	id_fish_food
	dw	id_s22_floor
	dw	id_fake_floor_22
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s22_floor	dw	0
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	s22_floor_table
	dw	128
	dw	240
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action



end32save_data

start32data



s22_floor_table	dw	id_s22_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s22_start_on
	dw	id_right_exit_22
	dw	GT_right_exit_22
	dw	id_lamb_bed
	dw	GT_lamb_bed
	dw	id_lamb_tv
	dw	GT_lamb_tv
	dw	id_fish_tank
	dw	GT_fish_tank
	dw	id_fish_poster
	dw	GT_fish_tank
	dw	id_pillow
	dw	GT_pillow
	dw	id_magazine
	dw	GT_magazine
	dw	id_reich_chair
	dw	GT_reich_chair
	dw	id_cabinet
	dw	GT_cabinet
	dw	id_cert
	dw	GT_cert
	dw	id_reich_picture
	dw	GT_reich_picture
	dw	id_fish_food
	dw	GT_fish_food
	dw	-1


rs_foster_20_22	dw	c_xcood
	dw	424
	dw	c_ycood
	dw	304
	dw	c_screen
	dw	22
	dw	c_place
	dw	id_s22_floor
	dw	-1



end32data

start32save_data



right_exit_22	dw	0
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	0
	dw	393
	dw	249
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	402-393
	dw	313-249
	dw	er22_action



end32save_data

start32data



rs_foster_22_20	dw	c_xcood
	dw	216
	dw	c_ycood
	dw	280
	dw	c_screen
	dw	20
	dw	c_place
	dw	id_s20_floor
	dw	-1



end32data

start32save_data



lamb_bed	dw	l_script
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	283
	dw	251
	dw	0
	dw	12731
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	365-283
	dw	275-251
	dw	bed_action


lamb_tv	dw	l_script
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	203
	dw	223
	dw	0
	dw	57
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	225-203
	dw	251-223
	dw	lamb_tv_action


fish_tank	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	245
	dw	238
	dw	s199
	dw	12738
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	-3
	dw	264-242
	dw	258-235
	dw	fish_tank_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	fish_logic
	dw	0


fish_poster	dw	l_script
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	232
	dw	193
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	248-232
	dw	232-193
	dw	fish_poster_action


pillow	dw	l_script
	dw	st_mouse+st_sort+st_logic+st_recreate
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	324
	dw	244
	dw	s196
	dw	12734
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	7
	dw	null
	dw	26
	dw	16
	dw	pillow_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	pillow_logic
	dw	0



end32save_data

start32data



remove_pillow	dw	s196
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	0


replace_pillow	dw	s196
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


fost_remove_pill	dw	s197
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	1
	dw	320
	dw	226
	dw	1
	dw	320
	dw	226
	dw	2
	dw	320
	dw	226
	dw	2
	dw	320
	dw	226
	dw	3
	dw	320
	dw	226
	dw	3
	dw	320
	dw	226
	dw	4
	dw	320
	dw	226
	dw	4
	dw	0


fost_replace_pill	dw	s197
	dw	320
	dw	226
	dw	3
	dw	320
	dw	226
	dw	3
	dw	320
	dw	226
	dw	2
	dw	320
	dw	226
	dw	2
	dw	320
	dw	226
	dw	1
	dw	320
	dw	226
	dw	1
	dw	320
	dw	226
	dw	0
	dw	320
	dw	226
	dw	0
	dw	0



end32data

start32save_data



magazine	dw	l_script
	dw	st_sort+st_recreate
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	340
	dw	249
	dw	s198
	dw	163
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	26
	dw	16
	dw	magazine_action



end32save_data

start32data



rs_magazine	dw	c_screen
	dw	424
	dw	-1


fish_seq	dw	s199
	dw	245
	dw	238
	dw	0
	dw	245
	dw	238
	dw	1
	dw	245
	dw	238
	dw	2
	dw	245
	dw	238
	dw	3
	dw	245
	dw	238
	dw	4
	dw	245
	dw	238
	dw	5
	dw	245
	dw	238
	dw	6
	dw	245
	dw	238
	dw	7
	dw	245
	dw	238
	dw	8
	dw	245
	dw	238
	dw	9
	dw	245
	dw	238
	dw	10
	dw	245
	dw	238
	dw	11
	dw	245
	dw	238
	dw	12
	dw	245
	dw	238
	dw	13
	dw	245
	dw	238
	dw	14
	dw	245
	dw	238
	dw	15
	dw	245
	dw	238
	dw	16
	dw	245
	dw	238
	dw	17
	dw	245
	dw	238
	dw	18
	dw	245
	dw	238
	dw	19
	dw	245
	dw	238
	dw	20
	dw	245
	dw	238
	dw	21
	dw	245
	dw	238
	dw	22
	dw	245
	dw	238
	dw	23
	dw	245
	dw	238
	dw	24
	dw	245
	dw	238
	dw	25
	dw	245
	dw	238
	dw	26
	dw	245
	dw	238
	dw	27
	dw	245
	dw	238
	dw	28
	dw	245
	dw	238
	dw	29
	dw	245
	dw	238
	dw	30
	dw	245
	dw	238
	dw	31
	dw	245
	dw	238
	dw	32
	dw	245
	dw	238
	dw	33
	dw	245
	dw	238
	dw	34
	dw	245
	dw	238
	dw	35
	dw	245
	dw	238
	dw	36
	dw	245
	dw	238
	dw	37
	dw	245
	dw	238
	dw	38
	dw	245
	dw	238
	dw	39
	dw	0


tank2_seq	dw	s91
	dw	245
	dw	238
	dw	0
	dw	245
	dw	238
	dw	1
	dw	245
	dw	238
	dw	2
	dw	245
	dw	238
	dw	3
	dw	245
	dw	238
	dw	4
	dw	245
	dw	238
	dw	5
	dw	245
	dw	238
	dw	6
	dw	245
	dw	238
	dw	7
	dw	245
	dw	238
	dw	8
	dw	245
	dw	238
	dw	4
	dw	245
	dw	238
	dw	9
	dw	245
	dw	238
	dw	6
	dw	245
	dw	238
	dw	7
	dw	245
	dw	238
	dw	10
	dw	245
	dw	238
	dw	11
	dw	245
	dw	238
	dw	12
	dw	245
	dw	238
	dw	13
	dw	245
	dw	238
	dw	14
	dw	245
	dw	238
	dw	15
	dw	245
	dw	238
	dw	16
	dw	245
	dw	238
	dw	17
	dw	245
	dw	238
	dw	18
	dw	245
	dw	238
	dw	19
	dw	245
	dw	238
	dw	20
	dw	245
	dw	238
	dw	21
	dw	245
	dw	238
	dw	22
	dw	245
	dw	238
	dw	23
	dw	245
	dw	238
	dw	24
	dw	245
	dw	238
	dw	25
	dw	245
	dw	238
	dw	26
	dw	0


tank3_seq	dw	s92
	dw	245
	dw	238
	dw	0
	dw	245
	dw	238
	dw	1
	dw	245
	dw	238
	dw	2
	dw	245
	dw	238
	dw	3
	dw	245
	dw	238
	dw	4
	dw	245
	dw	238
	dw	5
	dw	245
	dw	238
	dw	6
	dw	245
	dw	238
	dw	7
	dw	245
	dw	238
	dw	8
	dw	245
	dw	238
	dw	9
	dw	245
	dw	238
	dw	10
	dw	245
	dw	238
	dw	11
	dw	245
	dw	238
	dw	12
	dw	245
	dw	238
	dw	13
	dw	245
	dw	238
	dw	14
	dw	245
	dw	238
	dw	15
	dw	245
	dw	238
	dw	16
	dw	245
	dw	238
	dw	17
	dw	245
	dw	238
	dw	18
	dw	245
	dw	238
	dw	19
	dw	0


get_magazine_seq	dw	s200
	dw	273
	dw	218
	dw	0
	dw	273
	dw	218
	dw	1
	dw	273
	dw	218
	dw	2
	dw	273
	dw	218
	dw	3
	dw	273
	dw	218
	dw	3
	dw	273
	dw	218
	dw	3
	dw	273
	dw	218
	dw	2
	dw	273
	dw	218
	dw	1
	dw	273
	dw	218
	dw	0
	dw	0



end32data

start32save_data



reich_chair	dw	null
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	221
	dw	287
	dw	null
	dw	12752
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	240-221
	dw	314-287
	dw	reich_chair_action


cabinet	dw	null
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	312
	dw	239
	dw	null
	dw	12749
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	340-312
	dw	248-239
	dw	cabinet_action


cert	dw	null
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	310
	dw	215
	dw	null
	dw	12746
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	325-310
	dw	224-215
	dw	cert_action


reich_picture	dw	null
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	259
	dw	175
	dw	null
	dw	12744
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	326-259
	dw	210-175
	dw	reich_picture_action


fish_food	dw	null
	dw	st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	179
	dw	236
	dw	null
	dw	12668
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	192-179
	dw	289-236
	dw	fish_food_action


fake_floor_22	dw	0
	dw	0
	dw	0
	dw	22
	dw	NULL
	dd	s22_floor_table
	dw	128
	dw	136
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action


inner_reich_door	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	22
	dw	NULL
	dd	NULL
	dw	393
	dw	249
	dw	s85
	dw	181
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	403-393
	dw	313-249
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	inner_r_door_logic
	dw	0



end32save_data

start32data



inner_reich_open	dw	s85
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	12
	dw	0


inner_reich_close	dw	s85
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



end32save_data
