start32data



s24_chip_list	dw	136+disk_8
	dw	137+disk_8
	dw	61+disk_8
	dw	62+disk_8
	dw	63+disk_8
	dw	64+disk_8
	dw	65+disk_8
	dw	66+disk_8
	dw	67+disk_8
	dw	68+disk_8
	dw	69+disk_8
	dw	70+disk_8
	dw	72+disk_8
	dw	74+disk_8
	dw	71+disk_8
	dw	75+disk_8
	dw	29+disk_8
	dw	30+disk_8
	dw	31+disk_8
	dw	0


s24_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	0


grid24	dd 0 dup (0)

s24_pal	dw	0
	dw	0
	dw	0
	dw	5
	dw	512
	dw	2
	dw	773
	dw	2560
	dw	1
	dw	512
	dw	1040
	dw	518
	dw	525
	dw	2049
	dw	1029
	dw	769
	dw	2069
	dw	1798
	dw	1291
	dw	4099
	dw	5
	dw	1540
	dw	2838
	dw	1288
	dw	2054
	dw	4882
	dw	772
	dw	2825
	dw	1796
	dw	2826
	dw	2314
	dw	1807
	dw	5897
	dw	2577
	dw	4098
	dw	2057
	dw	1306
	dw	5121
	dw	1288
	dw	3594
	dw	5638
	dw	264
	dw	3601
	dw	2821
	dw	3088
	dw	1566
	dw	6659
	dw	266
	dw	3346
	dw	3850
	dw	3342
	dw	2840
	dw	3590
	dw	2322
	dw	2082
	dw	5378
	dw	1807
	dw	3352
	dw	3338
	dw	4114
	dw	4108
	dw	7962
	dw	1290
	dw	3356
	dw	3844
	dw	5138
	dw	3616
	dw	6145
	dw	3089
	dw	5137
	dw	9232
	dw	1291
	dw	4371
	dw	7702
	dw	1808
	dw	5398
	dw	8713
	dw	1296
	dw	4880
	dw	4382
	dw	5909
	dw	4633
	dw	4625
	dw	4887
	dw	3622
	dw	6920
	dw	3348
	dw	4895
	dw	5386
	dw	4121
	dw	5654
	dw	8984
	dw	2067
	dw	5651
	dw	9759
	dw	2834
	dw	5911
	dw	10525
	dw	533
	dw	5919
	dw	5134
	dw	8474
	dw	5666
	dw	6161
	dw	6427
	dw	6429
	dw	9752
	dw	2327
	dw	5415
	dw	9230
	dw	3352
	dw	7191
	dw	8222
	dw	5147
	dw	6445
	dw	10498
	dw	3097
	dw	7448
	dw	6947
	dw	8220
	dw	6691
	dw	11031
	dw	4120
	dw	7454
	dw	11035
	dw	2075
	dw	7460
	dw	10258
	dw	3868
	dw	7713
	dw	6936
	dw	8736
	dw	6446
	dw	8979
	dw	7454
	dw	7211
	dw	12053
	dw	544
	dw	7976
	dw	11028
	dw	4127
	dw	8736
	dw	11810
	dw	3105
	dw	8233
	dw	12313
	dw	1570
	dw	7982
	dw	11028
	dw	5410
	dw	8999
	dw	8476
	dw	10020
	dw	8494
	dw	8984
	dw	8997
	dw	8753
	dw	11029
	dw	7716
	dw	9521
	dw	12559
	dw	6946
	dw	10275
	dw	10023
	dw	9512
	dw	9777
	dw	11801
	dw	7207
	dw	10030
	dw	9761
	dw	10794
	dw	9779
	dw	13085
	dw	5674
	dw	10801
	dw	12829
	dw	8745
	dw	11052
	dw	10536
	dw	11053
	dw	11572
	dw	12831
	dw	9261
	dw	12332
	dw	13100
	dw	10032
	dw	12592
	dw	12586
	dw	11827
	dw	12853
	dw	13355
	dw	12853
	dw	0
	dw	0
	dw	4098
	dw	1540
	dw	1538
	dw	4616
	dw	2825
	dw	1796
	dw	2826
	dw	2314
	dw	4367
	dw	1294
	dw	3599
	dw	6157
	dw	3089
	dw	4371
	dw	5654
	dw	2325
	dw	4880
	dw	7966
	dw	3607
	dw	7454
	dw	9499
	dw	9765
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	15167
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	15163
	dw	13883
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s24_logic	dw	id_foster
	dw	id_joey
	dw	id_trevor
	dw	id_ticket
	dw	id_globe
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_lift_29
	dw	id_gallager_bel
	dw	$ffff
	dw	id_menu_logic


s24_mouse	dw	id_joey
	dw	id_left_exit_24
	dw	id_london_poster
	dw	id_new_york
	dw	id_pidgeons
	dw	id_mural
	dw	id_trevor
	dw	id_ticket
	dw	id_globe
	dw	id_s24_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s24_floor	dw	0
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	s24_floor_table
	dw	128
	dw	272
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action



end32save_data

start32data



s24_floor_table	dw	id_s24_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s24_left_on
	dw	id_left_exit_24
	dw	GT_left_exit_24
	dw	id_london_poster
	dw	GT_london_poster
	dw	id_new_york
	dw	GT_new_york
	dw	id_mural
	dw	GT_mural
	dw	id_pidgeons
	dw	GT_pidgeons
	dw	id_trevor
	dw	GT_trevor
	dw	id_ticket
	dw	GT_ticket
	dw	id_globe
	dw	GT_globe
	dw	-1


rs_foster_23_24	dw	c_xcood
	dw	160
	dw	c_ycood
	dw	296
	dw	c_screen
	dw	24
	dw	c_place
	dw	id_s24_floor
	dw	-1



end32data

start32save_data



left_exit_24	dw	0
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	0
	dw	175
	dw	247
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	196-175
	dw	308-247
	dw	el24_action



end32save_data

start32data



rs_foster_24_23	dw	c_xcood
	dw	328
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	23
	dw	c_place
	dw	id_s23_floor
	dw	-1



end32data

start32save_data



london_poster	dw	l_script
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	207
	dw	166
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	237-207
	dw	226-166
	dw	london_action


new_york_poster	dw	l_script
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	162
	dw	166
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	200-162
	dw	245-166
	dw	new_york_action


mural	dw	l_script
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	244
	dw	159
	dw	0
	dw	12767
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	383-244
	dw	238-159
	dw	mural_action


pidgeons	dw	l_script
	dw	st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	246
	dw	232
	dw	0
	dw	12772
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	291-246
	dw	275-232
	dw	pidgeons_action


trevor	dw	l_script
	dw	st_recreate+st_logic+st_mouse+st_background
	dw	0
	dw	24
	dw	0
	dd	0
	dw	351
	dw	239
	dw	s62
	dw	4
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	16
	dw	0
	dw	297-271
	dw	256-233
	dw	trevor_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	trevor_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	null
	dw	null
	dw	null
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_trevor
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	null
	dw	0



end32save_data

start32data



trevor_relax	dw	s61
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	0


trevor_unrelax	dw	s61
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


joey_list_s24	dw	224
	dw	344
	dw	280
	dw	320
	dw	1
	dw	293
	dw	361
	dw	264
	dw	294
	dw	0
	dw	0


trevor_scratch	dw	s62
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	4
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	4
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	4
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	4
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	0
	dw	0


trev_get_mag	dw	s63
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	3
	dw	351
	dw	239
	dw	4
	dw	351
	dw	239
	dw	5
	dw	351
	dw	239
	dw	6
	dw	0


trev_read_mag	dw	s64
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	0
	dw	0


trev_turn_page	dw	s65
	dw	351
	dw	239
	dw	0
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	2
	dw	351
	dw	239
	dw	1
	dw	351
	dw	239
	dw	0
	dw	0


mag_out	dw	s66
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


mag_away	dw	s66
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	0


mag_back_seq	dw	s69
	dw	253
	dw	226
	dw	0
	dw	253
	dw	226
	dw	1
	dw	253
	dw	226
	dw	2
	dw	253
	dw	226
	dw	3
	dw	253
	dw	226
	dw	3
	dw	253
	dw	226
	dw	3
	dw	253
	dw	226
	dw	3
	dw	253
	dw	226
	dw	4
	dw	253
	dw	226
	dw	5
	dw	253
	dw	226
	dw	6
	dw	253
	dw	226
	dw	6
	dw	253
	dw	226
	dw	7
	dw	0


give_mag_seq	dw	s70
	dw	131
	dw	226
	dw	0
	dw	131
	dw	226
	dw	0
	dw	131
	dw	226
	dw	0
	dw	131
	dw	226
	dw	1
	dw	131
	dw	226
	dw	2
	dw	131
	dw	226
	dw	2
	dw	131
	dw	226
	dw	2
	dw	131
	dw	226
	dw	3
	dw	131
	dw	226
	dw	4
	dw	0



end32data

start32save_data



ticket	dw	l_script
	dw	st_logic+st_recreate
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	324
	dw	244
	dw	0
	dw	189
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	6
	dw	5
	dw	ticket_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	ticket_logic
	dw	0



end32save_data

start32data



ticket_seq	dw	s74
	dw	352
	dw	254
	dw	0
	dw	352
	dw	254
	dw	1
	dw	352
	dw	254
	dw	2
	dw	352
	dw	254
	dw	3
	dw	352
	dw	254
	dw	4
	dw	352
	dw	254
	dw	5
	dw	352
	dw	254
	dw	6
	dw	0


get_ticket	dw	s72
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	4
	dw	send_sync
	dw	id_ticket
	dw	1
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



globe	dw	l_script
	dw	st_logic+st_recreate+st_mouse
	dw	0
	dw	24
	dw	NULL
	dd	NULL
	dw	274
	dw	275
	dw	0
	dw	12769
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	311-274
	dw	312-275
	dw	globe_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	globe_logic
	dw	0



end32save_data

start32data



globe_spin	dw	s71
	dw	274
	dw	275
	dw	0
	dw	274
	dw	275
	dw	1
	dw	274
	dw	275
	dw	2
	dw	274
	dw	275
	dw	3
	dw	274
	dw	275
	dw	4
	dw	274
	dw	275
	dw	5
	dw	274
	dw	275
	dw	6
	dw	274
	dw	275
	dw	7
	dw	274
	dw	275
	dw	8
	dw	274
	dw	275
	dw	9
	dw	274
	dw	275
	dw	10
	dw	274
	dw	275
	dw	11
	dw	274
	dw	275
	dw	12
	dw	274
	dw	275
	dw	13
	dw	274
	dw	275
	dw	14
	dw	274
	dw	275
	dw	15
	dw	274
	dw	275
	dw	16
	dw	274
	dw	275
	dw	17
	dw	274
	dw	275
	dw	0
	dw	274
	dw	275
	dw	0
	dw	0


push_globe	dw	s75
	dw	265
	dw	193
	dw	0
	dw	265
	dw	193
	dw	1
	dw	265
	dw	193
	dw	2
	dw	265
	dw	193
	dw	2
	dw	265
	dw	193
	dw	1
	dw	265
	dw	193
	dw	0
	dw	0



end32data

start32save_data



end32save_data
