start32data



s26_chip_list	dw	136+disk_9
	dw	137+disk_9
	dw	93+disk_9
	dw	94+disk_9
	dw	95+disk_9
	dw	96+disk_9
	dw	97+disk_9
	dw	98+disk_9
	dw	99+disk_9
	dw	100+disk_9
	dw	140+disk_9
	dw	141+disk_9
	dw	142+disk_9
	dw	0


s26_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	86+disk_9
	dw	87+disk_9
	dw	88+disk_9
	dw	0


grid26	dd 0 dup (0)

s26_pal	dw	0
	dw	2560
	dw	2312
	dw	2314
	dw	3854
	dw	1800
	dw	3085
	dw	4873
	dw	1289
	dw	3086
	dw	4622
	dw	2570
	dw	3601
	dw	5640
	dw	2059
	dw	3344
	dw	3346
	dw	5901
	dw	3098
	dw	4870
	dw	3342
	dw	3857
	dw	3606
	dw	6927
	dw	3358
	dw	6152
	dw	3599
	dw	4122
	dw	4617
	dw	6673
	dw	4630
	dw	7696
	dw	3088
	dw	4629
	dw	6421
	dw	2836
	dw	3618
	dw	4362
	dw	8978
	dw	4886
	dw	4891
	dw	7956
	dw	5401
	dw	7702
	dw	3093
	dw	4641
	dw	8719
	dw	2579
	dw	4389
	dw	4621
	dw	6426
	dw	5915
	dw	7439
	dw	4885
	dw	5656
	dw	10526
	dw	2322
	dw	5414
	dw	6667
	dw	6679
	dw	5922
	dw	8717
	dw	4886
	dw	5414
	dw	5648
	dw	10008
	dw	7704
	dw	7954
	dw	5912
	dw	7957
	dw	6423
	dw	8985
	dw	5420
	dw	6923
	dw	7706
	dw	7709
	dw	7952
	dw	7193
	dw	6185
	dw	9486
	dw	4122
	dw	6680
	dw	10283
	dw	5145
	dw	7197
	dw	6690
	dw	10011
	dw	7968
	dw	11284
	dw	4632
	dw	6446
	dw	9741
	dw	6172
	dw	7457
	dw	10783
	dw	4380
	dw	7451
	dw	12333
	dw	4378
	dw	7964
	dw	9256
	dw	6432
	dw	7712
	dw	11557
	dw	5404
	dw	8994
	dw	10518
	dw	5663
	dw	7474
	dw	10254
	dw	6943
	dw	8483
	dw	12835
	dw	5149
	dw	8238
	dw	9491
	dw	7972
	dw	8498
	dw	10769
	dw	6691
	dw	8994
	dw	13866
	dw	4639
	dw	8752
	dw	9751
	dw	7208
	dw	9770
	dw	13342
	dw	5411
	dw	10279
	dw	14370
	dw	4900
	dw	9266
	dw	13086
	dw	6437
	dw	9774
	dw	10017
	dw	7724
	dw	10031
	dw	10012
	dw	5935
	dw	9528
	dw	15384
	dw	4646
	dw	9782
	dw	11549
	dw	9515
	dw	13354
	dw	14870
	dw	5673
	dw	10043
	dw	13339
	dw	8748
	dw	10553
	dw	11295
	dw	7476
	dw	10047
	dw	14878
	dw	6445
	dw	11324
	dw	11549
	dw	6199
	dw	13358
	dw	13860
	dw	9519
	dw	11070
	dw	11809
	dw	8247
	dw	12350
	dw	12060
	dw	10294
	dw	12348
	dw	13860
	dw	11314
	dw	12863
	dw	12832
	dw	11319
	dw	13884
	dw	15905
	dw	10035
	dw	13882
	dw	13098
	dw	11835
	dw	14140
	dw	15919
	dw	11064
	dw	15165
	dw	16177
	dw	13629
	dw	15677
	dw	16186
	dw	16191
	dw	0
	dw	3840
	dw	1800
	dw	2323
	dw	4613
	dw	2570
	dw	2838
	dw	6664
	dw	1548
	dw	3358
	dw	6664
	dw	2320
	dw	3618
	dw	8714
	dw	2579
	dw	4389
	dw	7437
	dw	4885
	dw	4649
	dw	9737
	dw	4117
	dw	5420
	dw	11787
	dw	3353
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	14851
	dw	9522
	dw	10806
	dw	12828
	dw	5410
	dw	6443
	dw	9485
	dw	1809
	dw	2591
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	13375
	dw	14375
	dw	7724
	dw	9781
	dw	12823
	dw	2589
	dw	5679
	dw	6144
	dw	787
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	7936
	dw	0
	dw	39
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	13881
	dw	14634
	dw	9519
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s26_logic	dw	id_foster
	dw	id_joey
	dw	id_burke
	dw	id_holo
	dw	id_bio_door
	dw	id_leaflet
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_lift_29
	dw	$ffff
	dw	id_menu_logic


s26_mouse	dw	id_joey
	dw	id_bio_door
	dw	id_left_exit_26
	dw	id_right_exit_26
	dw	id_poster1
	dw	id_poster2
	dw	id_poster3
	dw	id_poster4
	dw	id_26_plant
	dw	id_leaflet
	dw	id_holo
	dw	id_s26_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s26_floor	dw	0
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	s26_floor_table
	dw	128
	dw	264
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action



end32save_data

start32data



s26_floor_table	dw	id_s26_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s26_right_on
	dw	1
	dw	s26_left_on
	dw	id_right_exit_26
	dw	GT_right_exit_26
	dw	id_left_exit_26
	dw	GT_left_exit_26
	dw	id_poster1
	dw	GT_poster
	dw	id_poster2
	dw	GT_poster
	dw	id_poster3
	dw	GT_poster
	dw	id_poster4
	dw	GT_poster
	dw	id_26_plant
	dw	GT_plant
	dw	id_leaflet
	dw	GT_leaflet
	dw	id_holo
	dw	GT_holo
	dw	id_bio_door
	dw	GT_bio_door
	dw	-1


rs_foster_19_26	dw	c_xcood
	dw	416
	dw	c_ycood
	dw	288
	dw	c_screen
	dw	26
	dw	c_place
	dw	id_s26_floor
	dw	c_frame
	dw	s12+42
	dw	-1



end32data

start32save_data



right_exit_26	dw	0
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	0
	dw	389
	dw	232
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	398-389
	dw	298-232
	dw	er26_action



end32save_data

start32data



rs_foster_26_19	dw	c_xcood
	dw	136
	dw	c_ycood
	dw	264
	dw	c_screen
	dw	19
	dw	c_place
	dw	id_s19_floor
	dw	-1


rs_joey_start_26	dw	c_xcood
	dw	344
	dw	c_ycood
	dw	312
	dw	c_screen
	dw	26
	dw	c_place
	dw	id_s26_floor
	dw	c_logic
	dw	l_script
	dw	c_base_sub
	dw	joey_logic
	dw	c_base_sub+2
	dw	0
	dw	c_frame
	dw	s136+2
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_collision+st_mouse+st_grid_plot
	dw	c_dir
	dw	down
	dw	-1


joey_list_s26	dw	208
	dw	360
	dw	280
	dw	321
	dw	1
	dw	0



end32data

start32save_data



poster1	dw	l_script
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	262
	dw	184
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	293-262
	dw	204-184
	dw	poster1_action


poster2	dw	l_script
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	297
	dw	184
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	329-297
	dw	204-184
	dw	poster2_action


poster3	dw	l_script
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	262
	dw	208
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	293-262
	dw	225-208
	dw	poster3_action


poster4	dw	l_script
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	297
	dw	208
	dw	0
	dw	12741
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	329-297
	dw	225-208
	dw	poster4_action


plant_26	dw	l_script
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	330
	dw	211
	dw	0
	dw	12785
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	353-330
	dw	237-211
	dw	plant_26_action


holo	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	226
	dw	211
	dw	0
	dw	12783
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	6
	dw	32
	dw	250-231
	dw	251-244
	dw	holo_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	helga_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_holo
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0


left_exit_26	dw	0
	dw	st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	0
	dw	181
	dw	233
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	192-181
	dw	295-233
	dw	el26_action



end32save_data

start32data



helga_awake	dw	s94
	dw	300
	dw	212
	dw	0
	dw	300
	dw	212
	dw	1
	dw	300
	dw	212
	dw	2
	dw	300
	dw	212
	dw	3
	dw	300
	dw	212
	dw	4
	dw	300
	dw	212
	dw	5
	dw	300
	dw	212
	dw	6
	dw	300
	dw	212
	dw	7
	dw	300
	dw	212
	dw	8
	dw	300
	dw	212
	dw	7
	dw	300
	dw	212
	dw	9
	dw	300
	dw	212
	dw	7
	dw	300
	dw	212
	dw	10
	dw	300
	dw	212
	dw	10
	dw	300
	dw	212
	dw	7
	dw	300
	dw	212
	dw	10
	dw	300
	dw	212
	dw	10
	dw	300
	dw	212
	dw	11
	dw	300
	dw	212
	dw	7
	dw	300
	dw	212
	dw	12
	dw	300
	dw	212
	dw	10
	dw	0


helga_byeee	dw	s97
	dw	415
	dw	217
	dw	0
	dw	415
	dw	217
	dw	1
	dw	415
	dw	217
	dw	2
	dw	415
	dw	217
	dw	1
	dw	415
	dw	217
	dw	3
	dw	415
	dw	217
	dw	1
	dw	415
	dw	217
	dw	4
	dw	415
	dw	217
	dw	5
	dw	415
	dw	217
	dw	6
	dw	415
	dw	217
	dw	7
	dw	415
	dw	217
	dw	8
	dw	415
	dw	217
	dw	9
	dw	415
	dw	217
	dw	10
	dw	0


wobble1	dw	s95
	dw	340
	dw	217
	dw	0
	dw	340
	dw	217
	dw	1
	dw	340
	dw	217
	dw	2
	dw	340
	dw	217
	dw	3
	dw	340
	dw	217
	dw	4
	dw	340
	dw	217
	dw	5
	dw	340
	dw	217
	dw	6
	dw	340
	dw	217
	dw	7
	dw	340
	dw	217
	dw	8
	dw	340
	dw	217
	dw	9
	dw	340
	dw	217
	dw	10
	dw	340
	dw	217
	dw	11
	dw	340
	dw	217
	dw	12
	dw	340
	dw	217
	dw	13
	dw	340
	dw	217
	dw	14
	dw	340
	dw	217
	dw	15
	dw	340
	dw	217
	dw	16
	dw	340
	dw	217
	dw	17
	dw	340
	dw	217
	dw	18
	dw	340
	dw	217
	dw	19
	dw	340
	dw	217
	dw	20
	dw	340
	dw	217
	dw	21
	dw	0


wobble2	dw	s96
	dw	378
	dw	217
	dw	0
	dw	378
	dw	217
	dw	1
	dw	378
	dw	217
	dw	2
	dw	378
	dw	217
	dw	3
	dw	378
	dw	217
	dw	4
	dw	378
	dw	217
	dw	5
	dw	378
	dw	217
	dw	6
	dw	378
	dw	217
	dw	7
	dw	378
	dw	217
	dw	8
	dw	378
	dw	217
	dw	9
	dw	378
	dw	217
	dw	10
	dw	378
	dw	217
	dw	11
	dw	378
	dw	217
	dw	12
	dw	378
	dw	217
	dw	13
	dw	378
	dw	217
	dw	14
	dw	378
	dw	217
	dw	15
	dw	378
	dw	217
	dw	16
	dw	378
	dw	217
	dw	17
	dw	378
	dw	217
	dw	18
	dw	378
	dw	217
	dw	19
	dw	378
	dw	217
	dw	20
	dw	378
	dw	217
	dw	21
	dw	378
	dw	217
	dw	22
	dw	378
	dw	217
	dw	23
	dw	0



end32data

start32save_data



bio_door	dw	l_script
	dw	st_background+st_logic+st_recreate+st_mouse
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	181
	dw	232
	dw	s93
	dw	181
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	13
	dw	63
	dw	bio_door_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bio_door_logic
	dw	0



end32save_data

start32data



bio_door_open	dw	s93
	dw	181
	dw	232
	dw	0
	dw	181
	dw	232
	dw	1
	dw	181
	dw	232
	dw	2
	dw	181
	dw	232
	dw	3
	dw	181
	dw	232
	dw	4
	dw	0



end32data

start32save_data



leaflet	dw	l_script
	dw	st_mouse+st_logic+st_sort+st_recreate
	dw	0
	dw	26
	dw	NULL
	dd	NULL
	dw	291
	dw	266
	dw	s86
	dw	12784
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	309-291
	dw	8
	dw	leaflet_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	leaflet_logic
	dw	0



end32save_data

start32data



get_leaflet	dw	s87
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	0


return_leaflet	dw	s87
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



end32save_data
