start32data



s27_chip_list	dw	150+disk_8
	dw	151+disk_8
	dw	152+disk_8
	dw	153+disk_8
	dw	154+disk_8
	dw	155+disk_8
	dw	159+disk_8
	dw	162+disk_8+$000
	dw	164+disk_8
	dw	165+disk_8
	dw	167+disk_8
	dw	168+disk_8
	dw	143+disk_8
	dw	144+disk_8
	dw	145+disk_8
	dw	146+disk_8
	dw	0


s27_fast_list	dw	12
	dw	51
	dw	52
	dw	53
	dw	54
	dw	135
	dw	147+disk_8
	dw	148+disk_8
	dw	149+disk_8
	dw	169+disk_8
	dw	204+disk_8
	dw	209+disk_8
	dw	211+disk_8
	dw	213+disk_8
	dw	163+disk_8+$000
	dw	0


grid27	dd 0 dup (0)

s27_pal	dw	0
	dw	1280
	dw	1286
	dw	1545
	dw	1797
	dw	1800
	dw	2061
	dw	2054
	dw	2570
	dw	2570
	dw	2823
	dw	2571
	dw	2577
	dw	3079
	dw	2829
	dw	3343
	dw	2824
	dw	3342
	dw	4108
	dw	3594
	dw	3598
	dw	4109
	dw	4879
	dw	3085
	dw	4111
	dw	4364
	dw	3345
	dw	4373
	dw	5640
	dw	3600
	dw	4881
	dw	6416
	dw	2065
	dw	4627
	dw	4111
	dw	4373
	dw	5138
	dw	6420
	dw	3349
	dw	5651
	dw	7187
	dw	4370
	dw	5398
	dw	5140
	dw	5654
	dw	5401
	dw	7442
	dw	3348
	dw	6421
	dw	5136
	dw	4635
	dw	5151
	dw	5906
	dw	5911
	dw	6171
	dw	5391
	dw	5951
	dw	7191
	dw	6164
	dw	6426
	dw	5410
	dw	6932
	dw	5913
	dw	6175
	dw	8213
	dw	4122
	dw	6940
	dw	6426
	dw	6941
	dw	7962
	dw	7699
	dw	5915
	dw	6434
	dw	8983
	dw	4380
	dw	7963
	dw	8217
	dw	7453
	dw	8732
	dw	7703
	dw	6944
	dw	7717
	dw	10259
	dw	6427
	dw	8477
	dw	8735
	dw	6687
	dw	8992
	dw	8217
	dw	7458
	dw	7465
	dw	8988
	dw	7712
	dw	8486
	dw	8469
	dw	8483
	dw	9760
	dw	9755
	dw	6946
	dw	7981
	dw	8989
	dw	6952
	dw	9256
	dw	10782
	dw	8226
	dw	9509
	dw	10786
	dw	6437
	dw	10017
	dw	9252
	dw	7722
	dw	10277
	dw	10020
	dw	8231
	dw	9006
	dw	11296
	dw	6696
	dw	10536
	dw	9510
	dw	8237
	dw	9520
	dw	12066
	dw	6442
	dw	10795
	dw	11556
	dw	7467
	dw	11816
	dw	12578
	dw	9256
	dw	11561
	dw	11046
	dw	10283
	dw	11568
	dw	11803
	dw	9770
	dw	11058
	dw	13087
	dw	10025
	dw	12076
	dw	13095
	dw	7215
	dw	11823
	dw	11305
	dw	10801
	dw	11316
	dw	11561
	dw	9266
	dw	10807
	dw	13352
	dw	9520
	dw	12591
	dw	13612
	dw	8497
	dw	12593
	dw	12585
	dw	9780
	dw	11831
	dw	13866
	dw	9267
	dw	13616
	dw	14124
	dw	11313
	dw	13107
	dw	12846
	dw	10550
	dw	13617
	dw	14385
	dw	9781
	dw	13621
	dw	14640
	dw	11827
	dw	14131
	dw	13875
	dw	11065
	dw	14393
	dw	15401
	dw	10550
	dw	14646
	dw	14127
	dw	12855
	dw	14649
	dw	14388
	dw	12603
	dw	14909
	dw	16170
	dw	11579
	dw	15418
	dw	15673
	dw	14141
	dw	15932
	dw	16187
	dw	15679
	dw	0
	dw	2048
	dw	2570
	dw	2827
	dw	3082
	dw	2829
	dw	3598
	dw	3342
	dw	3856
	dw	4111
	dw	4364
	dw	4115
	dw	4627
	dw	4111
	dw	4373
	dw	5138
	dw	4884
	dw	4886
	dw	5652
	dw	5910
	dw	5911
	dw	6680
	dw	6937
	dw	5913
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	6688
	dw	10768
	dw	6437
	dw	5138
	dw	5908
	dw	5911
	dw	3340
	dw	2827
	dw	2571
	dw	12076
	dw	10023
	dw	8231
	dw	4377
	dw	6408
	dw	6941
	dw	4881
	dw	7440
	dw	3348
	dw	2061
	dw	4358
	dw	1802
	dw	9760
	dw	16155
	dw	16191
	dw	16189
	dw	13113
	dw	11575
	dw	12072
	dw	7970
	dw	6440
	dw	8213
	dw	3345
	dw	2841
	dw	4358
	dw	517
	dw	522
	dw	1285
	dw	16133
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	14399
	dw	13364
	dw	12338
	dw	11820
	dw	10028
	dw	8226
	dw	7452
	dw	5142
	dw	3605
	dw	1804
	dw	1799
	dw	1799
	dw	14343
	dw	9518
	dw	10035
	dw	11802
	dw	4383
	dw	6441
	dw	9226
	dw	786
	dw	3360
	dw	11264
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	12548
	dw	13361
	dw	10281
	dw	8236
	dw	8734
	dw	10284
	dw	9264
	dw	10271
	dw	5917
	dw	5664
	dw	6159
	dw	2319
	dw	2064
	dw	2052
	dw	13631
	dw	14376
	dw	6694
	dw	6189
	dw	8975
	dw	1805
	dw	1048
	dw	3586
	dw	0
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	13631
	dw	14376
	dw	6694
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s27_logic	dw	id_foster
	dw	id_joey
	dw	id_burke
	dw	id_scanner_27
	dw	id_helmet_cole
	dw	id_medi_comp
	dw	id_body
	dw	id_glass_slot
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_lift_29
	dw	$ffff
	dw	id_menu_logic


s27_mouse	dw	id_joey
	dw	id_burke
	dw	id_right_exit_27
	dw	id_chart1
	dw	id_chart2
	dw	id_gas
	dw	id_scanner_27
	dw	id_medi_comp
	dw	id_chair_27
	dw	id_body
	dw	id_helmet_cole
	dw	id_s27_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s27_floor	dw	0
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	s27_floor_table
	dw	128
	dw	240
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	4242
	dw	floor_action



end32save_data

start32data



s27_floor_table	dw	id_s27_floor
	dw	return_ok
	dw	id_right_exit_27
	dw	GT_right_exit_27
	dw	id_joey_park
	dw	get_to_jp2
	dw	id_std_left_talk
	dw	GT_l_talk_27
	dw	id_std_right_talk
	dw	GT_r_talk_27
	dw	0
	dw	s27_right_on
	dw	id_chart1
	dw	GT_chart1
	dw	id_chart2
	dw	GT_chart2
	dw	id_gas
	dw	GT_gas
	dw	id_scanner_27
	dw	GT_scanner_27
	dw	id_medi_comp
	dw	GT_medi_comp
	dw	id_chair_27
	dw	GT_chair_27
	dw	id_helmet_cole
	dw	GT_helmet
	dw	id_body
	dw	GT_body
	dw	-1


rs_foster_26_27	dw	c_xcood
	dw	392
	dw	c_ycood
	dw	256
	dw	c_screen
	dw	27
	dw	c_place
	dw	id_s27_floor
	dw	-1



end32data

start32save_data



right_exit_27	dw	0
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	0
	dw	363
	dw	202
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	382-363
	dw	267-202
	dw	er27_action



end32save_data

start32data



rs_foster_27_26	dw	c_xcood
	dw	160
	dw	c_ycood
	dw	288
	dw	c_screen
	dw	26
	dw	c_place
	dw	id_s26_floor
	dw	-1



end32data

start32save_data



chart1	dw	l_script
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	263
	dw	193
	dw	0
	dw	12778
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	289-263
	dw	241-193
	dw	chart1_action


chart2	dw	l_script
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	395
	dw	201
	dw	0
	dw	12778
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	416-395
	dw	251-201
	dw	chart2_action


gas	dw	l_script
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	276
	dw	269
	dw	0
	dw	12797
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	294-276
	dw	326-269
	dw	gas_action


medi_comp	dw	l_script
	dw	st_mouse+st_sort+st_logic
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	194
	dw	264
	dw	s165
	dw	12668
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	235-194
	dw	301-261
	dw	medi_comp_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	medic_logic
	dw	0



end32save_data

start32data



glove_on_seq	dw	s154
	dw	328
	dw	261
	dw	0
	dw	328
	dw	261
	dw	1
	dw	328
	dw	261
	dw	2
	dw	328
	dw	261
	dw	3
	dw	328
	dw	261
	dw	4
	dw	328
	dw	261
	dw	5
	dw	328
	dw	261
	dw	6
	dw	0


glove_off_seq	dw	s154
	dw	328
	dw	261
	dw	6
	dw	328
	dw	261
	dw	5
	dw	328
	dw	261
	dw	4
	dw	328
	dw	261
	dw	3
	dw	328
	dw	261
	dw	2
	dw	328
	dw	261
	dw	1
	dw	328
	dw	261
	dw	0
	dw	0


operate_seq	dw	s155
	dw	326
	dw	260
	dw	0
	dw	326
	dw	260
	dw	0
	dw	326
	dw	260
	dw	1
	dw	326
	dw	260
	dw	1
	dw	326
	dw	260
	dw	1
	dw	326
	dw	260
	dw	1
	dw	326
	dw	260
	dw	1
	dw	326
	dw	260
	dw	2
	dw	326
	dw	260
	dw	3
	dw	326
	dw	260
	dw	3
	dw	326
	dw	260
	dw	4
	dw	326
	dw	260
	dw	4
	dw	326
	dw	260
	dw	5
	dw	326
	dw	260
	dw	6
	dw	326
	dw	260
	dw	6
	dw	326
	dw	260
	dw	6
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	8
	dw	326
	dw	260
	dw	8
	dw	326
	dw	260
	dw	8
	dw	326
	dw	260
	dw	8
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	7
	dw	326
	dw	260
	dw	6
	dw	326
	dw	260
	dw	6
	dw	326
	dw	260
	dw	4
	dw	326
	dw	260
	dw	4
	dw	326
	dw	260
	dw	5
	dw	326
	dw	260
	dw	5
	dw	326
	dw	260
	dw	9
	dw	326
	dw	260
	dw	9
	dw	326
	dw	260
	dw	10
	dw	326
	dw	260
	dw	10
	dw	326
	dw	260
	dw	11
	dw	326
	dw	260
	dw	12
	dw	326
	dw	260
	dw	11
	dw	326
	dw	260
	dw	11
	dw	326
	dw	260
	dw	0
	dw	0


gas_seq	dw	s153
	dw	288
	dw	256
	dw	0
	dw	288
	dw	256
	dw	1
	dw	288
	dw	256
	dw	2
	dw	288
	dw	256
	dw	3
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	3
	dw	288
	dw	256
	dw	5
	dw	288
	dw	256
	dw	6
	dw	288
	dw	256
	dw	7
	dw	288
	dw	256
	dw	8
	dw	288
	dw	256
	dw	9
	dw	288
	dw	256
	dw	10
	dw	288
	dw	256
	dw	10
	dw	288
	dw	256
	dw	10
	dw	288
	dw	256
	dw	10
	dw	288
	dw	256
	dw	11
	dw	288
	dw	256
	dw	12
	dw	288
	dw	256
	dw	12
	dw	288
	dw	256
	dw	12
	dw	288
	dw	256
	dw	12
	dw	288
	dw	256
	dw	7
	dw	288
	dw	256
	dw	6
	dw	288
	dw	256
	dw	5
	dw	288
	dw	256
	dw	3
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	4
	dw	288
	dw	256
	dw	3
	dw	288
	dw	256
	dw	2
	dw	288
	dw	256
	dw	1
	dw	288
	dw	256
	dw	0
	dw	0


shake_seq	dw	s152
	dw	325
	dw	256
	dw	0
	dw	325
	dw	256
	dw	1
	dw	325
	dw	256
	dw	2
	dw	325
	dw	256
	dw	3
	dw	325
	dw	256
	dw	4
	dw	325
	dw	256
	dw	5
	dw	325
	dw	256
	dw	2
	dw	325
	dw	256
	dw	3
	dw	325
	dw	256
	dw	4
	dw	325
	dw	256
	dw	2
	dw	325
	dw	256
	dw	4
	dw	325
	dw	256
	dw	2
	dw	325
	dw	256
	dw	4
	dw	325
	dw	256
	dw	6
	dw	325
	dw	256
	dw	7
	dw	325
	dw	256
	dw	8
	dw	325
	dw	256
	dw	9
	dw	325
	dw	256
	dw	10
	dw	0


scan_27_seq	dw	s159
	dw	308
	dw	212
	dw	0
	dw	308
	dw	212
	dw	1
	dw	0


heart_seq	dd 0 dup (0)

lung_seq	dw	s157
	dw	308
	dw	212
	dw	0
	dw	308
	dw	212
	dw	1
	dw	308
	dw	212
	dw	2
	dw	308
	dw	212
	dw	3
	dw	308
	dw	212
	dw	4
	dw	308
	dw	212
	dw	5
	dw	308
	dw	212
	dw	6
	dw	308
	dw	212
	dw	7
	dw	308
	dw	212
	dw	8
	dw	308
	dw	212
	dw	9
	dw	308
	dw	212
	dw	10
	dw	308
	dw	212
	dw	11
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	14
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	14
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	11
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	11
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	14
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	9
	dw	308
	dw	212
	dw	17
	dw	308
	dw	212
	dw	5
	dw	308
	dw	212
	dw	18
	dw	308
	dw	212
	dw	19
	dw	308
	dw	212
	dw	20
	dw	308
	dw	212
	dw	21
	dw	0


kidney_seq	dw	s158
	dw	308
	dw	212
	dw	0
	dw	308
	dw	212
	dw	1
	dw	308
	dw	212
	dw	2
	dw	308
	dw	212
	dw	3
	dw	308
	dw	212
	dw	4
	dw	308
	dw	212
	dw	3
	dw	308
	dw	212
	dw	5
	dw	308
	dw	212
	dw	6
	dw	308
	dw	212
	dw	7
	dw	308
	dw	212
	dw	8
	dw	308
	dw	212
	dw	9
	dw	308
	dw	212
	dw	10
	dw	308
	dw	212
	dw	11
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	14
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	16
	dw	308
	dw	212
	dw	15
	dw	308
	dw	212
	dw	14
	dw	308
	dw	212
	dw	13
	dw	308
	dw	212
	dw	12
	dw	308
	dw	212
	dw	11
	dw	308
	dw	212
	dw	10
	dw	308
	dw	212
	dw	9
	dw	308
	dw	212
	dw	8
	dw	308
	dw	212
	dw	7
	dw	308
	dw	212
	dw	6
	dw	308
	dw	212
	dw	5
	dw	308
	dw	212
	dw	3
	dw	308
	dw	212
	dw	4
	dw	308
	dw	212
	dw	3
	dw	308
	dw	212
	dw	4
	dw	308
	dw	212
	dw	2
	dw	308
	dw	212
	dw	1
	dw	308
	dw	212
	dw	0
	dw	0



end32data

start32save_data



scanner_27	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	308
	dw	212
	dw	s159
	dw	12799
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	329-308
	dw	245-212
	dw	scanner_27_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	scanner_27_logic
	dw	0


chair_27	dw	l_script
	dw	st_mouse
	dw	0
	dw	27
	dw	NULL
	dd	chair_table
	dw	230
	dw	236
	dw	0
	dw	12752
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	256-230
	dw	283-236
	dw	chair_27_action



end32save_data

start32data



chair_table	dw	id_chair_27
	dw	return_ok
	dw	id_s27_floor
	dw	GT_floor_from_chair
	dw	id_right_exit_27
	dw	GT_floor_from_chair
	dw	id_std_left_talk
	dw	GT_floor_from_chair
	dw	id_chart1
	dw	GT_floor_from_chair
	dw	id_chart2
	dw	GT_floor_from_chair
	dw	id_gas
	dw	GT_floor_from_chair
	dw	id_scanner_27
	dw	GT_floor_from_chair
	dw	id_medi_comp
	dw	GT_floor_from_chair
	dw	id_body
	dw	GT_floor_from_chair
	dw	id_helmet_cole
	dw	GT_floor_from_chair
	dw	-1


in_chair_seq	dw	s160
	dw	252
	dw	234
	dw	0
	dw	249
	dw	234
	dw	1
	dw	240
	dw	235
	dw	2
	dw	233
	dw	236
	dw	3
	dw	229
	dw	236
	dw	4
	dw	230
	dw	236
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	7
	dw	230
	dw	235
	dw	8
	dw	230
	dw	235
	dw	9
	dw	231
	dw	235
	dw	10
	dw	233
	dw	235
	dw	11
	dw	0


out_chair_seq	dw	s161
	dw	233
	dw	235
	dw	0
	dw	231
	dw	235
	dw	1
	dw	230
	dw	235
	dw	2
	dw	230
	dw	235
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	5
	dw	230
	dw	236
	dw	6
	dw	237
	dw	236
	dw	7
	dw	240
	dw	236
	dw	8
	dw	246
	dw	234
	dw	9
	dw	246
	dw	235
	dw	10
	dw	248
	dw	235
	dw	11
	dw	254
	dw	234
	dw	12
	dw	258
	dw	234
	dw	13
	dw	0



end32data

start32save_data



helmet_cole	dw	l_script
	dw	st_mouse+st_logic+st_recreate+st_foreground
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	232
	dw	207
	dw	s162
	dw	12798
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	253-232
	dw	226-207
	dw	helmet_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	helmet_logic
	dw	0



end32save_data

start32data



helmet_down	dw	s162
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	0


helmet_up	dw	s162
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


helmet_op_seq	dw	s163
	dw	232
	dw	207
	dw	0
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	4
	dw	232
	dw	207
	dw	4
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	6
	dw	232
	dw	207
	dw	6
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	7
	dw	232
	dw	207
	dw	7
	dw	232
	dw	207
	dw	7
	dw	232
	dw	207
	dw	7
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	4
	dw	232
	dw	207
	dw	4
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	5
	dw	232
	dw	207
	dw	6
	dw	232
	dw	207
	dw	6
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	3
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	2
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	1
	dw	232
	dw	207
	dw	7
	dw	232
	dw	207
	dw	7
	dw	0


squirm_seq	dw	s164
	dw	230
	dw	234
	dw	0
	dw	230
	dw	234
	dw	1
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	1
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	4
	dw	230
	dw	234
	dw	3
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	6
	dw	230
	dw	234
	dw	5
	dw	230
	dw	234
	dw	2
	dw	230
	dw	234
	dw	0
	dw	230
	dw	234
	dw	0
	dw	230
	dw	234
	dw	7
	dw	0


medi_comp_seq	dw	s165
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	2
	dw	194
	dw	264
	dw	3
	dw	194
	dw	264
	dw	4
	dw	194
	dw	264
	dw	5
	dw	194
	dw	264
	dw	6
	dw	194
	dw	264
	dw	7
	dw	194
	dw	264
	dw	8
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	10
	dw	194
	dw	264
	dw	11
	dw	194
	dw	264
	dw	12
	dw	194
	dw	264
	dw	13
	dw	194
	dw	264
	dw	14
	dw	194
	dw	264
	dw	15
	dw	194
	dw	264
	dw	16
	dw	194
	dw	264
	dw	17
	dw	194
	dw	264
	dw	18
	dw	194
	dw	264
	dw	17
	dw	194
	dw	264
	dw	19
	dw	194
	dw	264
	dw	20
	dw	194
	dw	264
	dw	21
	dw	194
	dw	264
	dw	22
	dw	194
	dw	264
	dw	23
	dw	194
	dw	264
	dw	24
	dw	194
	dw	264
	dw	25
	dw	194
	dw	264
	dw	26
	dw	194
	dw	264
	dw	27
	dw	194
	dw	264
	dw	28
	dw	194
	dw	264
	dw	29
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	32
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	32
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	32
	dw	194
	dw	264
	dw	30
	dw	0


rs_big_burke	dw	c_mouse_rel_x
	dw	-16
	dw	c_mouse_rel_y
	dw	-48
	dw	-1


rs_small_burke	dw	c_mouse_rel_x
	dw	0
	dw	c_mouse_rel_y
	dw	0
	dw	-1



end32data

start32save_data



body	dw	l_script
	dw	st_recreate+st_logic+st_mouse
	dw	0
	dw	27
	dw	0
	dd	body_table
	dw	353
	dw	283
	dw	s169
	dw	4
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	10
	dw	10
	dw	body_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	body_sss
	dw	0
	dd	0
	dd	0
	dd	0
	dw	null
	dw	null
	dw	null
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_body
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	null
	dw	0



end32save_data

start32data



body_table	dw	id_chair_27
	dw	GT_chair_27
	dw	id_gas
	dw	GT_gas
	dw	id_std_right_talk
	dw	GT_r_talk_27
	dw	-1



end32data

start32save_data



glass_slot	dw	l_script
	dw	st_logic+st_recreate
	dw	0
	dw	27
	dw	NULL
	dd	NULL
	dw	224
	dw	285
	dw	s204
	dw	0
	dw	0
	dw	0
	dw	0
	dw	null
	dw	null
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	glass_slot_logic
	dw	0



end32save_data

start32data



glass_slot_open	dw	s204
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


glass_slot_close	dw	s204
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


put_glass_seq	dw	s203
	dw	241
	dw	250
	dw	0
	dw	236
	dw	254
	dw	1
	dw	235
	dw	262
	dw	2
	dw	233
	dw	262
	dw	3
	dw	233
	dw	262
	dw	3
	dw	231
	dw	262
	dw	4
	dw	229
	dw	262
	dw	5
	dw	227
	dw	262
	dw	6
	dw	227
	dw	262
	dw	6
	dw	227
	dw	262
	dw	6
	dw	231
	dw	262
	dw	4
	dw	233
	dw	262
	dw	3
	dw	234
	dw	262
	dw	7
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	8
	dw	234
	dw	262
	dw	7
	dw	230
	dw	262
	dw	9
	dw	225
	dw	262
	dw	10
	dw	224
	dw	262
	dw	11
	dw	226
	dw	262
	dw	12
	dw	227
	dw	262
	dw	13
	dw	232
	dw	262
	dw	14
	dw	234
	dw	262
	dw	7
	dw	235
	dw	262
	dw	2
	dw	236
	dw	254
	dw	1
	dw	241
	dw	250
	dw	15
	dw	0


hand_in_seq	dw	s209
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	4
	dw	0


glass_scan	dw	s212
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	2
	dw	194
	dw	264
	dw	3
	dw	194
	dw	264
	dw	4
	dw	194
	dw	264
	dw	5
	dw	194
	dw	264
	dw	6
	dw	194
	dw	264
	dw	7
	dw	194
	dw	264
	dw	8
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	10
	dw	194
	dw	264
	dw	11
	dw	194
	dw	264
	dw	12
	dw	194
	dw	264
	dw	13
	dw	194
	dw	264
	dw	14
	dw	194
	dw	264
	dw	15
	dw	194
	dw	264
	dw	16
	dw	194
	dw	264
	dw	17
	dw	194
	dw	264
	dw	18
	dw	194
	dw	264
	dw	19
	dw	194
	dw	264
	dw	20
	dw	194
	dw	264
	dw	21
	dw	194
	dw	264
	dw	22
	dw	194
	dw	264
	dw	23
	dw	194
	dw	264
	dw	24
	dw	194
	dw	264
	dw	25
	dw	194
	dw	264
	dw	26
	dw	194
	dw	264
	dw	27
	dw	194
	dw	264
	dw	28
	dw	194
	dw	264
	dw	29
	dw	194
	dw	264
	dw	30
	dw	194
	dw	264
	dw	31
	dw	194
	dw	264
	dw	32
	dw	194
	dw	264
	dw	7
	dw	194
	dw	264
	dw	8
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	10
	dw	194
	dw	264
	dw	11
	dw	194
	dw	264
	dw	33
	dw	194
	dw	264
	dw	34
	dw	194
	dw	264
	dw	35
	dw	194
	dw	264
	dw	36
	dw	194
	dw	264
	dw	37
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	9
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	38
	dw	194
	dw	264
	dw	39
	dw	194
	dw	264
	dw	40
	dw	194
	dw	264
	dw	41
	dw	194
	dw	264
	dw	42
	dw	0


hand_op_seq	dw	s210
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	5
	dw	216
	dw	240
	dw	6
	dw	216
	dw	240
	dw	5
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	216
	dw	240
	dw	5
	dw	216
	dw	240
	dw	6
	dw	216
	dw	240
	dw	5
	dw	216
	dw	240
	dw	6
	dw	216
	dw	240
	dw	5
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	7
	dw	216
	dw	240
	dw	8
	dw	216
	dw	240
	dw	8
	dw	216
	dw	240
	dw	9
	dw	216
	dw	240
	dw	10
	dw	216
	dw	240
	dw	11
	dw	216
	dw	240
	dw	12
	dw	216
	dw	240
	dw	13
	dw	216
	dw	240
	dw	14
	dw	216
	dw	240
	dw	15
	dw	0


fprint_seq	dw	s211
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	194
	dw	264
	dw	0
	dw	194
	dw	264
	dw	1
	dw	0


hands_out_seq	dw	s213
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	0
	dw	216
	dw	240
	dw	1
	dw	216
	dw	240
	dw	2
	dw	216
	dw	240
	dw	3
	dw	216
	dw	240
	dw	4
	dw	0



end32data

start32save_data



burke	dw	l_script
	dw	st_sort+st_recreate+st_logic+st_mouse+st_grid_plot
	dw	0
	dw	27
	dw	id_s27_floor
	dd	0
	dw	344
	dw	304
	dw	s150
	dw	12694
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-16
	dw	-48
	dw	32
	dw	48
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	burke_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_burke
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	burke_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	burke_up
	dd	burke_down
	dd	burke_left
	dd	burke_right
	dd	burke_st_up
	dd	burke_st_down
	dd	burke_st_left
	dd	burke_st_right
	dd	burke_st_talk
	dd	0
	dd	burke_u_to_d
	dd	burke_u_to_l
	dd	burke_u_to_r
	dd	0
	dd	burke_d_to_u
	dd	0
	dd	burke_d_to_l
	dd	burke_d_to_r
	dd	0
	dd	burke_l_to_u
	dd	burke_l_to_d
	dd	0
	dd	burke_l_to_r
	dd	0
	dd	burke_r_to_u
	dd	burke_r_to_d
	dd	burke_r_to_l
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0


burke_auto	db	64 dup (0)



end32save_data

start32data



burke_left	dw	4
	dw	16+s150
	dw	-4
	dw	0
	dw	4
	dw	17+s150
	dw	-4
	dw	0
	dw	4
	dw	18+s150
	dw	-4
	dw	0
	dw	4
	dw	19+s150
	dw	-4
	dw	0
	dw	4
	dw	20+s150
	dw	-4
	dw	0
	dw	4
	dw	21+s150
	dw	-4
	dw	0
	dw	4
	dw	22+s150
	dw	-4
	dw	0
	dw	4
	dw	23+s150
	dw	-4
	dw	0
	dw	0


burke_right	dw	4
	dw	24+s150
	dw	4
	dw	0
	dw	4
	dw	25+s150
	dw	4
	dw	0
	dw	4
	dw	26+s150
	dw	4
	dw	0
	dw	4
	dw	27+s150
	dw	4
	dw	0
	dw	4
	dw	28+s150
	dw	4
	dw	0
	dw	4
	dw	29+s150
	dw	4
	dw	0
	dw	4
	dw	30+s150
	dw	4
	dw	0
	dw	4
	dw	31+s150
	dw	4
	dw	0
	dw	0


burke_up	dw	2
	dw	0+s150
	dw	0
	dw	-2
	dw	2
	dw	1+s150
	dw	0
	dw	-2
	dw	2
	dw	2+s150
	dw	0
	dw	-2
	dw	2
	dw	3+s150
	dw	0
	dw	-2
	dw	2
	dw	4+s150
	dw	0
	dw	-2
	dw	2
	dw	5+s150
	dw	0
	dw	-2
	dw	2
	dw	6+s150
	dw	0
	dw	-2
	dw	2
	dw	7+s150
	dw	0
	dw	-2
	dw	0


burke_down	dw	2
	dw	8+s150
	dw	0
	dw	2
	dw	2
	dw	9+s150
	dw	0
	dw	2
	dw	2
	dw	10+s150
	dw	0
	dw	2
	dw	2
	dw	11+s150
	dw	0
	dw	2
	dw	2
	dw	12+s150
	dw	0
	dw	2
	dw	2
	dw	13+s150
	dw	0
	dw	2
	dw	2
	dw	14+s150
	dw	0
	dw	2
	dw	2
	dw	15+s150
	dw	0
	dw	2
	dw	0


burke_st_up	dw	s150
	dw	1
	dw	1
	dw	36
	dw	0


burke_st_down	dw	s150
	dw	1
	dw	1
	dw	32
	dw	0


burke_st_left	dw	s150
	dw	1
	dw	1
	dw	34
	dw	0


burke_st_right	dw	s150
	dw	1
	dw	1
	dw	38
	dw	0


burke_st_talk	dw	s151
	dw	1
	dw	1
	dw	0
	dw	0


burke_r_to_u	dw	45-8+s150
	dw	0


burke_r_to_d	dw	47-8+s150
	dw	0


burke_r_to_l	dw	45-8+s150
	dw	44-8+s150
	dw	43-8+s150
	dw	0


burke_u_to_d	dw	43-8+s150
	dw	42-8+s150
	dw	41-8+s150
	dw	0


burke_u_to_l	dw	43-8+s150
	dw	0


burke_u_to_r	dw	45-8+s150
	dw	0


burke_d_to_u	dw	47-8+s150
	dw	46-8+s150
	dw	45-8+s150
	dw	0


burke_d_to_l	dw	41-8+s150
	dw	0


burke_d_to_r	dw	47-8+s150
	dw	0


burke_l_to_u	dw	43-8+s150
	dw	0


burke_l_to_d	dw	41-8+s150
	dw	0


burke_l_to_r	dw	41-8+s150
	dw	40-8+s150
	dw	47-8+s150
	dw	0



end32data

start32save_data



end32save_data
