start32data



s28_chip_list	dw	136+disk_9
	dw	137+disk_9
	dw	86+disk_8
	dw	131+disk_2
	dw	132+disk_2
	dw	63+disk_9
	dw	64+disk_9
	dw	65+disk_9
	dw	66+disk_9
	dw	67+disk_9
	dw	13
	dw	69+disk_9
	dw	18+disk_8
	dw	0


grid28	dd 0 dup (0)

s28_pal	dw	0
	dw	512
	dw	514
	dw	1028
	dw	1540
	dw	773
	dw	1797
	dw	1794
	dw	1541
	dw	2568
	dw	2817
	dw	1542
	dw	2056
	dw	3592
	dw	1030
	dw	2059
	dw	2570
	dw	780
	dw	2065
	dw	3587
	dw	2570
	dw	2572
	dw	3085
	dw	1294
	dw	2323
	dw	4102
	dw	1803
	dw	2578
	dw	3594
	dw	3852
	dw	3088
	dw	3596
	dw	785
	dw	2837
	dw	3592
	dw	2064
	dw	2586
	dw	4099
	dw	4366
	dw	4112
	dw	4619
	dw	3598
	dw	3353
	dw	6150
	dw	2573
	dw	4116
	dw	5643
	dw	3598
	dw	4626
	dw	8461
	dw	1036
	dw	5394
	dw	6918
	dw	2063
	dw	3615
	dw	6407
	dw	3600
	dw	4375
	dw	5138
	dw	3860
	dw	4124
	dw	5388
	dw	1815
	dw	5144
	dw	5135
	dw	6164
	dw	4890
	dw	7698
	dw	3091
	dw	4135
	dw	8709
	dw	2578
	dw	5659
	dw	6671
	dw	3096
	dw	5405
	dw	6162
	dw	4888
	dw	4899
	dw	10767
	dw	1554
	dw	5412
	dw	8458
	dw	4629
	dw	6174
	dw	6672
	dw	6168
	dw	5918
	dw	10261
	dw	2581
	dw	5164
	dw	9224
	dw	3096
	dw	5922
	dw	7957
	dw	4890
	dw	5674
	dw	9997
	dw	3608
	dw	7197
	dw	8729
	dw	3357
	dw	6692
	dw	8468
	dw	5659
	dw	7198
	dw	11037
	dw	3865
	dw	7206
	dw	12050
	dw	3097
	dw	6952
	dw	8981
	dw	5918
	dw	6958
	dw	9231
	dw	5152
	dw	7717
	dw	8474
	dw	7967
	dw	7467
	dw	11797
	dw	4637
	dw	8229
	dw	10525
	dw	6943
	dw	7728
	dw	11023
	dw	6175
	dw	8745
	dw	11286
	dw	5153
	dw	8240
	dw	10770
	dw	7458
	dw	9253
	dw	12833
	dw	5408
	dw	8751
	dw	10776
	dw	6693
	dw	9011
	dw	11283
	dw	7972
	dw	9521
	dw	12566
	dw	6692
	dw	9771
	dw	13347
	dw	6180
	dw	9775
	dw	13343
	dw	5159
	dw	10543
	dw	12827
	dw	7462
	dw	10038
	dw	12567
	dw	8488
	dw	10287
	dw	11300
	dw	9770
	dw	10293
	dw	14107
	dw	6442
	dw	10805
	dw	12831
	dw	8236
	dw	11310
	dw	13608
	dw	6956
	dw	11058
	dw	13607
	dw	9516
	dw	11574
	dw	14369
	dw	7469
	dw	12082
	dw	14631
	dw	8239
	dw	12084
	dw	14122
	dw	8753
	dw	12854
	dw	14376
	dw	9523
	dw	13112
	dw	14379
	dw	10294
	dw	13623
	dw	14640
	dw	11574
	dw	0
	dw	5120
	dw	2832
	dw	4124
	dw	8972
	dw	3859
	dw	6170
	dw	11288
	dw	2068
	dw	6687
	dw	7699
	dw	7452
	dw	7715
	dw	10519
	dw	5666
	dw	10543
	dw	13595
	dw	7978
	dw	11317
	dw	14117
	dw	8753
	dw	12854
	dw	14376
	dw	11059
	dw	0
	dw	8448
	dw	4629
	dw	6687
	dw	10259
	dw	5403
	dw	8746
	dw	12061
	dw	6178
	dw	10543
	dw	12827
	dw	7462
	dw	10805
	dw	13599
	dw	9516
	dw	11574
	dw	14369
	dw	7469
	dw	12599
	dw	13858
	dw	10290
	dw	13112
	dw	14373
	dw	10294
	dw	0
	dw	512
	dw	514
	dw	1028
	dw	1540
	dw	773
	dw	1797
	dw	1794
	dw	1541
	dw	2568
	dw	7681
	dw	3091
	dw	5412
	dw	12298
	dw	3870
	dw	9011
	dw	13331
	dw	5159
	dw	10293
	dw	13595
	dw	6956
	dw	12599
	dw	14626
	dw	11574
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s28_logic	dw	id_foster
	dw	id_joey
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_reich_door_20
	dw	id_inner_r_door
	dw	id_gallager_bel
	dw	id_lift_29
	dw	id_lift_28
	dw	id_cat
	dw	id_catfood
	dw	$ffff
	dw	id_menu_logic


s28_mouse	dw	id_joey
	dw	id_lamb
	dw	id_right_exit_28
	dw	id_left_exit_28
	dw	id_dustbin_28
	dw	id_up_exit_28
	dw	id_lift_28
	dw	id_slot_28
	dw	id_s28_floor
	dw	$ffff
	dw	id_text_mouse


s28_sml_mouse	dw	id_joey
	dw	id_small_l_28
	dw	id_small_r_28
	dw	id_s28_sml_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s28_floor	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	s28_floor_table
	dw	128
	dw	248
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	312-248
	dw	floor_action



end32save_data

start32data



s28_floor_table	dw	id_s28_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	0
	dw	s28_right_on
	dw	1
	dw	s28_left_on
	dw	3
	dw	s28_up_on
	dw	id_right_exit_28
	dw	GT_right_exit_28
	dw	id_left_exit_28
	dw	GT_left_exit_28
	dw	id_up_exit_28
	dw	GT_up_exit_28
	dw	id_dustbin_28
	dw	GT_dustbin_28
	dw	id_std_left_talk
	dw	GT_l_talk_28
	dw	id_std_right_talk
	dw	GT_r_talk_28
	dw	id_lift_28
	dw	GT_lift_28
	dw	id_slot_28
	dw	GT_slot_28
	dw	-1


rs_foster_29_28	dw	c_xcood
	dw	456
	dw	c_ycood
	dw	288
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_floor
	dw	-1


rs_foster_28_29	dw	c_xcood
	dw	120
	dw	c_ycood
	dw	272
	dw	c_screen
	dw	29
	dw	c_place
	dw	id_s29_floor
	dw	-1



end32data

start32save_data



right_exit_28	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	0
	dw	429
	dw	189
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	30
	dw	306-189
	dw	er28_action


left_exit_28	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	0
	dw	127
	dw	180
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	144-127
	dw	308-180
	dw	el28_action


dustbin_28	dw	l_script
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	NULL
	dw	326
	dw	236
	dw	0
	dw	12757
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	339-326
	dw	253-236
	dw	dustbin_action


up_exit_28	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	0
	dw	369
	dw	196
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	394-369
	dw	254-196
	dw	eu28_action



end32save_data

start32data



rs_lamb_28	dw	c_xcood
	dw	376
	dw	c_ycood
	dw	280
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_floor
	dw	c_logic
	dw	l_script
	dw	c_mode
	dw	0
	dw	c_base_sub
	dw	lamb_bell_logic
	dw	c_base_sub+2
	dw	0
	dw	-1



end32data

start32save_data



s28_sml_floor	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	s28_sml_table
	dw	192
	dw	168
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	304-192
	dw	16
	dw	floor_action



end32save_data

start32data



s28_sml_table	dw	id_s28_sml_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	id_small_r_28
	dw	GT_sml_r_28
	dw	id_small_l_28
	dw	GT_sml_l_28
	dw	4
	dw	sml_right_28
	dw	5
	dw	sml_left_28
	dw	-1



end32data

start32save_data



small_r_28	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	0
	dw	308
	dw	137
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	339-308
	dw	186-137
	dw	r_28_sml_action


small_l_28	dw	0
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	0
	dw	173
	dw	137
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	200-173
	dw	186-137
	dw	l_28_sml_action


lift_28	dw	l_script
	dw	st_sort+st_logic+st_recreate+st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	NULL
	dw	237
	dw	196
	dw	s69
	dw	45+t7
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	268-$f2
	dw	236-$b5
	dw	lift_28_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	lift_28_logic
	dw	0



end32save_data

start32data



lift_28_open	dw	s69
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	0


lift_28_close	dw	s69
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


slot_28_anim	dw	s18
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



slot_28	dw	null
	dw	st_mouse
	dw	0
	dw	28
	dw	NULL
	dd	NULL
	dw	267
	dw	217
	dw	NULL
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	5
	dw	8
	dw	s28_slot_action



end32save_data

start32data



rs_31_28	dw	c_xcood
	dw	248
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	28
	dw	c_frame
	dw	s12+40
	dw	c_dir
	dw	down
	dw	c_place
	dw	id_s28_floor
	dw	-1



end32data

start32save_data



end32save_data
