start32data



data_3	dd	s29_chip_list
	dd	useless_char
	dd	grid29
	dd	s29_pal
	dd	s29_floor
	dd	s29_mouse
	dd	s29_logic
	dd	rs_foster_7_29
	dd	lift_29
	dd	s29_lift_open
	dd	s29_lift_close
	dd	s29_card_slot
	dd	card_slot_29_anim
	dd	lift29_light
	dd	rs_joey_7_29
	dd	joey_list_s29
	dd	right_exit_29
	dd	s23_chip_list
	dd	s23_fast_list
	dd	grid23
	dd	s23_pal
	dd	s23_floor
	dd	s23_mouse
	dd	s23_logic
	dd	rs_foster_29_23
	dd	left_exit_23
	dd	rs_foster_23_29
	dd	anchor_exit_23
	dd	s25_chip_list
	dd	s25_fast_list
	dd	grid25
	dd	s25_pal
	dd	s25_floor
	dd	s25_mouse
	dd	s25_logic
	dd	rs_foster_23_25
	dd	anchor_exit_25
	dd	rs_foster_25_23
	dd	joey_list_s25
	dd	travel_exit_23
	dd	s24_fast_list
	dd	s24_chip_list
	dd	grid24
	dd	s24_pal
	dd	s24_floor
	dd	s24_mouse
	dd	s24_logic
	dd	rs_foster_23_24
	dd	left_exit_24
	dd	rs_foster_24_23
	dd	left_exit_29
	dd	0
	dd	s28_chip_list
	dd	grid28
	dd	s28_pal
	dd	s28_floor
	dd	s28_mouse
	dd	s28_logic
	dd	rs_foster_29_28
	dd	right_exit_28
	dd	rs_foster_28_29
	dd	left_exit_28
	dd	s19_fast_list
	dd	s19_chip_list
	dd	grid19
	dd	s19_pal
	dd	s19_floor
	dd	s19_mouse
	dd	s19_logic
	dd	rs_foster_28_19
	dd	right_exit_19
	dd	rs_foster_19_28
	dd	joey_list_s19
	dd	left_exit_19
	dd	s26_fast_list
	dd	s26_chip_list
	dd	grid26
	dd	s26_pal
	dd	s26_floor
	dd	s26_mouse
	dd	s26_logic
	dd	rs_foster_19_26
	dd	right_exit_26
	dd	rs_foster_26_19
	dd	dustbin_28
	dd	rs_joey_start_26
	dd	joey_list_s26
	dd	poster1
	dd	poster2
	dd	poster3
	dd	poster4
	dd	plant_26
	dd	leaflet
	dd	holo
	dd	bin_23
	dd	sculpture
	dd	link_23
	dd	wreck_23
	dd	london_poster
	dd	new_york_poster
	dd	mural
	dd	0
	dd	left_exit_26
	dd	s27_fast_list
	dd	s27_chip_list
	dd	grid27
	dd	s27_pal
	dd	s27_floor
	dd	s27_mouse
	dd	s27_logic
	dd	rs_foster_26_27
	dd	right_exit_27
	dd	rs_foster_27_26
	dd	chart1
	dd	chart2
	dd	gas
	dd	scanner_27
	dd	pidgeons
	dd	0
	dd	burke
	dd	glove_on_seq
	dd	glove_off_seq
	dd	operate_seq
	dd	gas_seq
	dd	shake_seq
	dd	scan_27_seq
	dd	heart_seq
	dd	lung_seq
	dd	kidney_seq
	dd	chair_27
	dd	in_chair_seq
	dd	out_chair_seq
	dd	helmet_cole
	dd	helmet_down
	dd	helmet_up
	dd	helmet_op_seq
	dd	squirm_seq
	dd	medi_comp
	dd	medi_comp_seq
	dd	rs_big_burke
	dd	rs_small_burke
	dd	body
	dd	anchor
	dd	anchor_seq
	dd	anchor_leave_seq
	dd	anchor_return_seq
	dd	hook
	dd	statue_25
	dd	hook_seq
	dd	lazer_25
	dd	lazer_25_seq
	dd	spark_25
	dd	spark_25_seq
	dd	get_anchor_seq
	dd	trevor
	dd	trevor_relax
	dd	trevor_unrelax
	dd	joey_list_s24
	dd	trevor_scratch
	dd	up_exit_28
	dd	s20_fast_list
	dd	s20_chip_list
	dd	grid20
	dd	s20_pal
	dd	s20_floor
	dd	s20_mouse
	dd	s20_logic
	dd	rs_all_28_20
	dd	down_exit_20
	dd	rs_foster_20_28
	dd	joey_list_20
	dd	reich_door_20
	dd	reich_20_open
	dd	reich_20_close
	dd	reich_slot
	dd	s22_fast_list
	dd	s22_chip_list
	dd	grid22
	dd	s22_pal
	dd	s22_floor
	dd	s22_mouse
	dd	s22_logic
	dd	rs_foster_20_22
	dd	right_exit_22
	dd	rs_foster_22_20
	dd	usecard_seq
	dd	lamb_door_20
	dd	lamb_20_open
	dd	lamb_20_close
	dd	lamb_slot
	dd	s21_fast_list
	dd	s21_chip_list
	dd	grid21
	dd	s21_pal
	dd	s21_floor
	dd	s21_mouse
	dd	s21_logic
	dd	rs_foster_20_21
	dd	left_exit_21
	dd	rs_foster_21_20
	dd	shrub_1
	dd	shrub_2
	dd	shrub_3
	dd	rs_joey_start_20
	dd	lamb_bed
	dd	lamb_tv
	dd	fish_tank
	dd	fish_poster
	dd	pillow
	dd	remove_pillow
	dd	replace_pillow
	dd	fost_remove_pill
	dd	fost_replace_pill
	dd	magazine
	dd	rs_magazine
	dd	fish_seq
	dd	get_magazine_seq
	dd	reich_chair
	dd	cabinet
	dd	cert
	dd	reich_picture
	dd	fish_food
	dd	lambs_books
	dd	lambs_chair
	dd	dispensor
	dd	push_dispensor
	dd	cat_food
	dd	cat_food_seq
	dd	video
	dd	cassette
	dd	put_video_in
	dd	take_video_out
	dd	video_in
	dd	video_out
	dd	take_cassette_seq
	dd	more_cassette_seq
	dd	big_pict1
	dd	video_screen
	dd	big_pict2
	dd	big_pict3
	dd	cat1_seq
	dd	cat2_seq
	dd	cat3_seq
	dd	cat4_seq
	dd	bend_down
	dd	watch_film
	dd	cat
	dd	cat_walk_seq
	dd	cat_eat_seq
	dd	helga_awake
	dd	helga_byeee
	dd	wobble1
	dd	wobble2
	dd	bio_door
	dd	bio_door_open
	dd	tank2_seq
	dd	tank3_seq
	dd	sales_chart
	dd	gallager_bel
	dd	gal_look_up
	dd	gal_look_down
	dd	trev_get_mag
	dd	trev_read_mag
	dd	trev_turn_page
	dd	mag_out
	dd	mag_away
	dd	fake_floor_22
	dd	reich_window
	dd	lamb_window
	dd	fake_floor_21
	dd	inner_lamb_door
	dd	inner_lamb_open
	dd	inner_lamb_close
	dd	get_leaflet
	dd	return_leaflet
	dd	mag_back_seq
	dd	give_mag_seq
	dd	ticket
	dd	ticket_seq
	dd	get_ticket
	dd	globe
	dd	globe_spin
	dd	push_globe
	dd	inner_reich_door
	dd	inner_reich_open
	dd	inner_reich_close
	dd	glass_slot
	dd	glass_slot_open
	dd	glass_slot_close
	dd	put_glass_seq
	dd	hand_in_seq
	dd	glass_scan
	dd	hand_op_seq
	dd	fprint_seq
	dd	hands_out_seq
	dd	rs_lamb_28
	dd	lamb_card_seq2
	dd	lamb_card_29
	dd	lamb_sit_seq
	dd	lamb_sit_up
	dd	cable_29
	dd	get_cable_29_seq
	dd	0
	dd	s11_chip_list
	dd	grid11
	dd	s11_pal
	dd	s11_floor
	dd	s11_mouse
	dd	s11_logic
	dd	rs_foster_1_11
	dd	fallin_seq
	dd	fallin2_seq
	dd	fallin3_seq
	dd	cable_fall
	dd	cable_fall1_seq
	dd	cable_fall2_seq
	dd	cable_fall2
	dd	smashed_window
	dd	smashed_window_seq
	dd	bits
	dd	bits_seq
	dd	bits2
	dd	bits2_seq
	dd	get_cable_11
	dd	spy_11
	dd	locker_11
	dd	locker_11_open
	dd	locker_11_close
	dd	slot_11
	dd	usecard_11_seq
	dd	open_11_locker
	dd	close_11_locker
	dd	soccer_1
	dd	soccer_2
	dd	soccer_3
	dd	soccer_4
	dd	soccer_5
	dd	cant_open_locker
	dd	slat_1
	dd	slat_2
	dd	slat_3
	dd	slat_4
	dd	slat_5
	dd	right_exit_11
	dd	0
	dd	s10_chip_list
	dd	grid10
	dd	s10_pal
	dd	s10_floor
	dd	s10_mouse
	dd	s10_logic
	dd	rs_foster_11_10
	dd	rs_foster_10_11
	dd	left_exit_10
	dd	lift_10
	dd	lift_10_open
	dd	lift_slot_10
	dd	card2_seq
	dd	scanline_seq
	dd	scanner_10
	dd	pod
	dd	pod_down
	dd	pod_up
	dd	linc_10
	dd	pod_light
	dd	pod_light_seq
	dd	linc_card_seq
	dd	sit_10_seq
	dd	stand_10_seq
	dd	monitor_10
	dd	monitor_10_seq
	dd	liyt_1
	dd	liyt_1_seq
	dd	liyt_2
	dd	liyt_2_seq
	dd	liyt_3
	dd	liyt_3_seq
	dd	liyt_4
	dd	liyt_4_seq
	dd	litebank
	dd	litebank_seq
	dd	fsit_talk_seq
	dd	terminal_10
	dd	lift_10_close
	dd	fake_floor_10
	dd	rs_lamb_start_bel
	dd	0
	dd	rs_foster_from_linc
	dd	small_exit_23
	dd	small_r_29
	dd	small_l_29
	dd	small_r_28
	dd	small_l_28
	dd	top_right_19
	dd	s29_sml_floor
	dd	rs_23_sml_29
	dd	s29_sml_mouse
	dd	rs_29_sml_23
	dd	s28_sml_floor
	dd	rs_29_sml_28
	dd	s28_sml_mouse
	dd	rs_28_sml_29
	dd	rs_28_sml_19
	dd	rs_19_sml_28
	dd	sml_joey_list_29
	dd	sml_joey_list_28
	dd	lift_28
	dd	lift_28_open
	dd	lift_28_close
	dd	slot_28
	dd	slot_28_anim
	dd	rs_31_28


s29_chip_list	dw	136+disk_8
	dw	137+disk_8
	dw	131+disk_2
	dw	132+disk_2
	dw	86+disk_8
	dw	17+disk_8
	dw	18+disk_8
	dw	20+disk_8
	dw	76+disk_8
	dw	14+disk_8
	dw	15+disk_8
	dw	16+disk_8
	dw	13
	dw	0


grid29	dd 0 dup (0)

s29_pal	dw	0
	dw	512
	dw	514
	dw	1028
	dw	1540
	dw	773
	dw	1797
	dw	1794
	dw	1541
	dw	2568
	dw	2817
	dw	1542
	dw	2056
	dw	3592
	dw	1030
	dw	2059
	dw	2570
	dw	780
	dw	2065
	dw	3587
	dw	2570
	dw	2572
	dw	3085
	dw	1294
	dw	2323
	dw	4102
	dw	1803
	dw	2578
	dw	3594
	dw	3852
	dw	3088
	dw	3596
	dw	785
	dw	2837
	dw	3592
	dw	2064
	dw	2586
	dw	4099
	dw	4366
	dw	4112
	dw	4619
	dw	3598
	dw	3353
	dw	6150
	dw	2573
	dw	4116
	dw	5643
	dw	3598
	dw	4626
	dw	8461
	dw	1036
	dw	5394
	dw	6918
	dw	2063
	dw	3615
	dw	6407
	dw	3600
	dw	4375
	dw	5138
	dw	3860
	dw	4124
	dw	5388
	dw	1815
	dw	5144
	dw	5135
	dw	6164
	dw	4890
	dw	7698
	dw	3091
	dw	4135
	dw	8709
	dw	2578
	dw	5659
	dw	6671
	dw	3096
	dw	5405
	dw	6162
	dw	4888
	dw	4899
	dw	10767
	dw	1554
	dw	5412
	dw	8458
	dw	4629
	dw	6174
	dw	6672
	dw	6168
	dw	5918
	dw	10261
	dw	2581
	dw	5164
	dw	9224
	dw	3096
	dw	5922
	dw	7957
	dw	4890
	dw	5674
	dw	9997
	dw	3608
	dw	7197
	dw	8729
	dw	3357
	dw	6692
	dw	8468
	dw	5659
	dw	7198
	dw	11037
	dw	3865
	dw	7206
	dw	12050
	dw	3097
	dw	6952
	dw	8981
	dw	5918
	dw	6958
	dw	9231
	dw	5152
	dw	7717
	dw	8474
	dw	7967
	dw	7467
	dw	11797
	dw	4637
	dw	8229
	dw	10525
	dw	6943
	dw	7728
	dw	11023
	dw	6175
	dw	8745
	dw	11286
	dw	5153
	dw	8240
	dw	10770
	dw	7458
	dw	9253
	dw	12833
	dw	5408
	dw	8751
	dw	10776
	dw	6693
	dw	9011
	dw	11283
	dw	7972
	dw	9521
	dw	12566
	dw	6692
	dw	9771
	dw	13347
	dw	6180
	dw	9775
	dw	13343
	dw	5159
	dw	10543
	dw	12827
	dw	7462
	dw	10038
	dw	12567
	dw	8488
	dw	10287
	dw	11300
	dw	9770
	dw	10293
	dw	14107
	dw	6442
	dw	10805
	dw	12831
	dw	8236
	dw	11310
	dw	13608
	dw	6956
	dw	11058
	dw	13607
	dw	9516
	dw	11574
	dw	14369
	dw	7469
	dw	12082
	dw	14631
	dw	8239
	dw	12084
	dw	14122
	dw	8753
	dw	12854
	dw	14376
	dw	9523
	dw	13112
	dw	14379
	dw	10294
	dw	13623
	dw	14640
	dw	11574
	dw	0
	dw	5120
	dw	2832
	dw	4124
	dw	8972
	dw	3859
	dw	6170
	dw	11288
	dw	2068
	dw	6687
	dw	7699
	dw	7452
	dw	7715
	dw	10519
	dw	5666
	dw	10543
	dw	13595
	dw	7978
	dw	11317
	dw	14117
	dw	8753
	dw	12854
	dw	14376
	dw	11059
	dw	0
	dw	8448
	dw	4629
	dw	6687
	dw	10259
	dw	5403
	dw	8746
	dw	12061
	dw	6178
	dw	10543
	dw	12827
	dw	7462
	dw	10805
	dw	13599
	dw	9516
	dw	11574
	dw	14369
	dw	7469
	dw	12599
	dw	13858
	dw	10290
	dw	13112
	dw	14373
	dw	10294
	dw	0
	dw	512
	dw	514
	dw	1028
	dw	1540
	dw	773
	dw	1797
	dw	1794
	dw	1541
	dw	2568
	dw	7681
	dw	3091
	dw	5412
	dw	12298
	dw	3870
	dw	9011
	dw	13331
	dw	5159
	dw	10293
	dw	13595
	dw	6956
	dw	12599
	dw	14626
	dw	11574
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


s29_logic	dw	id_foster
	dw	id_joey
	dw	id_lamb
	dw	id_lamb_door_20
	dw	id_inner_lamb_door
	dw	id_lift_29
	dw	id_lift29_light
	dw	id_cable_29
	dw	$ffff
	dw	id_menu_logic


s29_mouse	dw	id_joey
	dw	id_lift_29
	dw	id_lamb
	dw	id_s29_card_slot
	dw	id_right_exit_29
	dw	id_left_exit_29
	dw	id_cable_29
	dw	id_s29_floor
	dw	$ffff
	dw	id_text_mouse


s29_sml_mouse	dw	id_joey
	dw	id_small_r_29
	dw	id_small_l_29
	dw	id_s29_sml_floor
	dw	$ffff
	dw	id_text_mouse



end32data

start32save_data



s29_floor	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	s29_floor_table
	dw	128
	dw	248
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	48
	dw	floor_action



end32save_data

start32data



s29_floor_table	dw	id_s29_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	id_lift_29
	dw	GT_29_lift
	dw	id_s29_card_slot
	dw	GT_29_card_slot
	dw	id_lift_wait
	dw	GT_lift_wait
	dw	id_right_exit_29
	dw	GT_right_exit_29
	dw	id_left_exit_29
	dw	GT_left_exit_29
	dw	1
	dw	s29_right_on
	dw	3
	dw	s29_left_on
	dw	id_lift_wait
	dw	GT_lift_wait
	dw	id_std_left_talk
	dw	GT_l_talk_29
	dw	id_std_right_talk
	dw	GT_r_talk_29
	dw	id_cable_29
	dw	GT_cable_29
	dw	-1


rs_foster_7_29	dw	c_xcood
	dw	240
	dw	c_ycood
	dw	232
	dw	c_screen
	dw	29
	dw	c_frame
	dw	s12+40
	dw	c_dir
	dw	down
	dw	c_place
	dw	id_s29_floor
	dw	-1


rs_joey_7_29	dw	c_xcood
	dw	240
	dw	c_ycood
	dw	240
	dw	c_screen
	dw	29
	dw	c_place
	dw	id_s29_floor
	dw	c_logic
	dw	l_script
	dw	c_base_sub
	dw	joey_out_of_lift
	dw	c_base_sub+2
	dw	0
	dw	c_frame
	dw	s136+2
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_collision+st_mouse
	dw	c_dir
	dw	down
	dw	c_mega_set
	dw	1*next_mega_set
	dw	c_frame
	dw	s136+2
	dw	-1


rs_lamb_start_bel	dw	c_xcood
	dw	360
	dw	c_ycood
	dw	264
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_floor
	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	-1



end32data

start32save_data



lift_29	dw	l_script
	dw	st_sort+st_logic+st_recreate+st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	NULL
	dw	$e5
	dw	$c5
	dw	s17
	dw	45+t7
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	268-$f5
	dw	236-$b5
	dw	lift_29_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	s29_lift_logic
	dw	0



end32save_data

start32data



s29_lift_open	dw	s17
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	0


s29_lift_close	dw	s17
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


card_slot_29_anim	dw	s18
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



s29_card_slot	dw	null
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	NULL
	dw	258
	dw	219
	dw	NULL
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	NULL
	dw	NULL
	dw	5
	dw	8
	dw	s29_slot_action


lift29_light	dw	l_script
	dw	st_recreate
	dw	0
	dw	29
	dw	0
	dd	0
	dw	$ee
	dw	$be
	dw	s20



end32save_data

start32data



joey_list_s29	dw	156
	dw	360
	dw	276
	dw	304
	dw	1
	dw	0



end32data

start32save_data



right_exit_29	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	0
	dw	397
	dw	201
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	414-397
	dw	262-201
	dw	er29_action



end32save_data

start32data



rs_foster_23_29	dw	c_xcood
	dw	440
	dw	c_ycood
	dw	264
	dw	c_screen
	dw	29
	dw	c_place
	dw	id_s29_floor
	dw	-1



end32data

start32save_data



left_exit_29	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	0
	dw	127
	dw	180
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	144-127
	dw	300-180
	dw	el29_action



end32save_data

start32data



lamb_card_29	dw	s76
	dw	276
	dw	231
	dw	0
	dw	276
	dw	231
	dw	1
	dw	276
	dw	231
	dw	2
	dw	276
	dw	231
	dw	3
	dw	276
	dw	231
	dw	4
	dw	276
	dw	231
	dw	5
	dw	276
	dw	231
	dw	6
	dw	276
	dw	231
	dw	1
	dw	276
	dw	231
	dw	0
	dw	0



end32data

start32save_data



cable_29	dw	l_script
	dw	st_recreate
	dw	0
	dw	29
	dw	NULL
	dd	NULL
	dw	335
	dw	236
	dw	s171
	dw	49
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	16
	dw	45
	dw	20
	dw	cable_29_action



end32save_data

start32data



get_cable_29_seq	dw	s170
	dw	293
	dw	252
	dw	0
	dw	293
	dw	252
	dw	1
	dw	293
	dw	252
	dw	2
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	3
	dw	293
	dw	252
	dw	2
	dw	293
	dw	252
	dw	1
	dw	293
	dw	252
	dw	0
	dw	0



end32data

start32save_data



s29_sml_floor	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	s29_sml_table
	dw	176
	dw	168
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320-176
	dw	16
	dw	floor_action



end32save_data

start32data



s29_sml_table	dw	id_s29_sml_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	id_small_r_29
	dw	GT_sml_r_29
	dw	id_small_l_29
	dw	GT_sml_l_29
	dw	4
	dw	sml_right_29
	dw	5
	dw	sml_left_29
	dw	-1


rs_23_sml_29	dw	c_xcood
	dw	328
	dw	c_ycood
	dw	168
	dw	c_screen
	dw	29
	dw	c_place
	dw	id_s29_sml_floor
	dw	c_frame
	dw	44+s13
	dw	-1



end32data

start32save_data



small_r_29	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	0
	dw	319
	dw	137
	dw	0
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	348-319
	dw	186-137
	dw	r_29_sml_action



end32save_data

start32data



rs_29_sml_23	dw	c_xcood
	dw	184
	dw	c_ycood
	dw	248
	dw	c_screen
	dw	23
	dw	c_place
	dw	id_s23_floor
	dw	c_frame
	dw	44+s12
	dw	-1



end32data

start32save_data



small_l_29	dw	0
	dw	st_mouse
	dw	0
	dw	29
	dw	NULL
	dd	0
	dw	156
	dw	136
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	179-156
	dw	188-136
	dw	l_29_sml_action



end32save_data

start32data



rs_29_sml_28	dw	c_xcood
	dw	312
	dw	c_ycood
	dw	168
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_sml_floor
	dw	-1


rs_28_sml_29	dw	c_xcood
	dw	168
	dw	c_ycood
	dw	176
	dw	c_screen
	dw	29
	dw	c_place
	dw	id_s29_sml_floor
	dw	-1


rs_19_sml_28	dw	c_xcood
	dw	192
	dw	c_ycood
	dw	176
	dw	c_screen
	dw	28
	dw	c_place
	dw	id_s28_sml_floor
	dw	c_frame
	dw	44+s13
	dw	-1


sml_joey_list_29	dw	202
	dw	294
	dw	166
	dw	186
	dw	1
	dw	0


sml_joey_list_28	dw	222
	dw	284
	dw	166
	dw	186
	dw	1
	dw	0



end32data

start32save_data



end32save_data
