start32data



sc38_palette	dw	0
	dw	1280
	dw	1798
	dw	1797
	dw	2051
	dw	1033
	dw	1804
	dw	5127
	dw	1284
	dw	2571
	dw	2313
	dw	2061
	dw	1809
	dw	3593
	dw	1292
	dw	2325
	dw	6150
	dw	2824
	dw	3090
	dw	3339
	dw	2831
	dw	1566
	dw	5382
	dw	3850
	dw	4113
	dw	3591
	dw	4114
	dw	2336
	dw	8714
	dw	1290
	dw	2843
	dw	4622
	dw	3090
	dw	3606
	dw	5907
	dw	3600
	dw	2342
	dw	4105
	dw	5396
	dw	3614
	dw	5131
	dw	4371
	dw	5398
	dw	6922
	dw	4623
	dw	5393
	dw	12058
	dw	1544
	dw	2858
	dw	9222
	dw	1808
	dw	3624
	dw	4874
	dw	8213
	dw	5911
	dw	11535
	dw	2827
	dw	4644
	dw	7693
	dw	5396
	dw	3626
	dw	5135
	dw	7193
	dw	3377
	dw	10759
	dw	1810
	dw	4390
	dw	6418
	dw	6679
	dw	5410
	dw	5905
	dw	8983
	dw	3887
	dw	11022
	dw	3603
	dw	6676
	dw	13354
	dw	2831
	dw	7192
	dw	7198
	dw	8217
	dw	5671
	dw	4627
	dw	12059
	dw	5677
	dw	10762
	dw	6421
	dw	5925
	dw	6171
	dw	10269
	dw	6689
	dw	13597
	dw	4114
	dw	7706
	dw	5667
	dw	11550
	dw	5425
	dw	5141
	dw	12831
	dw	7455
	dw	11042
	dw	7449
	dw	6446
	dw	11800
	dw	3867
	dw	5431
	dw	6676
	dw	12320
	dw	8475
	dw	7978
	dw	9761
	dw	6707
	dw	10261
	dw	8480
	dw	8984
	dw	8244
	dw	11809
	dw	6455
	dw	12825
	dw	6939
	dw	9501
	dw	8752
	dw	10532
	dw	7989
	dw	13332
	dw	6688
	dw	9756
	dw	13622
	dw	7966
	dw	9762
	dw	8494
	dw	13349
	dw	9015
	dw	6928
	dw	15144
	dw	9767
	dw	14378
	dw	5922
	dw	9521
	dw	13340
	dw	5926
	dw	9773
	dw	8230
	dw	14377
	dw	9271
	dw	8988
	dw	13098
	dw	10296
	dw	10772
	dw	10282
	dw	11039
	dw	13885
	dw	8232
	dw	10552
	dw	13338
	dw	9513
	dw	11555
	dw	12090
	dw	10794
	dw	11303
	dw	11318
	dw	11821
	dw	11323
	dw	13847
	dw	8749
	dw	11322
	dw	9502
	dw	16175
	dw	11828
	dw	12583
	dw	11311
	dw	12073
	dw	13883
	dw	12333
	dw	12337
	dw	14386
	dw	9521
	dw	12603
	dw	13600
	dw	11826
	dw	12851
	dw	14647
	dw	10803
	dw	12855
	dw	14899
	dw	12084
	dw	13622
	dw	14650
	dw	13623
	dw	14388
	dw	14654
	dw	15673
	dw	14906
	dw	15165
	dw	15931
	dw	15677
	dw	16190
	dw	16191
	dw	3592
	dw	4121
	dw	4112
	dw	6939
	dw	10011
	dw	10023
	dw	13107
	dw	16179
	dw	16191
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	1287
	dw	2822
	dw	2568
	dw	2830
	dw	4622
	dw	4622
	dw	4372
	dw	5910
	dw	6677
	dw	6169
	dw	7198
	dw	8733
	dw	8480
	dw	9254
	dw	10791
	dw	11049
	dw	11822
	dw	12848
	dw	13363
	dw	14646
	dw	14905
	dw	16191
	dw	63
	dw	0
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	10541
	dw	9766
	dw	7716
	dw	7453
	dw	5140
	dw	3093
	dw	1805
	dw	770
	dw	519
	dw	14851
	dw	8751
	dw	10295
	dw	13596
	dw	5921
	dw	5931
	dw	9488
	dw	2576
	dw	3104
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	12607
	dw	14885
	dw	7209
	dw	8501
	dw	11797
	dw	3352
	dw	4135
	dw	8199
	dw	778
	dw	9791
	dw	14893
	dw	9759
	dw	5938
	dw	10783
	dw	6417
	dw	2332
	dw	3857
	dw	2308
	dw	2865
	dw	11531
	dw	1542
	dw	287
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	0
	dw	63
	dw	16128
	dw	0
	dw	63
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


sc38_walk_grid	dd 0 dup (0)

sc38_fast_list	dw	12+disk_14
	dw	51+disk_14
	dw	52+disk_14
	dw	53+disk_14
	dw	54+disk_14
	dw	it_sc38_layer_1+disk_14
	dw	it_sc38_layer_2+disk_14
	dw	it_sc38_grid_1+disk_14
	dw	it_sc38_grid_2+disk_14
	dw	0


sc38_chip_list	dw	it_sc38_layer_0+disk_14
	dw	it_sc38_sexy_dani+disk_14+$8000
	dw	it_spunky+disk_12
	dw	it_sniff_left+disk_12
	dw	it_bark+disk_12
	dw	it_sc38_foster_lift+disk_14
	dw	it_sc38_dani_anims+disk_14+$8000
	dw	it_sc38_dani_sattlk+disk_14
	dw	it_sc38_dani_get_up+disk_14+$8000
	dw	it_sc38_hand_set+disk_14
	dw	it_sc38_get_phone+disk_14+$8000
	dw	it_sc38_phone_talk+disk_14
	dw	it_sc38_get_food+disk_14+$8000
	dw	it_sc38_use_video+disk_14+$8000
	dw	it_sc38_video_anim+disk_14
	dw	it_sc38_screen_1+$8000+disk_14
	dw	it_sc38_screen_2+$8000+disk_14
	dw	it_sc38_screen_3+$8000+disk_14
	dw	it_sc38_screen_4+disk_14
	dw	140+disk_14
	dw	0


sc38_logic_list	dw	id_foster
	dw	id_danielle
	dw	id_spunky
	dw	id_dog_bark_thing
	dw	id_sc38_monitor
	dw	id_sc38_video
	dw	id_sc38_hand_set
	dw	id_sc38_lift
	dw	$ffff
	dw	id_std_menu_logic


sc38_mouse_list	dw	id_spunky
	dw	id_sc32_buzzer
	dw	id_danielle
	dw	id_sc38_sofa
	dw	id_sc38_statue
	dw	id_sc38_video
	dw	id_sc38_monitor
	dw	id_sc38_biscuits
	dw	id_sc38_dog_tray
	dw	id_sc38_lift
	dw	id_sc38_floor
	dw	$ffff
	dw	id_text_mouse


reset_32_38	dw	c_screen
	dw	38
	dw	c_place
	dw	id_sc38_floor
	dw	c_xcood
	dw	192
	dw	c_ycood
	dw	288
	dw	c_frame
	dw	46+s12
	dw	c_dir
	dw	right
	dw	-1


reset_spunky_38	dw	c_status
	dw	st_sort+st_recreate+st_logic+st_collision;
	dw	c_screen
	dw	38
	dw	c_place
	dw	id_sc38_floor
	dw	c_xcood
	dw	248
	dw	c_ycood
	dw	256
	dw	c_frame
	dw	34+s71
	dw	c_dir
	dw	left
	dw	c_mouse_click
	dw	advisor_188
	dw	-1


reset_dani_sit	dw	c_status
	dw	st_logic+st_sort+st_recreate
	dw	c_screen
	dw	38
	dw	c_place
	dw	id_sc38_floor
	dw	c_xcood
	dw	294
	dw	c_ycood
	dw	244
	dw	c_frame
	dw	s107
	dw	-1


reset_dani_stand	dw	c_status
	dw	st_logic+st_sort+st_recreate+st_grid_plot+st_collision
	dw	c_xcood
	dw	328
	dw	c_ycood
	dw	288
	dw	c_frame
	dw	32+s106
	dw	c_dir
	dw	down
	dw	c_mouse_click
	dw	advisor_188
	dw	c_mouse_rel_x
	dw	4
	dw	c_mouse_rel_y
	dw	2
	dw	c_mouse_size_x
	dw	20
	dw	c_mouse_size_y
	dw	54
	dw	c_action_script
	dw	sc38_danielle_action
	dw	c_mega_set
	dw	next_mega_set
	dw	-1


sc38_dani_anim_1	dw	s107
	dw	294
	dw	244
	dw	0
	dw	294
	dw	245
	dw	1
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	4
	dw	294
	dw	244
	dw	5
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	9
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	15
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	18
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	19
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	15
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	9
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	5
	dw	294
	dw	245
	dw	4
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	1
	dw	0


sc38_dani_anim_2	dw	s107
	dw	294
	dw	244
	dw	0
	dw	294
	dw	245
	dw	1
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	4
	dw	294
	dw	244
	dw	5
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	9
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	15
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	18
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	19
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	18
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	19
	dw	294
	dw	244
	dw	19
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	18
	dw	294
	dw	244
	dw	18
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	17
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	16
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	5
	dw	294
	dw	245
	dw	4
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	1
	dw	0


sc38_dani_anim_3	dw	s107
	dw	294
	dw	244
	dw	0
	dw	294
	dw	245
	dw	1
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	4
	dw	294
	dw	244
	dw	5
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	9
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	14
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	13
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	12
	dw	294
	dw	244
	dw	11
	dw	294
	dw	244
	dw	10
	dw	294
	dw	244
	dw	9
	dw	294
	dw	244
	dw	8
	dw	294
	dw	244
	dw	7
	dw	294
	dw	244
	dw	6
	dw	294
	dw	244
	dw	5
	dw	294
	dw	245
	dw	4
	dw	294
	dw	245
	dw	3
	dw	294
	dw	245
	dw	2
	dw	294
	dw	245
	dw	1
	dw	294
	dw	244
	dw	0
	dw	0


sniff_left	dw	s72
	dw	208
	dw	219
	dw	0
	dw	208
	dw	219
	dw	1
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	3
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	7
	dw	208
	dw	219
	dw	7
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	3
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	7
	dw	208
	dw	219
	dw	6
	dw	208
	dw	219
	dw	5
	dw	208
	dw	219
	dw	3
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	1
	dw	208
	dw	219
	dw	0
	dw	0


piss_left	dw	s75
	dw	208
	dw	219
	dw	0
	dw	208
	dw	219
	dw	1
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	3
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	4
	dw	208
	dw	219
	dw	3
	dw	208
	dw	219
	dw	2
	dw	208
	dw	219
	dw	1
	dw	208
	dw	219
	dw	0
	dw	0


sniff_right	dw	s74
	dw	257
	dw	219
	dw	0
	dw	257
	dw	219
	dw	1
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	3
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	7
	dw	257
	dw	219
	dw	7
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	3
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	7
	dw	257
	dw	219
	dw	6
	dw	257
	dw	219
	dw	5
	dw	257
	dw	219
	dw	3
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	1
	dw	257
	dw	219
	dw	0
	dw	0


piss_right	dw	s76
	dw	257
	dw	219
	dw	0
	dw	257
	dw	219
	dw	1
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	3
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	4
	dw	257
	dw	219
	dw	3
	dw	257
	dw	219
	dw	2
	dw	257
	dw	219
	dw	1
	dw	257
	dw	219
	dw	0
	dw	0


bark	dw	s65
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	1
	dw	243
	dw	225
	dw	2
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	243
	dw	225
	dw	0
	dw	0


sc38_scr_bark	dw	s140
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	3
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	3
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	3
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	1
	dw	202
	dw	253
	dw	2
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	202
	dw	253
	dw	0
	dw	0


sc38_lift_up	dw	s101
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	send_sync
	dw	id_foster
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc38_lift_down	dw	s101
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	send_sync
	dw	id_foster
	dw	1
	dw	0


sc38_dani_get_up	dw	s109
	dw	294
	dw	244
	dw	0
	dw	295
	dw	244
	dw	1
	dw	298
	dw	245
	dw	2
	dw	301
	dw	241
	dw	3
	dw	305
	dw	238
	dw	4
	dw	307
	dw	238
	dw	5
	dw	308
	dw	238
	dw	6
	dw	311
	dw	238
	dw	7
	dw	319
	dw	239
	dw	8
	dw	319
	dw	238
	dw	9
	dw	317
	dw	242
	dw	10
	dw	317
	dw	243
	dw	11
	dw	317
	dw	243
	dw	12
	dw	0


sc38_get_phone	dw	s130
	dw	156
	dw	259
	dw	0
	dw	156
	dw	259
	dw	1
	dw	156
	dw	259
	dw	2
	dw	156
	dw	259
	dw	3
	dw	157
	dw	259
	dw	4
	dw	157
	dw	259
	dw	4
	dw	158
	dw	259
	dw	5
	dw	164
	dw	259
	dw	6
	dw	165
	dw	259
	dw	7
	dw	0


sc38_ringer_anim	dw	s129
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	1
	dw	161
	dw	261
	dw	2
	dw	161
	dw	261
	dw	3
	dw	161
	dw	261
	dw	4
	dw	161
	dw	261
	dw	5
	dw	161
	dw	261
	dw	4
	dw	161
	dw	261
	dw	3
	dw	161
	dw	261
	dw	2
	dw	161
	dw	261
	dw	6
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	0
	dw	161
	dw	261
	dw	0
	dw	0


sc38_use_video	dw	s132
	dw	354
	dw	210
	dw	0
	dw	354
	dw	210
	dw	1
	dw	354
	dw	210
	dw	2
	dw	354
	dw	210
	dw	3
	dw	354
	dw	210
	dw	4
	dw	354
	dw	210
	dw	5
	dw	354
	dw	210
	dw	6
	dw	354
	dw	210
	dw	7
	dw	0


sc38_video_anim	dw	s133
	dw	376
	dw	252
	dw	0
	dw	376
	dw	252
	dw	1
	dw	376
	dw	252
	dw	2
	dw	376
	dw	252
	dw	3
	dw	376
	dw	252
	dw	4
	dw	376
	dw	252
	dw	5
	dw	376
	dw	252
	dw	6
	dw	0


sc38_screen_1	dw	s134
	dw	379
	dw	209
	dw	0
	dw	379
	dw	209
	dw	1
	dw	379
	dw	209
	dw	2
	dw	379
	dw	209
	dw	3
	dw	379
	dw	209
	dw	4
	dw	379
	dw	209
	dw	5
	dw	379
	dw	209
	dw	6
	dw	379
	dw	209
	dw	7
	dw	379
	dw	209
	dw	8
	dw	379
	dw	209
	dw	9
	dw	379
	dw	209
	dw	10
	dw	379
	dw	209
	dw	11
	dw	379
	dw	209
	dw	12
	dw	379
	dw	209
	dw	13
	dw	379
	dw	209
	dw	14
	dw	379
	dw	209
	dw	15
	dw	379
	dw	209
	dw	16
	dw	379
	dw	209
	dw	17
	dw	379
	dw	209
	dw	18
	dw	379
	dw	209
	dw	19
	dw	379
	dw	209
	dw	20
	dw	379
	dw	209
	dw	21
	dw	379
	dw	209
	dw	22
	dw	379
	dw	209
	dw	23
	dw	379
	dw	209
	dw	24
	dw	379
	dw	209
	dw	25
	dw	379
	dw	209
	dw	26
	dw	379
	dw	209
	dw	27
	dw	379
	dw	209
	dw	28
	dw	379
	dw	209
	dw	29
	dw	379
	dw	209
	dw	30
	dw	379
	dw	209
	dw	31
	dw	379
	dw	209
	dw	32
	dw	379
	dw	209
	dw	33
	dw	379
	dw	209
	dw	34
	dw	379
	dw	209
	dw	35
	dw	379
	dw	209
	dw	36
	dw	379
	dw	209
	dw	37
	dw	379
	dw	209
	dw	38
	dw	379
	dw	209
	dw	28
	dw	379
	dw	209
	dw	29
	dw	379
	dw	209
	dw	30
	dw	379
	dw	209
	dw	31
	dw	379
	dw	209
	dw	32
	dw	379
	dw	209
	dw	33
	dw	379
	dw	209
	dw	34
	dw	379
	dw	209
	dw	35
	dw	379
	dw	209
	dw	36
	dw	379
	dw	209
	dw	37
	dw	379
	dw	209
	dw	38
	dw	379
	dw	209
	dw	39
	dw	379
	dw	209
	dw	40
	dw	379
	dw	209
	dw	41
	dw	379
	dw	209
	dw	42
	dw	379
	dw	209
	dw	43
	dw	379
	dw	209
	dw	44
	dw	379
	dw	209
	dw	45
	dw	0


sc38_screen_2	dw	s136
	dw	379
	dw	209
	dw	0
	dw	379
	dw	209
	dw	1
	dw	379
	dw	209
	dw	2
	dw	379
	dw	209
	dw	3
	dw	379
	dw	209
	dw	4
	dw	379
	dw	209
	dw	5
	dw	379
	dw	209
	dw	6
	dw	379
	dw	209
	dw	7
	dw	379
	dw	209
	dw	8
	dw	379
	dw	209
	dw	9
	dw	379
	dw	209
	dw	10
	dw	379
	dw	209
	dw	11
	dw	379
	dw	209
	dw	12
	dw	379
	dw	209
	dw	13
	dw	379
	dw	209
	dw	14
	dw	379
	dw	209
	dw	15
	dw	379
	dw	209
	dw	16
	dw	379
	dw	209
	dw	17
	dw	379
	dw	209
	dw	18
	dw	379
	dw	209
	dw	19
	dw	379
	dw	209
	dw	20
	dw	379
	dw	209
	dw	21
	dw	379
	dw	209
	dw	22
	dw	0


sc38_screen_3	dw	s137
	dw	379
	dw	209
	dw	0
	dw	379
	dw	209
	dw	1
	dw	379
	dw	209
	dw	2
	dw	379
	dw	209
	dw	3
	dw	379
	dw	209
	dw	4
	dw	379
	dw	209
	dw	5
	dw	379
	dw	209
	dw	6
	dw	379
	dw	209
	dw	7
	dw	379
	dw	209
	dw	8
	dw	379
	dw	209
	dw	9
	dw	379
	dw	209
	dw	10
	dw	379
	dw	209
	dw	11
	dw	379
	dw	209
	dw	12
	dw	379
	dw	209
	dw	13
	dw	379
	dw	209
	dw	14
	dw	379
	dw	209
	dw	15
	dw	379
	dw	209
	dw	16
	dw	379
	dw	209
	dw	17
	dw	379
	dw	209
	dw	18
	dw	379
	dw	209
	dw	19
	dw	379
	dw	209
	dw	20
	dw	379
	dw	209
	dw	21
	dw	379
	dw	209
	dw	22
	dw	379
	dw	209
	dw	23
	dw	379
	dw	209
	dw	24
	dw	379
	dw	209
	dw	25
	dw	379
	dw	209
	dw	26
	dw	379
	dw	209
	dw	27
	dw	379
	dw	209
	dw	28
	dw	0


sc38_screen_4	dw	s138
	dw	379
	dw	209
	dw	0
	dw	379
	dw	209
	dw	1
	dw	379
	dw	209
	dw	2
	dw	379
	dw	209
	dw	3
	dw	379
	dw	209
	dw	4
	dw	379
	dw	209
	dw	5
	dw	379
	dw	209
	dw	6
	dw	379
	dw	209
	dw	7
	dw	379
	dw	209
	dw	8
	dw	379
	dw	209
	dw	9
	dw	379
	dw	209
	dw	10
	dw	379
	dw	209
	dw	11
	dw	379
	dw	209
	dw	12
	dw	379
	dw	209
	dw	13
	dw	379
	dw	209
	dw	14
	dw	379
	dw	209
	dw	15
	dw	379
	dw	209
	dw	16
	dw	379
	dw	209
	dw	17
	dw	379
	dw	209
	dw	18
	dw	379
	dw	209
	dw	19
	dw	0


sc38_reach_food	dw	s139
	dw	235
	dw	216
	dw	0
	dw	235
	dw	216
	dw	1
	dw	235
	dw	216
	dw	2
	dw	235
	dw	216
	dw	3
	dw	235
	dw	216
	dw	4
	dw	235
	dw	216
	dw	5
	dw	235
	dw	216
	dw	6
	dw	235
	dw	216
	dw	7
	dw	235
	dw	216
	dw	8
	dw	235
	dw	216
	dw	0
	dw	0


sc38_get_food	dw	s139
	dw	235
	dw	216
	dw	0
	dw	235
	dw	216
	dw	1
	dw	235
	dw	216
	dw	2
	dw	235
	dw	216
	dw	3
	dw	235
	dw	216
	dw	4
	dw	235
	dw	216
	dw	5
	dw	235
	dw	216
	dw	6
	dw	235
	dw	216
	dw	6
	dw	235
	dw	216
	dw	6
	dw	235
	dw	216
	dw	5
	dw	235
	dw	216
	dw	4
	dw	235
	dw	216
	dw	3
	dw	235
	dw	216
	dw	2
	dw	235
	dw	216
	dw	1
	dw	235
	dw	216
	dw	0
	dw	0



end32data

start32save_data



sc38_floor	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	38
	dw	NULL
	dd	sc38_floor_table
	dw	200
	dw	256
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	447-200
	dw	327-256
	dw	floor_action



end32save_data

start32data



sc38_floor_table	dw	id_sc38_floor
	dw	return_ok
	dw	id_sc38_lift
	dw	GT_sc38_lift
	dw	id_sc38_sofa
	dw	GT_sc38_sofa
	dw	id_sc38_statue
	dw	GT_sc38_statue
	dw	id_sc38_video
	dw	GT_sc38_video
	dw	id_sc38_monitor
	dw	GT_sc38_monitor
	dw	id_sc38_biscuits
	dw	GT_sc38_biscuits
	dw	id_sc38_dog_tray
	dw	GT_sc38_dog_tray
	dw	id_sc38_hand_set
	dw	GT_sc38_hand_set
	dw	id_danielle
	dw	GT_sc38_danielle
	dw	id_std_left_talk
	dw	GT_sc38_left_talk
	dw	id_std_right_talk
	dw	GT_sc38_right_talk
	dw	-1



end32data

start32save_data



sc38_lift	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	182
	dw	242
	dw	7+s101
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	8
	dw	-8
	dw	201-190
	dw	300-234
	dw	sc38_lift_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc38_lift_logic
	dw	0


sc38_statue	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	354
	dw	199
	dw	NULL
	dw	16620
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	366-354
	dw	254-199
	dw	sc38_statue_action


sc38_monitor	dw	l_script
	dw	st_logic+st_mouse
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	379
	dw	209
	dw	s134
	dw	57
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-1
	dw	0
	dw	406-378
	dw	242-209
	dw	sc38_monitor_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc38_monitor_logic
	dw	0


sc38_video	dw	l_script
	dw	st_logic+st_mouse+st_recreate
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	376
	dw	252
	dw	s133
	dw	16678
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	-4
	dw	401-376
	dw	264-248
	dw	sc38_video_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc38_video_logic
	dw	0


sc38_sofa	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	272
	dw	242
	dw	NULL
	dw	16679
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	308-272
	dw	301-242
	dw	sc38_sofa_action


sc38_dog_tray	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	220
	dw	251
	dw	NULL
	dw	17178
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	241-220
	dw	267-251
	dw	sc38_dog_tray_action


sc38_biscuits	dw	NULL
	dw	0
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	228
	dw	258
	dw	NULL
	dw	198
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	237-228
	dw	261-258
	dw	sc38_biscuits_action


dna	dd 0 dup (0)

danielle	dw	l_script
	dw	st_logic+st_mouse+st_sort+st_recreate+st_grid_plot+st_collision
	dw	0
	dw	31
	dw	id_sc31_floor
	dd	0
	dw	352
	dw	248
	dw	38+s55
	dw	54
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-8
	dw	-43
	dw	14
	dw	50
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	danielle_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	right
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_dan_col
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	dan_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	dan_up
	dd	dan_down
	dd	dan_left
	dd	dan_right
	dd	dan_st_up
	dd	dan_st_down
	dd	dan_st_left
	dd	dan_st_right
	dd	dan_st_talk
	dd	0
	dd	dan_u_to_d
	dd	dan_u_to_l
	dd	dan_u_to_r
	dd	dan_u_to_t
	dd	dan_d_to_u
	dd	0
	dd	dan_d_to_l
	dd	dan_d_to_r
	dd	0
	dd	dan_l_to_u
	dd	dan_l_to_d
	dd	0
	dd	dan_l_to_r
	dd	0
	dd	dan_r_to_u
	dd	dan_r_to_d
	dd	dan_r_to_l
	dd	0
	dd	dan_r_to_t
	dd	dan_t_to_u
	dd	0
	dd	0
	dd	dan_t_to_r
	dd	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	sex_up
	dd	sex_down
	dd	sex_left
	dd	sex_right
	dd	sex_st_up
	dd	sex_st_down
	dd	sex_st_left
	dd	sex_st_right
	dd	sex_st_talk
	dd	0
	dd	sex_u_to_d
	dd	sex_u_to_l
	dd	sex_u_to_r
	dd	sex_u_to_t
	dd	sex_d_to_u
	dd	0
	dd	sex_d_to_l
	dd	sex_d_to_r
	dd	0
	dd	sex_l_to_u
	dd	sex_l_to_d
	dd	0
	dd	sex_l_to_r
	dd	0
	dd	sex_r_to_u
	dd	sex_r_to_d
	dd	sex_r_to_l
	dd	0
	dd	sex_r_to_t
	dd	sex_t_to_u
	dd	0
	dd	0
	dd	sex_t_to_r
	dd	0


dan_auto	db	64 dup (0)



end32save_data

start32data



dan_up	dw	2
	dw	0+s55
	dw	0
	dw	-2
	dw	2
	dw	1+s55
	dw	0
	dw	-2
	dw	2
	dw	2+s55
	dw	0
	dw	-2
	dw	2
	dw	3+s55
	dw	0
	dw	-2
	dw	2
	dw	4+s55
	dw	0
	dw	-2
	dw	2
	dw	5+s55
	dw	0
	dw	-2
	dw	2
	dw	6+s55
	dw	0
	dw	-2
	dw	2
	dw	7+s55
	dw	0
	dw	-2
	dw	0


dan_down	dw	2
	dw	8+s55
	dw	0
	dw	2
	dw	2
	dw	9+s55
	dw	0
	dw	2
	dw	2
	dw	10+s55
	dw	0
	dw	2
	dw	2
	dw	11+s55
	dw	0
	dw	2
	dw	2
	dw	12+s55
	dw	0
	dw	2
	dw	2
	dw	13+s55
	dw	0
	dw	2
	dw	2
	dw	14+s55
	dw	0
	dw	2
	dw	2
	dw	15+s55
	dw	0
	dw	2
	dw	0


dan_left	dw	4
	dw	16+s55
	dw	-4
	dw	0
	dw	4
	dw	17+s55
	dw	-4
	dw	0
	dw	4
	dw	18+s55
	dw	-4
	dw	0
	dw	4
	dw	19+s55
	dw	-4
	dw	0
	dw	4
	dw	20+s55
	dw	-4
	dw	0
	dw	4
	dw	21+s55
	dw	-4
	dw	0
	dw	4
	dw	22+s55
	dw	-4
	dw	0
	dw	4
	dw	23+s55
	dw	-4
	dw	0
	dw	0


dan_right	dw	4
	dw	24+s55
	dw	4
	dw	0
	dw	4
	dw	25+s55
	dw	4
	dw	0
	dw	4
	dw	26+s55
	dw	4
	dw	0
	dw	4
	dw	27+s55
	dw	4
	dw	0
	dw	4
	dw	28+s55
	dw	4
	dw	0
	dw	4
	dw	29+s55
	dw	4
	dw	0
	dw	4
	dw	30+s55
	dw	4
	dw	0
	dw	4
	dw	31+s55
	dw	4
	dw	0
	dw	0


dan_st_up	dw	s55
	dw	1
	dw	0
	dw	36
	dw	0


dan_st_down	dw	s55
	dw	1
	dw	0
	dw	32
	dw	0


dan_st_left	dw	s55
	dw	1
	dw	0
	dw	34
	dw	0


dan_st_right	dw	s55
	dw	1
	dw	0
	dw	38
	dw	0


dan_st_talk	dw	s85
	dw	1
	dw	0
	dw	0
	dw	0


dan_u_to_d	dw	35+s55
	dw	34+s55
	dw	33+s55
	dw	0


dan_u_to_l	dw	35+s55
	dw	0


dan_u_to_r	dw	37+s55
	dw	0


dan_u_to_t	dw	37+s55
	dw	38+s55
	dw	0


dan_d_to_u	dw	39+s55
	dw	38+s55
	dw	37+s55
	dw	0


dan_d_to_l	dw	33+s55
	dw	0


dan_d_to_r	dw	39+s55
	dw	0


dan_l_to_u	dw	35+s55
	dw	0


dan_l_to_d	dw	33+s55
	dw	0


dan_l_to_r	dw	33+s55
	dw	32+s55
	dw	39+s55
	dw	0


dan_r_to_u	dw	37+s55
	dw	0


dan_r_to_d	dw	39+s55
	dw	0


dan_r_to_l	dw	37+s55
	dw	36+s55
	dw	35+s55
	dw	0


dan_r_to_t	dw	39+s55
	dw	32+s55
	dw	0


dan_t_to_u	dw	38+s55
	dw	37+s55
	dw	0


dan_t_to_r	dw	32+s55
	dw	39+s55
	dw	0


sex_up	dw	2
	dw	0+s106
	dw	0
	dw	-2
	dw	2
	dw	1+s106
	dw	0
	dw	-2
	dw	2
	dw	2+s106
	dw	0
	dw	-2
	dw	2
	dw	3+s106
	dw	0
	dw	-2
	dw	2
	dw	4+s106
	dw	0
	dw	-2
	dw	2
	dw	5+s106
	dw	0
	dw	-2
	dw	2
	dw	6+s106
	dw	0
	dw	-2
	dw	2
	dw	7+s106
	dw	0
	dw	-2
	dw	0


sex_down	dw	2
	dw	8+s106
	dw	0
	dw	2
	dw	2
	dw	9+s106
	dw	0
	dw	2
	dw	2
	dw	10+s106
	dw	0
	dw	2
	dw	2
	dw	11+s106
	dw	0
	dw	2
	dw	2
	dw	12+s106
	dw	0
	dw	2
	dw	2
	dw	13+s106
	dw	0
	dw	2
	dw	2
	dw	14+s106
	dw	0
	dw	2
	dw	2
	dw	15+s106
	dw	0
	dw	2
	dw	0


sex_left	dw	4
	dw	16+s106
	dw	-4
	dw	0
	dw	4
	dw	17+s106
	dw	-4
	dw	0
	dw	4
	dw	18+s106
	dw	-4
	dw	0
	dw	4
	dw	19+s106
	dw	-4
	dw	0
	dw	4
	dw	20+s106
	dw	-4
	dw	0
	dw	4
	dw	21+s106
	dw	-4
	dw	0
	dw	4
	dw	22+s106
	dw	-4
	dw	0
	dw	4
	dw	23+s106
	dw	-4
	dw	0
	dw	0


sex_right	dw	4
	dw	24+s106
	dw	4
	dw	0
	dw	4
	dw	25+s106
	dw	4
	dw	0
	dw	4
	dw	26+s106
	dw	4
	dw	0
	dw	4
	dw	27+s106
	dw	4
	dw	0
	dw	4
	dw	28+s106
	dw	4
	dw	0
	dw	4
	dw	29+s106
	dw	4
	dw	0
	dw	4
	dw	30+s106
	dw	4
	dw	0
	dw	4
	dw	31+s106
	dw	4
	dw	0
	dw	0


sex_st_up	dw	s106
	dw	1
	dw	0
	dw	36
	dw	0


sex_st_down	dw	s106
	dw	1
	dw	0
	dw	32
	dw	0


sex_st_left	dw	s106
	dw	1
	dw	0
	dw	34
	dw	0


sex_st_right	dw	s106
	dw	1
	dw	0
	dw	38
	dw	0


sex_st_talk	dw	s106
	dw	1
	dw	0
	dw	0
	dw	0


sex_u_to_d	dw	35+s106
	dw	34+s106
	dw	33+s106
	dw	0


sex_u_to_l	dw	35+s106
	dw	0


sex_u_to_r	dw	37+s106
	dw	0


sex_u_to_t	dw	37+s106
	dw	38+s106
	dw	0


sex_d_to_u	dw	39+s106
	dw	38+s106
	dw	37+s106
	dw	0


sex_d_to_l	dw	33+s106
	dw	0


sex_d_to_r	dw	39+s106
	dw	0


sex_l_to_u	dw	35+s106
	dw	0


sex_l_to_d	dw	33+s106
	dw	0


sex_l_to_r	dw	33+s106
	dw	32+s106
	dw	39+s106
	dw	0


sex_r_to_u	dw	37+s106
	dw	0


sex_r_to_d	dw	39+s106
	dw	0


sex_r_to_l	dw	37+s106
	dw	36+s106
	dw	35+s106
	dw	0


sex_r_to_t	dw	39+s106
	dw	32+s106
	dw	0


sex_t_to_u	dw	38+s106
	dw	37+s106
	dw	0


sex_t_to_r	dw	32+s106
	dw	39+s106
	dw	0



end32data

start32save_data



spu	dd 0 dup (0)

spunky	dw	l_script
	dw	st_logic+st_sort+st_recreate+st_grid_plot+st_collision
	dw	0
	dw	31
	dw	id_sc31_floor
	dd	0
	dw	312
	dw	240
	dw	38+s71
	dw	16614
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-8
	dw	-43
	dw	14
	dw	50
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	spunky_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	right
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	7
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	spu_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	spu_up
	dd	spu_down
	dd	spu_left
	dd	spu_right
	dd	spu_st_up
	dd	spu_st_down
	dd	spu_st_left
	dd	spu_st_right
	dd	spu_st_talk
	dd	0
	dd	spu_u_to_d
	dd	spu_u_to_l
	dd	spu_u_to_r
	dd	spu_u_to_t
	dd	spu_d_to_u
	dd	0
	dd	spu_d_to_l
	dd	spu_d_to_r
	dd	0
	dd	spu_l_to_u
	dd	spu_l_to_d
	dd	0
	dd	spu_l_to_r
	dd	spu_l_to_t
	dd	spu_r_to_u
	dd	spu_r_to_d
	dd	spu_r_to_l
	dd	0
	dd	0
	dd	spu_t_to_u
	dd	0
	dd	spu_t_to_l
	dd	0
	dd	0


spu_auto	db	64 dup (0)



end32save_data

start32data



spu_up	dw	1
	dw	0+s71
	dw	0
	dw	-1
	dw	1
	dw	1+s71
	dw	0
	dw	-1
	dw	1
	dw	2+s71
	dw	0
	dw	-1
	dw	1
	dw	3+s71
	dw	0
	dw	-1
	dw	1
	dw	4+s71
	dw	0
	dw	-1
	dw	1
	dw	5+s71
	dw	0
	dw	-1
	dw	1
	dw	6+s71
	dw	0
	dw	-1
	dw	1
	dw	7+s71
	dw	0
	dw	-1
	dw	0


spu_down	dw	1
	dw	8+s71
	dw	0
	dw	1
	dw	1
	dw	9+s71
	dw	0
	dw	1
	dw	1
	dw	10+s71
	dw	0
	dw	1
	dw	1
	dw	11+s71
	dw	0
	dw	1
	dw	1
	dw	12+s71
	dw	0
	dw	1
	dw	1
	dw	13+s71
	dw	0
	dw	1
	dw	1
	dw	14+s71
	dw	0
	dw	1
	dw	1
	dw	15+s71
	dw	0
	dw	1
	dw	0


spu_left	dw	2
	dw	16+s71
	dw	-2
	dw	0
	dw	2
	dw	17+s71
	dw	-2
	dw	0
	dw	2
	dw	18+s71
	dw	-2
	dw	0
	dw	2
	dw	19+s71
	dw	-2
	dw	0
	dw	2
	dw	20+s71
	dw	-2
	dw	0
	dw	2
	dw	21+s71
	dw	-2
	dw	0
	dw	2
	dw	22+s71
	dw	-2
	dw	0
	dw	2
	dw	23+s71
	dw	-2
	dw	0
	dw	0


spu_right	dw	2
	dw	24+s71
	dw	2
	dw	0
	dw	2
	dw	25+s71
	dw	2
	dw	0
	dw	2
	dw	26+s71
	dw	2
	dw	0
	dw	2
	dw	27+s71
	dw	2
	dw	0
	dw	2
	dw	28+s71
	dw	2
	dw	0
	dw	2
	dw	29+s71
	dw	2
	dw	0
	dw	2
	dw	30+s71
	dw	2
	dw	0
	dw	2
	dw	31+s71
	dw	2
	dw	0
	dw	0


spu_st_up	dw	s71
	dw	1
	dw	0
	dw	36
	dw	0


spu_st_down	dw	s71
	dw	1
	dw	0
	dw	32
	dw	0


spu_st_left	dw	s71
	dw	1
	dw	0
	dw	34
	dw	0


spu_st_right	dw	s71
	dw	1
	dw	0
	dw	38
	dw	0


spu_st_talk	dw	s71
	dw	1
	dw	0
	dw	0
	dw	0


spu_u_to_d	dw	35+s71
	dw	34+s71
	dw	33+s71
	dw	0


spu_u_to_l	dw	35+s71
	dw	0


spu_u_to_r	dw	37+s71
	dw	0


spu_u_to_t	dw	37+s71
	dw	38+s71
	dw	0


spu_d_to_u	dw	39+s71
	dw	38+s71
	dw	37+s71
	dw	0


spu_d_to_l	dw	33+s71
	dw	0


spu_d_to_r	dw	39+s71
	dw	0


spu_l_to_u	dw	35+s71
	dw	0


spu_l_to_d	dw	33+s71
	dw	0


spu_l_to_r	dw	33+s71
	dw	32+s71
	dw	39+s71
	dw	0


spu_l_to_t	dw	33+s71
	dw	32+s71
	dw	0


spu_r_to_u	dw	37+s71
	dw	0


spu_r_to_d	dw	39+s71
	dw	0


spu_r_to_l	dw	37+s71
	dw	36+s71
	dw	35+s71
	dw	0


spu_t_to_u	dw	38+s71
	dw	37+s71
	dw	0


spu_t_to_l	dw	32+s71
	dw	33+s71
	dw	0



end32data

start32save_data



sc38_hand_set	dw	NULL
	dw	st_background+st_recreate
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	156
	dw	267
	dw	s110


sc38_ringer	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	161
	dw	261
	dw	s129
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc38_ringer_logic
	dw	0


dog_bark_thing	dw	l_script
	dw	st_logic
	dw	NULL
	dw	38
	dw	NULL
	dd	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	dog_bark_logic
	dw	0



end32save_data

start32data



end32data
