start32data



sc40_palette	dw	0
	dw	768
	dw	515
	dw	1283
	dw	1539
	dw	1285
	dw	1544
	dw	1797
	dw	1544
	dw	2056
	dw	2056
	dw	1803
	dw	2570
	dw	3336
	dw	2057
	dw	2826
	dw	3082
	dw	2318
	dw	3087
	dw	2826
	dw	2830
	dw	3090
	dw	3338
	dw	2320
	dw	4109
	dw	6157
	dw	2315
	dw	4622
	dw	3597
	dw	2579
	dw	4114
	dw	6671
	dw	3084
	dw	4625
	dw	3851
	dw	3858
	dw	5392
	dw	7436
	dw	2829
	dw	5393
	dw	5135
	dw	3093
	dw	3613
	dw	5902
	dw	3348
	dw	5652
	dw	5391
	dw	4885
	dw	3872
	dw	8975
	dw	3086
	dw	4890
	dw	5903
	dw	3608
	dw	6166
	dw	4881
	dw	4122
	dw	4131
	dw	5903
	dw	5144
	dw	4390
	dw	6670
	dw	3865
	dw	6170
	dw	5395
	dw	4636
	dw	4900
	dw	8209
	dw	4630
	dw	7190
	dw	6422
	dw	5658
	dw	6940
	dw	5649
	dw	4127
	dw	6684
	dw	6933
	dw	7449
	dw	5415
	dw	6673
	dw	4382
	dw	7959
	dw	6163
	dw	5663
	dw	7454
	dw	7187
	dw	7196
	dw	7452
	dw	10007
	dw	4377
	dw	7457
	dw	6676
	dw	6432
	dw	8729
	dw	7956
	dw	4384
	dw	7711
	dw	8471
	dw	5408
	dw	7714
	dw	6680
	dw	6179
	dw	8480
	dw	7960
	dw	8478
	dw	9500
	dw	9238
	dw	5409
	dw	8228
	dw	7706
	dw	7203
	dw	9756
	dw	8473
	dw	8481
	dw	9504
	dw	7706
	dw	5416
	dw	9757
	dw	9500
	dw	6179
	dw	8486
	dw	9757
	dw	5412
	dw	9505
	dw	8477
	dw	6184
	dw	9255
	dw	9243
	dw	7717
	dw	10274
	dw	10011
	dw	6182
	dw	9509
	dw	9505
	dw	7208
	dw	11040
	dw	8733
	dw	6443
	dw	10530
	dw	10271
	dw	6951
	dw	9768
	dw	8994
	dw	7211
	dw	10534
	dw	9506
	dw	6701
	dw	11299
	dw	10529
	dw	8489
	dw	10542
	dw	9751
	dw	7469
	dw	10795
	dw	10524
	dw	7724
	dw	11813
	dw	11043
	dw	9258
	dw	12072
	dw	10779
	dw	8493
	dw	12328
	dw	10270
	dw	9007
	dw	11308
	dw	10535
	dw	9266
	dw	11568
	dw	11305
	dw	7732
	dw	12842
	dw	12328
	dw	9519
	dw	13611
	dw	11815
	dw	8246
	dw	13871
	dw	11811
	dw	10550
	dw	12852
	dw	12587
	dw	9017
	dw	14385
	dw	12585
	dw	11833
	dw	14899
	dw	13099
	dw	11836
	dw	15670
	dw	14384
	dw	12863
	dw	0
	dw	2560
	dw	2571
	dw	3595
	dw	3595
	dw	3346
	dw	4623
	dw	4367
	dw	3861
	dw	5652
	dw	5903
	dw	5144
	dw	8218
	dw	7705
	dw	7203
	dw	10273
	dw	8728
	dw	6952
	dw	10530
	dw	9503
	dw	6701
	dw	11558
	dw	10269
	dw	7728
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


sc40_walk_grid	dd 0 dup (0)

sc40_fast_list	dw	12+disk_14
	dw	51+disk_14
	dw	52+disk_14
	dw	53+disk_14
	dw	54+disk_14
	dw	135+disk_14
	dw	0


sc40_chip_list	dw	it_sc40_layer_0+disk_14
	dw	it_sc40_layer_1+disk_14
	dw	it_sc40_layer_2+disk_14
	dw	it_sc40_grid_1+disk_14
	dw	it_sc40_grid_2+disk_14
	dw	it_sc40_locker+disk_14
	dw	it_sc40_open_door+disk_14
	dw	it_sc40_close_door+disk_14
	dw	25+disk_14
	dw	26+disk_14
	dw	0


sc40_logic_list	dw	id_foster
	dw	id_danielle
	dw	id_spunky
	dw	id_sc40_locker_1
	dw	id_sc40_locker_2
	dw	id_sc40_locker_3
	dw	id_sc40_locker_4
	dw	id_sc40_locker_5
	dw	$ffff
	dw	id_std_menu_logic


sc40_mouse_list	dw	id_sc40_cabinet
	dw	id_sc40_trolley
	dw	id_sc40_locker_1
	dw	id_sc40_locker_2
	dw	id_sc40_locker_3
	dw	id_sc40_locker_4
	dw	id_sc40_locker_5
	dw	id_sc40_body_1
	dw	id_sc40_body_2
	dw	id_sc40_body_3
	dw	id_sc40_body_4
	dw	id_sc40_body_5
	dw	id_sc40_exit_39
	dw	id_sc40_floor
	dw	$ffff
	dw	id_text_mouse


reset_39_40	dw	c_screen
	dw	40
	dw	c_place
	dw	id_sc40_floor
	dw	c_xcood
	dw	197
	dw	c_ycood
	dw	196
	dw	c_frame
	dw	s25
	dw	c_dir
	dw	right
	dw	-1


sc40_descend	dw	s25
	dw	197
	dw	196
	dw	0
	dw	197
	dw	199
	dw	1
	dw	200
	dw	200
	dw	2
	dw	203
	dw	201
	dw	3
	dw	203
	dw	202
	dw	4
	dw	203
	dw	206
	dw	5
	dw	207
	dw	207
	dw	6
	dw	209
	dw	208
	dw	7
	dw	209
	dw	209
	dw	0
	dw	209
	dw	212
	dw	1
	dw	212
	dw	213
	dw	2
	dw	215
	dw	214
	dw	3
	dw	215
	dw	215
	dw	8
	dw	215
	dw	218
	dw	9
	dw	219
	dw	219
	dw	10
	dw	221
	dw	219
	dw	11
	dw	221
	dw	218
	dw	12
	dw	222
	dw	218
	dw	13
	dw	226
	dw	218
	dw	14
	dw	0


sc40_ascend	dw	s26
	dw	217
	dw	218
	dw	0
	dw	214
	dw	218
	dw	1
	dw	212
	dw	218
	dw	2
	dw	212
	dw	216
	dw	3
	dw	211
	dw	214
	dw	4
	dw	208
	dw	214
	dw	5
	dw	206
	dw	214
	dw	6
	dw	204
	dw	214
	dw	7
	dw	204
	dw	211
	dw	8
	dw	203
	dw	209
	dw	9
	dw	200
	dw	208
	dw	10
	dw	198
	dw	208
	dw	11
	dw	198
	dw	207
	dw	12
	dw	198
	dw	204
	dw	13
	dw	198
	dw	202
	dw	14
	dw	195
	dw	201
	dw	15
	dw	193
	dw	201
	dw	16
	dw	193
	dw	199
	dw	17
	dw	0


sc40_locker_open	dw	s14
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


sc40_locker_shut	dw	s14
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc40_open_door	dw	s15
	dw	240
	dw	208
	dw	0
	dw	240
	dw	208
	dw	0
	dw	240
	dw	208
	dw	0
	dw	240
	dw	208
	dw	0
	dw	240
	dw	208
	dw	1
	dw	240
	dw	208
	dw	1
	dw	240
	dw	208
	dw	2
	dw	240
	dw	208
	dw	2
	dw	240
	dw	208
	dw	3
	dw	240
	dw	208
	dw	3
	dw	0


sc40_close_door	dw	s16
	dw	232
	dw	208
	dw	0
	dw	232
	dw	208
	dw	0
	dw	232
	dw	208
	dw	1
	dw	232
	dw	208
	dw	1
	dw	232
	dw	208
	dw	2
	dw	232
	dw	208
	dw	2
	dw	232
	dw	208
	dw	3
	dw	232
	dw	208
	dw	3
	dw	232
	dw	208
	dw	3
	dw	232
	dw	208
	dw	3
	dw	0



end32data

start32save_data



sc40_floor	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	sc40_floor_table
	dw	168
	dw	256
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	415-168
	dw	327-256
	dw	floor_action



end32save_data

start32data



sc40_floor_table	dw	id_sc40_floor
	dw	return_ok
	dw	id_sc40_exit_39
	dw	GT_sc40_exit_39
	dw	id_sc40_cabinet
	dw	GT_sc40_cabinet
	dw	id_sc40_trolley
	dw	GT_sc40_trolley
	dw	id_sc40_locker_1
	dw	GT_sc40_locker_1
	dw	id_sc40_locker_2
	dw	GT_sc40_locker_2
	dw	id_sc40_locker_3
	dw	GT_sc40_locker_3
	dw	id_sc40_locker_4
	dw	GT_sc40_locker_4
	dw	id_sc40_locker_5
	dw	GT_sc40_locker_5
	dw	id_sc40_body_1
	dw	GT_sc40_body_1
	dw	id_sc40_body_2
	dw	GT_sc40_body_2
	dw	id_sc40_body_3
	dw	GT_sc40_body_3
	dw	id_sc40_body_4
	dw	GT_sc40_body_4
	dw	id_sc40_body_5
	dw	GT_sc40_body_5
	dw	-1



end32data

start32save_data



sc40_exit_39	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	211
	dw	214
	dw	NULL
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	222-211
	dw	268-214
	dw	sc40_exit_39_action


sc40_cabinet	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	336
	dw	280
	dw	NULL
	dw	16682
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	357-336
	dw	312-280
	dw	sc40_cabinet_action


sc40_trolley	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	264
	dw	264
	dw	NULL
	dw	16683
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	336-264
	dw	280-264
	dw	sc40_trolley_action


sc40_locker_1	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	231
	dw	208
	dw	s14
	dw	16681
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	0
	dw	20
	dw	251-208
	dw	sc40_locker_1_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc40_locker_1_logic
	dw	0


sc40_locker_2	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	256
	dw	208
	dw	s14
	dw	16681
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	0
	dw	20
	dw	251-208
	dw	sc40_locker_2_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc40_locker_2_logic
	dw	0


sc40_locker_3	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	281
	dw	208
	dw	s14
	dw	16681
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	0
	dw	20
	dw	251-208
	dw	sc40_locker_3_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc40_locker_3_logic
	dw	0


sc40_locker_4	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	306
	dw	208
	dw	s14
	dw	16681
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	0
	dw	20
	dw	251-208
	dw	sc40_locker_4_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc40_locker_4_logic
	dw	0


sc40_locker_5	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	331
	dw	208
	dw	s14
	dw	16681
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	5
	dw	0
	dw	20
	dw	251-208
	dw	sc40_locker_5_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc40_locker_5_logic
	dw	0


sc40_body_1	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	236
	dw	208
	dw	NULL
	dw	16689
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	250-236
	dw	245-208
	dw	sc40_body_1_action


sc40_body_2	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	263
	dw	222
	dw	NULL
	dw	16689
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	280-263
	dw	248-222
	dw	sc40_body_2_action


sc40_body_3	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	286
	dw	220
	dw	NULL
	dw	16689
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	305-286
	dw	249-220
	dw	sc40_body_3_action


sc40_body_4	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	311
	dw	219
	dw	NULL
	dw	16689
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	328-311
	dw	249-219
	dw	sc40_body_4_action


sc40_body_5	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	40
	dw	NULL
	dd	NULL
	dw	342
	dw	240
	dw	NULL
	dw	16950
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	353-342
	dw	249-240
	dw	sc40_body_5_action



end32save_data

start32data



end32data
