start32data



sc71_palette	dw	0
	dw	512
	dw	514
	dw	1285
	dw	2053
	dw	2056
	dw	2315
	dw	2570
	dw	3082
	dw	3083
	dw	3342
	dw	3084
	dw	3085
	dw	3854
	dw	3596
	dw	3596
	dw	3342
	dw	4109
	dw	3599
	dw	3856
	dw	4623
	dw	3858
	dw	4113
	dw	4113
	dw	4113
	dw	3859
	dw	4882
	dw	4369
	dw	4629
	dw	4626
	dw	5137
	dw	7700
	dw	3085
	dw	5396
	dw	5142
	dw	5141
	dw	4132
	dw	10766
	dw	4371
	dw	5396
	dw	5656
	dw	5654
	dw	5910
	dw	6936
	dw	5398
	dw	6166
	dw	6170
	dw	6168
	dw	6168
	dw	5659
	dw	6426
	dw	6682
	dw	6162
	dw	6939
	dw	7197
	dw	6928
	dw	6682
	dw	6682
	dw	7197
	dw	5916
	dw	7448
	dw	6686
	dw	7197
	dw	7965
	dw	6929
	dw	7964
	dw	7712
	dw	7440
	dw	5919
	dw	7453
	dw	8221
	dw	4640
	dw	7708
	dw	7969
	dw	7965
	dw	8221
	dw	7967
	dw	7455
	dw	8482
	dw	7444
	dw	8737
	dw	7968
	dw	8225
	dw	6435
	dw	8741
	dw	8211
	dw	8993
	dw	8479
	dw	7718
	dw	9251
	dw	8996
	dw	8730
	dw	8482
	dw	9255
	dw	8465
	dw	9763
	dw	8739
	dw	7972
	dw	10021
	dw	9505
	dw	10793
	dw	4391
	dw	9507
	dw	9764
	dw	9252
	dw	9507
	dw	10023
	dw	6185
	dw	9766
	dw	9254
	dw	10790
	dw	10276
	dw	11047
	dw	4906
	dw	10282
	dw	9757
	dw	8489
	dw	10278
	dw	9257
	dw	10538
	dw	10029
	dw	10274
	dw	11048
	dw	11056
	dw	9746
	dw	11050
	dw	11566
	dw	9750
	dw	11819
	dw	11566
	dw	10522
	dw	11562
	dw	10795
	dw	13099
	dw	4653
	dw	11053
	dw	10792
	dw	9518
	dw	11560
	dw	11054
	dw	11564
	dw	12085
	dw	10770
	dw	12333
	dw	12340
	dw	12823
	dw	9517
	dw	12076
	dw	12334
	dw	11053
	dw	12335
	dw	11814
	dw	12334
	dw	12331
	dw	13617
	dw	5683
	dw	12080
	dw	12078
	dw	12848
	dw	12845
	dw	13106
	dw	10290
	dw	12848
	dw	12848
	dw	5142
	dw	12847
	dw	12852
	dw	12849
	dw	14135
	dw	13853
	dw	9014
	dw	13106
	dw	12340
	dw	13876
	dw	13364
	dw	12854
	dw	13878
	dw	14135
	dw	13356
	dw	14390
	dw	13878
	dw	13878
	dw	14392
	dw	14647
	dw	14651
	dw	14649
	dw	15161
	dw	15163
	dw	15675
	dw	15677
	dw	16190
	dw	16191
	dw	0
	dw	16128
	dw	16191
	dw	14647
	dw	12347
	dw	13876
	dw	11046
	dw	8494
	dw	10533
	dw	3358
	dw	9228
	dw	3600
	dw	4906
	dw	12817
	dw	5142
	dw	6682
	dw	7442
	dw	4383
	dw	10535
	dw	13592
	dw	4655
	dw	14135
	dw	14109
	dw	11319
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	15107
	dw	9007
	dw	10554
	dw	13593
	dw	4641
	dw	5936
	dw	10508
	dw	1807
	dw	2082
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	5141
	dw	6165
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	14649
	dw	12601
	dw	13105
	dw	10537
	dw	8749
	dw	10018
	dw	7196
	dw	5665
	dw	6934
	dw	2879
	dw	13835
	dw	1542
	dw	558
	dw	9730
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


grid71	dd 0 dup (0)

sc71_joey_list	dw	184
	dw	399
	dw	272
	dw	327
	dw	1
	dw	184
	dw	215
	dw	272
	dw	279
	dw	0
	dw	328
	dw	447
	dw	280
	dw	287
	dw	0
	dw	336
	dw	447
	dw	304
	dw	311
	dw	0
	dw	0


sc71_fast_list	dw	12+disk_5
	dw	51+disk_5
	dw	52+disk_5
	dw	53+disk_5
	dw	54+disk_5
	dw	268+disk_5
	dw	0


sc71_chip_list	dw	it_sc71_layer_0+disk_5
	dw	it_sc71_layer_1+disk_5
	dw	it_sc71_layer_2+disk_5
	dw	it_sc71_grid_1+disk_5
	dw	it_sc71_grid_2+disk_5
	dw	it_medi+disk_5
	dw	it_medi_talk+disk_5
	dw	it_sc71_light1+disk_5
	dw	it_sc71_light2+disk_5
	dw	it_sc71_panel+disk_5
	dw	it_sc71_panel2+disk_5
	dw	it_sc71_charge_light+disk_5
	dw	it_sc71_screen+disk_5
	dw	it_sc71_medi_charge+disk_5
	dw	it_sc71_use_board+disk_5
	dw	0


sc710_chip_list	dw	it_sc710_layer_0+disk_5
	dw	it_sc710_layer_1+disk_5
	dw	it_sc710_layer_2+disk_5
	dw	it_sc710_grid_1+disk_5
	dw	it_sc710_grid_2+disk_5
	dw	it_medi+disk_5
	dw	it_medi_talk+disk_5
	dw	it_sc71_light1+disk_5
	dw	it_sc71_light2+disk_5
	dw	it_sc71_panel+disk_5
	dw	it_sc71_panel2+disk_5
	dw	it_sc71_charge_light+disk_5
	dw	it_sc71_screen+disk_5
	dw	it_sc71_medi_charge+disk_5
	dw	0


sc71_logic_list	dw	id_foster
	dw	id_medi
	dw	id_witness
	dw	id_sc67_door
	dw	id_sc68_door
	dw	id_sc71_light1
	dw	id_sc71_controls
	dw	id_sc71_chlite
	dw	id_sc71_monitor
	dw	id_sc71_recharger
	dw	id_sc71_panel2
	dw	id_sc72_spill
	dw	$ffff
	dw	id_std_menu_logic


sc71_mouse_list	dw	id_sc71_medi_slot
	dw	id_medi
	dw	id_sc71_recharger
	dw	id_sc71_monitor
	dw	id_sc71_controls
	dw	id_sc71_door69
	dw	id_sc71_door72
	dw	id_sc71_locked_door
	dw	id_sc71_floor
	dw	id_sc71_fake_floor
	dw	$ffff
	dw	id_text_mouse


reset_69_71	dw	c_screen
	dw	71
	dw	c_place
	dw	id_sc71_floor
	dw	c_xcood
	dw	152
	dw	c_ycood
	dw	288
	dw	-1


reset_72_71	dw	c_screen
	dw	71
	dw	c_place
	dw	id_sc71_floor
	dw	c_xcood
	dw	176
	dw	c_ycood
	dw	264
	dw	-1


sc71_panel_anim	dw	s167
	dw	272
	dw	226
	dw	0
	dw	272
	dw	226
	dw	1
	dw	272
	dw	226
	dw	2
	dw	272
	dw	226
	dw	3
	dw	272
	dw	226
	dw	4
	dw	272
	dw	226
	dw	5
	dw	272
	dw	226
	dw	6
	dw	272
	dw	226
	dw	7
	dw	272
	dw	226
	dw	8
	dw	272
	dw	226
	dw	9
	dw	272
	dw	226
	dw	10
	dw	272
	dw	226
	dw	11
	dw	0


sc71_panel2_anim	dw	s168
	dw	287
	dw	226
	dw	0
	dw	287
	dw	226
	dw	1
	dw	287
	dw	226
	dw	2
	dw	287
	dw	226
	dw	3
	dw	287
	dw	226
	dw	4
	dw	287
	dw	226
	dw	5
	dw	287
	dw	226
	dw	6
	dw	287
	dw	226
	dw	7
	dw	287
	dw	226
	dw	8
	dw	287
	dw	226
	dw	9
	dw	287
	dw	226
	dw	10
	dw	287
	dw	226
	dw	11
	dw	0


sc71_light1_anim	dw	s162
	dw	249
	dw	197
	dw	0
	dw	249
	dw	197
	dw	1
	dw	249
	dw	197
	dw	1
	dw	249
	dw	197
	dw	2
	dw	249
	dw	197
	dw	2
	dw	249
	dw	197
	dw	3
	dw	249
	dw	197
	dw	4
	dw	249
	dw	197
	dw	4
	dw	249
	dw	197
	dw	5
	dw	249
	dw	197
	dw	5
	dw	0


sc71_light2_anim	dw	s163
	dw	372
	dw	270
	dw	0
	dw	372
	dw	270
	dw	1
	dw	372
	dw	270
	dw	2
	dw	372
	dw	270
	dw	3
	dw	372
	dw	270
	dw	4
	dw	372
	dw	270
	dw	5
	dw	372
	dw	270
	dw	6
	dw	372
	dw	270
	dw	7
	dw	372
	dw	270
	dw	8
	dw	372
	dw	270
	dw	9
	dw	372
	dw	270
	dw	10
	dw	372
	dw	270
	dw	11
	dw	372
	dw	270
	dw	12
	dw	372
	dw	270
	dw	13
	dw	372
	dw	270
	dw	14
	dw	372
	dw	270
	dw	15
	dw	372
	dw	270
	dw	16
	dw	372
	dw	270
	dw	17
	dw	372
	dw	270
	dw	18
	dw	372
	dw	270
	dw	19
	dw	0


sc71_chlite_anim	dw	s165
	dw	268
	dw	197
	dw	0
	dw	268
	dw	197
	dw	0
	dw	268
	dw	197
	dw	1
	dw	268
	dw	197
	dw	1
	dw	268
	dw	197
	dw	2
	dw	268
	dw	197
	dw	2
	dw	268
	dw	197
	dw	3
	dw	268
	dw	197
	dw	3
	dw	268
	dw	197
	dw	4
	dw	268
	dw	197
	dw	4
	dw	268
	dw	197
	dw	5
	dw	268
	dw	197
	dw	5
	dw	0


sc71_mon_anim	dw	s164
	dw	372
	dw	248
	dw	0
	dw	372
	dw	248
	dw	1
	dw	372
	dw	248
	dw	2
	dw	372
	dw	248
	dw	3
	dw	372
	dw	248
	dw	4
	dw	372
	dw	248
	dw	5
	dw	0


sc71_medi_charge	dw	s166
	dw	279
	dw	196
	dw	0
	dw	279
	dw	196
	dw	1
	dw	279
	dw	196
	dw	2
	dw	279
	dw	196
	dw	3
	dw	279
	dw	196
	dw	4
	dw	279
	dw	196
	dw	5
	dw	279
	dw	196
	dw	6
	dw	279
	dw	196
	dw	7
	dw	279
	dw	196
	dw	8
	dw	279
	dw	196
	dw	9
	dw	0


sc71_medi_get_up	dw	s166
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc71_use_board	dw	s148
	dw	243
	dw	191
	dw	0
	dw	243
	dw	191
	dw	1
	dw	243
	dw	191
	dw	2
	dw	243
	dw	191
	dw	3
	dw	243
	dw	191
	dw	4
	dw	243
	dw	191
	dw	5
	dw	243
	dw	191
	dw	6
	dw	243
	dw	191
	dw	7
	dw	243
	dw	191
	dw	8
	dw	243
	dw	191
	dw	9
	dw	243
	dw	191
	dw	9
	dw	243
	dw	191
	dw	9
	dw	243
	dw	191
	dw	9
	dw	243
	dw	191
	dw	8
	dw	243
	dw	191
	dw	7
	dw	243
	dw	191
	dw	6
	dw	243
	dw	191
	dw	3
	dw	243
	dw	191
	dw	2
	dw	243
	dw	191
	dw	1
	dw	243
	dw	191
	dw	0
	dw	0



end32data

start32save_data



sc71_fake_floor	dw	NULL
	dw	0
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	128
	dw	136
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	447-128
	dw	327-136
	dw	NULL


sc71_floor	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	71
	dw	NULL
	dd	sc71_floor_table
	dw	194
	dw	256
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	395-194
	dw	327-256
	dw	floor_action



end32save_data

start32data



sc71_floor_table	dw	id_sc71_floor
	dw	return_ok
	dw	0
	dw	sc71_door69_walk_on
	dw	3
	dw	sc71_door72_walk_on
	dw	1
	dw	get_into_recharging_unit
	dw	id_sc71_door69
	dw	GT_sc71_door69
	dw	id_sc71_door72
	dw	GT_sc71_door72
	dw	id_sc71_locked_door
	dw	GT_sc71_locked_door
	dw	id_sc71_recharger
	dw	GT_sc71_recharger
	dw	id_sc71_monitor
	dw	GT_sc71_monitor
	dw	id_sc71_controls
	dw	GT_sc71_controls
	dw	id_medi
	dw	GT_recharging_medi
	dw	id_sc71_medi_slot
	dw	GT_sc71_medi_slot
	dw	id_joey_park
	dw	GT_joey_park
	dw	-1



end32data

start32save_data



sc71_door69	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	163
	dw	230
	dw	NULL
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	178-163
	dw	296-230
	dw	sc71_door69_action


sc71_door72	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	194
	dw	219
	dw	NULL
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	208-194
	dw	280-219
	dw	sc71_door72_action


sc71_locked_door	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	353
	dw	222
	dw	NULL
	dw	181
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	362-353
	dw	280-222
	dw	sc71_locked_door_action


sc71_recharger	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	272
	dw	226
	dw	s167
	dw	20549
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-4
	dw	-2
	dw	300-268
	dw	231-224
	dw	sc71_recharger_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_recharger_logic
	dw	0


sc71_panel2	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	287
	dw	226
	dw	s168
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_panel2_logic
	dw	0


sc71_monitor	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	372
	dw	248
	dw	s164
	dw	57
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-2
	dw	0
	dw	380-370
	dw	266-248
	dw	sc71_monitor_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_monitor_logic
	dw	0


sc71_controls	dw	l_script
	dw	st_mouse+st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	372
	dw	270
	dw	s163
	dw	20551
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-2
	dw	-3
	dw	380-370
	dw	283-267
	dw	sc71_controls_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_controls_logic
	dw	0


sc71_light1	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	249
	dw	197
	dw	s162
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_light1_logic
	dw	0


sc71_chlite	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	268
	dw	197
	dw	s165
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc71_chlite_logic
	dw	0


sc71_medi_slot	dw	NULL
	dw	0
	dw	NULL
	dw	71
	dw	NULL
	dd	NULL
	dw	275
	dw	242
	dw	NULL
	dw	50
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	280-275
	dw	247-242
	dw	sc71_medi_slot_action


medi	dw	l_script
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_collision+st_mouse
	dw	0
	dw	69
	dw	id_sc69_floor
	dd	0
	dw	128
	dw	280
	dw	16+s32
	dw	20527
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-7
	dw	-32
	dw	12
	dw	29
	dw	medi_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	medi_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	left
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_col_medi
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	medi_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	medi_up
	dd	medi_down
	dd	medi_left
	dd	medi_right
	dd	medi_st_up
	dd	medi_st_down
	dd	medi_st_left
	dd	medi_st_right
	dd	0
	dd	0
	dd	medi_u_to_d
	dd	medi_u_to_l
	dd	medi_u_to_r
	dd	0
	dd	medi_d_to_u
	dd	0
	dd	medi_d_to_l
	dd	medi_d_to_r
	dd	0
	dd	medi_l_to_u
	dd	medi_l_to_d
	dd	0
	dd	medi_l_to_r
	dd	0
	dd	medi_r_to_u
	dd	medi_r_to_d
	dd	medi_r_to_l
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0


medi_auto	db	64 dup (0)



end32save_data

start32data



medi_up	dw	1
	dw	0+s32
	dw	0
	dw	-1
	dw	1
	dw	1+s32
	dw	0
	dw	-1
	dw	1
	dw	2+s32
	dw	0
	dw	-1
	dw	1
	dw	3+s32
	dw	0
	dw	-1
	dw	1
	dw	4+s32
	dw	0
	dw	-1
	dw	1
	dw	5+s32
	dw	0
	dw	-1
	dw	1
	dw	6+s32
	dw	0
	dw	-1
	dw	1
	dw	7+s32
	dw	0
	dw	-1
	dw	0


medi_down	dw	1
	dw	8+s32
	dw	0
	dw	1
	dw	1
	dw	9+s32
	dw	0
	dw	1
	dw	1
	dw	10+s32
	dw	0
	dw	1
	dw	1
	dw	11+s32
	dw	0
	dw	1
	dw	1
	dw	12+s32
	dw	0
	dw	1
	dw	1
	dw	13+s32
	dw	0
	dw	1
	dw	1
	dw	14+s32
	dw	0
	dw	1
	dw	1
	dw	15+s32
	dw	0
	dw	1
	dw	0


medi_left	dw	2
	dw	16+s32
	dw	-2
	dw	0
	dw	2
	dw	17+s32
	dw	-2
	dw	0
	dw	2
	dw	18+s32
	dw	-2
	dw	0
	dw	2
	dw	19+s32
	dw	-2
	dw	0
	dw	2
	dw	20+s32
	dw	-2
	dw	0
	dw	2
	dw	21+s32
	dw	-2
	dw	0
	dw	2
	dw	22+s32
	dw	-2
	dw	0
	dw	2
	dw	23+s32
	dw	-2
	dw	0
	dw	0


medi_right	dw	2
	dw	24+s32
	dw	2
	dw	0
	dw	2
	dw	25+s32
	dw	2
	dw	0
	dw	2
	dw	26+s32
	dw	2
	dw	0
	dw	2
	dw	27+s32
	dw	2
	dw	0
	dw	2
	dw	28+s32
	dw	2
	dw	0
	dw	2
	dw	29+s32
	dw	2
	dw	0
	dw	2
	dw	30+s32
	dw	2
	dw	0
	dw	2
	dw	31+s32
	dw	2
	dw	0
	dw	0


medi_st_up	dw	s32
	dw	1
	dw	1
	dw	0
	dw	0


medi_st_down	dw	s32
	dw	1
	dw	1
	dw	8
	dw	0


medi_st_left	dw	s32
	dw	1
	dw	1
	dw	16
	dw	0


medi_st_right	dw	s32
	dw	1
	dw	1
	dw	24
	dw	0


medi_r_to_u	dw	34+s32
	dw	0


medi_r_to_d	dw	35+s32
	dw	0


medi_r_to_l	dw	34+s32
	dw	0+s32
	dw	33+s32
	dw	0


medi_u_to_d	dw	33+s32
	dw	16+s32
	dw	32+s32
	dw	0


medi_u_to_l	dw	33+s32
	dw	0


medi_u_to_r	dw	34+s32
	dw	0


medi_d_to_u	dw	35+s32
	dw	24+s32
	dw	34+s32
	dw	0


medi_d_to_l	dw	32+s32
	dw	0


medi_d_to_r	dw	35+s32
	dw	0


medi_l_to_u	dw	33+s32
	dw	0


medi_l_to_d	dw	32+s32
	dw	0


medi_l_to_r	dw	32+s32
	dw	8+s32
	dw	35+s32
	dw	0



end32data

start32save_data



end32save_data
