start32data



sc72_palette	dw	0
	dw	1024
	dw	1028
	dw	1286
	dw	1285
	dw	1799
	dw	1543
	dw	2056
	dw	1800
	dw	2311
	dw	2569
	dw	2057
	dw	2569
	dw	3594
	dw	2056
	dw	2827
	dw	3337
	dw	3083
	dw	3339
	dw	4108
	dw	2830
	dw	3598
	dw	3086
	dw	3345
	dw	3347
	dw	3341
	dw	4625
	dw	3857
	dw	3856
	dw	3858
	dw	3861
	dw	4368
	dw	4881
	dw	4627
	dw	4111
	dw	4373
	dw	4375
	dw	5138
	dw	4628
	dw	5138
	dw	3349
	dw	4889
	dw	5650
	dw	6168
	dw	4629
	dw	4890
	dw	5140
	dw	5656
	dw	5401
	dw	4119
	dw	5915
	dw	5660
	dw	5651
	dw	6680
	dw	5408
	dw	6931
	dw	5656
	dw	6932
	dw	5916
	dw	5914
	dw	5918
	dw	4376
	dw	7710
	dw	8210
	dw	6682
	dw	5916
	dw	5921
	dw	5398
	dw	6686
	dw	6940
	dw	5914
	dw	7709
	dw	5924
	dw	4888
	dw	8225
	dw	8212
	dw	4644
	dw	7203
	dw	7961
	dw	8732
	dw	6171
	dw	8215
	dw	9248
	dw	6938
	dw	7709
	dw	9756
	dw	6170
	dw	9493
	dw	7965
	dw	6688
	dw	7458
	dw	5407
	dw	9763
	dw	8729
	dw	7715
	dw	7969
	dw	6953
	dw	10010
	dw	6686
	dw	10006
	dw	6432
	dw	10020
	dw	8733
	dw	8484
	dw	7202
	dw	9500
	dw	6432
	dw	8742
	dw	7721
	dw	6173
	dw	7721
	dw	7974
	dw	8991
	dw	7205
	dw	8236
	dw	7198
	dw	7211
	dw	8744
	dw	7204
	dw	11049
	dw	10783
	dw	9504
	dw	8486
	dw	11036
	dw	7971
	dw	9769
	dw	11548
	dw	11815
	dw	7972
	dw	9258
	dw	7719
	dw	10539
	dw	12317
	dw	10017
	dw	9768
	dw	9772
	dw	7716
	dw	7730
	dw	12066
	dw	8739
	dw	11309
	dw	11304
	dw	8232
	dw	11823
	dw	10032
	dw	9256
	dw	12077
	dw	12324
	dw	8743
	dw	8244
	dw	12583
	dw	9253
	dw	9012
	dw	12326
	dw	13101
	dw	11048
	dw	11309
	dw	9772
	dw	10802
	dw	12076
	dw	9768
	dw	9271
	dw	12839
	dw	10290
	dw	10038
	dw	13608
	dw	12080
	dw	11569
	dw	13865
	dw	10796
	dw	13108
	dw	13613
	dw	11313
	dw	11064
	dw	13362
	dw	11565
	dw	12089
	dw	14895
	dw	13612
	dw	13109
	dw	14129
	dw	12084
	dw	12857
	dw	14387
	dw	12592
	dw	13371
	dw	14899
	dw	13623
	dw	14653
	dw	15417
	dw	15161
	dw	15423
	dw	3082
	dw	4362
	dw	3344
	dw	63
	dw	0
	dw	47
	dw	16191
	dw	10520
	dw	3881
	dw	4883
	dw	8198
	dw	2848
	dw	9
	dw	2816
	dw	0
	dw	13
	dw	3840
	dw	0
	dw	20
	dw	6400
	dw	0
	dw	40
	dw	14080
	dw	0
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	5141
	dw	3854
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	14649
	dw	12601
	dw	13105
	dw	10537
	dw	8749
	dw	10018
	dw	7196
	dw	5665
	dw	6934
	dw	2879
	dw	13835
	dw	1542
	dw	558
	dw	9730
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	7743
	dw	6166
	dw	5662
	dw	7704
	dw	6166
	dw	5662
	dw	13848
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


grid72	dd 0 dup (0)

sc72_joey_list	dw	152
	dw	343
	dw	272
	dw	319
	dw	1
	dw	288
	dw	343
	dw	296
	dw	303
	dw	0
	dw	184
	dw	231
	dw	272
	dw	295
	dw	0
	dw	0


sc72_fast_list	dw	12+disk_7
	dw	51+disk_7
	dw	52+disk_7
	dw	53+disk_7
	dw	54+disk_7
	dw	it_sc72_tank+disk_7
	dw	it_sc72_rot_light+disk_7
	dw	268+disk_7
	dw	0


sc72_chip_list	dw	it_sc72_layer_0+disk_7
	dw	it_sc72_layer_1+disk_7
	dw	it_sc72_layer_2+disk_7
	dw	it_sc72_grid_1+disk_7
	dw	it_sc72_grid_2+disk_7
	dw	it_medi+disk_7
	dw	it_medi_talk+disk_7
	dw	it_witness+disk_7+$8000
	dw	it_walter_talk_up+disk_7
	dw	it_walter_talk_down+disk_7
	dw	it_walter_talk_left+disk_7
	dw	it_walter_conversation+disk_7+$8000
	dw	133+disk_7
	dw	it_sc72_walter_kill+disk_7
	dw	it_sc72_cham1_light+disk_7
	dw	it_sc72_cham2_light+disk_7
	dw	it_sc72_computer+disk_7
	dw	it_sc72_computer2+disk_7
	dw	it_sc72_chamber1+disk_7
	dw	it_sc72_chamber2+disk_7
	dw	it_sc72_chamber3+disk_7
	dw	it_sc72_grill+disk_7
	dw	it_sc72_joey_tap+disk_7
	dw	it_sc72_spill+disk_7
	dw	0


sc720_chip_list	dw	it_sc720_layer_0+disk_7
	dw	it_sc720_layer_1+disk_7
	dw	it_sc720_layer_2+disk_7
	dw	it_sc720_grid_1+disk_7
	dw	it_sc720_grid_2+disk_7
	dw	it_medi+disk_7
	dw	it_medi_talk+disk_7
	dw	it_witness+disk_7+$8000
	dw	it_walter_talk_up+disk_7
	dw	it_walter_talk_down+disk_7
	dw	it_walter_talk_left+disk_7
	dw	it_sc72_cham1_light+disk_7
	dw	it_sc72_cham2_light+disk_7
	dw	it_sc72_computer+disk_7
	dw	it_sc72_computer2+disk_7
	dw	it_sc72_chamber1+disk_7
	dw	it_sc72_chamber2+disk_7
	dw	it_sc72_chamber3+disk_7
	dw	it_sc72_grill+disk_7
	dw	it_sc72_joey_tap+disk_7
	dw	it_sc72_spill+disk_7
	dw	0


sc72_logic_list	dw	id_foster
	dw	id_medi
	dw	id_witness
	dw	id_ken
	dw	id_sc67_door
	dw	id_sc68_door
	dw	id_sc72_chamber1
	dw	id_sc72_cham1_light
	dw	id_sc72_chamber2
	dw	id_sc72_cham2_light
	dw	id_sc72_chamber3
	dw	id_sc72_tank
	dw	id_sc72_rot_light
	dw	id_sc72_computer
	dw	id_sc72_computer2
	dw	id_sc72_spill
	dw	id_sc72_grill
	dw	id_sc75_tongs
	dw	$ffff
	dw	id_std_menu_logic


sc72_mouse_list	dw	id_medi
	dw	id_sc72_tap
	dw	id_sc72_spill
	dw	id_sc72_tank
	dw	id_sc72_grill
	dw	id_witness
	dw	id_sc72_computer
	dw	id_sc72_chamber1
	dw	id_sc72_chamber2
	dw	id_sc72_door
	dw	id_sc72_exit
	dw	id_sc72_floor
	dw	id_sc72_fake_floor
	dw	$ffff
	dw	id_text_mouse


reset_71_72	dw	c_screen
	dw	72
	dw	c_place
	dw	id_sc72_floor
	dw	c_xcood
	dw	400
	dw	c_ycood
	dw	296
	dw	-1


reset_73_72	dw	c_screen
	dw	72
	dw	c_place
	dw	id_sc72_floor
	dw	c_xcood
	dw	368
	dw	c_ycood
	dw	272
	dw	-1


sc72_cham1_anim	dw	s174
	dw	221
	dw	190
	dw	0
	dw	221
	dw	190
	dw	1
	dw	221
	dw	190
	dw	2
	dw	221
	dw	190
	dw	3
	dw	221
	dw	190
	dw	4
	dw	221
	dw	190
	dw	5
	dw	221
	dw	190
	dw	6
	dw	221
	dw	190
	dw	7
	dw	221
	dw	190
	dw	8
	dw	221
	dw	190
	dw	9
	dw	221
	dw	190
	dw	10
	dw	221
	dw	190
	dw	11
	dw	221
	dw	190
	dw	12
	dw	221
	dw	190
	dw	13
	dw	221
	dw	190
	dw	14
	dw	221
	dw	190
	dw	15
	dw	221
	dw	190
	dw	16
	dw	221
	dw	190
	dw	17
	dw	221
	dw	190
	dw	18
	dw	221
	dw	190
	dw	19
	dw	0


sc72_cham1_flash	dw	s171
	dw	232
	dw	244
	dw	0
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	232
	dw	244
	dw	1
	dw	0


sc72_cham2_anim	dw	s175
	dw	280
	dw	190
	dw	0
	dw	280
	dw	190
	dw	1
	dw	280
	dw	190
	dw	2
	dw	280
	dw	190
	dw	3
	dw	280
	dw	190
	dw	4
	dw	280
	dw	190
	dw	5
	dw	280
	dw	190
	dw	6
	dw	280
	dw	190
	dw	7
	dw	280
	dw	190
	dw	8
	dw	280
	dw	190
	dw	9
	dw	280
	dw	190
	dw	10
	dw	280
	dw	190
	dw	11
	dw	280
	dw	190
	dw	12
	dw	280
	dw	190
	dw	13
	dw	280
	dw	190
	dw	14
	dw	280
	dw	190
	dw	15
	dw	280
	dw	190
	dw	16
	dw	280
	dw	190
	dw	17
	dw	280
	dw	190
	dw	18
	dw	280
	dw	190
	dw	19
	dw	0


sc72_cham2_flash	dw	s172
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	1
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	293
	dw	244
	dw	0
	dw	0


sc72_cham3_anim	dw	s176
	dw	344
	dw	191
	dw	0
	dw	344
	dw	191
	dw	1
	dw	344
	dw	191
	dw	2
	dw	344
	dw	191
	dw	3
	dw	344
	dw	191
	dw	4
	dw	344
	dw	191
	dw	5
	dw	344
	dw	191
	dw	6
	dw	344
	dw	191
	dw	7
	dw	344
	dw	191
	dw	8
	dw	344
	dw	191
	dw	9
	dw	344
	dw	191
	dw	10
	dw	344
	dw	191
	dw	11
	dw	344
	dw	191
	dw	12
	dw	344
	dw	191
	dw	13
	dw	344
	dw	191
	dw	14
	dw	344
	dw	191
	dw	15
	dw	344
	dw	191
	dw	16
	dw	344
	dw	191
	dw	17
	dw	344
	dw	191
	dw	18
	dw	344
	dw	191
	dw	19
	dw	0


sc72_tank_anim	dw	s173
	dw	278
	dw	255
	dw	0
	dw	278
	dw	255
	dw	1
	dw	278
	dw	255
	dw	2
	dw	278
	dw	255
	dw	3
	dw	278
	dw	255
	dw	4
	dw	278
	dw	255
	dw	5
	dw	278
	dw	255
	dw	6
	dw	278
	dw	255
	dw	7
	dw	278
	dw	255
	dw	8
	dw	278
	dw	255
	dw	9
	dw	278
	dw	255
	dw	10
	dw	278
	dw	255
	dw	11
	dw	278
	dw	255
	dw	12
	dw	278
	dw	255
	dw	13
	dw	278
	dw	255
	dw	14
	dw	278
	dw	255
	dw	15
	dw	278
	dw	255
	dw	16
	dw	278
	dw	255
	dw	17
	dw	278
	dw	255
	dw	18
	dw	278
	dw	255
	dw	19
	dw	0


sc72_comp_flash	dw	s169
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	1
	dw	169
	dw	225
	dw	2
	dw	169
	dw	225
	dw	3
	dw	169
	dw	225
	dw	4
	dw	169
	dw	225
	dw	5
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	169
	dw	225
	dw	0
	dw	0


sc72_comp2_flash	dw	s170
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	1
	dw	178
	dw	222
	dw	2
	dw	178
	dw	222
	dw	3
	dw	178
	dw	222
	dw	4
	dw	178
	dw	222
	dw	5
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	178
	dw	222
	dw	0
	dw	0


sc72_rotating	dw	s177
	dw	145
	dw	283
	dw	0
	dw	145
	dw	283
	dw	1
	dw	145
	dw	283
	dw	2
	dw	145
	dw	283
	dw	3
	dw	145
	dw	283
	dw	4
	dw	145
	dw	283
	dw	5
	dw	145
	dw	283
	dw	6
	dw	145
	dw	283
	dw	7
	dw	145
	dw	283
	dw	8
	dw	145
	dw	283
	dw	8
	dw	145
	dw	283
	dw	8
	dw	145
	dw	283
	dw	9
	dw	145
	dw	283
	dw	10
	dw	145
	dw	283
	dw	11
	dw	0


sc72_walter_kill	dw	s178
	dw	320
	dw	253
	dw	0
	dw	320
	dw	253
	dw	1
	dw	320
	dw	253
	dw	2
	dw	321
	dw	253
	dw	3
	dw	319
	dw	253
	dw	4
	dw	317
	dw	254
	dw	5
	dw	321
	dw	253
	dw	6
	dw	322
	dw	252
	dw	7
	dw	322
	dw	252
	dw	8
	dw	324
	dw	252
	dw	9
	dw	326
	dw	252
	dw	10
	dw	327
	dw	252
	dw	11
	dw	328
	dw	252
	dw	12
	dw	329
	dw	252
	dw	13
	dw	330
	dw	252
	dw	14
	dw	331
	dw	252
	dw	15
	dw	332
	dw	252
	dw	16
	dw	334
	dw	252
	dw	17
	dw	336
	dw	252
	dw	18
	dw	337
	dw	252
	dw	19
	dw	337
	dw	252
	dw	20
	dw	337
	dw	252
	dw	20
	dw	337
	dw	252
	dw	21
	dw	337
	dw	252
	dw	22
	dw	337
	dw	252
	dw	23
	dw	337
	dw	252
	dw	24
	dw	337
	dw	252
	dw	25
	dw	337
	dw	252
	dw	26
	dw	337
	dw	252
	dw	27
	dw	335
	dw	252
	dw	28
	dw	332
	dw	252
	dw	29
	dw	335
	dw	252
	dw	30
	dw	337
	dw	252
	dw	31
	dw	337
	dw	252
	dw	32
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	337
	dw	253
	dw	33
	dw	0


sc72_foster_die	dw	s179
	dw	340
	dw	250
	dw	0
	dw	340
	dw	250
	dw	0
	dw	340
	dw	250
	dw	0
	dw	340
	dw	250
	dw	0
	dw	341
	dw	249
	dw	1
	dw	340
	dw	249
	dw	2
	dw	340
	dw	248
	dw	3
	dw	339
	dw	247
	dw	4
	dw	341
	dw	246
	dw	5
	dw	345
	dw	246
	dw	6
	dw	345
	dw	246
	dw	7
	dw	346
	dw	247
	dw	8
	dw	345
	dw	247
	dw	9
	dw	342
	dw	247
	dw	10
	dw	343
	dw	246
	dw	11
	dw	342
	dw	246
	dw	12
	dw	348
	dw	246
	dw	13
	dw	350
	dw	246
	dw	14
	dw	349
	dw	246
	dw	15
	dw	350
	dw	246
	dw	16
	dw	350
	dw	247
	dw	17
	dw	348
	dw	247
	dw	18
	dw	344
	dw	247
	dw	19
	dw	344
	dw	246
	dw	20
	dw	341
	dw	246
	dw	21
	dw	350
	dw	246
	dw	22
	dw	349
	dw	246
	dw	23
	dw	350
	dw	246
	dw	24
	dw	349
	dw	248
	dw	25
	dw	351
	dw	248
	dw	26
	dw	342
	dw	249
	dw	27
	dw	349
	dw	249
	dw	28
	dw	349
	dw	248
	dw	29
	dw	348
	dw	248
	dw	30
	dw	352
	dw	249
	dw	31
	dw	353
	dw	249
	dw	32
	dw	351
	dw	249
	dw	33
	dw	352
	dw	249
	dw	34
	dw	353
	dw	249
	dw	35
	dw	354
	dw	249
	dw	36
	dw	353
	dw	249
	dw	37
	dw	353
	dw	249
	dw	38
	dw	352
	dw	249
	dw	39
	dw	353
	dw	249
	dw	38
	dw	0


sc72_walter_die	dw	s30
	dw	222
	dw	228
	dw	0
	dw	223
	dw	230
	dw	1
	dw	224
	dw	233
	dw	2
	dw	220
	dw	239
	dw	3
	dw	216
	dw	245
	dw	4
	dw	215
	dw	256
	dw	5
	dw	212
	dw	267
	dw	6
	dw	213
	dw	278
	dw	7
	dw	218
	dw	278
	dw	8
	dw	222
	dw	278
	dw	9
	dw	0


sc72_joey_tap	dw	s29
	dw	248
	dw	240
	dw	0
	dw	248
	dw	240
	dw	1
	dw	248
	dw	240
	dw	2
	dw	248
	dw	240
	dw	0
	dw	248
	dw	240
	dw	1
	dw	248
	dw	240
	dw	2
	dw	248
	dw	240
	dw	0
	dw	248
	dw	240
	dw	1
	dw	248
	dw	240
	dw	2
	dw	0


sc72_spill_anim	dw	s31
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	0


sc72_drip_anim	dw	s31
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	12
	dw	1
	dw	1
	dw	13
	dw	1
	dw	1
	dw	14
	dw	1
	dw	1
	dw	15
	dw	1
	dw	1
	dw	16
	dw	1
	dw	1
	dw	17
	dw	1
	dw	1
	dw	18
	dw	1
	dw	1
	dw	19
	dw	0



end32data

start32save_data



sc72_fake_floor	dw	NULL
	dw	0
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	128
	dw	136
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	447-128
	dw	327-136
	dw	NULL


sc72_floor	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	72
	dw	NULL
	dd	sc72_floor_table
	dw	140
	dw	260
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	374-140
	dw	327-260
	dw	floor_action



end32save_data

start32data



sc72_floor_table	dw	id_sc72_floor
	dw	return_ok
	dw	0
	dw	sc72_door_walk_on
	dw	1
	dw	sc72_exit_walk_on
	dw	3
	dw	GT_sc72_witness_talk
	dw	4
	dw	GT_sc72_foster_talk
	dw	5
	dw	GT_sc72_witness_kill
	dw	id_sc72_door
	dw	GT_sc72_door
	dw	id_sc72_exit
	dw	GT_sc72_exit
	dw	id_sc72_tank
	dw	GT_sc72_tank
	dw	id_sc72_tap
	dw	GT_sc72_tap
	dw	id_sc72_spill
	dw	GT_sc72_spill
	dw	id_sc72_grill
	dw	GT_sc72_grill
	dw	id_sc72_chamber1
	dw	GT_sc72_chamber1
	dw	id_sc72_chamber2
	dw	GT_sc72_chamber2
	dw	id_sc72_chamber3
	dw	GT_sc72_chamber3
	dw	id_sc72_light1
	dw	GT_sc72_light1
	dw	id_sc72_light2
	dw	GT_sc72_light2
	dw	id_sc72_light3
	dw	GT_sc72_light3
	dw	id_sc72_computer
	dw	GT_sc72_computer
	dw	id_joey_park
	dw	GT_joey_park
	dw	-1



end32data

start32save_data



sc72_door	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	368
	dw	227
	dw	NULL
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	387-368
	dw	306-227
	dw	sc72_door_action


sc72_exit	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	342
	dw	180
	dw	NULL
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	355-342
	dw	282-180
	dw	sc72_exit_action


sc72_tank	dw	l_script
	dw	st_mouse+st_logic+st_sort
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	278
	dw	255
	dw	s173
	dw	20568
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-1
	dw	-1
	dw	331-277
	dw	283-254
	dw	sc72_tank_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_tank_logic
	dw	0


sc72_tap	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	269
	dw	269
	dw	NULL
	dw	20567
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	278-269
	dw	278-269
	dw	sc72_tap_action


sc72_spill	dw	l_script
	dw	st_logic
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	250
	dw	279
	dw	s31
	dw	20577
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	2
	dw	277-250
	dw	295-281
	dw	sc72_spill_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_spill_logic
	dw	0


sc72_grill	dw	l_script
	dw	st_mouse+st_logic+st_background+st_recreate
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	214
	dw	282
	dw	s28
	dw	20511
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	1
	dw	-1
	dw	242-215
	dw	287-281
	dw	sc72_grill_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_grill_logic
	dw	0


sc72_chamber1	dw	l_script
	dw	st_mouse+st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	223
	dw	191
	dw	s174
	dw	20569
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-3
	dw	-2
	dw	249-220
	dw	242-189
	dw	sc72_chambers_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_chamber1_logic
	dw	0


sc72_cham1_light	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	232
	dw	244
	dw	s171
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_cham1_light_logic
	dw	0


sc72_chamber2	dw	l_script
	dw	st_mouse+st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	284
	dw	190
	dw	s175
	dw	20569
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-4
	dw	-1
	dw	309-280
	dw	242-189
	dw	sc72_chambers_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_chamber2_logic
	dw	0


sc72_cham2_light	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	293
	dw	244
	dw	s172
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_cham2_light_logic
	dw	0


sc72_chamber3	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	344
	dw	191
	dw	s176
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_chamber3_logic
	dw	0


sc72_computer	dw	l_script
	dw	st_mouse+st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	169
	dw	227
	dw	s169
	dw	20695
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-4
	dw	-6
	dw	183-165
	dw	236-221
	dw	sc72_computer_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_computer_logic
	dw	0


sc72_computer2	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	178
	dw	224
	dw	s170
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_computer2_logic
	dw	0


sc72_rot_light	dw	l_script
	dw	st_logic+st_foreground
	dw	NULL
	dw	72
	dw	NULL
	dd	NULL
	dw	145
	dw	283
	dw	s177
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc72_rot_light_logic
	dw	0


wit	dd 0 dup (0)

witness	dw	l_script
	dw	st_sort+st_recreate+st_logic+st_grid_plot+st_mouse+st_collision
	dw	0
	dw	72
	dw	id_sc72_floor
	dd	0
	dw	256
	dw	280
	dw	32+s159
	dw	4
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-8
	dw	-43
	dw	14
	dw	50
	dw	mega_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	witness_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_col_witness
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	wit_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	wit_up
	dd	wit_down
	dd	wit_left
	dd	wit_right
	dd	wit_st_up
	dd	wit_st_down
	dd	wit_st_left
	dd	wit_st_right
	dd	wit_st_talk
	dd	0
	dd	wit_u_to_d
	dd	wit_u_to_l
	dd	wit_u_to_r
	dd	wit_u_to_t
	dd	wit_d_to_u
	dd	0
	dd	wit_d_to_l
	dd	wit_d_to_r
	dd	0
	dd	wit_l_to_u
	dd	wit_l_to_d
	dd	0
	dd	wit_l_to_r
	dd	wit_l_to_t
	dd	wit_r_to_u
	dd	wit_r_to_d
	dd	wit_r_to_l
	dd	0
	dd	0
	dd	wit_t_to_u
	dd	0
	dd	wit_t_to_l
	dd	0
	dd	0


wit_auto	db	64 dup (0)



end32save_data

start32data



wit_left	dw	4
	dw	16+s159
	dw	-4
	dw	0
	dw	4
	dw	17+s159
	dw	-4
	dw	0
	dw	4
	dw	18+s159
	dw	-4
	dw	0
	dw	4
	dw	19+s159
	dw	-4
	dw	0
	dw	4
	dw	20+s159
	dw	-4
	dw	0
	dw	4
	dw	21+s159
	dw	-4
	dw	0
	dw	4
	dw	22+s159
	dw	-4
	dw	0
	dw	4
	dw	23+s159
	dw	-4
	dw	0
	dw	0


wit_right	dw	4
	dw	24+s159
	dw	4
	dw	0
	dw	4
	dw	25+s159
	dw	4
	dw	0
	dw	4
	dw	26+s159
	dw	4
	dw	0
	dw	4
	dw	27+s159
	dw	4
	dw	0
	dw	4
	dw	28+s159
	dw	4
	dw	0
	dw	4
	dw	29+s159
	dw	4
	dw	0
	dw	4
	dw	30+s159
	dw	4
	dw	0
	dw	4
	dw	31+s159
	dw	4
	dw	0
	dw	0


wit_up	dw	2
	dw	0+s159
	dw	0
	dw	-2
	dw	2
	dw	1+s159
	dw	0
	dw	-2
	dw	2
	dw	2+s159
	dw	0
	dw	-2
	dw	2
	dw	3+s159
	dw	0
	dw	-2
	dw	2
	dw	4+s159
	dw	0
	dw	-2
	dw	2
	dw	5+s159
	dw	0
	dw	-2
	dw	2
	dw	6+s159
	dw	0
	dw	-2
	dw	2
	dw	7+s159
	dw	0
	dw	-2
	dw	0


wit_down	dw	2
	dw	8+s159
	dw	0
	dw	2
	dw	2
	dw	9+s159
	dw	0
	dw	2
	dw	2
	dw	10+s159
	dw	0
	dw	2
	dw	2
	dw	11+s159
	dw	0
	dw	2
	dw	2
	dw	12+s159
	dw	0
	dw	2
	dw	2
	dw	13+s159
	dw	0
	dw	2
	dw	2
	dw	14+s159
	dw	0
	dw	2
	dw	2
	dw	15+s159
	dw	0
	dw	2
	dw	0


wit_st_up	dw	s159
	dw	1
	dw	0
	dw	36
	dw	0


wit_st_down	dw	s159
	dw	1
	dw	0
	dw	32
	dw	0


wit_st_left	dw	s159
	dw	1
	dw	0
	dw	34
	dw	0


wit_st_right	dw	s159
	dw	1
	dw	0
	dw	38
	dw	0


wit_st_talk	dw	s129
	dw	1
	dw	0
	dw	0
	dw	0


wit_u_to_d	dw	35+s159
	dw	34+s159
	dw	33+s159
	dw	0


wit_u_to_l	dw	35+s159
	dw	0


wit_u_to_r	dw	37+s159
	dw	0


wit_u_to_t	dw	37+s159
	dw	38+s159
	dw	0


wit_d_to_u	dw	39+s159
	dw	38+s159
	dw	37+s159
	dw	0


wit_d_to_l	dw	33+s159
	dw	0


wit_d_to_r	dw	39+s159
	dw	0


wit_l_to_u	dw	35+s159
	dw	0


wit_l_to_d	dw	33+s159
	dw	0


wit_l_to_r	dw	33+s159
	dw	32+s159
	dw	39+s159
	dw	0


wit_l_to_t	dw	33+s159
	dw	32+s159
	dw	0


wit_r_to_u	dw	37+s159
	dw	0


wit_r_to_d	dw	39+s159
	dw	0


wit_r_to_l	dw	37+s159
	dw	36+s159
	dw	35+s159
	dw	0


wit_t_to_u	dw	38+s159
	dw	37+s159
	dw	0


wit_t_to_l	dw	32+s159
	dw	33+s159
	dw	0



end32data

start32save_data



end32save_data
