start32data



sc76_palette	dw	0
	dw	1024
	dw	1540
	dw	1029
	dw	1540
	dw	1542
	dw	2054
	dw	2056
	dw	1799
	dw	2056
	dw	2570
	dw	2825
	dw	0
	dw	3072
	dw	3082
	dw	2826
	dw	3086
	dw	3085
	dw	3087
	dw	3084
	dw	3853
	dw	3599
	dw	3342
	dw	4623
	dw	4111
	dw	4368
	dw	4113
	dw	3859
	dw	3856
	dw	4626
	dw	4626
	dw	4116
	dw	5395
	dw	4882
	dw	4626
	dw	5140
	dw	4882
	dw	5911
	dw	4626
	dw	5141
	dw	4887
	dw	5910
	dw	5653
	dw	5653
	dw	5654
	dw	5147
	dw	5654
	dw	6167
	dw	5911
	dw	5914
	dw	6937
	dw	6679
	dw	6425
	dw	6937
	dw	6933
	dw	8478
	dw	6166
	dw	6174
	dw	7448
	dw	7449
	dw	7194
	dw	6939
	dw	7707
	dw	7197
	dw	8220
	dw	7450
	dw	7196
	dw	6689
	dw	7454
	dw	6435
	dw	7195
	dw	7966
	dw	7710
	dw	9761
	dw	7195
	dw	8474
	dw	10530
	dw	6938
	dw	8732
	dw	9248
	dw	7965
	dw	8222
	dw	7971
	dw	7969
	dw	7969
	dw	7970
	dw	8483
	dw	8737
	dw	9763
	dw	8224
	dw	7470
	dw	7452
	dw	9765
	dw	7724
	dw	8990
	dw	9506
	dw	9251
	dw	11299
	dw	8224
	dw	8238
	dw	8477
	dw	9765
	dw	9253
	dw	10789
	dw	8482
	dw	10273
	dw	11816
	dw	8226
	dw	8497
	dw	9758
	dw	9766
	dw	9003
	dw	9254
	dw	10535
	dw	10274
	dw	10027
	dw	9766
	dw	9008
	dw	11554
	dw	8997
	dw	11044
	dw	10019
	dw	10536
	dw	10536
	dw	9510
	dw	11049
	dw	9521
	dw	10788
	dw	10792
	dw	11558
	dw	12067
	dw	9511
	dw	11048
	dw	9769
	dw	11563
	dw	10033
	dw	10023
	dw	9519
	dw	10543
	dw	13096
	dw	9511
	dw	11050
	dw	10027
	dw	12077
	dw	11563
	dw	12841
	dw	10537
	dw	12585
	dw	11045
	dw	11565
	dw	11310
	dw	11565
	dw	11054
	dw	12073
	dw	11054
	dw	10033
	dw	11820
	dw	13104
	dw	11051
	dw	12331
	dw	12083
	dw	11568
	dw	13101
	dw	11559
	dw	12593
	dw	12590
	dw	12340
	dw	12082
	dw	12339
	dw	13617
	dw	12079
	dw	13360
	dw	13110
	dw	12595
	dw	13106
	dw	13364
	dw	13109
	dw	14129
	dw	13622
	dw	13623
	dw	14131
	dw	14136
	dw	14135
	dw	14649
	dw	14902
	dw	14649
	dw	15159
	dw	15161
	dw	14909
	dw	15676
	dw	15933
	dw	15935
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	13886
	dw	15149
	dw	9520
	dw	10809
	dw	13854
	dw	5924
	dw	7988
	dw	12817
	dw	2841
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	63
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	13824
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


grid76	dd 0 dup (0)

sc76_joey_list	dw	168
	dw	415
	dw	272
	dw	311
	dw	1
	dw	168
	dw	191
	dw	272
	dw	279
	dw	0
	dw	384
	dw	415
	dw	272
	dw	279
	dw	0
	dw	0


sc76_fast_list	dw	12+disk_10
	dw	51+disk_10
	dw	52+disk_10
	dw	53+disk_10
	dw	54+disk_10
	dw	268+disk_10
	dw	0


sc76_chip_list	dw	it_sc76_layer_0+disk_10
	dw	it_sc76_layer_1+disk_10
	dw	it_sc76_layer_2+disk_10
	dw	it_sc76_grid_1+disk_10
	dw	it_sc76_grid_2+disk_10
	dw	it_ken+disk_10
	dw	it_sc76_ken_talk+disk_10
	dw	it_sc76_light1+disk_10
	dw	it_sc76_light2+disk_10
	dw	it_sc76_light3+disk_10
	dw	it_sc76_light4+disk_10
	dw	it_sc76_light5+disk_10
	dw	it_sc76_light6+disk_10
	dw	it_sc76_light7+disk_10
	dw	it_sc76_light8+disk_10
	dw	it_sc76_light9+disk_10
	dw	it_sc76_cabinet_1+disk_10
	dw	it_sc76_cabinet_2+disk_10
	dw	it_sc76_cabinet_3+disk_10
	dw	it_sc76_board_1+disk_10
	dw	it_sc76_board_2+disk_10
	dw	it_sc76_board_3+disk_10
	dw	it_sc76_open_cab+disk_10
	dw	it_sc76_low_get+disk_10
	dw	it_sc76_hatch_1+disk_10
	dw	it_sc76_android_2+disk_10
	dw	it_sc76_hatch_2+disk_10+$8000
	dw	it_sc76_android_3+disk_10
	dw	it_sc76_hatch_3+disk_10+$8000
	dw	it_sc76_punch+disk_10
	dw	it_sc76_and2_babble+disk_10
	dw	0


sc76_logic_list	dw	id_foster
	dw	id_ken
	dw	id_sc76_android_1
	dw	id_sc76_android_2
	dw	id_sc76_android_3
	dw	id_sc76_light1
	dw	id_sc76_light2
	dw	id_sc76_light3
	dw	id_sc76_light4
	dw	id_sc76_light5
	dw	id_sc76_light6
	dw	id_sc76_light7
	dw	id_sc76_light8
	dw	id_sc76_light9
	dw	id_sc76_board_1
	dw	id_sc76_board_2
	dw	id_sc76_board_3
	dw	id_sc76_cabinet_1
	dw	id_sc76_cabinet_2
	dw	id_sc76_cabinet_3
	dw	id_sc75_tongs
	dw	$ffff
	dw	id_std_menu_logic


sc76_mouse_list	dw	id_ken
	dw	id_sc76_android_1
	dw	id_sc76_android_2
	dw	id_sc76_android_3
	dw	id_sc76_console_1
	dw	id_sc76_console_2
	dw	id_sc76_console_3
	dw	id_sc76_board_1
	dw	id_sc76_board_2
	dw	id_sc76_board_3
	dw	id_sc76_cabinet_1
	dw	id_sc76_cabinet_2
	dw	id_sc76_cabinet_3
	dw	id_sc76_door75
	dw	id_sc76_door77
	dw	id_sc76_floor
	dw	$ffff
	dw	id_text_mouse


reset_75_76	dw	c_screen
	dw	76
	dw	c_place
	dw	id_sc76_floor
	dw	c_xcood
	dw	160
	dw	c_ycood
	dw	264
	dw	-1


reset_77_76	dw	c_screen
	dw	76
	dw	c_place
	dw	id_sc76_floor
	dw	c_xcood
	dw	408
	dw	c_ycood
	dw	272
	dw	-1


sc76_light1_anim	dw	s29
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	0
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	228
	dw	182
	dw	1
	dw	0


sc76_light2_anim	dw	s30
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	1
	dw	232
	dw	182
	dw	2
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	232
	dw	182
	dw	0
	dw	0


sc76_light3_anim	dw	s31
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	1
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	0
	dw	278
	dw	182
	dw	0
	dw	0


sc76_light4_anim	dw	s32
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	0
	dw	282
	dw	182
	dw	1
	dw	282
	dw	182
	dw	2
	dw	282
	dw	182
	dw	0
	dw	0


sc76_light5_anim	dw	s43
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	0
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	1
	dw	323
	dw	182
	dw	0
	dw	0


sc76_light6_anim	dw	s44
	dw	327
	dw	182
	dw	0
	dw	327
	dw	182
	dw	1
	dw	327
	dw	182
	dw	2
	dw	327
	dw	182
	dw	2
	dw	327
	dw	182
	dw	2
	dw	327
	dw	182
	dw	2
	dw	0


sc76_light7_anim	dw	s45
	dw	247
	dw	239
	dw	0
	dw	247
	dw	239
	dw	1
	dw	247
	dw	239
	dw	2
	dw	247
	dw	239
	dw	3
	dw	247
	dw	239
	dw	4
	dw	247
	dw	239
	dw	5
	dw	247
	dw	239
	dw	6
	dw	247
	dw	239
	dw	7
	dw	247
	dw	239
	dw	8
	dw	247
	dw	239
	dw	9
	dw	247
	dw	239
	dw	9
	dw	247
	dw	239
	dw	9
	dw	247
	dw	239
	dw	9
	dw	0


sc76_light8_anim	dw	s46
	dw	304
	dw	239
	dw	0
	dw	304
	dw	239
	dw	0
	dw	304
	dw	239
	dw	1
	dw	304
	dw	239
	dw	1
	dw	304
	dw	239
	dw	2
	dw	304
	dw	239
	dw	3
	dw	304
	dw	239
	dw	4
	dw	304
	dw	239
	dw	5
	dw	304
	dw	239
	dw	6
	dw	304
	dw	239
	dw	7
	dw	304
	dw	239
	dw	8
	dw	304
	dw	239
	dw	9
	dw	304
	dw	239
	dw	10
	dw	304
	dw	239
	dw	11
	dw	0


sc76_light9_anim	dw	s47
	dw	357
	dw	239
	dw	0
	dw	357
	dw	239
	dw	1
	dw	357
	dw	239
	dw	2
	dw	357
	dw	239
	dw	3
	dw	357
	dw	239
	dw	4
	dw	357
	dw	239
	dw	5
	dw	357
	dw	239
	dw	6
	dw	357
	dw	239
	dw	7
	dw	357
	dw	239
	dw	8
	dw	357
	dw	239
	dw	9
	dw	357
	dw	239
	dw	10
	dw	357
	dw	239
	dw	10
	dw	0


sc76_cab1_open	dw	s55
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


sc76_cab1_close	dw	s55
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_cab2_open	dw	s56
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


sc76_cab2_close	dw	s56
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_cab3_open	dw	s57
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	0


sc76_cab3_close	dw	s57
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_low_get	dw	s63
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_open_cab	dw	s63
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	0+s62
	dw	1
	dw	1
	dw	1+s62
	dw	1
	dw	1
	dw	2+s62
	dw	1
	dw	1
	dw	2+s62
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_shut_cab	dw	s63
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	0+s62
	dw	1
	dw	1
	dw	2+s62
	dw	1
	dw	1
	dw	1+s62
	dw	1
	dw	1
	dw	0+s62
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


sc76_hatch_1	dw	s66
	dw	224
	dw	204
	dw	0
	dw	224
	dw	204
	dw	0
	dw	224
	dw	204
	dw	1
	dw	224
	dw	204
	dw	1
	dw	224
	dw	204
	dw	2
	dw	224
	dw	204
	dw	2
	dw	224
	dw	204
	dw	3
	dw	224
	dw	204
	dw	3
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	4
	dw	224
	dw	204
	dw	3
	dw	224
	dw	204
	dw	3
	dw	224
	dw	204
	dw	2
	dw	224
	dw	204
	dw	2
	dw	224
	dw	204
	dw	1
	dw	224
	dw	204
	dw	1
	dw	224
	dw	204
	dw	0
	dw	224
	dw	204
	dw	0
	dw	0


sc76_hatch_2	dw	s68
	dw	271
	dw	204
	dw	0
	dw	271
	dw	204
	dw	0
	dw	266
	dw	204
	dw	1
	dw	266
	dw	204
	dw	1
	dw	263
	dw	204
	dw	2
	dw	263
	dw	204
	dw	2
	dw	263
	dw	212
	dw	3
	dw	263
	dw	212
	dw	3
	dw	263
	dw	216
	dw	4
	dw	263
	dw	216
	dw	4
	dw	262
	dw	219
	dw	5
	dw	262
	dw	219
	dw	5
	dw	256
	dw	222
	dw	6
	dw	256
	dw	222
	dw	6
	dw	251
	dw	224
	dw	7
	dw	251
	dw	224
	dw	7
	dw	248
	dw	224
	dw	8
	dw	248
	dw	224
	dw	8
	dw	247
	dw	226
	dw	9
	dw	247
	dw	226
	dw	9
	dw	247
	dw	228
	dw	10
	dw	247
	dw	228
	dw	10
	dw	247
	dw	228
	dw	11
	dw	247
	dw	228
	dw	11
	dw	0


sc76_hatch_3	dw	s65
	dw	319
	dw	204
	dw	0
	dw	319
	dw	204
	dw	0
	dw	317
	dw	204
	dw	1
	dw	317
	dw	204
	dw	1
	dw	315
	dw	204
	dw	2
	dw	315
	dw	204
	dw	2
	dw	312
	dw	213
	dw	3
	dw	312
	dw	213
	dw	3
	dw	316
	dw	216
	dw	4
	dw	316
	dw	216
	dw	4
	dw	315
	dw	219
	dw	5
	dw	315
	dw	219
	dw	5
	dw	308
	dw	222
	dw	6
	dw	308
	dw	222
	dw	7
	dw	305
	dw	224
	dw	8
	dw	305
	dw	224
	dw	8
	dw	302
	dw	221
	dw	9
	dw	302
	dw	221
	dw	9
	dw	303
	dw	220
	dw	10
	dw	303
	dw	220
	dw	10
	dw	301
	dw	220
	dw	11
	dw	302
	dw	220
	dw	12
	dw	307
	dw	220
	dw	13
	dw	0


sc76_punch	dw	s69
	dw	307
	dw	220
	dw	0
	dw	312
	dw	220
	dw	1
	dw	311
	dw	221
	dw	2
	dw	312
	dw	221
	dw	3
	dw	318
	dw	221
	dw	4
	dw	326
	dw	220
	dw	5
	dw	331
	dw	220
	dw	6
	dw	331
	dw	221
	dw	7
	dw	337
	dw	220
	dw	0
	dw	337
	dw	220
	dw	0
	dw	324
	dw	223
	dw	8
	dw	323
	dw	224
	dw	9
	dw	320
	dw	224
	dw	10
	dw	330
	dw	224
	dw	11
	dw	331
	dw	222
	dw	12
	dw	331
	dw	222
	dw	13
	dw	332
	dw	221
	dw	14
	dw	337
	dw	220
	dw	0
	dw	337
	dw	220
	dw	0
	dw	337
	dw	220
	dw	15
	dw	0


sc76_fostfall	dw	s70
	dw	354
	dw	218
	dw	0
	dw	355
	dw	218
	dw	1
	dw	355
	dw	218
	dw	2
	dw	357
	dw	219
	dw	3
	dw	366
	dw	216
	dw	4
	dw	371
	dw	222
	dw	5
	dw	376
	dw	234
	dw	6
	dw	381
	dw	255
	dw	7
	dw	382
	dw	261
	dw	8
	dw	381
	dw	262
	dw	9
	dw	382
	dw	262
	dw	10
	dw	382
	dw	262
	dw	11
	dw	382
	dw	262
	dw	11
	dw	0



end32data

start32save_data



sc76_floor	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	sc76_floor_table
	dw	175
	dw	255
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	advisor_188
	dw	0
	dw	0
	dw	391-175
	dw	327-255
	dw	floor_action



end32save_data

start32data



sc76_floor_table	dw	id_sc76_floor
	dw	return_ok
	dw	id_sc76_door75
	dw	GT_sc76_door75
	dw	0
	dw	sc76_door75_walk_on
	dw	id_sc76_door77
	dw	GT_sc76_door77
	dw	1
	dw	sc76_door77_walk_on
	dw	id_sc76_android_1
	dw	GT_sc76_anything
	dw	id_sc76_android_2
	dw	GT_sc76_anything
	dw	id_sc76_android_3
	dw	GT_sc76_anything
	dw	id_sc76_console_1
	dw	GT_sc76_anything
	dw	id_sc76_console_2
	dw	GT_sc76_anything
	dw	id_sc76_console_3
	dw	GT_sc76_anything
	dw	id_sc76_cabinet_1
	dw	GT_sc76_anything
	dw	id_sc76_cabinet_2
	dw	GT_sc76_anything
	dw	id_sc76_cabinet_3
	dw	GT_sc76_anything
	dw	id_sc76_board_1
	dw	GT_sc76_anything
	dw	id_sc76_board_2
	dw	GT_sc76_anything
	dw	id_sc76_board_3
	dw	GT_sc76_anything
	dw	id_joey_park
	dw	GT_joey_park
	dw	-1



end32data

start32save_data



sc76_door75	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	174
	dw	210
	dw	NULL
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	190-174
	dw	275-210
	dw	sc76_door75_action


sc76_door77	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	377
	dw	208
	dw	NULL
	dw	1+t7
	dw	std_exit_right_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	392-377
	dw	271-208
	dw	sc76_door77_action


sc76_android_1	dw	l_script
	dw	st_logic+st_mouse+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	224
	dw	204
	dw	s66
	dw	20691
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-8
	dw	0
	dw	238-216
	dw	243-204
	dw	sc76_android_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_android_1_logic
	dw	0


sc76_android_2	dw	l_script
	dw	st_logic+st_mouse+st_sort+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	271
	dw	204
	dw	s67
	dw	20691
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	289-271
	dw	243-204
	dw	sc76_android_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_android_2_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_col_android2
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0


sc76_android_3	dw	l_script
	dw	st_logic+st_mouse+st_sort+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	319
	dw	204
	dw	s64
	dw	20691
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	340-319
	dw	243-204
	dw	sc76_android_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_android_3_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	right
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_col_android3
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0


sc76_console_1	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	244
	dw	210
	dw	NULL
	dw	182
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	260-244
	dw	244-210
	dw	sc76_console_1_action


sc76_console_2	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	299
	dw	210
	dw	NULL
	dw	182
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	316-299
	dw	244-210
	dw	sc76_console_2_action


sc76_console_3	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	350
	dw	210
	dw	NULL
	dw	182
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	369-350
	dw	244-210
	dw	sc76_console_3_action


sc76_cabinet_1	dw	l_script
	dw	st_logic+st_mouse+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	245
	dw	246
	dw	s55
	dw	20692
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-1
	dw	-1
	dw	261-244
	dw	265-245
	dw	sc76_cabinet_1_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_cabinet_1_logic
	dw	0


sc76_cabinet_2	dw	l_script
	dw	st_logic+st_mouse+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	301
	dw	246
	dw	s56
	dw	20692
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	1
	dw	1
	dw	316-302
	dw	265-245
	dw	sc76_cabinet_2_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_cabinet_2_logic
	dw	0


sc76_cabinet_3	dw	l_script
	dw	st_logic+st_mouse+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	355
	dw	246
	dw	s57
	dw	20692
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	1
	dw	-1
	dw	370-356
	dw	265-245
	dw	sc76_cabinet_3_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_cabinet_3_logic
	dw	0


sc76_board_1	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	248
	dw	253
	dw	s58
	dw	6
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-1
	dw	-2
	dw	257-247
	dw	254-251
	dw	sc76_board_1_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_board_1_logic
	dw	0


sc76_board_2	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	302
	dw	253
	dw	s59
	dw	6
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	-2
	dw	312-302
	dw	254-251
	dw	sc76_board_2_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_board_2_logic
	dw	0


sc76_board_3	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	356
	dw	253
	dw	s60
	dw	6
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	-1
	dw	-2
	dw	365-355
	dw	254-251
	dw	sc76_board_3_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_board_3_logic
	dw	0


sc76_light1	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	228
	dw	182
	dw	s29
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light1_logic
	dw	0


sc76_light2	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	232
	dw	182
	dw	s30
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light2_logic
	dw	0


sc76_light3	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	278
	dw	182
	dw	s31
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light3_logic
	dw	0


sc76_light4	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	282
	dw	182
	dw	s32
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light4_logic
	dw	0


sc76_light5	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	323
	dw	182
	dw	s43
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light5_logic
	dw	0


sc76_light6	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	327
	dw	182
	dw	s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light6_logic
	dw	0


sc76_light7	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	247
	dw	239
	dw	s45
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light7_logic
	dw	0


sc76_light8	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	304
	dw	239
	dw	s46
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light8_logic
	dw	0


sc76_light9	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	76
	dw	NULL
	dd	NULL
	dw	357
	dw	239
	dw	s47
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	sc76_light9_logic
	dw	0


ken	dw	l_script
	dw	st_logic
	dw	0
	dw	76
	dw	id_sc76_floor
	dd	NULL
	dw	256
	dw	272
	dw	40+s61
	dw	3
	dw	std_on
	dw	std_off
	dw	mega_click
	dw	-8
	dw	-43
	dw	14
	dw	50
	dw	shout_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	ken_start_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_player_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96+32
	dw	sp_col_ken
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	ken_auto
	dw	0
	dw	3
	dw	8
	dw	16
	dw	24
	dd	ken_up
	dd	ken_down
	dd	ken_left
	dd	ken_right
	dd	ken_st_up
	dd	ken_st_down
	dd	ken_st_left
	dd	ken_st_right
	dd	0
	dd	0
	dd	ken_u_to_d
	dd	ken_u_to_l
	dd	ken_u_to_r
	dd	0
	dd	ken_d_to_u
	dd	0
	dd	ken_d_to_l
	dd	ken_d_to_r
	dd	0
	dd	ken_l_to_u
	dd	ken_l_to_d
	dd	0
	dd	ken_l_to_r
	dd	0
	dd	ken_r_to_u
	dd	ken_r_to_d
	dd	ken_r_to_l
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0
	dd	0


ken_auto	db	64 dup (0)



end32save_data

start32data



ken_left	dw	4
	dw	20+s61
	dw	-4
	dw	0
	dw	4
	dw	21+s61
	dw	-4
	dw	0
	dw	4
	dw	22+s61
	dw	-4
	dw	0
	dw	4
	dw	23+s61
	dw	-4
	dw	0
	dw	4
	dw	24+s61
	dw	-4
	dw	0
	dw	4
	dw	25+s61
	dw	-4
	dw	0
	dw	4
	dw	26+s61
	dw	-4
	dw	0
	dw	4
	dw	27+s61
	dw	-4
	dw	0
	dw	4
	dw	28+s61
	dw	-4
	dw	0
	dw	4
	dw	29+s61
	dw	-4
	dw	0
	dw	0


ken_right	dw	4
	dw	30+s61
	dw	4
	dw	0
	dw	4
	dw	31+s61
	dw	4
	dw	0
	dw	4
	dw	32+s61
	dw	4
	dw	0
	dw	4
	dw	33+s61
	dw	4
	dw	0
	dw	4
	dw	34+s61
	dw	4
	dw	0
	dw	4
	dw	35+s61
	dw	4
	dw	0
	dw	4
	dw	36+s61
	dw	4
	dw	0
	dw	4
	dw	37+s61
	dw	4
	dw	0
	dw	4
	dw	38+s61
	dw	4
	dw	0
	dw	4
	dw	39+s61
	dw	4
	dw	0
	dw	0


ken_up	dw	2
	dw	0+s61
	dw	0
	dw	-2
	dw	2
	dw	1+s61
	dw	0
	dw	-2
	dw	2
	dw	2+s61
	dw	0
	dw	-2
	dw	2
	dw	3+s61
	dw	0
	dw	-2
	dw	2
	dw	4+s61
	dw	0
	dw	-2
	dw	2
	dw	5+s61
	dw	0
	dw	-2
	dw	2
	dw	6+s61
	dw	0
	dw	-2
	dw	2
	dw	7+s61
	dw	0
	dw	-2
	dw	2
	dw	8+s61
	dw	0
	dw	-2
	dw	2
	dw	9+s61
	dw	0
	dw	-2
	dw	0


ken_down	dw	2
	dw	10+s61
	dw	0
	dw	2
	dw	2
	dw	11+s61
	dw	0
	dw	2
	dw	2
	dw	12+s61
	dw	0
	dw	2
	dw	2
	dw	13+s61
	dw	0
	dw	2
	dw	2
	dw	14+s61
	dw	0
	dw	2
	dw	2
	dw	15+s61
	dw	0
	dw	2
	dw	2
	dw	16+s61
	dw	0
	dw	2
	dw	2
	dw	17+s61
	dw	0
	dw	2
	dw	2
	dw	18+s61
	dw	0
	dw	2
	dw	2
	dw	19+s61
	dw	0
	dw	2
	dw	0


ken_st_up	dw	s61
	dw	1
	dw	0
	dw	44
	dw	0


ken_st_down	dw	s61
	dw	1
	dw	0
	dw	40
	dw	0


ken_st_left	dw	s61
	dw	1
	dw	0
	dw	42
	dw	0


ken_st_right	dw	s61
	dw	1
	dw	0
	dw	46
	dw	0


ken_r_to_u	dw	45+s61
	dw	0


ken_r_to_d	dw	47+s61
	dw	0


ken_r_to_l	dw	45+s61
	dw	44+s61
	dw	43+s61
	dw	0


ken_u_to_d	dw	43+s61
	dw	42+s61
	dw	41+s61
	dw	0


ken_u_to_l	dw	43+s61
	dw	0


ken_u_to_r	dw	45+s61
	dw	0


ken_d_to_u	dw	47+s61
	dw	46+s61
	dw	45+s61
	dw	0


ken_d_to_l	dw	41+s61
	dw	0


ken_d_to_r	dw	47+s61
	dw	0


ken_l_to_u	dw	43+s61
	dw	0


ken_l_to_d	dw	41+s61
	dw	0


ken_l_to_r	dw	41+s61
	dw	40+s61
	dw	47+s61
	dw	0



end32data

start32save_data



end32save_data
