start32save_data



slab1	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab1_table
	dw	145
	dw	294
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	79
	dw	29
	dw	slab_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab1_logic
	dw	0



end32save_data

start32data



slab1_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab1
	dw	return_ok
	dw	id_slab2
	dw	get_to_slab
	dw	id_slab4
	dw	get_to_slab
	dw	id_door_l92
	dw	get_to_door_l92
	dw	-1



end32data

start32save_data



slab2	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab2_table
	dw	250
	dw	294
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	76
	dw	29
	dw	slab_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab2_logic
	dw	0



end32save_data

start32data



slab2_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab1
	dw	get_to_slab
	dw	id_slab2
	dw	return_ok
	dw	id_slab3
	dw	get_to_slab
	dw	id_slab5
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab3	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab3_table
	dw	350
	dw	294
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	70
	dw	29
	dw	slab_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab3_logic
	dw	0



end32save_data

start32data



slab3_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab2
	dw	get_to_slab
	dw	id_slab3
	dw	return_ok
	dw	id_slab6
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab4	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab4_table
	dw	191
	dw	267
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	51
	dw	21
	dw	slab_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab4_logic
	dw	0



end32save_data

start32data



slab4_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab1
	dw	get_to_slab
	dw	id_slab4
	dw	return_ok
	dw	id_slab5
	dw	get_to_slab
	dw	id_slab7
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab5	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab5_table
	dw	260
	dw	267
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	55
	dw	21
	dw	slab_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab5_logic
	dw	0



end32save_data

start32data



slab5_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab2
	dw	get_to_slab
	dw	id_slab4
	dw	get_to_slab
	dw	id_slab5
	dw	return_ok
	dw	id_slab6
	dw	get_to_slab
	dw	id_slab8
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab6	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab6_table
	dw	332
	dw	267
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	53
	dw	21
	dw	slab_6_9_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab6_logic
	dw	0



end32save_data

start32data



slab6_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab3
	dw	get_to_slab
	dw	id_slab5
	dw	get_to_slab
	dw	id_slab6
	dw	return_ok
	dw	id_slab9
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab7	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab7_table
	dw	214
	dw	248
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	43
	dw	14
	dw	slab_6_9_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab7_logic
	dw	0



end32save_data

start32data



slab7_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab4
	dw	get_to_slab
	dw	id_slab7
	dw	return_ok
	dw	id_slab8
	dw	get_to_slab
	dw	-1



end32data

start32save_data



slab8	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab8_table
	dw	266
	dw	248
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	42
	dw	14
	dw	slab_6_9_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab8_logic
	dw	0



end32save_data

start32data



slab8_table	dw	id_green_circle
	dw	get_to_circle
	dw	id_red_circle
	dw	get_to_circle
	dw	id_slab5
	dw	get_to_slab
	dw	id_slab7
	dw	get_to_slab
	dw	id_slab8
	dw	return_ok
	dw	-1



end32data

start32save_data



slab9	dw	l_script
	dw	st_logic
	dw	NULL
	dw	92
	dw	NULL
	dd	slab9_table
	dw	319
	dw	248
	dw	NULL
	dw	NULL
	dw	slab_on
	dw	slab_off
	dw	advisor_188
	dw	0
	dw	0
	dw	41
	dw	14
	dw	slab_6_9_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	slab9_logic
	dw	0



end32save_data

start32data



slab9_table	dw	id_slab6
	dw	get_to_slab
	dw	id_slab9
	dw	return_ok
	dw	id_door_r92
	dw	get_to_door_r92
	dw	-1



end32data

start32save_data



bridge_a	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	217
	dw	295
	dw	s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_a_logic
	dw	0


bridge_b	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	320
	dw	295
	dw	1+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_b_logic
	dw	0


bridge_c	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	173
	dw	289
	dw	2+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_c_logic
	dw	0


bridge_d	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	257
	dw	289
	dw	3+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_d_logic
	dw	0


bridge_e	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	340
	dw	289
	dw	4+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_e_logic
	dw	0


bridge_f	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	236
	dw	268
	dw	5+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_f_logic
	dw	0


bridge_g	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	266
	dw	263
	dw	6+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_g_logic
	dw	0


bridge_h	dw	l_script
	dw	st_logic+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	325
	dw	263
	dw	7+s44
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	bridge_h_logic
	dw	0


door_l92	dw	l_script
	dw	st_mouse+st_logic+st_background
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	152
	dw	136
	dw	s54
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	-5
	dw	26
	dw	9
	dw	153
	dw	door_l92_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	door_l92_logic
	dw	0


door_l92f	dw	l_script
	dw	st_logic+st_sort
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	147
	dw	136
	dw	s55
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	door_l92f_logic
	dw	0


door_r92	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	323
	dw	136
	dw	s129
	dw	1+t7
	dw	std_exit_up_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	26
	dw	26
	dw	86
	dw	door_r92_action
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	NULL
	dw	c_base_mode
	dw	door_r92_logic
	dw	0


door_r92r	dw	l_script
	dw	st_logic+st_background
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	348
	dw	136
	dw	s130
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	NULL
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	door_r92r_logic
	dw	0


green_circle	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	0
	dw	0
	dw	s62
	dw	24603
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	2
	dw	28
	dw	6
	dw	green_circle_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	green_circle_logic
	dw	0


red_circle	dw	l_script
	dw	st_logic+st_background+st_recreate
	dw	NULL
	dw	92
	dw	NULL
	dd	NULL
	dw	0
	dw	0
	dw	2+s62
	dw	24603
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	-1
	dw	28
	dw	6
	dw	red_circle_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	red_circle_logic
	dw	0



end32save_data

start32data



rs_foster_92_91	dw	c_screen
	dw	91
	dw	c_place
	dw	id_sc91_floor
	dw	c_xcood
	dw	392
	dw	c_ycood
	dw	264
	dw	-1


rs_foster_92_93	dw	c_screen
	dw	93
	dw	c_place
	dw	id_sc93_floor
	dw	c_xcood
	dw	184
	dw	c_ycood
	dw	264
	dw	c_frame
	dw	46+s182
	dw	c_dir
	dw	right
	dw	-1


door_l92_anim	dw	s54
	dw	152
	dw	136
	dw	0
	dw	152
	dw	136
	dw	1
	dw	152
	dw	136
	dw	2
	dw	152
	dw	136
	dw	3
	dw	152
	dw	136
	dw	4
	dw	152
	dw	136
	dw	5
	dw	152
	dw	136
	dw	6
	dw	152
	dw	136
	dw	7
	dw	152
	dw	136
	dw	8
	dw	152
	dw	136
	dw	9
	dw	152
	dw	136
	dw	10
	dw	152
	dw	136
	dw	11
	dw	152
	dw	136
	dw	12
	dw	152
	dw	136
	dw	13
	dw	152
	dw	136
	dw	14
	dw	152
	dw	136
	dw	15
	dw	152
	dw	136
	dw	16
	dw	152
	dw	136
	dw	17
	dw	152
	dw	136
	dw	18
	dw	152
	dw	136
	dw	19
	dw	152
	dw	136
	dw	20
	dw	152
	dw	136
	dw	21
	dw	152
	dw	136
	dw	22
	dw	0


door_l92f_anim	dw	s55
	dw	147
	dw	136
	dw	0
	dw	147
	dw	136
	dw	1
	dw	147
	dw	136
	dw	2
	dw	147
	dw	136
	dw	3
	dw	147
	dw	136
	dw	4
	dw	147
	dw	136
	dw	5
	dw	147
	dw	136
	dw	6
	dw	147
	dw	136
	dw	7
	dw	147
	dw	136
	dw	8
	dw	147
	dw	136
	dw	9
	dw	147
	dw	136
	dw	10
	dw	147
	dw	136
	dw	11
	dw	147
	dw	136
	dw	12
	dw	147
	dw	136
	dw	13
	dw	147
	dw	136
	dw	14
	dw	147
	dw	136
	dw	15
	dw	147
	dw	136
	dw	16
	dw	147
	dw	136
	dw	17
	dw	147
	dw	136
	dw	18
	dw	147
	dw	136
	dw	19
	dw	147
	dw	136
	dw	20
	dw	147
	dw	136
	dw	21
	dw	147
	dw	136
	dw	22
	dw	0


door_r92_anim	dw	s129
	dw	323
	dw	136
	dw	0
	dw	323
	dw	136
	dw	1
	dw	323
	dw	136
	dw	2
	dw	323
	dw	136
	dw	3
	dw	323
	dw	136
	dw	4
	dw	323
	dw	136
	dw	5
	dw	323
	dw	136
	dw	6
	dw	323
	dw	136
	dw	7
	dw	323
	dw	136
	dw	8
	dw	323
	dw	136
	dw	9
	dw	323
	dw	136
	dw	10
	dw	323
	dw	136
	dw	11
	dw	323
	dw	136
	dw	12
	dw	323
	dw	136
	dw	13
	dw	323
	dw	136
	dw	14
	dw	323
	dw	136
	dw	15
	dw	323
	dw	136
	dw	16
	dw	323
	dw	136
	dw	17
	dw	323
	dw	136
	dw	18
	dw	323
	dw	136
	dw	19
	dw	323
	dw	136
	dw	20
	dw	323
	dw	136
	dw	21
	dw	323
	dw	136
	dw	22
	dw	0


door_r92r_anim	dw	s130
	dw	348
	dw	136
	dw	0
	dw	348
	dw	136
	dw	1
	dw	348
	dw	136
	dw	2
	dw	348
	dw	136
	dw	3
	dw	348
	dw	136
	dw	4
	dw	348
	dw	136
	dw	5
	dw	348
	dw	136
	dw	6
	dw	348
	dw	136
	dw	7
	dw	348
	dw	136
	dw	8
	dw	348
	dw	136
	dw	9
	dw	348
	dw	136
	dw	10
	dw	348
	dw	136
	dw	11
	dw	348
	dw	136
	dw	12
	dw	348
	dw	136
	dw	13
	dw	348
	dw	136
	dw	14
	dw	348
	dw	136
	dw	15
	dw	348
	dw	136
	dw	16
	dw	348
	dw	136
	dw	17
	dw	348
	dw	136
	dw	18
	dw	348
	dw	136
	dw	19
	dw	348
	dw	136
	dw	20
	dw	348
	dw	136
	dw	21
	dw	348
	dw	136
	dw	22
	dw	0


pal92	dw	0
	dw	3584
	dw	8960
	dw	1044
	dw	7211
	dw	12812
	dw	5413
	dw	11066
	dw	15390
	dw	29
	dw	8192
	dw	0
	dw	36
	dw	10240
	dw	0
	dw	1550
	dw	5888
	dw	10
	dw	3616
	dw	9472
	dw	20
	dw	7211
	dw	15360
	dw	39
	dw	43
	dw	0
	dw	0
	dw	15928
	dw	11071
	dw	13873
	dw	10015
	dw	6188
	dw	8990
	dw	5135
	dw	2587
	dw	5903
	dw	8458
	dw	783
	dw	1303
	dw	4096
	dw	12032
	dw	0
	dw	30
	dw	5632
	dw	0
	dw	6183
	dw	12058
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	16191
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191


fast_list_sc92	dw	it_blue_foster+disk_4
	dw	it_logoff+$8000+disk_4
	dw	it_window+$8000+disk_4
	dw	it_info_button+disk_4
	dw	it_link_arrows+disk_4
	dw	it_link_objects+disk_4
	dw	it_enter_top+disk_4+$8000
	dw	it_exit_top+disk_4+$8000
	dw	it_crouch_right+disk_4
	dw	it_sc92_layer_0+disk_4
	dw	it_sc92_layer_1+disk_4
	dw	it_sc92_grid_1+disk_4
	dw	0


chip_list_sc92	dw	it_bridges+disk_4
	dw	it_circles+disk_4
	dw	it_door_l92+disk_4
	dw	it_door_l92f+disk_4
	dw	it_door_r92+disk_4
	dw	it_door_r92r+disk_4
	dw	0


sc92_logic	dw	id_blue_foster
	dw	id_bridge_a
	dw	id_bridge_b
	dw	id_bridge_c
	dw	id_bridge_d
	dw	id_bridge_e
	dw	id_bridge_f
	dw	id_bridge_g
	dw	id_bridge_h
	dw	id_slab1
	dw	id_slab2
	dw	id_slab3
	dw	id_slab4
	dw	id_slab5
	dw	id_slab6
	dw	id_slab7
	dw	id_slab8
	dw	id_slab9
	dw	id_green_circle
	dw	id_red_circle
	dw	id_door_l92
	dw	id_door_l92f
	dw	id_door_r92
	dw	id_door_r92r
	dw	id_eyeball_90
	dw	$ffff
	dw	id_linc_menu_logic


sc92_mouse	dw	id_green_circle
	dw	id_red_circle
	dw	id_door_l92
	dw	id_door_r92
	dw	id_slab1
	dw	id_slab2
	dw	id_slab3
	dw	id_slab4
	dw	id_slab5
	dw	id_slab6
	dw	id_slab7
	dw	id_slab8
	dw	id_slab9
	dw	$ffff
	dw	id_linc_menu_mouse



end32data

start32save_data



end32save_data
