start32data



s9_logic	dw	id_foster
	dw	id_joey
	dw	id_fans
	dw	id_lobby_door
	dw	id_scanner
	dw	id_dad
	dw	id_son
	dw	id_monitor
	dw	id_lamb
	dw	id_lift_s7
	dw	id_lift7_light
	dw	$ffff
	dw	id_menu_logic


s9_mouse	dw	id_joey
	dw	id_monitor
	dw	id_left_exit_s9
	dw	id_lobby_door
	dw	id_scanner
	dw	id_lobby_slot
	dw	id_dad
	dw	id_son
	dw	id_fake_floor_9
	dw	id_linc_s9
	dw	id_s9_floor
	dw	$ffff
	dw	id_text_mouse


s9_pal	dw	0
	dw	1024
	dw	1028
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	512
	dw	0
	dw	0
	dw	514
	dw	512
	dw	4
	dw	1538
	dw	1026
	dw	512
	dw	4
	dw	1026
	dw	1026
	dw	4
	dw	1540
	dw	514
	dw	2054
	dw	1540
	dw	516
	dw	2566
	dw	1540
	dw	1030
	dw	2566
	dw	2054
	dw	1538
	dw	522
	dw	2052
	dw	2060
	dw	2056
	dw	2566
	dw	2054
	dw	522
	dw	2056
	dw	1546
	dw	2058
	dw	2564
	dw	1038
	dw	4106
	dw	3078
	dw	2056
	dw	1036
	dw	2566
	dw	2064
	dw	2572
	dw	3078
	dw	2578
	dw	3084
	dw	3594
	dw	2566
	dw	2062
	dw	3080
	dw	3092
	dw	3084
	dw	2574
	dw	2574
	dw	2064
	dw	3592
	dw	3092
	dw	2064
	dw	3596
	dw	3088
	dw	2576
	dw	4106
	dw	2062
	dw	6414
	dw	4106
	dw	2064
	dw	6926
	dw	3594
	dw	3097
	dw	2578
	dw	4108
	dw	2578
	dw	6416
	dw	4622
	dw	3594
	dw	4624
	dw	4622
	dw	3600
	dw	3092
	dw	4108
	dw	4125
	dw	3092
	dw	4618
	dw	4127
	dw	6416
	dw	4620
	dw	3101
	dw	5908
	dw	4620
	dw	4127
	dw	3095
	dw	5134
	dw	4631
	dw	4628
	dw	5904
	dw	3600
	dw	5143
	dw	5902
	dw	4631
	dw	3097
	dw	5134
	dw	5153
	dw	4631
	dw	5136
	dw	5153
	dw	3609
	dw	5902
	dw	4129
	dw	6425
	dw	5902
	dw	4131
	dw	6937
	dw	6420
	dw	4628
	dw	5147
	dw	6928
	dw	6939
	dw	2075
	dw	6937
	dw	6412
	dw	5145
	dw	6935
	dw	5911
	dw	4125
	dw	7447
	dw	4626
	dw	6941
	dw	6935
	dw	4633
	dw	7453
	dw	7956
	dw	6427
	dw	6429
	dw	7449
	dw	7451
	dw	3103
	dw	7961
	dw	5140
	dw	7455
	dw	7963
	dw	6420
	dw	6432
	dw	8729
	dw	5908
	dw	7714
	dw	8735
	dw	7184
	dw	8224
	dw	8988
	dw	7710
	dw	7203
	dw	9498
	dw	8222
	dw	4901
	dw	9757
	dw	8477
	dw	8486
	dw	10014
	dw	7712
	dw	8743
	dw	11040
	dw	8736
	dw	9257
	dw	11040
	dw	10020
	dw	5676
	dw	11813
	dw	9763
	dw	10797
	dw	11560
	dw	10536
	dw	10290
	dw	12331
	dw	11563
	dw	11568
	dw	13102
	dw	12334
	dw	12341
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	16184
	dw	13620
	dw	11068
	dw	14130
	dw	12067
	dw	7218
	dw	11559
	dw	8214
	dw	4901
	dw	8735
	dw	7440
	dw	3103
	dw	7452
	dw	6922
	dw	2075
	dw	5651
	dw	3593
	dw	2578
	dw	3338
	dw	2055
	dw	1547
	dw	2311
	dw	1541
	dw	1032
	dw	0
	dw	14336
	dw	13364
	dw	11569
	dw	9261
	dw	8481
	dw	6687
	dw	6681
	dw	4626
	dw	2578
	dw	1803
	dw	770
	dw	519
	dw	13571
	dw	9517
	dw	9778
	dw	11805
	dw	5151
	dw	5926
	dw	8205
	dw	1808
	dw	2586
	dw	11267
	dw	2056
	dw	8210
	dw	7441
	dw	6954
	dw	9494
	dw	4119
	dw	3866
	dw	4864
	dw	13316
	dw	13364
	dw	11563
	dw	8751
	dw	9506
	dw	10024
	dw	8242
	dw	10527
	dw	6174
	dw	5927
	dw	7698
	dw	3600
	dw	2325
	dw	2308
	dw	11573
	dw	12837
	dw	7462
	dw	7982
	dw	9748
	dw	3351
	dw	4128
	dw	6663
	dw	778
	dw	9533
	dw	13100
	dw	9244
	dw	5162
	dw	8476
	dw	5390
	dw	2072
	dw	3855
	dw	2308
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	4865
	dw	0
	dw	11573
	dw	12837
	dw	7462
	dw	0
	dw	16128
	dw	0
	dw	16191
	dw	16191
	dw	16128
	dw	63
	dw	16191
	dw	16128
	dw	63
	dw	13887
	dw	13878
	dw	12077
	dw	8241
	dw	10527
	dw	5917
	dw	5925
	dw	7698
	dw	2865
	dw	9995
	dw	1285
	dw	285
	dw	16129
	dw	16191



end32data

start32save_data



s9_floor	dw	0
	dw	st_mouse
	dw	0
	dw	9
	dw	NULL
	dd	s9_floor_table
	dw	128
	dw	288
	dw	0
	dw	0
	dw	0
	dw	0
	dw	advisor_188
	dw	0
	dw	0
	dw	320
	dw	37
	dw	floor_action



end32save_data

start32data



s9_floor_table	dw	id_s9_floor
	dw	return_ok
	dw	id_joey_park
	dw	get_to_jp2
	dw	42
	dw	s9_walk_on
	dw	id_dad
	dw	get_to_dad
	dw	id_son
	dw	get_to_son
	dw	id_left_exit_s9
	dw	get_to_l_exit_s9
	dw	id_lobby_door
	dw	get_to_lobby_door
	dw	id_scanner
	dw	get_to_scanner
	dw	id_lobby_slot
	dw	get_to_scanner
	dw	id_linc_s9
	dw	GT_linc_s9
	dw	-1


s9_chip_list	dw	173
	dw	111
	dw	93+disk_2
	dw	95+disk_2
	dw	96+disk_2
	dw	97+disk_2
	dw	98+disk_2
	dw	99+disk_2
	dw	106+disk_2+$8000
	dw	107+disk_2+$8000
	dw	110+disk_2+$8000
	dw	112+disk_2+$8000
	dw	74+disk_2
	dw	92+disk_2
	dw	47+disk_2
	dw	48+disk_2
	dw	0


rs_foster_to_9	dw	c_xcood
	dw	152
	dw	c_ycood
	dw	296
	dw	c_screen
	dw	9
	dw	c_place
	dw	id_s9_floor
	dw	-1



end32data

start32save_data



left_exit_s9	dw	0
	dw	st_mouse
	dw	0
	dw	9
	dw	NULL
	dd	0
	dw	175
	dw	244
	dw	0
	dw	1+t7
	dw	std_exit_left_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	16
	dw	304-244
	dw	el9_action


fans	dw	l_script
	dw	st_background+st_logic
	dw	0
	dw	9
	dw	NULL
	dd	NULL
	dw	0
	dw	0
	dw	s93
	dw	null
	dw	null
	dw	null
	dw	null
	dw	NULL
	dw	NULL
	dw	null
	dw	null
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	NULL
	dd	0
	dw	0
	dw	c_base_mode
	dw	fans_logic
	dw	0



end32save_data

start32data



fans_seq	dw	s93
	dw	188
	dw	199
	dw	0
	dw	188
	dw	199
	dw	1
	dw	188
	dw	199
	dw	2
	dw	188
	dw	199
	dw	3
	dw	188
	dw	199
	dw	4
	dw	188
	dw	199
	dw	5
	dw	188
	dw	199
	dw	6
	dw	188
	dw	199
	dw	7
	dw	188
	dw	199
	dw	8
	dw	188
	dw	199
	dw	9
	dw	188
	dw	199
	dw	10
	dw	188
	dw	199
	dw	11
	dw	188
	dw	199
	dw	12
	dw	188
	dw	199
	dw	13
	dw	188
	dw	199
	dw	14
	dw	188
	dw	199
	dw	15
	dw	0



end32data

start32save_data



lobby_door	dw	l_script
	dw	st_mouse+st_background+st_recreate+st_logic
	dw	0
	dw	9
	dw	NULL
	dd	null
	dw	379
	dw	241
	dw	s95
	dw	139
	dw	lobby_door_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	6
	dw	62
	dw	lobby_door_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	lobby_door_logic
	dw	0



end32save_data

start32data



lobby_up_seq	dw	s95
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	0


lobby_down_seq	dw	s95
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



scanner	dw	l_script
	dw	st_mouse+st_recreate+st_logic
	dw	0
	dw	9
	dw	NULL
	dd	null
	dw	349
	dw	250
	dw	s95
	dw	138
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	298-250
	dw	32
	dw	8
	dw	scanner_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	c_base_mode
	dw	scanner_logic
	dw	0


lobby_slot	dw	l_script
	dw	st_mouse
	dw	0
	dw	9
	dw	NULL
	dd	null
	dw	384
	dw	272
	dw	null
	dw	36+t7
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	5
	dw	12
	dw	lobby_slot_action



end32save_data

start32data



card_in_seq	dw	s106
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0



end32data

start32save_data



dad	dw	l_script
	dw	st_background+st_recreate+st_logic+st_mouse
	dw	0
	dw	9
	dw	0
	dd	0
	dw	$10e
	dw	$e6
	dw	s96
	dw	4
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	32
	dw	16
	dw	dad_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	dad_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_dad
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0



end32save_data

start32data



dad_work_seq	dw	s96
	dw	270
	dw	230
	dw	0
	dw	270
	dw	230
	dw	0
	dw	270
	dw	230
	dw	1
	dw	270
	dw	230
	dw	1
	dw	270
	dw	230
	dw	2
	dw	270
	dw	230
	dw	2
	dw	270
	dw	230
	dw	3
	dw	270
	dw	230
	dw	3
	dw	270
	dw	230
	dw	4
	dw	270
	dw	230
	dw	4
	dw	270
	dw	230
	dw	5
	dw	270
	dw	230
	dw	5
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	7
	dw	270
	dw	230
	dw	7
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	7
	dw	270
	dw	230
	dw	7
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	6
	dw	270
	dw	230
	dw	5
	dw	270
	dw	230
	dw	5
	dw	270
	dw	230
	dw	4
	dw	270
	dw	230
	dw	4
	dw	270
	dw	230
	dw	3
	dw	270
	dw	230
	dw	3
	dw	0


dad_work2_seq	dw	s97
	dw	307
	dw	230
	dw	0
	dw	307
	dw	230
	dw	0
	dw	307
	dw	230
	dw	1
	dw	307
	dw	230
	dw	1
	dw	307
	dw	230
	dw	1
	dw	307
	dw	230
	dw	1
	dw	307
	dw	230
	dw	1
	dw	307
	dw	230
	dw	0
	dw	307
	dw	230
	dw	2
	dw	307
	dw	230
	dw	2
	dw	307
	dw	230
	dw	3
	dw	307
	dw	230
	dw	3
	dw	307
	dw	230
	dw	4
	dw	307
	dw	230
	dw	5
	dw	307
	dw	230
	dw	5
	dw	307
	dw	230
	dw	6
	dw	307
	dw	230
	dw	6
	dw	307
	dw	230
	dw	7
	dw	307
	dw	230
	dw	7
	dw	307
	dw	230
	dw	8
	dw	307
	dw	230
	dw	8
	dw	307
	dw	230
	dw	7
	dw	307
	dw	230
	dw	7
	dw	307
	dw	230
	dw	6
	dw	307
	dw	230
	dw	6
	dw	307
	dw	230
	dw	5
	dw	307
	dw	230
	dw	5
	dw	307
	dw	230
	dw	9
	dw	307
	dw	230
	dw	3
	dw	307
	dw	230
	dw	3
	dw	0


dad_work3_seq	dw	s98
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	1
	dw	342
	dw	230
	dw	2
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	1
	dw	342
	dw	230
	dw	2
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	342
	dw	230
	dw	0
	dw	0


son_work_seq	dw	s103
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	5
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	3
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	1
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	2
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	0
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	223
	dw	240
	dw	4
	dw	0



end32data

start32save_data



son	dw	l_script
	dw	st_background+st_recreate+st_logic+st_mouse
	dw	0
	dw	9
	dw	0
	dd	0
	dw	$df
	dw	$f0
	dw	s104
	dw	4
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	0
	dw	0
	dw	32
	dw	16
	dw	son_action
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	son_logic
	dw	0
	dd	0
	dd	0
	dd	0
	dw	down
	dw	std_mega_stop
	dw	std_mini_bump
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	96
	dw	sp_col_son
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0



end32save_data

start32data



scan_seq	dw	s107
	dw	1
	dw	1
	dw	0
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	12
	dw	1
	dw	1
	dw	13
	dw	1
	dw	1
	dw	14
	dw	1
	dw	1
	dw	15
	dw	1
	dw	1
	dw	14
	dw	1
	dw	1
	dw	13
	dw	1
	dw	1
	dw	12
	dw	1
	dw	1
	dw	11
	dw	1
	dw	1
	dw	10
	dw	1
	dw	1
	dw	9
	dw	1
	dw	1
	dw	8
	dw	1
	dw	1
	dw	7
	dw	1
	dw	1
	dw	6
	dw	1
	dw	1
	dw	5
	dw	1
	dw	1
	dw	4
	dw	1
	dw	1
	dw	3
	dw	1
	dw	1
	dw	2
	dw	1
	dw	1
	dw	1
	dw	1
	dw	1
	dw	0
	dw	0


scandie_seq	dw	s112
	dw	349
	dw	250
	dw	0
	dw	349
	dw	250
	dw	1
	dw	349
	dw	250
	dw	2
	dw	349
	dw	250
	dw	3
	dw	349
	dw	250
	dw	4
	dw	349
	dw	250
	dw	5
	dw	349
	dw	250
	dw	6
	dw	349
	dw	250
	dw	7
	dw	349
	dw	250
	dw	8
	dw	349
	dw	250
	dw	9
	dw	349
	dw	250
	dw	10
	dw	349
	dw	250
	dw	11
	dw	349
	dw	250
	dw	12
	dw	349
	dw	250
	dw	13
	dw	349
	dw	250
	dw	14
	dw	349
	dw	250
	dw	15
	dw	349
	dw	250
	dw	16
	dw	349
	dw	250
	dw	17
	dw	349
	dw	250
	dw	18
	dw	349
	dw	250
	dw	18
	dw	349
	dw	250
	dw	19
	dw	349
	dw	250
	dw	19
	dw	349
	dw	250
	dw	20
	dw	349
	dw	250
	dw	21
	dw	349
	dw	250
	dw	22
	dw	349
	dw	250
	dw	23
	dw	349
	dw	250
	dw	24
	dw	349
	dw	250
	dw	25
	dw	349
	dw	250
	dw	26
	dw	349
	dw	250
	dw	27
	dw	349
	dw	250
	dw	28
	dw	349
	dw	250
	dw	29
	dw	349
	dw	250
	dw	30
	dw	349
	dw	250
	dw	31
	dw	349
	dw	250
	dw	32
	dw	349
	dw	250
	dw	33
	dw	349
	dw	250
	dw	34
	dw	349
	dw	250
	dw	35
	dw	349
	dw	250
	dw	36
	dw	349
	dw	250
	dw	37
	dw	349
	dw	250
	dw	38
	dw	349
	dw	250
	dw	39
	dw	0


rs_foster_10_9	dw	c_xcood
	dw	408
	dw	c_ycood
	dw	296
	dw	c_screen
	dw	9
	dw	c_place
	dw	id_s9_floor
	dw	-1



end32data

start32save_data



fake_floor_9	dw	0
	dw	st_mouse
	dw	0
	dw	9
	dw	NULL
	dd	s9_floor_table
	dw	386
	dw	291
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	320
	dw	314-291


linc_s9	dw	0
	dw	st_mouse
	dw	0
	dw	9
	dw	NULL
	dd	0
	dw	162
	dw	284
	dw	null
	dw	51
	dw	std_on
	dw	std_off
	dw	advisor_188
	dw	null
	dw	null
	dw	180-162
	dw	322-284
	dw	linc_s9_action



end32save_data

start32data



end32data
