start32save_data



info_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	1+s191
	dw	24577
	dw	touch_menu
	dw	untouch_menu
	dw	info_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


read_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	3+s191
	dw	24578
	dw	touch_menu
	dw	untouch_menu
	dw	dis_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


open_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	5+s191
	dw	24579
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


charon_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	15+s191
	dw	24599
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


orders_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	31+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	doc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


orders2_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	19+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


join_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	7+s191
	dw	24593
	dw	touch_menu
	dw	untouch_menu
	dw	join_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


green_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	11+s191
	dw	24580
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


red_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	13+s191
	dw	24580
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


report_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	31+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	doc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


report2_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	19+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


decomp_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	17+s191
	dw	24582
	dw	touch_menu
	dw	untouch_menu
	dw	decomp_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


decrypt_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	21+s191
	dw	24581
	dw	touch_menu
	dw	untouch_menu
	dw	decrypt_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


persona_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	23+s191
	dw	24583
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


adjust_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	31+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	doc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


adjust2_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	19+s191
	dw	24629
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


playbak_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	29+s191
	dw	24602
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


blind_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	9+s191
	dw	24600
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


oscill_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	27+s191
	dw	24589
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


kill_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	33+s191
	dw	24689
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0


virus_menu	dw	l_script
	dw	0
	dw	NULL
	dw	NULL
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	25+s191
	dw	24591
	dw	touch_menu
	dw	untouch_menu
	dw	linc_menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	linc_menu_script
	dw	0



end32save_data

start32data



linc_menu_logic	dw	18
	dw	47
	dw	48
	dw	id_info_menu
	dw	id_read_menu
	dw	id_open_menu
	dw	id_charon_menu
	dw	id_orders_menu
	dw	id_orders2_menu
	dw	id_join_menu
	dw	id_green_menu
	dw	id_red_menu
	dw	id_report_menu
	dw	id_report2_menu
	dw	id_decomp_menu
	dw	id_decrypt_menu
	dw	id_persona_menu
	dw	id_adjust_menu
	dw	id_adjust2_menu
	dw	id_playbak_menu
	dw	id_blind_menu
	dw	id_oscill_menu
	dw	id_kill_menu
	dw	id_virus_menu
	dw	51
	dw	52
	dw	53
	dw	54
	dw	55
	dw	56
	dw	57
	dw	58
	dw	59
	dw	60
	dw	61
	dw	23
	dw	24
	dw	25
	dw	26
	dw	27
	dw	28
	dw	29
	dw	30
	dw	31
	dw	32
	dw	0


linc_menu_mouse	dw	18
	dw	23
	dw	24
	dw	25
	dw	26
	dw	27
	dw	28
	dw	29
	dw	30
	dw	31
	dw	32
	dw	47
	dw	48
	dw	51
	dw	52
	dw	53
	dw	54
	dw	55
	dw	56
	dw	57
	dw	58
	dw	59
	dw	60
	dw	61
	dw	id_info_menu
	dw	id_read_menu
	dw	id_open_menu
	dw	id_charon_menu
	dw	id_orders_menu
	dw	id_orders2_menu
	dw	id_join_menu
	dw	id_green_menu
	dw	id_red_menu
	dw	id_report_menu
	dw	id_report2_menu
	dw	id_decomp_menu
	dw	id_decrypt_menu
	dw	id_persona_menu
	dw	id_adjust_menu
	dw	id_adjust2_menu
	dw	id_playbak_menu
	dw	id_blind_menu
	dw	id_oscill_menu
	dw	id_kill_menu
	dw	id_virus_menu
	dw	46
	dw	0



end32data

start32save_data



end32save_data
