start32save_data



menu_bar	dw	NULL
	dw	st_mouse
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	128
	dw	136
	dw	NULL
	dw	1
	dw	start_menu
	dw	untouch_menu
	dw	NULL
	dw	0
	dw	0
	dw	320
	dw	1


left_arrow	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	128
	dw	112
	dw	s49
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	click_left_arrow
	dw	-2
	dw	0
	dw	28
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


right_arrow	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	447-27
	dw	112
	dw	s49+1
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	click_right_arrow
	dw	-2
	dw	0
	dw	29
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank1	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank2	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank3	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank4	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank5	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank6	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank7	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank8	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank9	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank10	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


blank11	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50
	dw	NULL
	dw	touch_arrow
	dw	untouch_arrow
	dw	NULL
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


crow_bar_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+1
	dw	5
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


sarnie_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+5
	dw	4+t7
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


spanner_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+7
	dw	5+t7
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


joeyb_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+3
	dw	6
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


citycard_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+11
	dw	9
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


shades_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s50+9
	dw	10
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


putty_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s73
	dw	137
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


lightbulb_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s73+2
	dw	66
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0



end32save_data

start32data



move_list	dd	move_menu
	dd	move_2


move_menu	dw	46
	dw	18


move_2	dw	20
	dw	0



end32data

start32save_data



wd40_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s87
	dw	8373
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


skey_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s87+2
	dw	8380
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


anita_card_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s262
	dw	68
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


anchor_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s263
	dw	191
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


magazine_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s264
	dw	163
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


tape_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s265
	dw	173
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


glass_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s36
	dw	200
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


rope_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s266
	dw	49
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


ticket_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s269
	dw	189
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


new_cable_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s267
	dw	320
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


secateurs_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s272
	dw	180
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


plaster_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	0+s268
	dw	20506
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


brick_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	2+s268
	dw	20509
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


tongs_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	4+s268
	dw	20639
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


dog_food_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	s271
	dw	198
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0


gallcard_menu	dw	l_script
	dw	0
	dw	NULL
	dw	0
	dw	NULL
	dd	NULL
	dw	0
	dw	112
	dw	12+s268
	dw	68
	dw	touch_menu
	dw	untouch_menu
	dw	menu_select
	dw	-2
	dw	0
	dw	24
	dw	24
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dw	0
	dd	0
	dw	0
	dw	0
	dw	menu_script
	dw	0



end32save_data

start32data



end32data
